### ISSUE TITLE
commands_popup box opens in the wrong place

### ISSUE THREAD

**Issue by HanFox** [marius-wieschollek/passwords#1]
When clicking the cog to edit/copy/etc information the commands_popup box opens in the wrong place and has a bad z-index (200+ is high enough).

For the positioning of the box in the JS it's around here: https://github.com/marius-wieschollek/passwords/blob/stable/js/passwords.js#L425

I'd debug/fix myself, but have no time currently.

**Comment by marius-wieschollek** [comment]
It should be working now again

**Comment by HanFox** [comment]
That's got it :+1:
