### ISSUE TITLE
Copy to clipboard broken on Firefox and Chrome

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#100]
### System Information
- Nextcloud Version: 14
- PHP Version: 7.2
- Passwords Version: 2018.11.1
- Browser and Version: Firefox Mobile 63.0.2, Chrome 70.0.3538.77
- Client OS and Version: Android 8.0.0 and Windows 10
- Server OS and Version: Debian 9

### Steps to reproduce
1. Click on login or password from detail panel or use shortcut from password list or click "Copy password/login/URL" from contextual menu

### Actual result
login or password is not copied to clipboard when clicked from detail pannel or with mouse shortcut (simple or double click on password entry) or from menu.

### Expected result
login or password should be copied to clipboard as it did on version 2018.11.0

**Comment by marius-wieschollek** [comment]
Seems like i messed up when i tried to fix it for iOs in #95. I will release a fix shortly

**Comment by Salokyn** [comment]
Works for me.
