### ISSUE TITLE
"Move to" feature

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#102]
I can't find a way to move a password to a folder when the list is long.
The list should scroll up when dragging a password to the top of the screen or a new menu entry "Move to..." should be added.

**Comment by marius-wieschollek** [comment]
Mass actions like moving to specific folders and selecting multiple passwords will be added next year as part of the NC 15 redesign.

However the scroll up should have worked and seems to be broken. I will release a fix for this in 2018.11.2.

**Comment by Salokyn** [comment]
Works for me, thank you!
