### ISSUE TITLE
[Search as I type] Double key stroke

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#104]
### System Information
- Nextcloud Version: 14.0.4
- PHP Version: 7.2
- Passwords Version: 2018.11.2
- Browser and Version: **Chrome 70** and **Chromium 69**
- Client OS and Version: **Windows 10** and **Fedora 28**
- Server OS and Version: **Debian 9**

### Steps to reproduce
1. Type on keyboard from Passwords app

### Actual result
I have only seen this behaviour on Chrome/Chromium browser (no problem with Firefox).

The search bar begins to fill but the first key appears twice. Then the following ones are OK.
Ex: If I type "123", then "1123" is written in the search bar.

If I clicked on the Magnifier glass before typing, there's no problem.

### Expected result
The first key stroke should appear only once when searching as I type.

**Comment by marius-wieschollek** [comment]
It seems like Chromium and Firefox handle the focus action differently here. Firefox will focus the field after the `keypress` event has been completed. Chromium will focus the field instantly and then behave as if you typed in that field. Calling `preventDefault()` on the event when the search box is focused seems to fix this issue.

**Comment by Salokyn** [comment]
I tested on Opera 57. It has the same behaviour than Chrome.

**Comment by marius-wieschollek** [comment]
This should now be solved in 2018.12.0
