### ISSUE TITLE
PHP 7.1.8 is no longer supported. Please check the system requirements.

### ISSUE THREAD

**Issue by MAngel666** [marius-wieschollek/passwords#105]
### System Information
- Nextcloud Version: 15
- PHP Version: 7.1.8
- Passwords Version: 2019.1.0-build2624
- Browser and Version: chrome/firefox
- Client OS and Version: Fedora 29
- Server OS and Version: Centos 7.6

### Actual result
I get this error in nextcloud/configuration/passwords

### Expected result
AFAIK 7.1.8 is still suported

**Comment by marius-wieschollek** [comment]
This notice does not relate to the official support of PHP versions by the PHP developers.
Instead this is about the _officially_ supported minimum requirements for the Passwords app.

_This does not necessarily mean that the app does not work on PHP 7.1 anymore_ and as long as there are no known issues with PHP 7.1 you will still be able to use and install the app. But if any issue related to PHP 7.1 arises in 2019, it will no longer be fixed. Also PHP 7.1 will definitely be dropped in 2020.1.

Providing support for a wide range of PHP and Nextcloud versions requires a lot of time that could be used to develop much wanted features instead. Therefore i will always use the first version of a new year to drop official support for older versions.

Also, PHP 7.1.8 was released on 2017-08-03 and the current version of PHP is 7.1.25. This means that you are missing around 1.5 years of security patches and bug fixes. You should definitely make sure to upgrade.
