### ISSUE TITLE
HTTPS error despite HTTPS working (Docker, NC15, Traefik)

### ISSUE THREAD

**Issue by poVoq** [marius-wieschollek/passwords#111]
### System Information
- Nextcloud Version: 15.0.2 (Nextcloud Apache Docker image)
- PHP Version: 7.2.
- Passwords Version: 2019.1.0 (latest from app store)
- Browser and Version: Firefox latest
- Client OS and Version: Solus Linux
- Server OS and Version: Official Nextcloud 15 Apache Docker image

### Actual result
![nc_passwords](https://user-images.githubusercontent.com/940360/51376844-8929a280-1b33-11e9-8de3-8fc9102a3441.jpg)

I guess it might have to do with how the Traefik reverse-proxy handles the HTTPS connection? Internally the Docker image runs via port 80 and the SSL connection is added by the reverse-proxy. This is a very typical setup for docker images so it would probably be good to add a workaround for this check.

**Comment by marius-wieschollek** [comment]
Please follow the suggestions in the message (Point 1&3 if you have a proxy setup) or look at #47 .

**Comment by poVoq** [comment]
Adding:
`'overwriteprotocol' => 'https',`
to the nextcloud config.php works. Thanks.
