### ISSUE TITLE
Unable to update or move password

### ISSUE THREAD

**Issue by ruslan-murzin** [marius-wieschollek/passwords#113]
### System Information
- Nextcloud Version: 15.0.2
- PHP Version: 7.2
- Passwords Version: 2019.1.0
- Browser and Version: Vivaldi 2.2.1388.37, Chrome 72.0.3626.81, Firefox ESR 52.9.0
- Client OS and Version: Ubuntu 18.04.1 LTS
- Server OS and Version: CentOS 7.6.1810

### Steps to reproduce
I simply installed NextCloud and some apps, added some passwords. After I created folder and tried to move passwords there and got "Moving password failed" error. After I tried to update existing passwords and got "Saving password failed" error. So the only I can do is create and delete passwords. I tried to find something via Google, forum, issues but found nothing.

### Actual result
Password can't be updated or moved to a folder.

### Expected result
Password should be updated/moved to a folder.

### Additional info
I checked PHP logs but there is no any error. I have no idea what can it be.

**Comment by marius-wieschollek** [comment]
Can you please check the Nextcloud Log  (Admin Settings -> Logging) for any log entries?

**Comment by ruslan-murzin** [comment]
The only error is: "is_file(): open_basedir restriction in effect. File(/usr/share/dict/words) is not within the allowed path(s)"

Is this path needed for the Password app?

**Comment by ruslan-murzin** [comment]
I installed "words" on server and granted access to /usr/share/dict/words to PHP. After those I got many errors because of (as I understood) disabled exec() function. In the app settings I choosed "Random Characters" for "Password Generator Service" and since that I have no errors in logs but the issue still remains.

**Comment by ruslan-murzin** [comment]
There is no error in the log. 

Response after editing (saving) and moving is "(failed) net::ERR_SPDY_PROTOCOL_ERROR"

**Comment by marius-wieschollek** [comment]
After a quick google search, the SPDY error seems to be Chrome (Webkit) related. Can you check what happens in Firefox?

**Comment by ruslan-murzin** [comment]
As I wrote in the header I tried 3 browsers, including Firefox. But now I decided to check answer from the server in Firefox (you asked me to do). And there I saw the app uses PATCH HTTP method witch was disabled on the server. After allowing this method everything works fine, thank you very much!
