### ISSUE TITLE
Favorite button doesn't work anymore

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#115]
### System Information
- Nextcloud Version: 15
- PHP Version: 7.2
- Passwords Version: 2019.2.0
- Browser and Version: Chrome 71
- Client OS and Version: Windows 10
- Server OS and Version: Debian Stretch

### Steps to reproduce
1. Click the star on the detail panel

### Actual result
The favorite status do not change (but a new revision is created)

### Expected result
The favorite status should switch

**Comment by marius-wieschollek** [comment]
Thanks for reporting this. Version 2019.2.1 should fix the issue.

**Comment by Salokyn** [comment]
I confirm, it works on version 2019.2.2.
