### ISSUE TITLE
Updating password overwrites name

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#117]
I'm not sure if this is an issue of the extension or the Passwords app itself. The problem is the following:

1. I add a password via the login detection of the webextension
2. I dislike the name it generated ("website - username") and edit it through the web interface of the app
3. I change the password of the site and click on "update password" from the webextension
4. I check back to the Passwords app and see that not only the password but also the name has been reset.

Is there a (simple) way to cure this? It's more of a nuisance than an actual problem...

**Comment by marius-wieschollek** [comment]
The api used by the browser extension does not support names, so the name is generated by the app. It should be not much effort to make sure that the name gets copied when the password is updated.

**Comment by marius-wieschollek** [comment]
This behavior will be changed in 2019.3. If you don't use the standard naming schema, the name will not be changed by the legacy api anymore.

You can install the update already if you check the "Show Nightly Updates" box in the admin settings. (May take some time until it shows up, depending on your server configuration)

**Comment by simonspa** [comment]
Thank you very much - that was yet another very, very quick fix!

**Comment by marius-wieschollek** [comment]
Released in 2019.3.0
