### ISSUE TITLE
[Feature] Folder Tree and Move To support

### ISSUE THREAD

**Issue by ongun-kanat** [marius-wieschollek/passwords#119]
I am struggling to organize my passwords. I imported them from a text file and most of them lacking a folder structure. It would be awesome that we can see the folder structure on the left sidebar move into the folders via scrolling. One additional thing is adding a "Move To" button as discussed in #102 but the issue seems to be closed without actually being implemented although NC 15 is released.

### System Information
- Nextcloud Version: 15.0.4
- PHP Version: 7.2.5
- Passwords Version:  2019.2.2

**Comment by marius-wieschollek** [comment]
The "Move To" feature is planned as part of the passwords app redesign to match the design updates introduced by Nextcloud 15. This will be done this year, but right now #80 is top priority.

As part of the redesign i will also look into ways to implement the folder tree option you suggested.

**Comment by abjoseph** [comment]
> Mass actions like moving to specific folders and selecting multiple passwords will be added next year as part of the NC 15 redesign.
> 
> However the scroll up should have worked and seems to be broken. I will release a fix for this in 2018.11.2.

Responding to the comment you made in #102, in addition to having the ability to perform "Mass" actions through either a checkbox or multi-selct, I think it would be equally convenient to be to able import into a folder. 

e.g I'm coming from Keepass2 where I had multiple kdbx files for different purposes and it would be really helpful if I could have pre-configured folders for each and import the kdbx files into their respective folders.

**Comment by marius-wieschollek** [comment]
@abjoseph Please make a separate ticket for this

**Comment by evgenyvasilchenko** [comment]
I imported a few hudreds credentials for my very complex infrastructure and now really struggling to organize them. Totaly support mentioned feature - Tree View, Multi-Select and Move To. I'm even willing to pay a bit to see these features added ASAP...

NextCloud 17.0.1

**Comment by Albirew** [comment]
I don't know if it should be considered as same "move to" support or if i should create a different issue for mass manipulation but here my thoughts that can be explored:
- import page can contain an "import in *folder_name*" to ease mass import. (should be easy to implement)
- you can add a tickbox column and a "..." menu on table headers for mass copy/move/delete operations (require more work to implement, especially if you want to add a drag'n'drop support like with "NxC files")

*NextCloud 21.0.3 with Passwords 2021.7.23*

**Comment by marius-wieschollek** [comment]
The mass actions are mentioned in other tickets too, so i will do that there.

What's coming with the next update is that you will be able to access the folders in the root directory directly from the sidebar.

**Comment by marius-wieschollek** [comment]
Is part of the release 2023.1.0
