### ISSUE TITLE
Just getting a blank page

### ISSUE THREAD

**Issue by poVoq** [marius-wieschollek/passwords#12]
I tried installing this plugin on my NC12.0.5 on a shared OVH host (runs NC quite crappy to be honest) but I just get a blank page. No error message in the NC log or the browser console that seems to be related.

Is there any requirement for this app to work? Maybe some security setting without it displays nothing?

**Comment by marius-wieschollek** [comment]
Hi. the [System requirements can be found in the wiki](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements)
Which browser are you using?
Which Database are you using?
Which version of PHP are you using?

**Comment by poVoq** [comment]
Latest Firefox, mysql, php7.1.

The requirements are general nextcloud ones, no?

**Comment by marius-wieschollek** [comment]
Yes, the only special requirements are HTTPS and optionally Imagemagick.
If you do not have HTTPS, you should get a warning.

Is it a completely blank page?

**Comment by poVoq** [comment]
I have HTTPS but get several warnings in my NC admin page about X-XSS protection etc. that I can't fix due to the shared-hosting environment.

Except for the NC menu bar at the top it is completely blank.

**Comment by marius-wieschollek** [comment]
That sounds like the app is not being loaded at all.

If you are using Firefox, please open the developer tools (Press F12), go to the "Network" tab and check if there are any 404, 40x or 50x errors. Also check if the script `passwords/js/Static/app.js` is loaded. (There should be a search window at the top right of the developer tools. Also you can sort by status code)

If you have XSS errors listed in the admin panel, maybe you can tell me which ones so i can reproduce them.

**Comment by poVoq** [comment]
No errors in the Network tab, all 200 and app.js is loaded.

Warnings are:
```

    php does not seem to be setup properly to query system environment variables. The test with getenv("PATH") only returns an empty response.
    Please check the installation documentation ↗ for php configuration notes and the php configuration of your server, especially when using php-fpm.

    The "X-XSS-Protection" HTTP header is not configured to equal to "1; mode=block". This is a potential security or privacy risk and we recommend adjusting this setting.
    The "X-Content-Type-Options" HTTP header is not configured to equal to "nosniff". This is a potential security or privacy risk and we recommend adjusting this setting.
    The "X-Robots-Tag" HTTP header is not configured to equal to "none". This is a potential security or privacy risk and we recommend adjusting this setting.
    The "X-Download-Options" HTTP header is not configured to equal to "noopen". This is a potential security or privacy risk and we recommend adjusting this setting.
    The "X-Permitted-Cross-Domain-Policies" HTTP header is not configured to equal to "none". This is a potential security or privacy risk and we recommend adjusting this setting.
    The "Strict-Transport-Security" HTTP header is not configured to at least "15552000" seconds. For enhanced security we recommend enabling HSTS as described in our security tips.

    The PHP OPcache is not properly configured. For better performance we recommend to use following settings in the php.ini:

    opcache.enable=1
    opcache.enable_cli=1
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.save_comments=1
    opcache.revalidate_freq=1
```

However even though I can use NC fine in Firefox, I noticed that Chrome started to refuse loading it all together (some months ago it was working), so I guess there is a more general issue with my Nextcloud on OVH shared hosting.

**Comment by marius-wieschollek** [comment]
That sounds strange.
But even if the hosting has some issues, the basic interface on the left should still be there.
Can you check if a requrest to `https://[domain]/apps/passwords/api/1.0/password/list` or anything with `/apps/passwords/api/1.0/` is made?
Can you post what the browser console says? Usually it's only the message "JQMIGRATE: Migrate is installed, version 1.4.0" from the core but nothing else.
Also if you open the app, does it redirect you to `https://[domain]/index.php/apps/passwords/#/` with the **#** at the end?

**Comment by poVoq** [comment]
> Also if you open the app, does it redirect you to https://[domain]/index.php/apps/passwords/#/ with the # at the end?

Yes

> Can you check if a requrest to https://[domain]/apps/passwords/api/1.0/password/list or anything with /apps/passwords/api/1.0/ is made?

Neither, but I generally get a lot of warning messages on the console, so that is a bit too much to post here.

**Comment by marius-wieschollek** [comment]
does it look something like this?
![grafik](https://user-images.githubusercontent.com/8255857/35646611-02b04164-06d0-11e8-9e4b-fa70dc58cc3e.png)

**Comment by poVoq** [comment]
Sorry, no I meant unrelated warning messaged that always show in the browser console when using that nextcloud instance.

I guess you app is fine, just my setup too messed up. I should probably migrate to a more suitable host.

**Comment by marius-wieschollek** [comment]
I have released a new version which changes some things in the app initialization. Maybe this solves your problem.

**Comment by poVoq** [comment]
Looks much better now, but I get the following error in the browser console and the loading indicator just keeps spinning.

```
Request failed 
Response { type: "basic", url: "https://mydomain.com/index.php/apps/passwords/api/1.0/password/list", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers, bodyUsed: false }
```

And if I try to create a new password entry I get "password creation failed" message with this error in the browser console:
```
Request failed 
Response { type: "basic", url: "https://mydomain.com/index.php/apps/passwords/api/1.0/password/create", redirected: false, status: 404, ok: false, statusText: "Not Found", headers: Headers, bodyUsed: false }
```

**Comment by marius-wieschollek** [comment]
Ok. looks like there is something wring with the url resolving. i will look into this

**Comment by mitchy112** [comment]
Got the same here, has something to do with passwords not recognizing that my instance is running on /Cloud instead of on the root. (just a wild guess)

**Comment by marius-wieschollek** [comment]
@mitchy112 this seems to be the problem. I have released a nightly build [to the appstore](https://apps.nextcloud.com/apps/passwords/releases) that fixes the base url issues.

**Comment by mitchy112** [comment]
@marius-wieschollek installed the nightly build, works like a charm.

**Comment by poVoq** [comment]
How do I enable nightly builds in the updater? I guess I need to manually install it?

**Comment by marius-wieschollek** [comment]
Yes, currently you can not install nightly builds automatically. See [Nextcloud #7417](https://github.com/nextcloud/server/issues/7417)

**Comment by marius-wieschollek** [comment]
2018.3 has been released, so i consider this error fixed.

**Comment by poVoq** [comment]
Yes with NC13 and version 2018.3 it seems to be working now. Thanks a lot!
