### ISSUE TITLE
[Feature] Multiple URLs for one password

### ISSUE THREAD

**Issue by techexo** [marius-wieschollek/passwords#121]
Hello,

Would it be possible (or is it already and I'm lost?) to add multiple URLs for one password entry in this app?

The use case is not to use one password for multiple sites, but more for websites that allow with one account to log to various versions of the site. For example, one Amazon account is enough to connect to amazon.fr, amazon.co.uk, amazon.com etc. I think it's the same for ebay.

Another possibility would be to be able to use joker/wildcards in the URL field: `amazon.*` or `ebay.*`.

Cheers

**Comment by marius-wieschollek** [comment]
See [this ticket](https://github.com/marius-wieschollek/passwords-webextension/issues/45) for the webextension. The app supports this as "Custom Fields", but the Extension currently doesn't.
