### ISSUE TITLE
2019.3 bad update

### ISSUE THREAD

**Issue by cyrg38** [marius-wieschollek/passwords#122]
update from 2019.2.2 to 2019.3.0 as proposed goes to unaccessible passwords

### System Information
- Nextcloud Version: 15.0.5
- PHP Version: 7.2
- Passwords Version: 2019.3.0
- Browser and Version: Firefox Quantum 65.0.1
- Client OS and Version: Debian 9
- Server OS and Version: debian 9

### Steps to reproduce
1. Tell us how to reproduce your issue.
upgrade from 2019.2.2 to 2019.3.0
2. Provide sample data if needed
3. Include relevant user settings and app settings if not standard
legacy upgrade of PHP modules on server-side was done simultaneously, if any of these were requisite of app, it could fail.

### Actual result
passwords are not showed to any user : the default page is loading...
HTTP 503 marked on api : 

> POST /index.php/apps/passwords/api/1.0/settings/get HTTP/1.1 503

> POST /index.php/apps/passwords/api/1.0/folder/show HTTP/1.1" 503 

### Expected result
fully functionnal app as before

**Comment by marius-wieschollek** [comment]
Can you check the Nextcloud Log from the Admin interface if there is any error message related to the 503 error?

**Comment by cyrg38** [comment]
closing the issue relative to upgrading php libs in between.
so nothing to do with current password app and upgrade : reenabled 2019.3 version without problems...

hint : connecting from another browser/OS the error was clearer listing all faillings php libs (zip, curl, gd, mbstring)
