### ISSUE TITLE
Can't remove Tags

### ISSUE THREAD

**Issue by ffuentes** [marius-wieschollek/passwords#123]
### System Information
- Nextcloud Version: 15.0.5
- PHP Version: 7.2.12
- Passwords Version: 2019.3.0
- Browser and Version: Google Chrome Versión 72.0.3626.119 (Build oficial) (64 bits)
- Client OS and Version: Ubuntu 18.04
- Server OS and Version: Ubuntu 16.04

### Steps to reproduce
1. Open details windows for a password.
2. Try to remove a tag by clicking **X**.

### Actual result
The tag is removed from the list but a few seconds later it appears again. The revision history gets updated.

### Expected result
Remove the tag from the password.

**Comment by marius-wieschollek** [comment]
fixed in the nightly, will be in 2019.4.0
