### ISSUE TITLE
API usage help

### ISSUE THREAD

**Issue by markuman** [marius-wieschollek/passwords#124]
I'm failing with the simplest things

What's the base url for the route `/api/1.0/password/list`? I've tried  `https://mynextcloud/apps/passwords/api/1.0/password/list` but this is obviously not the right url :)

Furthermore, I'd like to know how the payload (username, app password) object must look like for `/api/1.0/password/show`?

Can someone help me?

**Comment by marius-wieschollek** [comment]
You can take a look at the api documentation in the [wiki](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Index).

The url is most likely missing the `index.php` part. Usually you can't access the api from the browser, but you can use the following curl command to test it from the cli.

```
curl -u {user}:{token} https://{host}/index.php/apps/passwords/api/1.0/password/list

# If you're using the dev environment
curl -u admin:admin https://localhost/index.php/apps/passwords/api/1.0/password/list
```

The payload for the show command is a [json formatted object with the id of the password](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Api/Password-Api#the-show-action).
```
curl -u {user}:{token} -H "Content-Type: application/json" -X POST -d "{\"id\":\"{id}\"}" https://{host}/index.php/apps/passwords/api/1.0/password/show

# If you're using the dev environment
curl -u admin:admin -H "Content-Type: application/json" -X POST -d "{\"id\":\"3e1f2ee5-0c65-49f3-8161-b05005262177\"}" https://localhost/index.php/apps/passwords/api/1.0/password/show
```

You can always press F12 in the Nextcloud app and then take a look at the requests in the Network tab.
