### ISSUE TITLE
[Feature] Allow user  add tags to left sidebar to quick access

### ISSUE THREAD

**Issue by ffuentes** [marius-wieschollek/passwords#126]
Hi,
similar to the issue #119 I would like to have custom tags on the left sidebar.

That way the user can easy access most common tags and password. **Starring** is how you can do this now, but if you have many password, even the starring list is extensive.

**Comment by marius-wieschollek** [comment]
Not sure if that is what you wanted, but tags and the base folders can now be viewed from the left sidebar

**Comment by marius-wieschollek** [comment]
Is part of the release 2023.1.0
