### ISSUE TITLE
[FEATURE] Paste passwords the Linux way - with the middle mouse button

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#127]
### System Information
- Nextcloud Version: 15
- PHP Version: 7.2
- Passwords Version: 2019.3.0
- Browser and Version: Firefox 60 ESR
- Client OS and Version: Debian 9
- Server OS and Version: Debian 9

I don't know if it's technically possible, but It would be great that on Linux OSes, the "copy password" feature could store the password so we can paste it the Linux way as well, with the middle mouse button.

**Comment by marius-wieschollek** [comment]
I have checked this.
It looks like the JS-APIs offered by the browser do not allow access of the mouse selection clipboard.
The clipboard API exposed by the browser only gives access to the normal clipboard and the selection api only selects the text, but does not copy it to the mouse clipboard.

So at the current time, i see no way of implementing this feature.
