### ISSUE TITLE
Update issue nextcloud 13 > 15

### ISSUE THREAD

**Issue by zippytiff** [marius-wieschollek/passwords#128]
Hi

So i am just upgrading from nextcloud 13 to 15

one of the apps now 'not enabled' is Passwords

Im going from  2018.7.0-build2321 to 2019.3.0

Below are a few of the logs on update

{"reqId":"mPmdwScjSKCRo4Ff48oZ","level":3,"time":"2019-03-22T14:38:19+00:00","remoteAddr":"x.x.x.x","user":"nextcloud","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/passwords","message":"copy(/var/www/nextcloud/apps/passwords/passwords/lib/Migration/DatabaseRepair/PasswordRevisionRepair.php): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/legacy/helper.php#175","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36","version":"15.0.5.3","id":"5c94f3682ef67"}

{"reqId":"mPmdwScjSKCRo4Ff48oZ","level":3,"time":"2019-03-22T14:38:19+00:00","remoteAddr":"x.x.x.x","user":"nextcloud","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/passwords","message":"mkdir(): No such file or directory at /var/www/nextcloud/lib/private/legacy/helper.php#166","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36","version":"15.0.5.3","id":"5c94f3682ee7f"}

{"reqId":"mPmdwScjSKCRo4Ff48oZ","level":3,"time":"2019-03-22T14:38:19+00:00","remoteAddr":"x.x.x.x","user":"nextcloud","app":"PHP","method":"GET","url":"/index.php/settings/apps/update/passwords","message":"copy(/var/www/nextcloud/apps/passwords/passwords/lib/Services/FaviconService.php): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/legacy/helper.php#175","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36","version":"15.0.5.3","id":"5c94f3682ebfe"}

Any thoughts

ZT

**Comment by marius-wieschollek** [comment]
It looks like there were issues while unpacking the update file.

You can either update the app manually by downloading the file from the [app store](https://apps.nextcloud.com/apps/passwords) or you can uninstall the app completely and then install it again via Nextcloud. (I would recommend a database backup before doing so)

**Comment by zippytiff** [comment]
Ok, thank you

Looks like it won’t remove either

Could you fire me some commands to run from ssh ?

ZT

On 23 Mar 2019, at 09:06, M. Wieschollek <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like there were issues while unpacking the update file.

You can either update the app manually by downloading the file from the app store<https://apps.nextcloud.com/apps/passwords> or you can uninstall the app completely and then install it again via Nextcloud. (I would recommend a database backup before doing so)

**Comment by marius-wieschollek** [comment]
```
# Go to the apps folder
cd /var/www/nextcloud/apps/
# Check that the passwords app is there
ls -lAhs
# Remove the folder
rm -r passwords

# Download the current version
wget https://git.mdns.eu/nextcloud/passwords/-/jobs/7620/artifacts/raw/passwords.tar.gz
# Unpack it
tar -xf passwords.tar.gz
# Delete the update file
rm passwords.tar.gz

# Go to the main folder
cd /var/www/nextcloud
# Execute the Nextcloud upgrade from command line
./occ upgrade
```

**Comment by zippytiff** [comment]
Hi

That’s sorted it, thank you

ZT

**Comment by marius-wieschollek** [comment]
Great, then i will close this issue
