### ISSUE TITLE
Request to add the ability to add shares after the full name of the account and not just after the username.

### ISSUE THREAD

**Issue by skibi82** [marius-wieschollek/passwords#129]
In the case of integration with eg Zimbra drive , the username is as sid so there is a problem to add shared passwords by visible name and not on username.

Example username 04664929-bacf-43b6-bb99-60553899706d 
Fullname Karolina .......
In this case, you can not search for a user, for example, on the string 046 or after the name Karolina

**Comment by marius-wieschollek** [comment]
Please file a complete bug report using the template: https://github.com/marius-wieschollek/passwords/issues/new?labels=bug&template=Bug_report.md
