### ISSUE TITLE
Passwords on NC 13 ?

### ISSUE THREAD

**Issue by Gardakant** [marius-wieschollek/passwords#13]
Hi, first of all thanks for the great work :)
Just upgraded from NC 12.0.5 to NC 13.0.0 RC3 and I can't activate Passwords anymore :/

root@host1:/var/www/nextcloud# sudo -u www-data php occ app:enable passwords
                                                                                                     
  [Exception]                                                                                        
  App "Passwords" cannot be installed because it is not compatible with this version of the server.                                                                                                    

app:enable [-g|--groups GROUPS] [--] <app-id>

root@host1:/var/www/nextcloud#

You state Passwords works on "Nextcloud 12+", does that include NC13 or if this true for NC12* only ?

Regards

**Comment by Gardakant** [comment]
Think I got my answer:
```
<nextcloud min-version="12" max-version="12" />
```

**Comment by Gardakant** [comment]
changing max-version in info.xml did the trick

**Comment by marius-wieschollek** [comment]
You're just too fast for me... :smile: 
Yes, you're right, the app is intended to work for Nextcloud 13 as well, but of course there can always be small incompatibilities. Therefore is is currently limited to NC 12. In a few days the version 2018.2 will be released and it will be tested and compatible with Nextcloud 13.
