### ISSUE TITLE
iOS App ? integration with Nextcloud app ?

### ISSUE THREAD

**Issue by zippytiff** [marius-wieschollek/passwords#130]
Hi

the last bit of the passwords puzzle i feel is an ios app 

any views on this ?

could you pull one together ?

ZT

**Comment by marius-wieschollek** [comment]
I do not have any experience in developing iOS apps and I currently spend all my time on some much requested features for the main app and the next generation of the browser extension.

Apple only releases its developer tools on its own platforms (macOS & iOS) and requires an expensive developer account to publish to their app store.

The Android app by daper can technically run on iOS but it looks like he does not have the capacity to maintain it (for iOS). If you are willing to do that or know someone who is, feel free to contact him (see [issue](https://github.com/daper/nextcloud-passwords-app/issues/19)).

Feel free to continue this discussion in the [forum](https://help.nextcloud.com/c/apps/passwords).

**Comment by zippytiff** [comment]
Hi

I have reached out to ‘daper’, do you have a way to be contacted outside of Git ?

Hope he comes back, as I see this as a great ‘close the loop’ to the functionality of nextcloud and passwords

Regards

ZT
