### ISSUE TITLE
Password in chrome are wrongly displayed

### ISSUE THREAD

**Issue by jlord87** [marius-wieschollek/passwords#131]
Hello, I'm facing a bug:
editing a saved password in chrome may result in wrong password display.

I'm using Nextcloud 15.0.2, Ubuntu 18.04.2, Passwords 2019.3.0.

Step to reproduce:
- Save in chrome the credentials for nextcloud (I'm using username: "name.surname", password: "password").
- Create a new password in Passwords, where username is "name.surname" and password *is not* "password"
- save it. The password will be correctly displayed in "details".
- if you edit the password, the fields username and password will be populated with nextcloud saved password and not with the one you saved.

It seems to be just a visualization problem related to chrome (tried in windows and linux).
However it is very annoying, I AM name.surname, so the most of my usernames are "name.surname"...

If you need further testing or information, I'm here

thank you

**Comment by marius-wieschollek** [comment]
A fix for this has been released as nightly and will be in the next release.

**Comment by jlord87** [comment]
Nice, super, awesome, thank you!

**Comment by jlord87** [comment]
I've just updated the app to 2019.4.0 and I can confirm that the bug has been fixed, great job!
