### ISSUE TITLE
Exception: HMAC does not match. in nc log when loading passwords page

### ISSUE THREAD

**Issue by Sociopaat** [marius-wieschollek/passwords#133]
Getting the error shown below in the nextcloud log on a clean install every time i try to access the passwords page.
Keeps showing a loading circle on the passwords page and the page doesnt show up
Imported passwords will not show also

Debian 9.8
nginx install

[passwords] Error: Exception: HMAC does not match. at <<closure>>

 0. /var/www/nextcloud/apps/passwords/lib/Encryption/SseV1Encryption.php line 136
    decrypt("*** sensitive parameters replaced ***")
 1. /var/www/nextcloud/apps/passwords/lib/Services/EncryptionService.php line 89
    decryptObject("*** sensitive parameters replaced ***")
 2. /var/www/nextcloud/apps/passwords/lib/Helper/ApiObjects/AbstractObjectHelper.php line 111
    decrypt("*** sensitive parameters replaced ***")
 3. /var/www/nextcloud/apps/passwords/lib/Helper/ApiObjects/PasswordObjectHelper.php line 104
    getRevision(OCA\Passwords\Db\Password {id: 116}, {hidden: false,trashed: false})
 4. /var/www/nextcloud/apps/passwords/lib/Controller/Api/AbstractObjectApiController.php line 91
    getApiObject(OCA\Passwords\Db\Password {id: 116}, "model", {hidden: false,trashed: false})
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    list("model")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Passwords\Co ... {}, "list")
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Passwords\Co ... {}, "list")
 8. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("PasswordApiController", "list", OC\AppFramework\ ... {}, {_route: "passwo ... "})
 9. <<closure>>
    __invoke({_route: "passwo ... "})
10. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "passwo ... "})
11. /var/www/nextcloud/lib/base.php line 987
    match("/apps/passwords/api/1.0/password/list")
12. /var/www/nextcloud/index.php line 42
    handleRequest()

POST /index.php/apps/passwords/api/1.0/password/list

**Comment by marius-wieschollek** [comment]
Did you try to import passwords using version 2019.3.0 of the app?

**Comment by Sociopaat** [comment]
i did use version 2019.4.0 
but now i have got it working  
did clear the admin level caches, still not working.
used the user level "remove everything" again and the problem was solved.
database import went well after.
