### ISSUE TITLE
Translation error in french

### ISSUE THREAD

**Issue by marcatsmci** [marius-wieschollek/passwords#134]
**Current Status**
Error in french email translation

**Feature Description**
The phrase in the frame at the end of the mail not perfectly correct :
  * Voir les mots de passe partagé avec moi

Need to be :
  * Voir les mots de passe partagé**s** avec moi (missing **s**)

**Additional context**
2019.04.0 on NC 15.05

![password](https://user-images.githubusercontent.com/47881838/55463781-0a081e80-55fa-11e9-94fe-31ae8c2fa47a.png)

**Comment by marius-wieschollek** [comment]
I have released a nightly update with a fix for this.

You can install nightly updates by enabling the option Show Nightly Updates in "Apps" in the Passwords admin settings.
