### ISSUE TITLE
Easier sharing options for multiple passwords

### ISSUE THREAD

**Issue by Ra72xx** [marius-wieschollek/passwords#136]
**Current Status**
To share a password, you have to enter the details of every single password you want to share and use the share tab. It is not possible to multiselect password entries, or to share whole tags and/or folders.

**Feature Description**
Multiselect passwords to share, and share tags or folders.

**Additional context**
Nothing.

**Comment by Art4** [comment]
Sharing a folder would be very nice

**Comment by timboven** [comment]
dupp of #27

**Comment by lgnch** [comment]
Just as a note, this would be perfect if you can share as a folder, rather than individual, Then users can share the folder and achieve this, as well as work on passwords when dealing with large client bases.

**Comment by oxedgar** [comment]
i vote for this too
