### ISSUE TITLE
JSON of passman cannot be imported if there is no password set

### ISSUE THREAD

**Issue by jkischel** [marius-wieschollek/passwords#137]
### System Information
- Nextcloud Version: 15
- PHP Version: 7.3
- Passwords Version: 2019.4.1
- Browser and Version: doesn't depend on browser
- Client OS and Version: Windows 7
- Server OS and Version: Linux, but distribution unknown (using web hosting company)

### Steps to reproduce
Import a passman JSON export that does not contain a passwort (but some custom fields, use case here: store other sensible information that you don't want to store in simple text files; here: serial numbers for software)

### Actual result
Import will fail / will be rejected as there is no password field in the JSON object.

### Expected result
Data is successful with a blank or dummy password, and the related extra data (comments, custom fields, etc.) is present.

**Comment by marius-wieschollek** [comment]
I was unaware that passman allows entries without password.
Passwords requires a password so the only option here is to use a placeholder.

I also noticed that the passman import will currently handle custom fields wrong. I will fix that too and release an update.

**Comment by marius-wieschollek** [comment]
I have released a nightly update with a fix for this.

You can install nightly updates by enabling the option Show Nightly Updates in "Apps" in the Passwords admin settings.
