### ISSUE TITLE
Enpass export compatibility

### ISSUE THREAD

**Issue by rayfun** [marius-wieschollek/passwords#138]
### System Information
- Nextcloud Version: 15.0.7
- PHP Version:
- Passwords Version: 2019.4.1
- Enpass Version: 6.0.6 (323)
- Browser and Version:
- Client OS and Version:
- Server OS and Version:

### Steps to reproduce
1. Export passwords from Enpass, formats available .txt & .json
2. Import Enpass passwords in NC, only Enpass CSV supported

### Actual result
Can't import exported data from Enpass

### Expected result
Provide import mechanism for Enpass json

![Screenshot from 2019-04-26 11-13-47](https://user-images.githubusercontent.com/15213735/56797605-57506800-6815-11e9-8bca-ae5d944295b9.png)
![Screenshot from 2019-04-26 11-16-57](https://user-images.githubusercontent.com/15213735/56797620-5ddedf80-6815-11e9-8cb4-a9410de261da.png)

**Comment by marius-wieschollek** [comment]
It looks like Enpass has removed the CSV export and replaced it with a new export format.
I think it should be possible to write a converter for the JSON export.

**Comment by marius-wieschollek** [comment]
After looking at the format of the Enpass Json Export it seems like it consists of the tags (as folders) and the passwords which are a loose set of individual fields.

I think i can write some mapping algorithm that tries to match the fields in each password to our standard fields and save all remaining fields as custom fields. 
The tags can be imported without much editing. The categories seem to be like our folders, so i would import them a such.
