### ISSUE TITLE
load csv from legacy password app ?

### ISSUE THREAD

**Issue by Gardakant** [marius-wieschollek/passwords#14]
Hi, is there a way to load a csv export from legacy password app into the new app ?

**Comment by marius-wieschollek** [comment]
Not yet, but with the next version.
If you had the legacy app, you can use the [migration guide](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration) to import the database. If the migration did not start automatically, take a look at the [f.a.q](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration#migration-does-not-start)

**Comment by Gardakant** [comment]
Sadly I didn't backup the database before uninstalling the old app so I can't use the migration procedure (I did look at it and cried when I discovered this procedure existed :))

**Comment by marius-wieschollek** [comment]
Nextcloud usually does not delete old tables, even when the app is uninstalled or does no longer use them.

If you have access to the database (mysql workbench, cli interface etc.) you can check if the tables [mentioned in the backup step](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration#database-backup) still exist (or just go for it). If they are, you can use the commands in "[Migration does not start](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration#migration-does-not-start)" to restart the migration.
_Note: the migration imports all passwords everytime._

**Comment by Gardakant** [comment]
ok, I didn't say it all : I deleted all oc_passwords% table manualy before installing new app. All I have is the csv export from prevous app :/

**Comment by marius-wieschollek** [comment]
Then you will have to wait for the next version

**Comment by Gardakant** [comment]
no problem, an estimation for the release date ?

**Comment by marius-wieschollek** [comment]
This weekend. i will leave a notice when the nightly has the import

**Comment by Gardakant** [comment]
you rock :)

**Comment by marius-wieschollek** [comment]
I thought if _someone_ would be willing to try out the highly experimental legacy import support in the [nightly build](https://apps.nextcloud.com/apps/passwords#downloads), it would probably be you.

Click on "More" in the lower left corner of the app and then on "Backup" => "Import" and select "ownCloud Passwords" as format. I can't guarantee for anything, but it should work.

**Comment by Gardakant** [comment]
I'll try it right now

**Comment by Gardakant** [comment]
It works like a charm, import was successful for all my passwords !!

**Comment by Gardakant** [comment]
thanks a million times Marius
