### ISSUE TITLE
API: 1.0/folder/list detailLevel does not affect the result

### ISSUE THREAD

**Issue by pvanek** [marius-wieschollek/passwords#141]
### System Information
- Nextcloud Version: 15.0.7
- PHP Version: 7.2.5
- Passwords Version: 2019.4.2
- Browser and Version: not related/any
- Client OS and Version: not related (Linux, openSUSE Leap 15.0)
- Server OS and Version: openSUSE Leap 15.0

### Steps to reproduce
1. use any http client (browser, curl, ...)
2. ` curl -u user:pass -X POST -d '{"detailLevel":"model+folders+passwords+parents"}' -H "Content-Type: application/json" https://.../index.php/apps/passwords/api/1.0/folder/list`
vs
`curl -u user:pass https://.../index.php/apps/passwords/api/1.0/folder/list`
3. n/a

### Actual result
I set up passwords app with some passwords items and one folder (with pass items) just for evaluation. Also I'm trying to write my own desktop frontend for it. But responses from POST `/api/1.0/folder/list` with various detailLevel is the same as in GET

### Expected result
I would expect to see expanded info as described in docs

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
no errors from 'passwords' app
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
POST:
https://.../index.php/apps/passwords/api/1.0/folder/list
Body:
{"detailLevel":"model+parent+folders+passwords"}

response:
[{"id":"4f157ed1-b2d8-4f36-addf-c213cbc7d514","created":1556797672,"updated":1556797672,"edited":1556797672,"revision":"b60f6743-ede5-4a2b-8de3-8e63b2d86942","label":"test","parent":"00000000-0000-0000-0000-000000000000","cseType":"none","sseType":"SSEv1r1","hidden":false,"trashed":false,"favorite":false}]
```

vs

```
GET:
https://.../index.php/apps/passwords/api/1.0/folder/list
Body: none

response:
[{"id":"4f157ed1-b2d8-4f36-addf-c213cbc7d514","created":1556797672,"updated":1556797672,"edited":1556797672,"revision":"b60f6743-ede5-4a2b-8de3-8e63b2d86942","label":"test","parent":"00000000-0000-0000-0000-000000000000","cseType":"none","sseType":"SSEv1r1","hidden":false,"trashed":false,"favorite":false}]
```
</details>

The problem is that the response is exactly the same as in GET without detailLevel

**Comment by marius-wieschollek** [comment]
I am sorry. The parameter name "detailsLevel" in the documentation is wrong. The correct parameter name is "details". I will update the documentation to fix that error.

The parameter for the parent folder is "parent" not "parents".

The following request should work:
```
curl -u user:pass -X POST -d '{"details":"model+folders+passwords+parent"}' -H "Content-Type: application/json" https://host/index.php/apps/passwords/api/1.0/folder/list
```

**Comment by pvanek** [comment]
excellent. It works now. Confirmed.
