### ISSUE TITLE
Use Nextcloud authentication after being inactive

### ISSUE THREAD

**Issue by florianwgnr** [marius-wieschollek/passwords#143]
Passwords app can be opened at any time when the user is logged in to his account - no matter when he logged in. Even if the user logs in, surfs the web and after x minutes tries to open the app.
Might be useful, but is a risk to everyone who stays logged in for a longer period of time. 

Better: Use a dialogue - just like the authentication needed for installing or activating apps after being logged in for some time - to confirm its still the right user who wants his passwords and not someone else.

**Comment by marius-wieschollek** [comment]
#80 will provide an option for that
