### ISSUE TITLE
'Auto' deactivation

### ISSUE THREAD

**Issue by mb-bibi** [marius-wieschollek/passwords#144]
### System Information
- Nextcloud Version: 15.0.7
- PHP Version: 7.3.5
- Passwords Version: 2019.5.0
- Browser and Version: Firefox 66.0.5
- Client OS and Version: Windows 10 / 1809
- Server OS and Version: CentOS 7.6.1810 (Core)‬

### Steps to reproduce
1. 
not possible without further request, because nextcloud and all other add ons are running without any problem
2. 
3. 

### Actual result
Password add on is disabled short time (max. minutes) after being activated without any action, cloud only connected by desktop app, no open browser tab (window) with cloud login. For the short time, password add on is running all works as it should do.

### Expected result
What should happen?

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

Error	no app in context	TypeError: Return value of OCA\Passwords\AppInfo\Application::registerController() must be an instance of OCA\Passwords\AppInfo\void, none returned
    /var/www/vhosts/[domain]/[subdomain].de/apps/passwords/lib/AppInfo/Application.php - line 72:
    OCA\Passwords\AppInfo\Application->registerController()
    /var/www/vhosts/[domain]/[subdomain].de/apps/passwords/lib/AppInfo/Application.php - line 57:
    OCA\Passwords\AppInfo\Application->registerDiClasses()
    /var/www/vhosts/[domain]/[subdomain].de/apps/passwords/appinfo/app.php - line 8:
    OCA\Passwords\AppInfo\Application->__construct()
    /var/www/vhosts/[domain]/[subdomain].de/lib/private/legacy/app.php - line 261:
    require_once("/var/www/vh ... p")
    /var/www/vhosts/[domain]/[subdomain].de/lib/private/legacy/app.php - line 154:
    OC_App::requireAppFile("passwords")
    /var/www/vhosts/[domain]/[subdomain].de/lib/private/legacy/app.php - line 127:
    OC_App::loadApp("passwords")
    /var/www/vhosts/[domain]/[subdomain].de/cron.php - line 53:
    OC_App::loadApps()
	
2019-05-09T10:30:03+0200
-- | -- | -- | --

```
See Settings > Log  (Copy Raw)
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
Can you please check the PHP setup on your server?

I assume your Web-Server uses PHP 7.3, but the stack trace you posted suggests that the cli still uses PHP 7.0 to execute your cron jobs. (The php version and configuration used by default differs depending on where you use it: cli, cgi, fpm or apache-mod)

`php -v` will show you the used PHP version and you may have to edit you cron command to somthing like 
```
*/5 * * * * /usr/bin/php7.3 /var/www/html/cron.php
```

**Comment by marius-wieschollek** [comment]
If you have any further questions, please visit our forum.
