### ISSUE TITLE
[Bug] Modified/Last updated date is wrong

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#146]
### System Information
- Nextcloud Version: 15
- PHP Version: 7.3
- Passwords Version: 2019.5.0
- Server OS and Version: Debian Stretch

### Steps to reproduce
1. Update an existing password
2. Check its "Last updated" field

### Actual result
"Last updated" field in details or "Modified" column = "Created on" field

### Expected result
Last updated date should be taken from the righgt field.

**Comment by marius-wieschollek** [comment]
The "Last updated" field should be changed by the client if the actual password is updated. Other changes such as the label or notes are ignored here.

**Comment by Salokyn** [comment]
I did not know that. It seems fine then.
Maybe 2 different fields would be useful? One for the last edition of the actual password and one for the last revision?

**Comment by marius-wieschollek** [comment]
You can see the individual changes in the "Revisions" tab. Technically the data is available to add a last modified field. If you want that or if you want the option to use the modified date instead of the last updated date in the app in general, feel free to make a feature request.
