### ISSUE TITLE
password sharing problem, still in sync 

### ISSUE THREAD

**Issue by Arnaudfly** [marius-wieschollek/passwords#148]
Hello, I have a problem sharing passwords:
When I share the synchronization does not end with the account of the used with whom I share, it only turns in a vacuum. capture.jpg
And when I'm going to control the sharing on the user's account, the sharing does not match ... While if I check it tells me that the sharing has been done. Capture2.jpg

thank you for your reply
a hello from France

### System Information
- Nextcloud Version: 16.0.1
- PHP Version: 7.2
- Passwords Version: 2019.5.0
- Browser and Version:
- Client OS and Version:
- Server OS and Version:

**Comment by Arnaudfly** [comment]
![Capture](https://user-images.githubusercontent.com/48674002/58162292-38ad8780-7c82-11e9-9a13-bd7177930fb3.JPG)
![Capture2](https://user-images.githubusercontent.com/48674002/58162293-38ad8780-7c82-11e9-9ca9-b228560016cf.JPG)

**Comment by marius-wieschollek** [comment]
The amount of shares displayed in the statistics section only means that you created the share, not that the creation process has been finished.

In the sharing section the spinning circle means that the synchronization with the other account is still in progress. This is usually done by a background job and might take some minutes depending on how your Nextcloud executes background jobs.
It might be possible that the background job crashed for some reason in which case you should find a log entry in the Nextcloud log in the admin section.
