### ISSUE TITLE
X-Forwarded-Proto

### ISSUE THREAD

**Issue by Lennix** [marius-wieschollek/passwords#15]
I really like that the app checks if its running on https. Unfortunately I'm running nextcloud behing a reverse proxy which prevents me from using the app.

Checking "X-Forwarded-Proto" would fix this problem :)

**Comment by marius-wieschollek** [comment]
The "X-Forwarded-Proto" header could be set by anyone, not just a proxy, so it's not a good way to detect HTTPS.
If you are running Nextcloud behind a proxy that does HTTPS offloading [use the overwriteprotocol setting](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations) to configure Nextcloud to use HTTPS anyway.

**Comment by Lennix** [comment]
Yes, its much easier to always send X-Forwarded-Proto instead of just activating https to use this app. Sorry, but that doesn't make sense...
Just add a check for X-Forwarded-Proto in your checkIfHttpsUsed() and the user doesn't have to change anything if working behind a proxy.

**Comment by marius-wieschollek** [comment]
Will be fixed in 2018.3
