### ISSUE TITLE
[Feature] Support Nextcloud Accessibility themes

### ISSUE THREAD

**Issue by madmath03** [marius-wieschollek/passwords#151]
**Current Status**
Starting with NextCloud 14, users have access to an "Accessibility" menu in their profile settings, allowing High contrast theme and Dark theme, but those themes are not applied to NextCloud Passwords app.

**Feature Description**
Expecting NextCloud Passwords to adapt its display based on the user accessibility settings.

**Additional context**
N/A

**Comment by marius-wieschollek** [comment]
Dark mode support was added in [2019.1.0](https://github.com/marius-wieschollek/passwords/blob/master/CHANGELOG.md#added-3). I just checked and all the themes seem to work just fine for me.
Is there something not working for you and can you go into details about that?

**Comment by madmath03** [comment]
OK, that explains the behavior I get then : themes basically not applied on popups and such
![image](https://user-images.githubusercontent.com/6967675/58665393-0b6f7200-8331-11e9-8bd4-4a561fd0b36f.png)


Release 2019.1.0 is only available starting NC 15, which is why it's not handled in NC 14 (Passwords 2018.12.0 installed).
I guess I just need to upgrade to NC 15.

I will close this ticket.
Thanks for your help.
