### ISSUE TITLE
appinfo/app.php is missing in 2019.6.0

### ISSUE THREAD

**Issue by donb9000** [marius-wieschollek/passwords#152]
It appears than appinfo/app.php is missing from the 2019.6.0 release. It may have even been deleted on purpose: https://github.com/marius-wieschollek/passwords/compare/535af5b...cc9ec16#diff-bcd4577cde4675ff93a95ed853d3690a

However Nextcloud 15.0.7 is not happy with this.

I've reinstalled passwords 2019.5.0 but now when I go to the passwords app page, it is completely blank.

How do I resolve this issue?

### System Information
- Nextcloud Version: 15.0.7
- PHP Version: 7.3.6
- Passwords Version: 2019.6.0
- Browser and Version: Firefox 67.0
- Client OS and Version: Arch Linux
- Server OS and Version: Arch Linux

### Steps to reproduce
1. Updated passwords app from 2019.5.0 to 2019.6.0 via admin's Apps page

### Actual result
Nextcloud became unresponsive. The following error appeared in the nextcloud log:

[PHP] Error: require_once(): Failed opening required 'passwords/appinfo/app.php' (include_path='/usr/share/webapps/nextcloud/3rdparty/pear/archive_tar:/usr/share/webapps/nextcloud/3rdparty/pear/console_getopt:/usr/share/webapps/nextcloud/3rdparty/pear/pear-core-minimal/src:/usr/share/webapps/nextcloud/3rdparty/pear/pear_exception:/usr/share/webapps/nextcloud/apps') at /usr/share/webapps/nextcloud/lib/private/legacy/app.php#261

GET /nextcloud/settings/apps/update/passwords
from 192.168.37.4 by admin at 2019-06-01T12:43:49+00:00

### Expected result
The app should update and nextcloud should work.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
See Settings > Log  (Copy Raw)
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
I'm so far unable to reproduce this error. The app.php file is no longer required and is usually just loaded by Nextcloud after a ckeck if it's actually there. I tried the update from the app store several times on the Nextcloud 15.0.7 docker container and did not see any error.

I would recommend to install the update manually and run `./occ upgrade` from the command line.

You said that "Nextcloud became unresponsive.". What do you mean by that?

**Comment by donb9000** [comment]
> You said that "Nextcloud became unresponsive.". What do you mean by that?

I kept getting "This page is temporarily unavailable" from NGINX. I later discovered that it was because after the update failed, nextcloud was left in maintenance mode. That is a red herring. Sorry.

> I would recommend to install the update manually and run ./occ upgrade from the command line.

I apologize, but I don't think I have proper manual install instructions. I've not done that before this morning and I don't think I did it correctly. The passwords-2019.5.0.tar.gz tar file I downloaded from github had a bunch of extra stuff around the "src" directory. I removed all the extra stuff and pushed everything in src to .. and rmdir'd the src directory. This is what I'm running now, but I don't get anything on the passwords app page as a user.

I compared the contents of that tar file with one downloaded from https://git.mdns.eu/nextcloud/passwords/-/jobs/8098/artifacts/raw/passwords.tar.gz . This tar file has none of the extra stuff, but it contains the 2019.6.0 version (I think) and this is the one that didn't work for me after pushing the app update button in the admin GUI.

Should I do the following:

1) put nextcloud into maintenance mode
2) remove old apps/passwords directory
3) untar passwords.tar.gz from the git.mdns.eu link above into the apps directory
4) ./occ upgrade
5) turn maintenance mode off

Thanks for your help.

**Comment by marius-wieschollek** [comment]
The github releases contain the source code and would need some assembly. Always download the app from the app store where you can also find older versions (see [here](https://apps.nextcloud.com/apps/passwords/releases?platform=15#15)).

Your steps for the upgrade seem correct. The link you have is for the 2019.6.0 version. If you want to, you can also install the 2019.5.0 version from the store, then check the app, make a backup if everything works (`./occ passwords:backup:create`) and then install 2019.6.0 manually again.

**Comment by donb9000** [comment]
Thank you for your help. I manually installed 2019.5.0 (from the app store), created a backup, and then manually installed 2019.6.0.

Everything seems to be working now.
