### ISSUE TITLE
Nextcloud - Passwords - Did not expect more than one result when executing: query

### ISSUE THREAD

**Issue by SpamReceiver** [marius-wieschollek/passwords#153]
Passwords app doesn't work anymore, spinning wheel keeps displaying.

Nextcloud of entry:
{"reqId":"S5RtL6UXiLcpCQxKeYor","level":3,"time":"2019-06-01T20:09:52+00:00","remoteAddr":"XXX","user":"XXX","app":"passwords","method":"POST","url":"\/nextcloud\/index.php\/apps\/passwords\/api\/1.0\/folder\/show","message":{"Exception":"OCP\\AppFramework\\Db\\MultipleObjectsReturnedException","Message":"Did not expect more than one result when executing: query \"SELECT * FROM `*PREFIX*passwords_entity_password_revision` WHERE (`deleted` = :dcValue1) AND (`user_id` = :dcValue2) AND (`uuid` = :dcValue3)\"; ","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/QBMapper.php","line":321,"function":"findOneQuery","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->","args":[{"__class__":"OC\\DB\\QueryBuilder\\QueryBuilder"}]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Db\/AbstractMapper.php","line":167,"function":"findEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->","args":[{"__class__":"OC\\DB\\QueryBuilder\\QueryBuilder"}]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Db\/AbstractMapper.php","line":140,"function":"findOneByFields","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->","args":[["uuid","04e4132f-7293-4234-be42-c123c74c703d",2,"eq"]]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Db\/AbstractMapper.php","line":65,"function":"findOneByField","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->","args":["uuid","04e4132f-7293-4234-be42-c123c74c703d"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Services\/Object\/AbstractRevisionService.php","line":94,"function":"findByUuid","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->","args":["04e4132f-7293-4234-be42-c123c74c703d"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/ApiObjects\/AbstractObjectHelper.php","line":108,"function":"findByUuid","class":"OCA\\Passwords\\Services\\Object\\AbstractRevisionService","type":"->","args":["04e4132f-7293-4234-be42-c123c74c703d"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/ApiObjects\/PasswordObjectHelper.php","line":104,"function":"getRevision","class":"OCA\\Passwords\\Helper\\ApiObjects\\AbstractObjectHelper","type":"->","args":[{"id":22,"__class__":"OCA\\Passwords\\Db\\Password"},{"hidden":"*** sensitive parameter replaced ***","trashed":"*** sensitive parameter replaced ***"}]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/ApiObjects\/FolderObjectHelper.php","line":247,"function":"getApiObject","class":"OCA\\Passwords\\Helper\\ApiObjects\\PasswordObjectHelper","type":"->","args":[{"id":22,"__class__":"OCA\\Passwords\\Db\\Password"},"model",{"hidden":"*** sensitive parameter replaced ***","trashed":"*** sensitive parameter replaced ***"}]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Helper\/ApiObjects\/FolderObjectHelper.php","line":109,"function":"getPasswords","class":"OCA\\Passwords\\Helper\\ApiObjects\\FolderObjectHelper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Controller\/Api\/AbstractObjectApiController.php","line":142,"function":"getApiObject","class":"OCA\\Passwords\\Helper\\ApiObjects\\FolderObjectHelper","type":"->","args":[{"id":null,"__class__":"OCA\\Passwords\\Db\\Folder"},"model+folders+passwords"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"show","class":"OCA\\Passwords\\Controller\\Api\\AbstractObjectApiController","type":"->","args":["00000000-0000-0000-0000-000000000000","model+folders+passwords"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\FolderApiController"},"show"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\FolderApiController"},"show"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["FolderApiController","show",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"passwords.folder_api.show"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"passwords.folder_api.show"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"passwords.folder_api.show"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/passwords\/api\/1.0\/folder\/show"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/public\/AppFramework\/Db\/QBMapper.php","Line":257,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}

**Comment by marius-wieschollek** [comment]
Did you do something specific before that happened?

**Comment by SpamReceiver** [comment]
Nothing that I would be aware of. The misbehaviour is like this for some days now, but only today I had time to look at the logs.  The misbehavior survived updates of Nextcloud as well as of the Password app. I use the Firefox app to access the stored passwords, and this method still works.

**Comment by marius-wieschollek** [comment]
Do you have database access?
Can you execute the query ```SELECT * FROM `*PREFIX*passwords_entity_password_revision` WHERE `uuid` LIKE '04e4132f-7293-4234-be42-c123c74c703d' ``` (where `*PREFIX*` is your database prefix if you have any)
If more than one row is returned, check the `model` column if it is the same. If it is, you should be able to just change the uuid of one of the entries and be find. After that you can check the app again and search for the id you found in the model column with `id:the-long-id`. This should tell you which entry made the issue.

**Comment by SpamReceiver** [comment]
Hm, strange. There is no table at all that begins with oc_passwords. Maybe that's the problem?

**Comment by marius-wieschollek** [comment]
If there table did not exist, the app would not work at all. Have you selected the database with `USE databasename`?

**Comment by SpamReceiver** [comment]
Yes, I was wrong. The table is there.I'll try your query tomorrow with a PC, not a smartphone...

**Comment by SpamReceiver** [comment]
Thank you very much, again. The query indeed returned two entries;
changing one of the UUIDs solved the issue.

However, I didn't find the model id anywhere on the UI. So, I can't be
sure about the entry. No matter, the problem is solved.

Thank you!


Am 01.06.2019 um 23:07 schrieb M. Wieschollek:
