### ISSUE TITLE
[Feature] Multiple URLs support

### ISSUE THREAD

**Issue by yukiisbored** [marius-wieschollek/passwords#154]
**Current Status**
At the moment, you can only have one URL for each identity/login. This is a problem for sites with unified logins like Amazon and eBay where the credentials are the same but they're on different domains (e.g amazon.com vs amazon.fr).

**Feature Description**
It would be ideal to have a way to add more URLs into each identity. UI wise, it can be a simple plus (+) icon right beside the URL textbox.

**Comment by marius-wieschollek** [comment]
There is already an option to add custom fields which can be used to store additional urls

**Comment by simonspa** [comment]
I am able to add additional URLs using the "link" type for custom fields - however, these do not seem to be searched by the browser plugin to match against the current domain.

I guess @yukiisbored meant to have multiple URLs to match agains one password entry.

**Comment by marius-wieschollek** [comment]
The browser extension has its own issue tracker. The development version matches the url of the tab against all urls in the password.

**Comment by ChameleonScales** [comment]
I think a more intuitive way to have this in the app would be to have a "+" button next to the Website field that would add a line. Does that seem like a good idea?
