### ISSUE TITLE
Error when importing Enpass JSON export file

### ISSUE THREAD

**Issue by rayfun** [marius-wieschollek/passwords#155]
Hi,

When trying to import an Enpass JSON export file, I get the error:
"Import error - Cannot read property 'length' of undefined"

Any other info I could provide?

![Screenshot from 2019-06-10 20-34-45](https://user-images.githubusercontent.com/15213735/59218071-a41eb100-8bbf-11e9-978f-45a1a092c0ed.png)
![Screenshot from 2019-06-10 20-34-30](https://user-images.githubusercontent.com/15213735/59218073-a4b74780-8bbf-11e9-88c5-5dc52bfe29f1.png)

Regards,
rayfun

**Comment by marius-wieschollek** [comment]
It would be great if you could check the browser console (Press F12 or right click and select "Inspect" and open the "Console" tab). If there are any errors listed, please paste them here (including the stack trace)

**Comment by rayfun** [comment]
```
BackupSection.cc8cdb9fb0f7fb0e390c.js:1 TypeError: Cannot read property 'length' of undefined
    at Function._processTags (ImportManager.cc8cdb9fb0f7fb0e390c.js:1)
    at async Function.processJson (ImportManager.cc8cdb9fb0f7fb0e390c.js:1)
    at async Function._convertInputData (ImportManager.cc8cdb9fb0f7fb0e390c.js:1)
    at async p.importDatabase (ImportManager.cc8cdb9fb0f7fb0e390c.js:1)
(anonymous) @ BackupSection.cc8cdb9fb0f7fb0e390c.js:1
```

**Comment by marius-wieschollek** [comment]
I have pushed a check which should prevent the issue in the current nightly.

You can install nightlies by enabling `Show Nightly Updates in "Apps"` in the admin settings.

**Comment by rayfun** [comment]
Getting a new error now:
```
BackupSection.54be5e031309e457f0b8.js:1 ReferenceError: Cannot access 't' before initialization
    at Function.processJson (ImportManager.54be5e031309e457f0b8.js:1)
    at Function._convertInputData (ImportManager.54be5e031309e457f0b8.js:1)
    at c.importDatabase (ImportManager.54be5e031309e457f0b8.js:1)
    at A.importDb (BackupSection.54be5e031309e457f0b8.js:1)
(anonymous) @ BackupSection.54be5e031309e457f0b8.js:1
```

**Comment by rayfun** [comment]
Looks good now.

Just a couple (6) of errors of type:
```
The label of "i agree to the terms of use and privacy policy required" in "X-plane" exceeds 48 characters and was cut. {label: "X-plane", field: "i agree to the terms of use and privacy policy required"}
```

Apart from that the import worked.

Maybe the message "Import partially failed" is a little bit harsh in that case?

Thanks,
rayfun
