### ISSUE TITLE
Add screeenly as Website Preview Service

### ISSUE THREAD

**Issue by GrillGuth** [marius-wieschollek/passwords#156]
**Current Status**
Several Website Preview Service are already supported. 
**Feature Description**
"Screeenly" could be added as additional Website Preview Service. The hosted service provides free screenshot generation. Furthermore, by not only allowing to specify the Screeenly API Key but also the Screeenly API URL a self hosted version can be used. 

**Additional context**
https://secure.screeenly.com/
https://github.com/stefanzweifel/screeenly
Screeenly is already integrated in e.g. [Nextcloud Bookmarks](https://github.com/nextcloud/bookmarks)

**Comment by marius-wieschollek** [comment]
Good idea. The feature will be in 2019.7.0 and is already available as nightly.

You can install nightlies by enabling `Show Nightly Updates in "Apps"` in the admin settings.

**Comment by marius-wieschollek** [comment]
@GrillGuth During testing i noticed that the service was not spelled correctly within passwords. I fixed that but this means that if you're using the service already, you will have to update the admin settings again.

Also, if you have one of the 2019.7.1 nightlies installed you will have to upgrade the app manually by downloading the package from the app store and deploying the files to your server.
