### ISSUE TITLE
Gateway timeout when accessing administrative settings

### ISSUE THREAD

**Issue by punk-t** [marius-wieschollek/passwords#161]
Hello!
I use your app (2019.6) on a NC 15.0.7 installation. All features seem to function normally except global app settings (user settings work normally). 
When I try to open administrative settings, I get an error 504 after a respectable amount of time. 

My providers Apache installation makes use of php-fpm without a configured Proxy timeout (hints according to apache_error.log), so to be honest I'm not sure whether this issue is really yours. I already read about some problems with php-fpm (PHP 7.3) and this behaviour in some forums.

Nextcloud itself doesn't log anything related.

On the other hand this error occurres only when trying to access this very page, all other things work as expected.

Greetings
 Punkt

### System Information
- Nextcloud Version: 15.0.7
- PHP Version: 7.3
- Passwords Version: 2019.6
- Browser and Version: all / browser independent
- Client OS and Version: tested with: Androids, Win (multiple), Linux 
- Server OS and Version: CentOS / Provider: Uberspace

### Steps to reproduce
1. Pls see description above

### Actual result
Error 504 Gateway timeout

### Expected result
I should see administrative settings page.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

{"reqId":"ZNZuu0bo8vbGkxH559DM","level":1,"time":"2019-06-30T16:45:03+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"15.0.7.0","id":"5d18e826cc7d6"}

----

{"reqId":"ZNZuu0bo8vbGkxH559DM","level":1,"time":"2019-06-30T16:45:03+00:00","remoteAddr":"","user":"--","app":"cli","method":"","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"15.0.7.0","id":"5d18e826cc804"}
</details>

### Browser log
<details>
<summary>Browser log</summary>
see screenshots attached

![firefox](https://user-images.githubusercontent.com/11180677/60399716-3be14080-9b69-11e9-8059-5e3681fc2cb4.PNG)

![chrome](https://user-images.githubusercontent.com/11180677/60399722-4a2f5c80-9b69-11e9-8822-600ab016addd.PNG)

</details>

**Comment by marius-wieschollek** [comment]
Can you please fill out the bug report form with all the requested data.

**Comment by punk-t** [comment]
Form filled in my first post. Feel free asking for special tasks / further investigation - this NC installation is actually not an productive one so we can hack it like hell :)

**Comment by marius-wieschollek** [comment]
Can you try to update to the current 2019.7.1 version?

Regarding the error you found in your log i could only find [this](https://help.nextcloud.com/t/nc13-memcache-oc-memcache-apcu-not-available-for-local-cache/31027). It does not seem to be related to the issue because according to the log entry the request causing the error was made from cli, not from web.

**Comment by punk-t** [comment]
Okay, great stuff! 2019.7.1 magically fixes my issue, thanks a lot.

Regarding to my MemCache Error: this is documented as expected behaviour due to my provider.
