### ISSUE TITLE
Web UI doesn't save custom field when editing password

### ISSUE THREAD

**Issue by ricalo** [marius-wieschollek/passwords#165]
### System Information
- Nextcloud Version: 16.0.2
- PHP Version: 7.3.2
- Passwords Version: 2019.7.1
- Browser and Version: Firefox 67.0.4
- Client OS and Version: Ubuntu 18.04
- Server OS and Version: FreeBSD 11.2-STABLE

### Steps to reproduce
1. Go to the passwords web UI interface at https://[nextcloud]/apps/passwords/#/
1. Click **Edit** on the overflow menu.
1. Expand the **Custom Fields** section.
1. Enter a name and value for the custom field.
1. Click **Save** at the bottom of the dialog.
1. Click **Details** to see the custom field.

### Actual result
Custom field does not appear in the **Details** section. The custom field also doesn't appear in the **Custom Fields** section when I click **Edit** again.

### Expected result
The custom field is displayed in the **Details** section.

### Nextcloud log

<details>
<summary>Nextcloud log</summary>

```

```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
TypeError: "e.values is not a function"
    arrayValues https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:1
    updateCustomFields https://[server-url]/apps/passwords/js/Static/CreatePassword.1db3e7b116fa8cbc8972.js:1
    je https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    r https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    je https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    $emit https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    updateField https://[server-url]/apps/passwords/js/Static/CreatePassword.1db3e7b116fa8cbc8972.js:1
    je https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    r https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    je https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    $emit https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    updateField https://[server-url]/apps/passwords/js/Static/CreatePassword.1db3e7b116fa8cbc8972.js:1
    value https://[server-url]/apps/passwords/js/Static/CreatePassword.1db3e7b116fa8cbc8972.js:1
    run https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    lr https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    nt https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    Ze https://[server-url]/apps/passwords/js/Static/app.js?v=32ac85d3-0:57
    o https://[server-url]/core/js/dist/main.js?v=32ac85d3-0:230
    H https://[server-url]/core/js/dist/main.js?v=32ac85d3-0:230
    u https://[server-url]/core/js/dist/main.js?v=32ac85d3-0:235
app.js:57:11676
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://[server-url]/core/js/dist/main.js?v=32ac85d3-0
Source Map URL: main.js.map
```
</details>

**Update:** Added browser logs.

**Comment by marius-wieschollek** [comment]
I was not able to reproduce this issue.

Especially in the "All Passwords" section it can happen that it takes some time until the password details are updated after a change since the entire list must be loaded again.

**Comment by ricalo** [comment]
Mmm... I'm not seeing the customs fields updated even after two days.

Anyway, I added some related browser logs to the original report. The issue might be related to my server configuration. Feel free to close this issue if it's not actionable. I'll update with more information if I find anything else.

**Comment by marius-wieschollek** [comment]
The log looks like there is some issue with the custom fields data. Can you open the network tab of the developer console and afterward open the details of the affected password in the app. There should be a  request called "show". If you click on that request there should be a field called "customFields" in the response. I would like to know how that field looks. It should start with a `[`.

**Comment by ricalo** [comment]
I see the field in the show request. It displays as follows:

```
customFields: "{}"
```

**Comment by marius-wieschollek** [comment]
Ok. can you run `./occ maintenance:repair` from the command line?

**Comment by marius-wieschollek** [comment]
I think i can reproduce the issue now. The old api initializes the custom fields wrong. As a result they can not be saved by the editor. I will include a fix in the next update.

**Comment by ricalo** [comment]
Just as a note. The fix works for new passwords. Existing passwords that already had the custom fields defined as `customFields: "{}"` instead of `customFields:"[]"` still cannot save custom fields.

A workaround is to use the **Backup and Restore** feature to make a Database backup. Once you download the JSON file, you can update it in a text editor and fix any customFIelds defined as `{}` by changing it to `[]`.

You can then restore your passwords making sure to select the **Overwrite existing** in the **Conflict handling** option.

Be careful, you can potentially lose passwords if you restore incorrect data. Use this workaround at your own risk.

**Comment by marius-wieschollek** [comment]
If you still have this issue, make sure to update to the latest version and then run `./occ maintenance:repair` from the command line.
