### ISSUE TITLE
Getting Loading Challenge Failed

### ISSUE THREAD

**Issue by donty** [marius-wieschollek/passwords#166]
Started working - sort of, but import had duplicate entries and got corrupted. Then tried deleting the passwords using the risking everything of delete all in the menu options. 

Seemed to clear but now it wont load the page for Passwords at all, just has the Loading Challenge Failed
![LoadingChallengeFailed](https://user-images.githubusercontent.com/2900842/60833824-0ebf0e80-a1b7-11e9-9c4a-ed99d5489de0.jpg)
. 

Is there a manual delete process or removal that will allow me to clear it all down and start again? Tried checking/removing Password tables in the DB, removing App etc but it seems to keep coming back to the same error.

**Comment by marius-wieschollek** [comment]
Can you please provide some additional info? Which version of the app were you using when you did the reset? Did you use a master password? What do you mean by "import had duplicate entries and got corrupted"?

**Comment by donty** [comment]
The initial version would have been 2019.7.0 or 2019.6.0.
The import problems were with an export from Firefox and pulling in incorrect CSV format which meant multiple entries for URLs and wrong passwords. Tried to clear the entire thing out of Nextcloud following the Passwords menu options to delete all but once done I get the error above. By master password if you mean the end to end encryption option, yes but not a master password setting from Firefox.
Does that help?

**Comment by marius-wieschollek** [comment]
You can try the following: 
1. Connect to your database.
2. Check the table `*PREFIX*_preferences` for an entry with the configkey `SSEv1UserKey` and your userid and delete it.
3. Check the table `*PREFIX*_preferences` for an entry with the configkey `user/challenge/id` and your userid and delete it.

Then you should be able to access the app again. Upgrade to the latest version and then just run the delete all option again.

**Comment by donty** [comment]
Yep, that did it. Thanks! Importing again and will check all is right before enabling end to end.

Thanks for working so long and hard on this app, it has really come along since the first time I saw it when looking for a Firefox alternative to use with Nextcloud. 

Happy to keep testing and feeding back, do let me know if there is something I can help with, I'm not a programmer but hack about a bit so can test out stuff.
