### ISSUE TITLE
No Password UI and unable to save password using the Chrome extension

### ISSUE THREAD

**Issue by Laurent-Campredon** [marius-wieschollek/passwords#169]
### System Information
- Nextcloud Version: 16.0.3.0
- PHP Version: 7.3.4
- Passwords Version: 2019.7.1
- Browser and Version: Chrome  75.0.3770.100 (Official Build) (64-bit)
- Client: Windows 7 Service Pack 1 64bit
- Server: Debian 10

### Steps to reproduce
Click on Application in the app bar

### Actual result
What does happen?
![image](https://user-images.githubusercontent.com/52736158/60948881-3ebffc00-a2f4-11e9-9f76-4ab0c116a1f3.png)
No UI and "Failed to Fetch" error

### Expected result
Initial screen should appear

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
{"reqId":"EUYWq1HZRCSrdYr02lot","level":2,"time":"2019-07-09T13:44:38+00:00","remoteAddr":"185.46.214.60","user":"cancan","app":"passwords","method":"GET","url":"\/index.php\/apps\/passwords\/","message":"Attempt to access expired session","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/75.0.3770.100 Safari\/537.36","version":"16.0.2.1"}

{"reqId":"dohrr36uYxxY5sVkO9mY","level":3,"time":"2019-07-09T13:56:35+00:00","remoteAddr":"185.46.214.60","user":"--","app":"no app in context","method":"GET","url":"\/","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"passwords.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":337,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["passwords.page.index",[],1]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["passwords.page.index",[],false]},{"file":"\/var\/www\/nextcloud\/lib\/private\/URLGenerator.php","line":79,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["passwords.page.index",[]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/NavigationManager.php","line":292,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["passwords.page.index"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/NavigationManager.php","line":113,"function":"init","class":"OC\\NavigationManager","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/theming\/lib\/ThemingDefaults.php","line":179,"function":"getAll","class":"OC\\NavigationManager","type":"->","args":["guest"]},{"file":"\/var\/www\/nextcloud\/lib\/public\/Defaults.php","line":158,"function":"getShortFooter","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/JSConfigHelper.php","line":270,"function":"getShortFooter","class":"OCP\\Defaults","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/TemplateLayout.php","line":176,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":183,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["guest",""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":131,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":399,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":930,"function":"printUpgradePage","class":"OC","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":130,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/75.0.3770.100 Safari\/537.36","version":"16.0.2.1"}
{"reqId":"dohrr36uYxxY5sVkO9mY","level":3,"time":"2019-07-09T13:56:35+00:00","remoteAddr":"185.46.214.60","user":"--","app":"no app in context","method":"GET","url":"\/","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"theming.Theming.getImage\" as such route does not exist.","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":337,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"41"},1]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/CachingRouter.php","line":60,"function":"generate","class":"OC\\Route\\Router","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"41"},false]},{"file":"\/var\/www\/nextcloud\/lib\/private\/URLGenerator.php","line":79,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"41"}]},{"file":"\/var\/www\/nextcloud\/apps\/theming\/lib\/ThemingDefaults.php","line":241,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->","args":["theming.Theming.getImage",{"key":"logo","useSvg":true,"v":"41"}]},{"file":"\/var\/www\/nextcloud\/lib\/public\/Defaults.php","line":187,"function":"getLogo","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[true]},{"file":"\/var\/www\/nextcloud\/core\/templates\/layout.guest.php","line":40,"function":"getLogo","class":"OCP\\Defaults","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":178,"args":["\/var\/www\/nextcloud\/core\/templates\/layout.guest.php"],"function":"include"},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->","args":["\/var\/www\/nextcloud\/core\/templates\/layout.guest.php",null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/legacy\/template.php","line":211,"function":"fetchPage","class":"OC_Template","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Template\/Base.php","line":131,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":399,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":930,"function":"printUpgradePage","class":"OC","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/3rdparty\/symfony\/routing\/Generator\/UrlGenerator.php","Line":130,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/75.0.3770.100 Safari\/537.36","version":"16.0.2.1"}

Any idea what could be missing in the config?
Mcrypt and PHP7.3-fpm installed 
Redis used for cache

Thanks
Laurent

**Comment by marius-wieschollek** [comment]
Based on the nextcloud errors i would assume that there are files missing or broken. I would recommend to remove the app (delete the files) and install it again.

**Comment by Laurent-Campredon** [comment]
I have remove the db entries prefix_passwords_* and the passwords folder in app directory
Re installed.
Same issue

**Comment by marius-wieschollek** [comment]
@Cancan68 Please don't  just delete tables. There are also config values and preferences which depend on objects from other tables. Please go to our [forum](https://help.nextcloud.com/c/apps/passwords) so we can figure out how to get your installation working again.

**Comment by NGXG** [comment]
Same issue here, updated passwords first -> broken
Then installed NC v16.0.3 -> still broken

If I remove and reinstall the app, will all stored passwords be still there?

EDIT : php 7.1.28
Nextcloud log : {"reqId":"XSc3xRbruZ4@2TAzQ1K-kwAAAAY","level":2,"time":"2019-07-11T13:21:10+00:00","remoteAddr":"92.154.13.49","user":"administrator","app":"passwords","method":"GET","url":"/index.php/apps/passwords/","message":"Cancelled expired session","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"16.0.3.0","id":"5d2737c6af5b4"}

Cleared browser cache (FF68), logged out then back in -> Still broken.

**Comment by marius-wieschollek** [comment]
You can try the fix from #174 

1. Update to 2019.7.*2*
2. Make a backup using the command line `./occ passwords:backup:create`
3. Run the repair job from the command line `./occ maintenance:repair`

If you do not have command line access try the occweb app.

**Comment by Laurent-Campredon** [comment]
Thanks. 
Working fine with my Nextcloud when I do it from home
Also Fine with the Chrome Extension (good enough for the moment)
But..... there is a but ;-)
Same error when accessing the Nextcloud App from outside (my work place for example)

**Comment by Laurent-Campredon** [comment]
Workind fine after last update even from outside my network

Thanks
