### ISSUE TITLE
Custom Password Fields

### ISSUE THREAD

**Issue by fanningert** [marius-wieschollek/passwords#17]
Hi, it would be a nice feature to have extra password fields (or other types of text fields) for PINs/PUKs (Mobil-Simcard) or second password for account restore and so on.

**Example:** In the app passman it is possible (not perfect) to add extra fields with different field types (simple textarea, password field, ...).
In KeyPass it is also possible to add custom fields to login.

**Comment by marius-wieschollek** [comment]
I have added it to the [roadmap](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Roadmap)

**Comment by tarpin** [comment]
In refer to #31 and #32. It will be possible do add custom field with limit of length larger than 4096 characters? It would be useful for secure storing RSA and PGP keys as a text. Usually these keys are smaller than 10 kB (ca. 10,000 characters), so it shouldn't have a big performance impact.

**Comment by marius-wieschollek** [comment]
Usually your browser should do the email check for you. But i will add a fallback.

**Comment by fanningert** [comment]
@marius-wieschollek 
I use Chromium 66.0.3359.139 as browser.

**Comment by fanningert** [comment]
@marius-wieschollek 
I think the problem is that this checks are only executed on submit of a specific form. You use for every custom-field a own sub-forms of the form of the submit button.

Here a testpage for email what is working.
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_email

**Comment by marius-wieschollek** [comment]
I already changed that when i added the regex checks. Now there should be only one form.

**Comment by fanningert** [comment]
@marius-wieschollek 
Changes working perfect. Now the browser give back the message for email and link with the wrong format.

_Passwords-Version:_ 2018.5.0-build2200

**Comment by marius-wieschollek** [comment]
@tarpin you can also link to files with this. I may add the option to upload files if the nextcloud community ever has the mercy to [explain me](https://help.nextcloud.com/t/how-do-i-use-the-nextcloud-file-upload-in-my-app/30842) how their file upload works.
