### ISSUE TITLE
Error: Cannot create tags

### ISSUE THREAD

**Issue by benmichael** [marius-wieschollek/passwords#170]
### System Information
- Nextcloud Version: 16.0.3
- PHP Version: 7.2
- Passwords Version: 2019.7.1
- Browser and Version: Google Chrome 75.0.3770.100 (Official Build) (64-bit)
- Client OS and Version: MacOS Mojave 10.14.5 (18F203)
- Server OS and Version: Ubuntu Server 18.04 LTS

### Steps to reproduce
1. Clean install of Nextcloud and Passwords App
1. In the Passwords app, attempt to create a tag, any name, any colour

### Actual result
What does happen?

* The create tag dialogue disappears
* The tag is not created

### Expected result
What should happen?

The tag should be created

### Nextcloud log
```
Uncaught (in promise) TypeError: this.validateTag is not a function
    at Object.createTagFromData (app.js?v=9628fc59-5:51)
    at app.js?v=9628fc59-5:51
createTagFromData @ app.js?v=9628fc59-5:51
(anonymous) @ app.js?v=9628fc59-5:51
Promise.catch (async)
(anonymous) @ app.js?v=9628fc59-5:51
createTag @ app.js?v=9628fc59-5:51
createTag @ app.js?v=9628fc59-5:57
je @ app.js?v=9628fc59-5:57
r @ app.js?v=9628fc59-5:57
a._wrapper @ app.js?v=9628fc59-5:57
```

**Comment by marius-wieschollek** [comment]
I already noticed that. A patch for this issue is available in the nightly version.
