### ISSUE TITLE
Hide other users for guests

### ISSUE THREAD

**Issue by DecaTec** [marius-wieschollek/passwords#171]
Hello,

I'm using this app on an instance where there is one "real" user. All other users are guest users (see the guests app: https://github.com/nextcloud/guests).

Within the guest app's settings I activated the option to hide other users fo guest users. This option was implemented not long ago within the guests app (see here: https://github.com/nextcloud/guests/issues/89).

Now, in the passwords app, guest users can share their passwords. But the app doesn't respect the option to hide other users from guest users. By typing in the share text box, a guest user can simply see all other users (real users as well as guest users).

Hiding other users from guest users is very important for my instance. Is there any way to achieve this, or is it a bug in the passwords app?

**Comment by marius-wieschollek** [comment]
This is not a bug, it's a feature.The guests app is not a default feature of Nextcloud. Therefore respecting this setting is a new functionality that would have to be implemented first. That makes it a feature.

I will look into adding this for the next feature release in august.

**Comment by DecaTec** [comment]
Alright, then it's a feature request.

Great that you already planned this feature!

**Comment by DecaTec** [comment]
I've updated to version 2019.8.1 and the issue is not really solved:
Normal users are hidden from guest users now.

More important for me would be that all users are hidden from guests, e.g. guest cannot see other guest users when typing in the share text box.

Would it be possible to implement such an option in the app's settings?
