### ISSUE TITLE
Folders and Tags not working

### ISSUE THREAD

**Issue by gucu** [marius-wieschollek/passwords#174]
When I click on the password app it says unable to complete request. It is trying to load folders first. If I click on All Passwords then passwords are displayed fine.
If I try to create a tag it allows me to click the + sign and also to change the colour but after pressing ok to save there is nothing created.

Operating system: Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

Webserver: Apache (cgi-fcgi)

Database: mysql 10.3.16

PHP version: 7.2.20

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, ctype, curl, dom, fileinfo, ftp, gd, iconv, intl, json, ldap, mbstring, mysqlnd, PDO, Phar, posix, SimpleXML, sqlite3, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, imagick, Zend OPcache

Nextcloud version: 16.0.3 - 16.0.3.0

**Comment by marius-wieschollek** [comment]
Can you please do the following:

Check the Browser Console for any errors (press F12), also check the Network tab for any failed requests (4xx or 5xx status codes).

Also please check the Nextcloud log (which you can access from the admin settings) for any errors or exceptions related to the passwords app.

**Comment by gucu** [comment]
Hi
Errors:
JQMIGRATE: Migrate is installed, version 1.4.1
app.js?v=4d1ce2bd-6:57 Encryption tests scheduled after login
/index.php/apps/passwords/api/1.0/folder/show:1 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
app.js?v=4d1ce2bd-6:57 Object
/index.php/apps/passwords/#/folders:1 Uncaught (in promise) Object
app.js?v=4d1ce2bd-6:57 POST https://gucu.me/index.php/apps/passwords/api/1.0/folder/list 503 (Service Unavailable)
_executeRequest @ app.js?v=4d1ce2bd-6:57
_sendRequest @ app.js?v=4d1ce2bd-6:57
listFolders @ app.js?v=4d1ce2bd-6:57
listFolders @ app.js?v=4d1ce2bd-6:57
testFolders @ app.js?v=4d1ce2bd-6:57
runTests @ app.js?v=4d1ce2bd-6:57
async function (async)
runTests @ app.js?v=4d1ce2bd-6:57
(anonymous) @ app.js?v=4d1ce2bd-6:57
app.js?v=4d1ce2bd-6:57 {status: "error", id: 0, message: "Unable to complete request", response: Response}
app.js?v=4d1ce2bd-6:57 Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Object.handleError (app.js?v=4d1ce2bd-6:57)
    at Object.runTests (app.js?v=4d1ce2bd-6:57)
handleError @ app.js?v=4d1ce2bd-6:57
runTests @ app.js?v=4d1ce2bd-6:57
async function (async)
runTests @ app.js?v=4d1ce2bd-6:57
(anonymous) @ app.js?v=4d1ce2bd-6:57

One 503 on Network:
{status: "error", id: 0, message: "Unable to complete request"}
id: 0
message: "Unable to complete request"
status: "error"

This is the error I get from NextCloud logging:

Error | passwords | Exception: HMAC does not match.
-- | -- | --

Hope that helps.

**Comment by marius-wieschollek** [comment]
It seems like there is a broken object in the database.

Please make sure that you have at least version 2019.7.2 and run `./occ maintenance:repair` from the command line.

**Comment by gucu** [comment]
I did run that command and I still get no folders. Here is what happens when I ran the command. Is this something I need to raise a ticket with my server for.

 - Repair MySQL collation     - All tables already have the correct collation -> nothing to do - Repair mime types - Clean tags and favorites     - 0 tags of deleted users have been removed.     - 0 tags for delete files have been removed.     - 0 tag entries for deleted tags have been removed.     - 0 tags with no entries have been removed. - Repair invalid shares - Remove shares of a users root folder - Move .step file of updater to backup location - Fix potential broken mount points     - No mounts updated - Repair invalid paths in file cache - Add log rotate job - Clear frontend caches     - Image cache cleared     - SCSS cache cleared     - JS cache cleared - Clear every generated avatar on major updates - Add preview background cleanup job - Queue a one-time job to cleanup old backups of the updater - Repair pending cron jobs     - No need to repair pending cron jobs. - Extract the vcard uid and store it in the db - Cleanup invalid photocache files for carddav - Add background job to cleanup login flow v2 tokens - Remove potentially over exposing share links     - No need to remove link shares. - Cleanup cypress files from viewer app - Fix component of birthday calendars     - 7 birthday calendars updated. - Regenerating birthday calendars to use new icons and fix old birthday events without year     - Repair step already executed - Fix broken values of calendar objects    0 [>---------------------------]    0 [>---------------------------] - Registering building of calendar search index as background job     - Repair step already executed - Registering background jobs to update cache for webcal calendars     - Added 0 background jobs to update webcal calendars - Clean up orphan event and contact data     - 0 events without a calendar have been cleaned up     - 0 properties without an events have been cleaned up     - 0 changes without a calendar have been cleaned up     - 0 contacts without an addressbook have been cleaned up     - 0 properties without a contact have been cleaned up     - 0 changes without an addressbook have been cleaned up - Remove activity entries of private events     - Removed 0 activity entries - Fix the share type of guest shares when migrating from ownCloud - Copy the share password into the dedicated column - Purify and migrate collected mail addresses 0/7 [>---------------------------]   0% 7/7 [============================] 100% 7/7 [============================] 100% - Remove any playlist files mistakenly added to music_tracks table - Update OAuth token expiration times - Passwords Legacy Database Migration     - Legacy migration not available for version 2019.7.1 - Duplicate Object Deletion - Repair Passwords Database Objects     - Checking 0 tag revisions    0 [>---------------------------]    0 [>---------------------------]     - Fixed 0 tag revisions     - Checking 53 folder revisions  0/53 [>---------------------------]   0%  1/53 [>---------------------------]   1%  2/53 [=>--------------------------]   3%  3/53 [=>--------------------------]   5%  4/53 [==>-------------------------]   7%  5/53 [==>-------------------------]   9%  6/53 [===>------------------------]  11%  7/53 [===>------------------------]  13%  8/53 [====>-----------------------]  15%  9/53 [====>-----------------------]  16% 10/53 [=====>----------------------]  18% 11/53 [=====>----------------------]  20% 12/53 [======>---------------------]  22% 13/53 [======>---------------------]  24% 14/53 [=======>--------------------]  26% 15/53 [=======>--------------------]  28% 16/53 [========>-------------------]  30% 17/53 [========>-------------------]  32% 18/53 [=========>------------------]  33% 19/53 [==========>-----------------]  35% 20/53 [==========>-----------------]  37% 21/53 [===========>----------------]  39% 22/53 [===========>----------------]  41% 23/53 [============>---------------]  43% 24/53 [============>---------------]  45% 25/53 [=============>--------------]  47% 26/53 [=============>--------------]  49% 27/53 [==============>-------------]  50% 28/53 [==============>-------------]  52% 29/53 [===============>------------]  54% 30/53 [===============>------------]  56% 31/53 [================>-----------]  58% 32/53 [================>-----------]  60% 33/53 [=================>----------]  62% 34/53 [=================>----------]  64% 35/53 [==================>---------]  66% 36/53 [===================>--------]  67% 37/53 [===================>--------]  69% 38/53 [====================>-------]  71% 39/53 [====================>-------]  73% 40/53 [=====================>------]  75% 41/53 [=====================>------]  77% 42/53 [======================>-----]  79% 43/53 [======================>-----]  81% 44/53 [=======================>----]  83% 45/53 [=======================>----]  84% 46/53 [========================>---]  86% 47/53 [========================>---]  88% 48/53 [=========================>--]  90% 49/53 [=========================>--]  92% 50/53 [==========================>-]  94% 51/53 [==========================>-]  96% 52/53 [===========================>]  98% 53/53 [============================] 100% 53/53 [============================] 100%     - Fixed 0 folder revisions     - Checking 36 password revisions  0/36 [>---------------------------]   0%  1/36 [>---------------------------]   2%  2/36 [=>--------------------------]   5%  3/36 [==>-------------------------]   8%  4/36 [===>------------------------]  11%  5/36 [===>------------------------]  13%  6/36 [====>-----------------------]  16%  7/36 [=====>----------------------]  19%  8/36 [======>---------------------]  22%  9/36 [=======>--------------------]  25% 10/36 [=======>--------------------]  27% 11/36 [========>-------------------]  30% 12/36 [=========>------------------]  33% 13/36 [==========>-----------------]  36% 14/36 [==========>-----------------]  38% 15/36 [===========>----------------]  41% 16/36 [============>---------------]  44% 17/36 [=============>--------------]  47% 18/36 [==============>-------------]  50% 19/36 [==============>-------------]  52% 20/36 [===============>------------]  55% 21/36 [================>-----------]  58% 22/36 [=================>----------]  61% 23/36 [=================>----------]  63% 24/36 [==================>---------]  66% 25/36 [===================>--------]  69% 26/36 [====================>-------]  72% 27/36 [=====================>------]  75% 28/36 [=====================>------]  77% 29/36 [======================>-----]  80% 30/36 [=======================>----]  83% 31/36 [========================>---]  86% 32/36 [========================>---]  88% 33/36 [=========================>--]  91% 34/36 [==========================>-]  94% 35/36 [===========================>]  97% 36/36 [============================] 100% 36/36 [============================] 100%     - Fixed 0 password revisions     - Checking 0 tag models    0 [>---------------------------]    0 [>---------------------------]     - Fixed 0 tag models     - Checking 53 folder models  0/53 [>---------------------------]   0%  1/53 [>---------------------------]   1%  2/53 [=>--------------------------]   3%  3/53 [=>--------------------------]   5%  4/53 [==>-------------------------]   7%  5/53 [==>-------------------------]   9%  6/53 [===>------------------------]  11%  7/53 [===>------------------------]  13%  8/53 [====>-----------------------]  15%  9/53 [====>-----------------------]  16% 10/53 [=====>----------------------]  18% 11/53 [=====>----------------------]  20% 12/53 [======>---------------------]  22% 13/53 [======>---------------------]  24% 14/53 [=======>--------------------]  26% 15/53 [=======>--------------------]  28% 16/53 [========>-------------------]  30% 17/53 [========>-------------------]  32% 18/53 [=========>------------------]  33% 19/53 [==========>-----------------]  35% 20/53 [==========>-----------------]  37% 21/53 [===========>----------------]  39% 22/53 [===========>----------------]  41% 23/53 [============>---------------]  43% 24/53 [============>---------------]  45% 25/53 [=============>--------------]  47% 26/53 [=============>--------------]  49% 27/53 [==============>-------------]  50% 28/53 [==============>-------------]  52% 29/53 [===============>------------]  54% 30/53 [===============>------------]  56% 31/53 [================>-----------]  58% 32/53 [================>-----------]  60% 33/53 [=================>----------]  62% 34/53 [=================>----------]  64% 35/53 [==================>---------]  66% 36/53 [===================>--------]  67% 37/53 [===================>--------]  69% 38/53 [====================>-------]  71% 39/53 [====================>-------]  73% 40/53 [=====================>------]  75% 41/53 [=====================>------]  77% 42/53 [======================>-----]  79% 43/53 [======================>-----]  81% 44/53 [=======================>----]  83% 45/53 [=======================>----]  84% 46/53 [========================>---]  86% 47/53 [========================>---]  88% 48/53 [=========================>--]  90% 49/53 [=========================>--]  92% 50/53 [==========================>-]  94% 51/53 [==========================>-]  96% 52/53 [===========================>]  98% 53/53 [============================] 100% 53/53 [============================] 100%     - Fixed 0 folder models     - Checking 30 password models  0/30 [>---------------------------]   0%  1/30 [>---------------------------]   3%  2/30 [=>--------------------------]   6%  3/30 [==>-------------------------]  10%  4/30 [===>------------------------]  13%  5/30 [====>-----------------------]  16%  6/30 [=====>----------------------]  20%  7/30 [======>---------------------]  23%  8/30 [=======>--------------------]  26%  9/30 [========>-------------------]  30% 10/30 [=========>------------------]  33% 11/30 [==========>-----------------]  36% 12/30 [===========>----------------]  40% 13/30 [============>---------------]  43% 14/30 [=============>--------------]  46% 15/30 [==============>-------------]  50% 16/30 [==============>-------------]  53% 17/30 [===============>------------]  56% 18/30 [================>-----------]  60% 19/30 [=================>----------]  63% 20/30 [==================>---------]  66% 21/30 [===================>--------]  70% 22/30 [====================>-------]  73% 23/30 [=====================>------]  76% 24/30 [======================>-----]  80% 25/30 [=======================>----]  83% 26/30 [========================>---]  86% 27/30 [=========================>--]  90% 28/30 [==========================>-]  93% 29/30 [===========================>]  96% 30/30 [============================] 100% 30/30 [============================] 100%     - Fixed 0 password models     - Checking 0 password tag relations    0 [>---------------------------]    0 [>---------------------------]     - Fixed 0 password tag relations - Add background job to check for backup codes

**Comment by gucu** [comment]
That repair did the trick I think. It has told me to update to 2019.7.2 - hopefully that will sort it.

**Comment by marius-wieschollek** [comment]
Probably. If not, please re-run the maintenance command with that version. It should contain a fix that removes broken revisions.

**Comment by gucu** [comment]
Now working but has about 15 copies of each folder none of which contains passwords. So I am clearing out the empties and will keep one instance of each folder and then move a password into a folder and come back to you to tell you if that has worked. Thanks for the help so far.

**Comment by gucu** [comment]
All working perfectly. Thank you for your help. Hopefully this will be useful to others.
