### ISSUE TITLE
Sharing all passwords within folder or by tag

### ISSUE THREAD

**Issue by joe-speedboat** [marius-wieschollek/passwords#18]
Hi
I just found your app and it looks great.
Is it possible to share a folder or tag to other users or groups?
I would love to find a easy way, sharing bunch of passwords to team
Thanks
Chris

**Comment by marius-wieschollek** [comment]
Right now you can only share passwords with other users.
Sharing folders or tags and sharing with groups is something i would like to add, however it is very complex and therefore also very difficult to do so. It might be added in the future (=> 2019.x), but i can't guarantee it.

**Comment by joe-speedboat** [comment]
Hi Marius
Thanks for the Answer.
That's ok, was just a question.
I am looking for a way to share customer/server passwords within team members.
So probably TeamPass is a good start for now to achieve the target.

Thanks a lot 
Chris

**Comment by mokkin** [comment]
That would be great.
I have a very similar usecase sharings passwords within team members.

**Comment by andriusign** [comment]
Hello. Indeed this is a great and long-awaited app! I agree that sharing of folders would be an awesome feature as well with sharing passwords/folder to user groups too. Is this matter something of funding-related and could the development of these mentioned features could be implemented faster with additional funding?
