### ISSUE TITLE
Passwords app doesn't load at all

### ISSUE THREAD

**Issue by ryanprior** [marius-wieschollek/passwords#182]
### System Information
- Nextcloud Version: 15
- PHP Version: how do I find out?
- Passwords Version: 2019.8.0
- Browser and Version: Firefox 68.0.1
- Client OS and Version: elementary OS 5.0
- Server OS and Version: Ubuntu 18.04

### Steps to reproduce
1. Upgrade a working Passwords installation to 2019.8.0
2. Visit passwords app as a normal user

### Actual result
No app loads at all. No error message reported, NextCloud header renders, but the app doesn't.

### Expected result
Passwords app should load.

### Nextcloud log
I don't have logging enabled.

### Browser log
<details>
<summary>Browser log</summary>

```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 passwords:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:552
TypeError: document.querySelector(...) is nullapp.js:57:161987
    _checkLoginRequirement https://moth.link/extra-apps/passwords/js/Static/app.js?v=8d4cc2b6-4:57
    _initApp https://moth.link/extra-apps/passwords/js/Static/app.js?v=8d4cc2b6-4:57
    init https://moth.link/extra-apps/passwords/js/Static/app.js?v=8d4cc2b6-4:57
```
</details>

**Comment by marius-wieschollek** [comment]
Can you check if the element `<meta name="pw-authenticate" content="false"/>` appears in the HTML source code of the page?

**Comment by ryanprior** [comment]
No hits for "pw-authenticate" in the source of the page.

**Comment by marius-wieschollek** [comment]
From which version did you upgrade? Do you use any kind of cache? (Opcode, memcache etc.)

**Comment by ryanprior** [comment]
I'm not sure what version I upgraded from. I think I last upgraded maybe a month ago. Is there an upgrade history I can look at?

I use the official NextCloud snap (https://github.com/nextcloud/nextcloud-snap) and I'm not sure whether it uses a cache or not.

**Comment by ryanprior** [comment]
I just updated to the latest (2019.8.1) and my app is back now. Thanks!
