### ISSUE TITLE
No PASSWORD AFTER ENCRYTION WAS ENABLED

### ISSUE THREAD

**Issue by Pixxelcrasher** [marius-wieschollek/passwords#185]
### System Information
- Nextcloud Version: 16
- PHP Version: 7.2 
- Passwords Version: 2019.9.0-build3126
- Browser and Version: Brave newest
- Client OS and Version: windows 10
- Server OS and Version: ubuntu 18.04

### Actual result
What does happen?
Hello,
after I have activate encryption in the password settings... I got no logins on my chrome addon.

### Expected result
What should happen?
Get logins after encryption was enabled.

**Comment by marius-wieschollek** [comment]
The browser plugin does not yet support encryption. This will be available later this year.

**Comment by Pixxelcrasher** [comment]
so can i disable it again ?

**Comment by marius-wieschollek** [comment]
There is no simple option to disable encryption for already encrypted passwords. You can do the following:

Upgrade to 2019.9.0-build3128 and then restore a server backup. You can limit this to only your user.

_or_

Upgrade to 2019.9.0-build3128. 
Go to settings, choose the "Advanced" view and then set "Server encryption mode" to "Simple encryption" and "Client encryption mode" to "No encryption". 
Go to the "Backup and Restore" section and make a database backup . 
Then import that backup with the "Conflict handling" set to "Overwrite existing".
The app will still ask for the master password, but the passwords will no longer be client side encrypted. If you actually want to use encryption, you need to change the settings back again and repeat the process.

**Comment by Pixxelcrasher** [comment]
when does this update come ?
