### ISSUE TITLE
2FA - require 2nd factor optionally (only) and expiry time

### ISSUE THREAD

**Issue by nextgen-networks** [marius-wieschollek/passwords#187]
Since one of the beta/night updates I am forced to enter a 2FA code every time I open a Passwords
There also seems to be an expiration time.

Please add an option to disable (separately) 2FA for the entire plugin and an option to disable the expiration time amount.

Thx for your hard work!

**Comment by marius-wieschollek** [comment]
_Please user our feature or bug templates if you want to request a feature or a bug. Also just put one feature or bug per issue_

> Please add an option to disable (separately) 2FA for the entire plugin

Offering a way to bypass 2FA in any way would make it less secure.

>  There also seems to be an expiration time. [...] an option to disable the expiration time amount.
What kind of expiration time do you mean?

**Comment by roru69** [comment]
Same problem here. After upgrading to Nextcloud 16.04 and the latest Nextcloud Passwords plugin (2019.9.0-build3140) the password plugin also asks seperatey for a TOTP token. 

When I Login to Nextcloud I have to supply a TOTP token, when logged in, and after clicking on the Password icon, it is asked again. Changing back to the file tab and after that returning to the password plugin TOTP is asked again. Also when I change settings of the password plugin, the TOTP token notification window appears again asking for a TOTP token when returning to the password plugin.

In NC16.01 after logging in to NC with TOTP the passwords plugin never asked for a TOTP code.

 the Nextcloud-Passwords android app (Daper) also doesn't work anymore. It fails to pull data.

I think that it has something to do with the fact that the Password plugin now seperately asks for a TOTP token. Earlier versions didn't do that.

When I disable TOTP. Everything works as excpeted. No TOTP at login, No TOTP when clicking on the Password plugin icon and the (Daper) Password App for android pulls all the passwords.

**Comment by marius-wieschollek** [comment]
@roru69 This seems to be correctly.

Whenever the passwords app in nextcloud is opened, reloaded or left and then returned to, it will ask for a 2FA code and master password if available.

This feature currently only exists in the nightly versions and requires that third party apps and extensions are updated.

**Comment by roru69** [comment]
Reverted back to the stable version. Problem solved.

Personally I find that when I enable TOTP for Nextcloud it only should ask the code on login to Nextcloud, not also when accessing Passwords or any other app inside Nextcloud.

If I can choose to enable TOTP on App level it would make my life much easyer.

In my humble opinion it could be done in two ways.

1. Force TOTP usage for Passwords systemwide by setting it in the admin module for Passwords.
2. If not forced by the Admin, then leave the option to the user.

Regards, RR69

**Comment by marius-wieschollek** [comment]
With 2020.3.0, the 2FA will only be required as a second factor if a master password has been set.
I think this will be how users expect 2FA to work.

I will not include an option to disable 2FA. I don't think that adding the possibility to just disable security features is a good idea.
