### ISSUE TITLE
passwords dosn't seem to support https applied outside of host (inside of haproxy)

### ISSUE THREAD

**Issue by dieterarn** [marius-wieschollek/passwords#188]
### System Information 
(techandme.se vm fully updated as of 2019.08.27
- Nextcloud Version: 16.0.4
- PHP Version: 7.1

i use haproxy to do https for my nextcloud instance at home. I have a couple of subdomains and also i don't want let lets encypt passed my firewall. I have the nextcloud segregated on its own vlan an it talks to haproxy via plain text http...

### Steps to reproduce
1.  setup a nextcloud instance but do https on a different machine and do https on a proxy server/load balancer.

### Actual result
What does happen? passwords gives: 
"HTTPS Required
This application requires HTTPS in order to work safely.

You can try to reload this page the page with HTTPS.

If this problem persists, you should contact your administrator."

### Expected result
What should happen? passwords should work

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
See Settings > Log  (Copy Raw)
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
The app will work with a proxy if Nextcloud is configured to trust that proxy. Please ask your administrator to fix the configuration. If he opens the app he will find links to all documentation and a debugging view.

**Comment by dieterarn** [comment]
duh! that makes sense sorry for the lame git hub issue. If anyone ends up here via google - try looking at:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html
