### ISSUE TITLE
Settings page: "API Request Failed" on update

### ISSUE THREAD

**Issue by simmstein** [marius-wieschollek/passwords#189]
### System Information

- Nextcloud Version: 16.0.4
- PHP Version: 7.3.9
- Passwords Version: 2019.8.1
- Browser and Version: Firefox 60.8.0esr (64 bits)
- Client OS and Version: Debian 10
- Server OS and Version: Debian 9

### Steps to reproduce

1. Access https://mynextcloud/index.php/settings/admin/passwords
2. Change anything

### Actual result

1. Red notification "Échec" (= fail)
2. The update is not saved.
3. The page is refreshed

### Expected result

1. Should show "Success"
2. The update must be saved
3. The page must not be refreshed

### Nextcloud log

None.

### Browser log

PUT https://mynextcloud/index.php/apps/passwords/admin/settings/request 
Error 401: `{"message":"Current user is not logged in"}`

**Comment by marius-wieschollek** [comment]
The behavior of the fetch command changed in Firefox 61. Updating to Firefox 68 ESR should solve this issue.

I will add a patch for the next version.

**Comment by simmstein** [comment]
Fixed in 2019.9.0 ([7be11eef](https://git.mdns.eu/nextcloud/passwords/commit/7be11eef152fc8d5b24ea9187048d6447d370c06)). Thanks.
