### ISSUE TITLE
HTTPS check failing

### ISSUE THREAD

**Issue by maximelouet** [marius-wieschollek/passwords#19]
Hello,

I installed this app on my Nextcloud today. The problem is that I'm getting the "HTTPS REQUIRED" page, blocking access to the app. The fun part is that my domain is fully in HTTPS :smiley: 

I guess the problem is that my Nextcloud server is internally forwarded (in HTTP) to a reverse proxy, which then serves it in HTTPS to the client (me). The check of your app seems to be on server side, although the most important part is the final request sent to the client.

I hope my explanation is clear. Here is my setup:

**OS**: Debian 9 (_stretch_) up-to-date
**Server**: nginx/1.12.2 (reverse proxy that forwards requests to Apache/2.4.25. _Nextcloud is processed by Apache_)
**HTTPS**: Yes, enabled in nginx (with Let's Encrypt)
**PHP version**: 7.2.2
**Nextcloud version**: 13.0.0

Thank you for your help and your awesome work!

**Comment by marius-wieschollek** [comment]
There is currently a known issue with the proxy detection. Installing the [2018.3 nightly version](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13) from the app store should fix this issue.
