### ISSUE TITLE
Password sharing user selection not working

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords#190]
### System Information
- Nextcloud Version: 16.0.4.1
- PHP Version: 7.3.8
- Passwords Version: 2019.8.1
- Browser and Version: Safari 12.1.2, also Firefox 68.0.2
- Client OS and Version:
- Server OS and Version: Linux in 1&1 Shared Hosting

### Steps to reproduce
1. Create Password
2. Try to share password with Nextcloud User
3. By typing username / name / email address

### Actual result
No user is shown. So no user can be selected for sharing.

### Expected result
Show user.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
{"reqId":"XXDc51KlVNoAACBrH18AAAAA","level":2,"time":"2019-09-05T10:01:11+00:00","remoteAddr":"77.7.119.98","user":"lm","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/session/keepalive","message":"Cancelled expired session d159e998-74fd-46f8-b0ab-b0df03f5c8e8 for lm","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15","version":"16.0.4.1","id":"5d70de0251962"}
</details>

### Browser log
-

**Comment by marius-wieschollek** [comment]
Can you check if this issue persists with the nightly version?

**Comment by ghost** [comment]
> Can you check if this issue persists with the nightly version?

I downloaded the nightly version from https://apps.nextcloud.com/apps/passwords and loaded the folder to /apps folder on my server via ftp. Then Nextcloud shows a message "App-Aktualisierung notwendig" // "App upgrade necessary". Should I perform this upgrade? Or is there another way to install the nightly version?

**Comment by marius-wieschollek** [comment]
You can click the button. It's the standard procedure when you update an app manually.

**Comment by ghost** [comment]
works like a charm with the nightly version 👍
