### ISSUE TITLE
Share passwords with user groups

### ISSUE THREAD

**Issue by mrcage** [marius-wieschollek/passwords#192]
**Current Status**
We have some passwords in our org. that we need to share with a specific user group (e.g. board of directors). For that, it would be great to have the opportunity to not only select users with whom a password can be shared, but also entire groups (like it can be done with files).

**Feature Description**
When typing in a name in the sharing field, groups should also be shown and can be selected.

**Additional context**
None

**Comment by eramlawi** [comment]
+100 on this

**Comment by eramlawi** [comment]
I went to log in to request the same feature and this guy already did only  4 hours ago

**Comment by marius-wieschollek** [comment]
Actually someone already requested it [more than one year ago](https://github.com/marius-wieschollek/passwords/issues/27). It's a big feature and as soon as i have the time i will add it.

**Comment by Ali-romdhani** [comment]
Hi, I see the issue is closed (as well as other issues reporting the same demand).
Does someone have a clue on the progress of this feature ?
Thanks

**Comment by marius-wieschollek** [comment]
See #27
