### ISSUE TITLE
[2019.9.0] Passwords won't work with custom Besticon server, no connection attempts

### ISSUE THREAD

**Issue by nRaecheR** [marius-wieschollek/passwords#193]
**Version:** 2019.9.0
**Nextcloud:** 16.0.4 (official docker image)
**Database:** Mariadb 11.4 (official docker image)
**Besticon:** Latest docker image

I've setup the besticon service as Docker image on my server which is running NextCloud and MariaDB as Docker images too. Best

The Besticon functionality won't work when I'm swtiching from the (working) default server to my own server, only the Letter images will be rendered. In the Nextcloud log file an entry for each password is generated like this:

```

[passwords] Error: Exception: Favicon service returned no data at <<closure>>

0. /var/www/html/custom_apps/passwords/lib/Services/FaviconService.php line 89
   OCA\Passwords\Helper\Favicon\AbstractFaviconHelper->getFavicon("www.gog.com", 32)
1. /var/www/html/custom_apps/passwords/lib/Controller/Api/ServiceApiController.php line 182
   OCA\Passwords\Services\FaviconService->getFavicon("www.gog.com", 32)
2. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\Passwords\Controller\Api\ServiceApiController->getFavicon("www.gog.com", 32)
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "getFavicon")
4. /var/www/html/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "getFavicon")
5. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("ServiceApiController", "getFavicon", OC\AppFramework\ ... {}, {domain: "www.go ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({domain: "www.go ... "})
7. /var/www/html/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {domain: "www.go ... "})
8. /var/www/html/lib/base.php line 975
   OC\Route\Router->match("/apps/passwords ... 2")
9. /var/www/html/index.php line 42
   OC::handleRequest()

GET /index.php/apps/passwords/api/1.0/service/favicon/www.gog.com/32
from 192.168.42.115 by Arne at 2019-09-10T05:32:26+00:00
```
There is NO log output in the Besticon container, there is NO access to it from Nextcloud. I've verified that the Besticon container is working by checking it from a browser. I tried from inside the Nextcloud container to connect to the Besticon image with curl with the same URL I entered in the settings for Passwords, it works too. See here:

```
root@9d9647f0db46:/var/www/html# curl "http://192.168.42.221:8080/icon?url=github.com&size=32..50..120"
<a href="https://github.com/apple-touch-icon.png">Found</a>.
```

News App, which is connecting from inside the container to the Internet and the database connection to another container on the same server/Ip are working normally.

It seems that the Password app won't connect to Besticon when I enter a custom IP.

**Comment by marius-wieschollek** [comment]
I have checked this, but i can't reproduce the issue. Using the IP does not seem to be the issue.
Have you entered `http://192.168.42.221:8080/icon` as  the url?

Alternatively have you tried using the IP of the container directly? You can get it with ` docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container-name`

**Comment by nRaecheR** [comment]
Thank you for your answer. Yes, I tried the connection to the IP of the container before I wrote the issue report. And the URL I've entered in the Settings of Passwords is exactly the URL (copy&paste) from my curl snippet. As I mentioned in my bug report I tried to connect from within the running Nextcloud container with curl from command line and it works as expected. 

Is there anything I can do to help you find the reason for this behavior?

**Comment by marius-wieschollek** [comment]
I currently don't really have an idea why this does not work. The app uses php-curl to perform the request so there should not be any difference to the cli command.

I will enhance the logging of errors during requests so that there will be an exact error message in the logs of what went wrong during the request.

**Comment by marius-wieschollek** [comment]
I have released a nightly to the app store with a more detailed logging when requests fail.

**Comment by nRaecheR** [comment]
Thank you very much for your work. For every password there are now 6 entries. The first is the same as before, see above. The 5 others are exactly the same, here's the one for gog from the comment above: 

```
[passwords] Error: "" when fetching  http://192.168.42.221:8080/icon?size=16..128..256&fallback_icon_color=d35400&url=www.gog.com

GET /index.php/apps/passwords/api/1.0/service/favicon/www.gog.com/32
from 192.168.42.115 by Arne at 2019-09-16T18:50:41+00:00
```

The same URL called with curl from within the running Nextcloud docker container: 
```
root@9d9647f0db46:/var/www/html# curl "http://192.168.42.221:8080/icon?size=16..128..256&fallback_icon_color=d35400&url=www.gog.com"
<a href="https://www.gog.com/apple-touch-icon-144x144.png">Found</a>.
```

**Comment by nRaecheR** [comment]
Here it is after update to 2019.11.0 : 

```
[passwords] Error: "Unexpected HTTP 0" when fetching  http://192.168.42.221:8080/icon?size=16..128..256&fallback_icon_color=16a085&url=www.gog.com (0 redirects)

GET /index.php/apps/passwords/api/1.0/service/favicon/www.gog.com/32
from 192.168.42.115 by Arne at 2019-11-03T09:19:45+00:00
```

BTW: Your system clock seems to be in the future...

**Comment by marius-wieschollek** [comment]
> [passwords] Error: "" when fetching  http://192.168.42.221:8080/icon?size=16..128..256&fallback_icon_color=d35400&url=www.gog.com

I have updated the error messages in the latest release. If you're still experiencing this issue there should be a more percise message now.

**Comment by marius-wieschollek** [comment]
HTTP 0 is strange because that would mean that it can not even find the server. Do you have some kind of firewall active?

**Comment by nRaecheR** [comment]
No, I tried it once again with a bash from inside the container: 
```
www-data@feb8420433aa:~/html$ curl "http://192.168.42.221:8080/icon?size=16..128..256&fallback_icon_color=d35400&url=www.gog.com"
<a href="https://www.gog.com/apple-touch-icon-144x144.png">Found</a>.
```
So, there's no firewall when there is no special handling from Nextcloud itself for plugins. But even the database is on the same IP address (192.168.42.221) and it works of course.

**Comment by nRaecheR** [comment]
The problem still exists with NC 18.0.1 and Password 2020.2.1

``` 
[passwords] Error: "Unexpected HTTP 0" when fetching  http://192.168.42.221:8080/icon?size=16..128..256&fallback_icon_color=d35400&url=www.gog.com (0 redirects)

GET /index.php/apps/passwords/api/1.0/service/favicon/www.gog.com/32
from 192.168.42.115 by Arne at 2020-02-19T06:03:15+00:00
```

**Comment by marius-wieschollek** [comment]
I know, but i have not been able to reproduce the issue so far. I am planning to switch to the standard http request method of Nextcloud in a future version and hope that this will fix the issue or at least make it possible to figure out what exactly is wrong.

**Comment by facorazza** [comment]
> I currently don't really have an idea why this does not work. The app uses php-curl to perform the request so there should not be any difference to the cli command.
> 
> I will enhance the logging of errors during requests so that there will be an exact error message in the logs of what went wrong during the request.

In my case the besticon container didn't have connection to the internet. I had to add it to an external network in my docker-compose file.

**Comment by nRaecheR** [comment]
The problem is still there with latest passwords app (2020.5.0)and Nextcloud (18.0.4). There are still no connection attempts from NC to the besticon container according to the logs. And the besticon container still works when accessed by a wget from the NC container (see above)

**Comment by marius-wieschollek** [comment]
In version 2020.9.0 the app will now use the Nextcloud HTTP api instead of the previous curl api. With this change, all requests will follow the settings set in Nextcloud. Using a local Besticon instance may require `allow_local_remote_servers` to be set to `true` in the config.php in order to allow requests to local servers.

**Comment by nRaecheR** [comment]
Yes, this version (2020.9.0) fixes the problem for me. Thank you very much, Marius!
