### ISSUE TITLE
fetch /api/1.0/folders/show Waiting (TTFB) is ~50 seconds on every passwords page load

### ISSUE THREAD

**Issue by AlexusBlack** [marius-wieschollek/passwords#194]
### System Information
- Nextcloud Version: 15.0.4.0
- PHP Version: 7.2.19
- Passwords Version: 2019.9.0
- Browser and Version: Firefox 69.0 and Chrome 76.0.3809.132
- Client OS and Version: Mac OS X 10.14.5
- Server OS and Version: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-1048-aws x86_64)

### Steps to reproduce
1. Open any Passwords page

### Actual result
Wait for 30-50 seconds till page open.

### Expected result
Wait time no longer than 3-5 seconds.

### Nextcloud log
no errors in log

### Browser log
<details>
<summary>Browser log</summary>
TypeError: "NetworkError when attempting to fetch resource." app.js:43:271434
</details>

**Comment by marius-wieschollek** [comment]
Is there anything in the admin logs?

**Comment by AlexusBlack** [comment]
@marius-wieschollek hey, just checked the logs and don't see anything related to passwords recently.
Surprisingly for now the problem disappeared, it happened in the past so I want to wait few days to be sure that it won't come back. I did update all software on the server yesterday and restarted it, but had same issue right after it still, so connection isn't clear.
Sorry for taking your time, I will observe it for 2-4 more days and if problem won't manifest itself again will close the bug report.

**Comment by marius-wieschollek** [comment]
It could be that this is related to favicons. If you have a lot of entries with favicons which can not be resolved (and therefore not cached) the app will try to resolve it again after some time. If this happens with a lot of icons at the same time it could cause any further request to be placed in a queue until it expires.
