### ISSUE TITLE
Multi select option

### ISSUE THREAD

**Issue by eglyn** [marius-wieschollek/passwords#195]
Hi :)

Is there a way to move mass passwords inside another folder ? Like a multi select password ?

I imported mass password from Keepass, but moving them one by one to a folder is not very funny ^^
Thx in advance :)

**Comment by marius-wieschollek** [comment]
_Please use the issue template if you open a new issue_
_Please ask questions in the [forum](https://help.nextcloud.com/c/apps/passwords)_

There is currently no such option #119 and #136 will make that possible at a later point.
