### ISSUE TITLE
Left menu broken since NC 16.0.5

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#198]
### System Information
- Nextcloud Version: 16.0.5
- PHP Version: 7.3
- Passwords Version: 2009.9.0
- Browser and Version: FF 69 and Chrome 77
- Client OS and Version: Windows 10
- Server OS and Version: Debian 9

### Steps to reproduce
1. Update from NC 16.0.4 to 16.0.5
2. Open Passwords
3. Look at the left menu

### Actual result
Only the trah bin appears

### Expected result
I should see the folder, favorites, all passwords, tags, settings ...

### Firefox log
Sorry it's in french. A script-src CSP has broken something.
<details>
<summary>Browser log</summary>
```
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »).
```
</details>

### Chrome log
Only deprecation warnings

### Screen capture

![image](https://user-images.githubusercontent.com/11018648/65799663-fc7cbd00-e174-11e9-953b-446c7b8633c5.png)

**Comment by Salokyn** [comment]
Here are the CSP received by FF:
```
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-S2tLblVnenB2cjFnVnNoOE5PQjNrZ3hGM2xhMlNPV1RvajJrN0RrMWZoVT06UlRIRUJXTzV6YzRhTExvVWM0YzIzMW9tbkdQamVkT3E2RkNQMzN4YUJrMD0=' my.domain 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob: raw.githubusercontent.com;font-src 'self' data:;connect-src 'self' stun.nextcloud.com:443 raw.githubusercontent.com data:;media-src 'self' raw.githubusercontent.com;frame-ancestors 'self';worker-src 'self' blob:
```

**Comment by marius-wieschollek** [comment]
Fix is released

**Comment by Salokyn** [comment]
Thanks, it works for me
