### ISSUE TITLE
Password page fails to load JS

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#2]
So after the request [here](https://github.com/marius-wieschollek/passwords-legacy/issues/4#issuecomment-356714202) to test the app I gave it a go.

I backed up the db, made sure I was on 2017.11 and then downloaded the master.zip from this repo, unpacking the src folder to the nextcloud/apps folder as passwords.

I did the upgrade, let it do the haveibeenpwned.com web service checks and then tried to access the app via the link and was presented with a blank screen.

The console log of the browser states it is unable to find the files in js/Static/

**Comment by marius-wieschollek** [comment]
I assume you tested the migration on your testing server and not with the docker environment?
Then this behavior is completely normal as the repository does not contain the compiled static files.
Use the [Static.zip](https://github.com/marius-wieschollek/passwords/files/1622635/Static.zip) or [compile the files form source](https://github.com/marius-wieschollek/passwords/blob/master/CONTRIBUTING.md#helpful-commands).
I will update the migration guide to contain this information

**Comment by HanPrower** [comment]
Ah, that got it to move on. And no, I'm being dumb and doing it on my live server (as I'm the only user it's no big deal... even if it is very stupid).

I must say I'm not a fan of the popup boxes asking for the username and the password. Especially as the password box is in an entirely visible, plain text form.

I am now on the loading throbber, but it's stuck.

Console log:
`ReferenceError: request is not defined
app.js:1:470923`

**Comment by marius-wieschollek** [comment]
Ahh! I'm sorry, these popups should not be there. That is from the current CORS implementation testing.I gave you the wrong files. This [Static.zip](https://github.com/marius-wieschollek/passwords/files/1622742/Static.zip) is from the master branch where that stuff does not happen. And this is the complete [src.zip](https://github.com/marius-wieschollek/passwords/files/1622746/src.zip) in case i have missed anything else.

If you are trying this in your productive system i should mention that there is a compatibility issue in the legacy api that i am currently working on.

**Comment by HanPrower** [comment]
No worries. The sheer amount of work you've done in a relatively short time for a hobby project is amazing 🥇 

It's mostly working now.

Favicons aren't loading and every now and then I get a 502 Bad Gateway error. Which the nextcloud.log points at being due to an error in the FaviconService.php#L96.

Like the old app, the edit time changes when any info is changed and not just the password (and possibly the username?).

I think I'd also like to still see the tag in the main view. It was a vaguely useful visual cue. They could possibly just be a 4px solid border on the left hand side of the password though if you're trying to avoid clutter.

**Comment by marius-wieschollek** [comment]
Thanks.
About the Favicons: If it is in line 96, there should be two errors before the message and it should look something like this:
![grafik](https://user-images.githubusercontent.com/8255857/34831162-772b5096-f6e6-11e7-9c56-9f808bc0173d.png)
Can you send me the stack trace (make sure to remove sensitive values) and check which settings are set in the admin settings in "Additional Settings" > "Passwords" > "Image Rendering" and "Additional Settings" > "Passwords" > "Favicon Service"? Also do you have imagemagick or graphicsmagic installed? Which PHP version do you use and on which OS?
Does the 502 error come when the Favicon is requested or does this affect other urls?

The **edit time** sounds like a good idea. It might be a bit tricky, since the server will not be able tho set this, but i think it can be done. Feel free to request this feature in another issue.

**Tags** in the main area is something i have thought about, but postponed due to the performance impact of loading and encrypting all the tags. I will reconsider it after I have added a fast client side cache.

**Comment by marius-wieschollek** [comment]
I just realized that if you did not have the javascript files you did not have the css files as well. You can download the complete ready to use app from the [builds page](https://git.mdns.eu/nextcloud/passwords/tags/2018.1-alpha1).

**Comment by HanPrower** [comment]
**OCA\Passwords\Exception\ApiException: Internal Favicon API Error**

```
    /usr/share/webapps/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php - line 140: OCA\Passwords\Services\FaviconService->getFavicon('www.just-eat.co...', 32)
    [internal function] OCA\Passwords\Controller\Api\ServiceApiController->getFavicon('www.just-eat.co...', 32)
    /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Passwords\Controller\Api\ServiceApiController), 'getFavicon')
    /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Passwords\Controller\Api\ServiceApiController), 'getFavicon')
    /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ServiceApiContr...', 'getFavicon', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /usr/share/webapps/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /usr/share/webapps/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/apps/passwords...')
    /usr/share/webapps/nextcloud/index.php - line 48: OC handleRequest()
    {main}
```

The first preceding errors is:
`unable to load module /usr/lib/ImageMagick-6.9.9/modules-Q16HDRI/coders/svg.la': file not found @ error/module.c/OpenModule/1303`

I am generally aware that errors like that with ImageMagick usually mean the file not found is the file being processed, not the actual module not being found... (as it does exist).

And the second preceding error is:
`Favicon service returned no data`

"Image Rendering" is set to `Imagick/GMagick (recommended)`.

The "Favicon Service" was set to `None` (oops). If I set it to `The Favicon Finder` it works. The above stacktrace, however, does still occur.

I am using Arch Linux with PHP 7.1.11.

**Comment by HanPrower** [comment]
Also, I have noticed that if I switch to a login's Details that doesn't have a screenshot from a login's Details that does have a screenshot the old screenshot persists until a new one is fetched.

After installing the bundled zip you provided I've not noticed any changes (just FYI).

**Comment by marius-wieschollek** [comment]
That the Favicon Service is set to "None" is normal. It will always return default icons. Nextcloud requires all settings to be set to the most privacy friendly option.

Usually if Imagick is present on the system it will try to use it and generate a default icon from a predefined svg file. But it seems like the ImageMagick on has an issue with it.

To mitigate the issue, you can set "Image Rendering" to GdLib, but that usually looks ugly and has issues in other areas.
If the file was missing (img/Avatar.svg or img/default.svg) you would see a file_get_contents error.
You could check if the file "svg.la" is really in the place where image magick needs it.
Other potential issues could be that graphics magick is installed at the same time or that librsvg2 is not installed correctly.
You could also check `phpinfo();` and `convert -list configure` to see if svg support works.

I aware of the website preview images issue, but that is something i will look into at a later point.

**Comment by HanPrower** [comment]
I was missing librsvg (on Arch that package provides 2.x). Installing it fixed the issue.

**Comment by marius-wieschollek** [comment]
Ah. Then i will update the system requirements to mention that.
