### ISSUE TITLE
No php7.0 maintained?

### ISSUE THREAD

**Issue by happyreacer** [marius-wieschollek/passwords#20]
is it hard to maintain php 7.0? In debian 9 it is the devault version,

**Comment by marius-wieschollek** [comment]
The app uses the PHP 7.1 feature set and is therefore incompatible to PHP 7.0. Maintaining a special PHP 7.0 branch is very time consuming. The app store does also not support different variants of the same app version so distributing updates would be difficult. Given that PHP 7.0 has no active support anymore and will run out of security support this year i would recommend to upgrade to [PHP 7.1 with the repository from deb.sury.org](https://deb.sury.org/#php-packages).
