### ISSUE TITLE
Support NC 17

### ISSUE THREAD

**Issue by jernst** [marius-wieschollek/passwords#200]
App V 2019.9.1. reports it is incompatible with NC17.

**Comment by marius-wieschollek** [comment]
I can't reproduce this. Can you please fill out the entire bug report form and add some details?

**Comment by jernst** [comment]
The problem may be that https://apps.nextcloud.com/apps/passwords hasn't been updated to 2019.10.x which you seem to have on github.

**Comment by marius-wieschollek** [comment]
The version 2019.9.0 an later are already [Nextcloud 17 compatible](https://apps.nextcloud.com/apps/passwords/releases?platform=17#17) and available in the app store.
Where is it reported that the app is incompatible with Nextcloud 17?

**Comment by jernst** [comment]
Ah, I see what the problem is: mistake on my part to correctly understand the actual download URL scheme for this app: unlike most other apps, the URLs have a job number or so in the URL that's unrelated to the release version identifier. Sorry 'bout that.

**Comment by marius-wieschollek** [comment]
To get the latest version of an app programmatically, i would recommend using the appstore api: https://apps.nextcloud.com/api/v1/apps.json . You can find all available versions, compatibility and download links there.
