### ISSUE TITLE
log errors "invalid user id" and `app:check-code` fail

### ISSUE THREAD

**Issue by kiv57** [marius-wieschollek/passwords#208]
### System Information
- Nextcloud Version: 17.0.1
- PHP Version: 7.3.11
- Passwords Version: 2019.11.1
- Server OS and Version: Debian 9.11

### Steps to reproduce

1. Go to logging web page, see same error every 10 minutes, see Nextcloud log below
2. On server type `sudo -u www-data php occ app:check-code passwords`, see command output below
3. **EDIT** My cron.php randomly ends with error according to web UI, but runs without output when launched through ssh. Not sure if this is related

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
[index] Error: Exception: Unable to verify user invalid user id at <<closure>>

 0. /var/www/owncloud/apps/passwords/lib/Services/EnvironmentService.php line 295
    OCA\Passwords\Services\EnvironmentService->loadUserInformation(null, OC\AppFramework\Http\Request {})
 1. /var/www/owncloud/apps/passwords/lib/Services/EnvironmentService.php line 159
    OCA\Passwords\Services\EnvironmentService->determineAppMode(null, OC\AppFramework\Http\Request {})
 2. <<closure>>
    OCA\Passwords\Services\EnvironmentService->__construct(null, OC\AllConfig {}, OC\AppFramework\Http\Request {}, OC\Session\CryptoSessionData {}, OCA\Passwords\Services\LoggingService {}, OC\Authentication\Token\Manager {}, OC\User\Manager {})
 3. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 82
    ReflectionClass->newInstanceArgs([null,OC\AllConf ... }])
 4. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 99
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 5. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 114
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwords\ ... e")
 6. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 414
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwords\ ... e")
 7. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwords\ ... e")
 8. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 69
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwords\ ... e", true)
 9. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 99
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
10. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 114
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwords\\Db\\SessionMapper")
11. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 414
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwords\\Db\\SessionMapper")
12. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwords\\Db\\SessionMapper")
13. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 69
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwords\\Db\\SessionMapper", true)
14. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 99
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
15. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 114
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwords\ ... e")
16. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 414
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwords\ ... e")
17. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwords\ ... e")
18. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 69
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwords\ ... e", true)
19. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 99
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
20. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 114
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwords\ ... r")
21. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 414
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwords\ ... r")
22. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwords\ ... r")
23. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 161
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwords\ ... r")
24. /var/www/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php line 114
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
25. /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php line 112
    Pimple\Container->offsetGet("SessionApiController")
26. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 407
    OC\AppFramework\Utility\SimpleContainer->query("SessionApiController")
27. /var/www/owncloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 385
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("SessionApiController")
28. /var/www/owncloud/lib/private/AppFramework/App.php line 97
    OC\AppFramework\DependencyInjection\DIContainer->query("SessionApiController")
29. /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("SessionApiController", "keepAlive", "*** sensitive parameter replaced ***", {_route: "passwo ... "})
30. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwo ... "})
31. /var/www/owncloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "passwo ... "})
32. /var/www/owncloud/lib/base.php line 1000
    OC\Route\Router->match("/apps/passwords ... e")
33. /var/www/owncloud/index.php line 42
    OC::handleRequest()

GET /index.php/apps/passwords/api/1.0/session/keepalive
from [container IP] at 2019-11-14T17:20:45+00:00
```
</details>

### apps:check-code output
<details>
<summary>apps:check-code output</summary>

```
Analysing /var/www/owncloud/apps/passwords/templates/partials/https.php
 1 errors
    line   17: OC_User - Static method of private class must not be called
Analysing /var/www/owncloud/apps/passwords/templates/partials/https_debug.php
 1 errors
    line   12: OC_User - Static method of private class must not be called
Analysing /var/www/owncloud/apps/passwords/templates/admin/settings.php
 2 errors
    line  178: == - is discouraged
    line  197: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/User/DeleteUserDataHelper.php
 1 errors
    line  128: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/ApiObjects/AbstractObjectHelper.php
 3 errors
    line   90: != - is discouraged
    line  135: != - is discouraged
    line  136: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/SecurityCheck/BigLocalDbSecurityCheckHelper.php
 2 errors
    line  125: == - is discouraged
    line  132: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/SecurityCheck/AbstractSecurityCheckHelper.php
 1 errors
    line  134: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Preview/AbstractPreviewHelper.php
 1 errors
    line  154: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Preview/PageresCliHelper.php
 1 errors
    line   55: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Survey/ServerReportHelper.php
 3 errors
    line  166: == - is discouraged
    line  168: == - is discouraged
    line  220: OC_App - private class must not be instantiated
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Icon/FallbackIconGenerator.php
 1 errors
    line  177: OC_Image - private class must not be instantiated
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Words/LocalWordsHelper.php
 1 errors
    line   65: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Http/RequestHelper.php
 1 errors
    line  296: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Http/FileDownloadHelper.php
 2 errors
    line   44: == - is discouraged
    line   57: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Sharing/ShareUserListHelper.php
 2 errors
    line  113: == - is discouraged
    line  133: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Token/ApiTokenHelper.php
 1 errors
    line  183: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Image/AbstractImageHelper.php
 4 errors
    line   64: != - is discouraged
    line   74: != - is discouraged
    line   92: == - is discouraged
    line   92: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Image/ImagickHelper.php
 4 errors
    line  172: != - is discouraged
    line  187: == - is discouraged
    line  189: == - is discouraged
    line  191: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Helper/Image/GdHelper.php
 5 errors
    line  176: != - is discouraged
    line  177: == - is discouraged
    line  182: == - is discouraged
    line  184: == - is discouraged
    line  188: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Services/WebsitePreviewService.php
 2 errors
    line  224: != - is discouraged
    line  226: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Services/ValidationService.php
 1 errors
    line  148: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Services/EnvironmentService.php
 1 errors
    line  422: OC_User - Static method of private class must not be called
Analysing /var/www/owncloud/apps/passwords/lib/Services/Object/PasswordTagRelationService.php
 1 errors
    line  100: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Services/Object/AbstractService.php
 2 errors
    line  152: == - is discouraged
    line  152: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Middleware/ApiSessionMiddleware.php
 2 errors
    line   81: != - is discouraged
    line  116: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Controller/Api/FolderApiController.php
 1 errors
    line  194: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Controller/Api/Legacy/LegacyPasswordApiController.php
 1 errors
    line  244: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Cron/CheckPasswordsJob.php
 2 errors
    line  107: != - is discouraged
    line  113: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Migration/DatabaseRepair/AbstractModelRepair.php
 1 errors
    line   96: != - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Migration/Legacy/LegacyPasswordMigration.php
 1 errors
    line  280: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Hooks/FolderHook.php
 1 errors
    line  135: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Hooks/PasswordHook.php
 2 errors
    line  103: != - is discouraged
    line  176: == - is discouraged
Analysing /var/www/owncloud/apps/passwords/lib/Hooks/TagHook.php
 2 errors
    line   70: != - is discouraged
    line  124: == - is discouraged
Database schema error: Name of table *dbprefix*passwords_entity_password is too long (25), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_password_revision is too long (34), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_password_revision is too long (34), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_folder is too long (23), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_folder_revision is too long (32), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_folder_revision is too long (32), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_tag_revision is too long (29), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_tag_revision is too long (29), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_relation_password_tag is too long (31), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_relation_password_tag is too long (31), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_share is too long (22), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_session is too long (24), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_keychain is too long (25), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
Database schema error: Name of table *dbprefix*passwords_entity_challenge is too long (26), max. 27 characters (21 characters for tables with autoincrement) + *dbprefix* allowed
App is not compliant
```
</details>

### What I did recently

* upgraded PHP from 7.2 to 7.3,
* upgraded debian server from 9.8 to 9.11
* apt autoremove, which removed a bunch of packages

Thanks in advance for your help, and feel free to ask for more details.

**Comment by marius-wieschollek** [comment]
Hi. `occ app:check-code` checks if the app is compliant with the Nextcloud coding standards - which it isn't because the command did not work prior to NC 16 and i did not yet have the time to fix all reported issues. The app will still run fine.

The problem you're facing comes from the user id check. The app can not figure out what your user name is when it tries to refresh the session. Usually there should be a warning with `Login attempt with invalid [...something...]` right before the exception in the log. Can you find that?

**Comment by kiv57** [comment]
Thank you for the answer. I got it, and I confirm the app works fine.

You're right : see for example the successive warning and error below.

<details>

<code>
{"reqId":"B6E7tgexH3zOrs2XcStM","level":2,"time":"2019-11-14T17:20:45+00:00","remoteAddr":"X.X.X.X","user":"--","app":"passwords","method":"GET","url":"\/index.php\/apps\/passwords\/api\/1.0\/session\/keepalive","message":"Login attempt with invalid authorization header for invalid user id","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
{"reqId":"B6E7tgexH3zOrs2XcStM","level":3,"time":"2019-11-14T17:20:45+00:00","remoteAddr":"X.X.X.X","user":"--","app":"index","method":"GET","url":"\/index.php\/apps\/passwords\/api\/1.0\/session\/keepalive","message":{"Exception":"Exception","Message":"Unable to verify user invalid user id","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Services\/EnvironmentService.php","line":295,"function":"loadUserInformation","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->","args":[null,{"__class__":"OC\\AppFramework\\Http\\Request"}]},{"file":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Services\/EnvironmentService.php","line":159,"function":"determineAppMode","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->","args":[null,{"__class__":"OC\\AppFramework\\Http\\Request"}]},{"function":"__construct","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->","args":[null,{"__class__":"OC\\AllConfig"},{"__class__":"OC\\AppFramework\\Http\\Request"},{"__class__":"OC\\Session\\CryptoSessionData"},{"__class__":"OCA\\Passwords\\Services\\LoggingService"},{"__class__":"OC\\Authentication\\Token\\Manager"},{"__class__":"OC\\User\\Manager"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":82,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[null,{"__class__":"OC\\AllConfig"},{"__class__":"OC\\AppFramework\\Http\\Request"},{"__class__":"OC\\Session\\CryptoSessionData"},{"__class__":"OCA\\Passwords\\Services\\LoggingService"},{"__class__":"OC\\Authentication\\Token\\Manager"},{"__class__":"OC\\User\\Manager"}]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":99,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Services\\EnvironmentService","__class__":"ReflectionClass"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":114,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":69,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService",true]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":99,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Db\\SessionMapper","__class__":"ReflectionClass"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":114,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Db\\SessionMapper"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Db\\SessionMapper"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Db\\SessionMapper"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":69,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Db\\SessionMapper",true]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":99,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Services\\SessionService","__class__":"ReflectionClass"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":114,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\SessionService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\SessionService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\SessionService"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":69,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\SessionService",true]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":99,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Controller\\Api\\SessionApiController","__class__":"ReflectionClass"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":114,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Controller\\Api\\SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Controller\\Api\\SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Controller\\Api\\SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":161,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Controller\\Api\\SessionApiController"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":112,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":407,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":97,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["SessionApiController"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["SessionApiController","keepAlive","*** sensitive parameter replaced ***",{"_route":"passwords.session_api.keep_alive"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"passwords.session_api.keep_alive"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"passwords.session_api.keep_alive"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/passwords\/api\/1.0\/session\/keepalive"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Services\/EnvironmentService.php","Line":330,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.1.1"}
</code>

</details>

**Comment by marius-wieschollek** [comment]
Is this error still present in 2020.2.1?

**Comment by kiv57** [comment]
Hi,

No, the last entry in my log was on january 19, I guess I updated the app around that date.

Thanks for the work!
