### ISSUE TITLE
Initialisation Error! The app was unable to obtain the api access credentials.

### ISSUE THREAD

**Issue by Xenon099** [marius-wieschollek/passwords#209]
**System Information**

    Nextcloud Version: 17.0.1
    PHP Version: 7.3.11
    Passwords Version: 2019.11.1
    Server OS and Version: Debian 9.11

**Steps to reproduce**
Login my Nextcloud account.
Attempt to open the Password app, but there is ownly this Message: Initialisation Error! The app was unable to obtain the api access credentials.

**Nextcloud Log**
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'UPDATE `oc_authtoken` SET `uid` = ?, `login_name` = ?, `public_key` = ?, `private_key` = ?, `password` = ?, `name` = ?, `token` = ?, `type` = ?, `remember` = ?, `last_activity` = ?, `last_check` = ?, `version` = ?, `scope` = ? WHERE `id` = ?' with params ["admin", "admin"

Thanks in advance for your help, and feel free to ask for more details.

**Comment by marius-wieschollek** [comment]
Can you check for any errors in the Nextcloud Log?

Also can you open the developer tools in the browser (Usually with F12) and check if there are errors in the console.

It would also be great to know it there is an element with the name `api-token`. Running `document.querySelector('meta[name=api-token]')` from the browser console should return this element or undefined if it is missing. If it is there, the attribute `content` should have a value.

**Comment by Xenon099** [comment]
I've put the Nextcloud log in my original Post.

If I search for the api-token, there is no result found. And there is no other error in the console from the developer tool.

**Comment by marius-wieschollek** [comment]
The formatting of the error message from the log seems broken. Can you update it using the "insert code" feature of github? Also please make sure to remove any personal data like a password from the query if it happens to be in there.

**Comment by Xenon099** [comment]
`Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'UPDATE oc_authtoken SET uid = ?, login_name = ?, public_key = ?, private_key = ?, password = ?, name = ?, token = ?, type = ?, remember = ?, last_activity = ?, last_check = ?, version = ?, scope = ? WHERE id = ?' with params ["admin", "admin", "-----BEGIN PUBLIC KEY-----...-----END PUBLIC KEY-----\n", "PRIVATE_KEY", "PASSWORD", "Passwords Session 17.11.19 21:18 - admin@XX.XX.XX.XX", "b165770c6e51e9c172b5b372e71003fb1343f3eab0d60b54a596dea1c1c49674280e0761c159f85905a9d1b1e29f35b8a445512690065a7d2d74397db2529a7e", 0, 0, 1574025538, 1574025538, 2, "{\"filesystem\":false}", 0]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'b165770c6e51e9c172b5b372e71003fb1343f3eab0d60b54a596dea1c1c49674' for key 'authtoken_token_index'`

**Comment by Xenon099** [comment]
I have found the issue. In the Table oc_authtoken, the column with the id was missing. After I inserted an id column, the issue was solved. I can open now the Password app
