### ISSUE TITLE
Passwords cannot create anything

### ISSUE THREAD

**Issue by magoralczyk** [marius-wieschollek/passwords#21]
I am using a fresh install under NC13. When I am starting the app, the spinner in the middle of the empty page never stops. When I am trying to add a folder or password, the message at the top "creation of the folder failed" (maybe not 100% correct due to translation) pops up. Any ideas? File rights in passwords folder are 755 and owner is apache.

**Comment by marius-wieschollek** [comment]
Is your Nextcloud running in a subfolder? Like `https://example.com/nextcloud/`?

**Comment by magoralczyk** [comment]
yes

**Comment by marius-wieschollek** [comment]
Then it's a duplicate of #12. You can install the [2018.3 nightly from the app store](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13) to fix the issue.

**Comment by magoralczyk** [comment]
Well, I tried the nightly and now the problem with the spinner and folders is solved, but I still cannot save passwords: I tried it several times manually or via the chrome plugin (I logged into a site, the plugin popped up for saving the password), but in both cases the "creation of the password failed" popup shows up. 
I also found another strange bug: When on the create password form, I cannot write anything into the notice box. The cursor is flashing and the markup characters are inserted (for bold etc), but I can only write into the other fields.

**Comment by marius-wieschollek** [comment]
I think i found the issue with the extension. The new [version 1.4.3](https://github.com/marius-wieschollek/passwords-webextension/wiki/chromium-builds) solves a problem when the login data is changed. A workaround would be to restart the browser.
I have also uploaded a new [nightly version](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13). This should fix the issues with the notes editor.
I'm not quite sure about the problems with creating a password manually. It could be that the repeated login attempts from the extension triggered the brute force protection. In that case, requests to the api would take very long and eventually time out. You can check that by looking into the `bruteforce_attempts` table.
Otherwise you should check the browser console when creating a new password.There should be a request to `[...]/passwords/api/1.0/password/create`.

**Comment by magoralczyk** [comment]
I installed the newest nightly and the notice box bug is fixed, but I still cannot create passwords. A restart of the browser did not help, so I tried firefox without installed plugin and tried to create a passwort justh within the webinterface (All, click on +, then new password). Then I have to wait around 10 seconds until the message appears at the top, that the password could not be created. The oc_bruteforce_attempts is empty, and the oc_passwords_entity_password_revision table has as many rows an I tried to add a password, the  oc_passwords_entity_password is empty.
In the browser console I see the following exceptions:
 Failed to load resource: the server responded with a status of 503 (Service Unavailable)
:port/subfolder/index.php/apps/passwords/api/1.0/password/create

When I try a get on the complete URL from above I get a 405, method not allowed. You could instruct me to test the API with postman, if it helps you. I am dazzled, that the api seems not to work, but information is saved to the database...

**Comment by marius-wieschollek** [comment]
Can you take a look into the Nextcloud error log?
Revisions are created before the actual password, that explains why one table has entries.
10 seconds is exactly the time you get, when the server tries to contact the [haveibeenpwned.com](https://haveibeenpwned.com/) api but gets a response other that 200, 404 or 429. That could happen if a firewall is installed. You might try to change the password security check in the admin settings to one of the local services to check that.

**Comment by magoralczyk** [comment]
I think, it maybe was the SE Linux, prohibiting to contact an external api. However, I changed the admin settings to local and it works like a charm. Thanks!

**Comment by marius-wieschollek** [comment]
Well i should mention that the "10 mio" and "1 mio" local password databases require a download [as mentioned in the wiki](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Administrative-Settings#password-security-checks). 10 million passwords is downloaded from archive.org and 1 million passwords from GitHub. Both files will be downloaded if necessary by a background job that runs once a day. They will not validate passwords correctly until the database has been downloaded.
So you should check if your firewall / SE Linux is configured to allow the download.

There is a list of all possibly contacted third party domains in the [system requirements](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#third-party-services)
