### ISSUE TITLE
SnakesWordsHelper::isAvailable() freeze the settings page

### ISSUE THREAD

**Issue by simmstein** [marius-wieschollek/passwords#211]
### System Information
- Nextcloud Version: 17.0.1
- PHP Version: 7.3
- Passwords Version: 2019.11.1
- Browser and Version: Firefox 68 ESR
- Client OS and Version: Debian 10 (buster)
- Server OS and Version: Debian 10 (buster)

### Steps to reproduce
1. Go to https://my.nextcloud.instance/index.php/settings/admin/passwords

### Actual result

It depends of the server configuration:

* Production environments with PHP-FPM: `The timeout specified has expired: [client 127.0.0.1:44408] AH01075: Error dispatching request to ...`
* With PHP 7.3 executed with Apache2: the page loads for many seconds

### Expected result

The page should be loaded in few seconds.

The problem seems to be from this instruction:

**apps/passwords/lib/Helper/Words/SnakesWordsHelper.php:181**
```        
$headers = @get_headers(SnakesWordsHelper::SERVICE_URL, 1);
```

```
% php -a
Interactive mode enabled

php > get_headers('http://watchout4snakes.com/wo4snakes/Random/RandomPhrase', 1);
PHP Warning:  get_headers(http://watchout4snakes.com/wo4snakes/Random/RandomPhrase): failed to open stream: HTTP request failed!  in php shell code on line 1
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. get_headers() php shell code:1
php > 
```

http://watchout4snakes.com/wo4snakes/Random/RandomPhrase is accessible from the 3 servers impacted.

Workarround: 

```
$ sed -i "s/'enabled' => SnakesWordsHelper::isAvailable()/'enabled' => false, \/\/ SnakesWordsHelper::isAvailable()/" apps/passwords/lib/Settings/AdminSettings.php
```

Rollback:
```
sed -i "s/'enabled' => false, \/\/ SnakesWordsHelper::isAvailable()/'enabled' => SnakesWordsHelper::isAvailable()/" apps/passwords/lib/Settings/AdminSettings.php
```

**Comment by simmstein** [comment]
Thanks!

**Comment by marius-wieschollek** [comment]
This issue should be fixed in the current nightly.

You can install this nightly by downloading it manually from the [app store website](https://apps.nextcloud.com/apps/passwords). You can also enable the setting "Show nightly updates in apps" in the passwords settings. If you can't open the settings you can also run `./occ config:app:set passwords nightly/enabled --value=1` from bash or occ web and wait about one hour until it shows up in the app store.
