### ISSUE TITLE
Image is missing from the password list entry

### ISSUE THREAD

**Issue by vanyolai** [marius-wieschollek/passwords#212]
### System Information
- Nextcloud Version:17.0.1
- PHP Version:7.3.12
- Passwords Version:2019.12.0
- Browser and Version:Chrome 78.0.3904.108
- Client OS and Version: Windows 10
- Server OS and Version: FreeBSD

### Steps to reproduce
1. 
Open the app
2. 
3. 

### Actual result
What does happen?
The leftmost end of all the lines are missing the icon
### Expected result
What should happen?

### Nextcloud log
<details>

OCA\Passwords\Exception\ApiException: Internal Favicon API Error/usr/local/www/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php - line 182:OCA\Passwords\Services\FaviconService->getFavicon(" ", 32)/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:OCA\Passwords\Controller\Api\ServiceApiController->getFavicon("default", 32)/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Password ... {}, "getFavicon")/usr/local/www/nextcloud/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Password ... {}, "getFavicon")/usr/local/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("ServiceApiController", "getFavicon", OC\AppFramew ... {}, { domain: "d ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ domain: "d ... "})/usr/local/www/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { domain: "d ... "})/usr/local/www/nextcloud/lib/base.php - line 1000:OC\Route\Router->match("/apps/passw ... 2")/usr/local/www/nextcloud/index.php - line 42:OC::handleRequest()LétrehoztaImagickException: attempt to perform an operation not allowed by the security policy `MVG' @ error/constitute.c/IsCoderAuthorized/408/usr/local/www/nextcloud/apps/passwords/lib/Helper/Image/ImagickHelper.php - line 109:Imagick->readimage("/tmp/5df01b301df06.svg")/usr/local/www/nextcloud/apps/passwords/lib/Helper/Icon/FallbackIconGenerator.php - line 124:OCA\Passwords\Helper\Image\ImagickHelper->getImageFromFile("/tmp/5df01b301df06.svg")/usr/local/www/nextcloud/apps/passwords/lib/Helper/Icon/FallbackIconGenerator.php - line 81:OCA\Passwords\Helper\Icon\FallbackIconGenerator->createIconFromSvg("#f39c12", " ", 32)/usr/local/www/nextcloud/apps/passwords/lib/Helper/Favicon/AbstractFaviconHelper.php - line 97:OCA\Passwords\Helper\Icon\FallbackIconGenerator->createIcon(" ", 32)/usr/local/www/nextcloud/apps/passwords/lib/Services/FaviconService.php - line 96:OCA\Passwords\Helper\Favicon\AbstractFaviconHelper->getDefaultFavicon(" ", 32)/usr/local/www/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php - line 182:OCA\Passwords\Services\FaviconService->getFavicon(" ", 32)/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:OCA\Passwords\Controller\Api\ServiceApiController->getFavicon("default", 32)/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Password ... {}, "getFavicon")/usr/local/www/nextcloud/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Password ... {}, "getFavicon")/usr/local/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("ServiceApiController", "getFavicon", OC\AppFramew ... {}, { domain: "d ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ domain: "d ... "})/usr/local/www/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { domain: "d ... "})/usr/local/www/nextcloud/lib/base.php - line 1000:OC\Route\Router->match("/apps/passw ... 2")/usr/local/www/nextcloud/index.php - line 42:OC::handleRequest() |  
-- | --

[passwords] Error: Error "Internal Favicon API Error" in OCA\Passwords\Controller\Api\ServiceApiController::getFavicon

GET /index.php/apps/passwords/api/1.0/service/favicon/default/32
from 192.168.250.1 by vanyo at 2019-12-10T22:24:48+00:00

[passwords] Error: ImagickException: attempt to perform an operation not allowed by the security policy `MVG' @ error/constitute.c/IsCoderAuthorized/408 at <<closure>>

 0. /usr/local/www/nextcloud/apps/passwords/lib/Helper/Image/ImagickHelper.php line 109
    Imagick->readimage("/tmp/5df01b301df06.svg")
 1. /usr/local/www/nextcloud/apps/passwords/lib/Helper/Icon/FallbackIconGenerator.php line 124
    OCA\Passwords\Helper\Image\ImagickHelper->getImageFromFile("/tmp/5df01b301df06.svg")
 2. /usr/local/www/nextcloud/apps/passwords/lib/Helper/Icon/FallbackIconGenerator.php line 81
    OCA\Passwords\Helper\Icon\FallbackIconGenerator->createIconFromSvg("#f39c12", " ", 32)
 3. /usr/local/www/nextcloud/apps/passwords/lib/Helper/Favicon/AbstractFaviconHelper.php line 97
    OCA\Passwords\Helper\Icon\FallbackIconGenerator->createIcon("      ", 32)
 4. /usr/local/www/nextcloud/apps/passwords/lib/Services/FaviconService.php line 96
    OCA\Passwords\Helper\Favicon\AbstractFaviconHelper->getDefaultFavicon("      ", 32)
 5. /usr/local/www/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php line 182
    OCA\Passwords\Services\FaviconService->getFavicon("      ", 32)
 6. /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Passwords\Controller\Api\ServiceApiController->getFavicon("default", 32)
 7. /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "getFavicon")
 8. /usr/local/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "getFavicon")
 9. /usr/local/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("ServiceApiController", "getFavicon", OC\AppFramework\ ... {}, {domain: "defaul ... "})
10. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({domain: "defaul ... "})
11. /usr/local/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {domain: "defaul ... "})
12. /usr/local/www/nextcloud/lib/base.php line 1000
    OC\Route\Router->match("/apps/passwords ... 2")
13. /usr/local/www/nextcloud/index.php line 42
    OC::handleRequest()

GET /index.php/apps/passwords/api/1.0/service/favicon/default/32
from 192.168.250.1 by vanyo at 2019-12-10T22:24:48+00:00
<summary>Nextcloud log</summary>

```
See Settings > Log  (Copy Raw)
```
</details>

### Browser log
<details>
GET https://vanyo.getmyip.com/index.php/apps/passwords/api/1.0/service/favicon/default/32 502 (Bad Gateway)
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
A `502 - Bad Request` response usually means that something went wrong while fetching or processing the requested image. These error are logged in the Nextcloud log.

Please update your ticket to include all relevant errors from the logs and all relevant settings from the settings page.

**Comment by vanyolai** [comment]
Updated! Hope it helps.

**Comment by marius-wieschollek** [comment]
```
ImagickException: attempt to perform an operation not allowed by the security policy `MVG' @ error/constitute.c/IsCoderAuthorized/408
```

It looks like the ImageMagick installation on your server advertises svg support, but a security policy does permit the usage of svg files. I would recommend to solve this issue by setting the image processing method in the passwords app settings to `PHP GDLib`

**Comment by vanyolai** [comment]
Thanks, it solved the problem.
