### ISSUE TITLE
Docs/FAQ don't contain text about "offline"

### ISSUE THREAD

**Issue by guettli** [marius-wieschollek/passwords#213]
The docs (FAQ) don't contain a hint about "offline".

Can I access the password if I am offline?

**Comment by marius-wieschollek** [comment]
A connection to the Nextcloud server with the app is always required. Passwords are not stored on your device.

If you're trying to run the app on a server without internet access, look in the [manual](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Administrator-Notes#how-do-i-use-the-app-on-a-server-without-internet-access).

**Comment by guettli** [comment]
Why not update the FAQ and add this?
