### ISSUE TITLE
Make Trash bin behave more like in "Files" app

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#215]
**Current Status**
In the trash bin I cannot bulk delete passwords, only one-by-one. At the beginning of each entry the "favorite" star marker is displayed - which seems a bit odd for the trash bin.

![image](https://user-images.githubusercontent.com/1677436/70777229-80f7d880-1d7f-11ea-9e90-1874aca17eba.png)

**Feature Description**
I'd suggest redesigning this to work more like the Files trash bin: the item at the beginning of the entry is a check box, there should be a "check all" option at the column header, and an action menu to allow bulk deletion:

![image](https://user-images.githubusercontent.com/1677436/70777147-4857ff00-1d7f-11ea-9765-557532a40717.png)

To be more coherent with the Files app one could also rename the "Trash" menu item to "Deleted passwords".

**Comment by marius-wieschollek** [comment]
The trash bin actually offers a delete all option in the "+" button. This is still the older Nextcloud design from NC12

**Comment by meonkeys** [comment]
How long does stuff sit in the trash? I'm wondering if it cleans itself out periodically.

**Comment by marius-wieschollek** [comment]
Nope.

**Comment by meonkeys** [comment]
Ooh, good to know, thanks!

"Archive" might be more a more intuitive name for it, then.
