### ISSUE TITLE
Password could not be generated  - local server error 504 / watchout4snakes.com error 500

### ISSUE THREAD

**Issue by nextgen-networks** [marius-wieschollek/passwords#217]
### System Information
- Nextcloud Version: 17.0.1
- PHP Version: 7.3.12
- Passwords Version: 2019.12.0
- Browser and Version: Chrome/79.0.3945.79
- Client OS and Version: Windows 10 Pro/1909
- Server OS and Version: NGINX

### Steps to reproduce
1. create new password entry
2. generate a new Passwort
3. circle turns and turns and turns around - later error 504 ist shown (sometimes)

Tested with complexity 1-4
### Actual result
No Password will be generated.

### Expected result
Password should be generated.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
{"reqId":"NDpGDykibcg9dE2h2DoG","level":3,"time":"2019-12-16T12:09:41+00:00","remoteAddr":"217.110.xxx.xxx","user":"MyUserName","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/service/password","message":"\"Unexpected HTTP 500\" when fetching http://watchout4snakes.com/wo4snakes/Random/RandomPhrase (0 redirects)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36","version":"17.0.1.1","id":"5df7740590ba0"}
</details>

**Comment by marius-wieschollek** [comment]
Looks like the service is down. You can switch to another service as a workaround.

**Comment by nextgen-networks** [comment]
.... jepp tried that ...
The result is bug ticket [218](https://github.com/marius-wieschollek/passwords/issues/218)

**Comment by marius-wieschollek** [comment]
since the service is still unavailable, i have added a new service in the 2020 release. This service will also be used as fallback as long as this one remains offline.

**Comment by marius-wieschollek** [comment]
It seems to be working again. I will still keep the fallback option if it fails again.
