### ISSUE TITLE
not possible to change passwort generator method

### ISSUE THREAD

**Issue by nextgen-networks** [marius-wieschollek/passwords#218]
### System Information
- Nextcloud Version: 17.0.1
- PHP Version: 7.3.12
- Passwords Version: 2019.12.0
- Browser and Version: Chrome/79.0.3945.79
- Client OS and Version: Windows 10 Pro/1909
- Server OS and Version: NGINX

### Steps to reproduce
1. changed password generator from "watchout4snakes.com" to "random generated characters" (zufällige Buchstaben)
2. try to change back to any of th other two options

### Actual result
Only the option "random generated characters" (zufällige Buchstaben) could be actively selected

### Expected result
All shown options should be selectable.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
{"reqId":"t8cNAeZp6DNDg7UCIIE1","level":3,"time":"2019-12-16T12:25:18+00:00","remoteAddr":"217.110.xxx.xxx","user":"MyUserName","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/service/password","message":"Error \"Internal Words API Error\" in OCA\\Passwords\\Controller\\Api\\ServiceApiController::generatePassword","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36","version":"17.0.1.1","id":"5df77b4685c8c"}
{"reqId":"t8cNAeZp6DNDg7UCIIE1","level":3,"time":"2019-12-16T12:25:18+00:00","remoteAddr":"217.110.xxx.xxx","user":"MyUserName","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/service/password","message":{"Exception":"OCA\\Passwords\\Exception\\ApiException","Message":"Internal Words API Error","Code":256,"Trace":[{"file":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","line":77,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","line":77,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","line":77,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","line":77,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","line":77,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","line":77,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/apps/passwords/lib/Controller/Api/ServiceApiController.php","line":141,"function":"getPassword","class":"OCA\\Passwords\\Services\\WordsService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/path/to/nc-installation/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"generatePassword","class":"OCA\\Passwords\\Controller\\Api\\ServiceApiController","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/path/to/nc-installation/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\ServiceApiController"},"generatePassword"]},{"file":"/path/to/nc-installation/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\ServiceApiController"},"generatePassword"]},{"file":"/path/to/nc-installation/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["ServiceApiController","generatePassword",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"passwords.service_api.generate_password"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"passwords.service_api.generate_password"}]},{"file":"/path/to/nc-installation/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"passwords.service_api.generate_password"}]},{"file":"/path/to/nc-installation/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/passwords/api/1.0/service/password"]},{"file":"/path/to/nc-installation/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/path/to/nc-installation/apps/passwords/lib/Services/WordsService.php","Line":80,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36","version":"17.0.1.1","id":"5df77b4685c72"}
</details>

**Comment by marius-wieschollek** [comment]
This looks like normal behavior to me. `Local dictionary` is only available if at least the file `/usr/share/dict/words` is available on the server. The `wa4snakes` service is only available if the service can be reached - which you currently can't because it's down.

The error you found in the NC log is from the password api, not from the admin settings

**Comment by nextgen-networks** [comment]
Ok sounds reasonable - if possible it may be a UI improvement to have a info message if any not available item is selected.

In my specific case this also means I've to wait and manual check on regular base if wa4snakes service is available again before I can change the option back to its original value.
From my (personal ;-)) point of view it would be more user friendly to let the option be choosen - even if the service is not available instead of trying that many times to figure out the availability.

... ahh and: thanks for your explanation and hard work @marius-wieschollek !
