### ISSUE TITLE
List-View of passwords looks quite confused

### ISSUE THREAD

**Issue by KRAtGitHub** [marius-wieschollek/passwords#219]
Hi Marius,
I'm using the newest version of the passwords-app for nextcloud.
After adding alist of passwords the list of the entries contains diffus information.
I will add ascreenshot of it.
This occures after installing the newest version!

### System Information
- Nextcloud Version: 17.0.2
- PHP Version: 	7.2.24
- Passwords Version: 2019.12.1
![Passwords_ListView](https://user-images.githubusercontent.com/59064147/71200120-c04e8980-2297-11ea-9b07-378c760aa9b1.png)

- Browser and Version: FireFox 70.0.1
- Client OS and Version: Win 10
- Server OS and Version:

### Steps to reproduce
1. Add a folder
2. Add a password
3. Save and look the result-list

### Actual result
The List of password-entries looks like confused.
Look at the screenshot I spend.

### Expected result
Normal list of password-entries with name and website and duedate

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
See Settings > Log  (Copy Raw)
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy what you see
```
</details>

**Comment by marius-wieschollek** [comment]
That looks like the `alt` tag of the favicon. It should disappear when the icon is loaded.

I will remove the tags with the next regular update
