### ISSUE TITLE
Removing "Rate Limit exceeded"

### ISSUE THREAD

**Issue by JonathanTreffler** [marius-wieschollek/passwords#220]
**Current Status**
If you want to share a password with multiple people and you type a new name in the user Search box while the last share is still processing, you get a Message "Rate Limit exceeded".
Then it takes a while until you can do something without getting another Message with the same text.

**Feature Description**
Please remove this annoying Rate Limit.

**Comment by marius-wieschollek** [comment]
With the new version this limit has been increased and should no longer appear under normal conditions
