### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Danielsc87** [marius-wieschollek/passwords#223]
Passwords won't display any passwords on Android app. It logs in no issues and when I sync it it shows in the log but nothing will display on the app.

Firefox has an error says login credentials are incorrect not sure if 2FA is the issue with this.
Running nextcloud 17.
Google authentication 2FA

I have upgraded passwords to latest version 2020.1 build 3270.and down graded to. To 2019.12 and lower 2019.11.1. And have the same issue. Any ideas.

**Comment by marius-wieschollek** [comment]
The issue tracker for the Android App can be found here: https://github.com/daper/nextcloud-passwords-app

If you use 2FA, you need to use an app password for the Firefox extension. For the Android app its probably the same.

**Comment by Danielsc87** [comment]
How do I use an app password with Firefox. I have look all over and there is no option to add a password.

Also I added the password login on the Android app and hasn't fixed anything still won't download. I'll ass an issue on the link provided. Above.

**Comment by marius-wieschollek** [comment]
In the Nextcloud settings, go to "Security" and at the end of "Devices & sessions" you will find the button to create app passwords.

In the Firefox extension, click on the cog-icon and enter that password in the password field.

![grafik](https://user-images.githubusercontent.com/8255857/71764598-09364d00-2eea-11ea-9fb4-2cda2aad4827.png)

**Comment by Danielsc87** [comment]
Hi i have done this and i still get the same result but no errors, the add on just comes up as no login found. 
also FYI the android app users the same login details as the normal nextcloud app, it take you to your domain put in you details and 2FA and press grant access, it looks like it creates that app password for you, pic below, could there be something else going on because both items dont seem to be working. 

 
![Capture](https://user-images.githubusercontent.com/59422629/71772816-187ad080-2fa6-11ea-9d84-8b557a110e63.PNG)

![Capture](https://user-images.githubusercontent.com/59422629/71772823-3b0ce980-2fa6-11ea-8558-80692473a11a.PNG)

**Comment by marius-wieschollek** [comment]
Have you tried the search feature of the Firefox extension? The first tab will say "no logins" until it can find something that could be related to the current page. 

Also try the synchronize button in the top right.
Also have you set up the experimental end to end encryption in the app?

**Comment by Danielsc87** [comment]
Yes I have tried the search function and the sync function as well. What's the experimental end to end encryption I haven't found a setting for this.

**Comment by Danielsc87** [comment]
sorry i found the end to end encryption i had already set this up it hasn't made a difference, 
![Capture](https://user-images.githubusercontent.com/59422629/71773736-89c27f80-2fb6-11ea-96da-42d3039b35cc.PNG)

**Comment by marius-wieschollek** [comment]
Well that explains the problem. E2E is an experimental functionality which can only be enabled in nightly builds of the app. It is currently unsupported by all clients.

The Android app does not support E2E: https://github.com/daper/nextcloud-passwords-app/issues/54
The Firefox Extension does not support E2E: https://github.com/marius-wieschollek/passwords-webextension/issues/72
Progress about E2E is in #80

**Comment by Danielsc87** [comment]
Thankyou. Is there a way to turn E2E Off. I have a back up of all passwords so deleting them is an option as well. I just csnt see how to turn it off.

**Comment by marius-wieschollek** [comment]
You can't just turn E2E off.

For individual passwords, you can just edit them and select the encryption method in the advanced options. Theis will help with the Firefox/Chrome Extension, but not the Android app.

If you do not care about loosing your individual settings and the password history,
and if you do not have any passwords shared with anyone or by anyone,
then you can just make a database export, reset your account and then import all passwords again.
Take a look at the user handbook in the app for more details.

_Just for your security i would recommend [making a server backup](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Backups#creating-backups) before you do anything that could possibly result in data loss._

**Comment by Danielsc87** [comment]
hi mate, 
everything is working now, i backed up the passwords and pressed delete everything, then reloaded the passwords, everything is working now. thank you for your help. 

![Capture](https://user-images.githubusercontent.com/59422629/71786374-e37e8480-305e-11ea-83a8-bf62624beffb.PNG)
