### ISSUE TITLE
UI Polishing: Hide screenshot when website preview service is "none"

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#224]
**Current Status**
Currently when no website preview service is configured, a place holder image is shown above the password detail pane.

**Feature Description**
My suggestion is to hide this placeholder image if no preview is available (or no preview service is configured). This would also be more in line with the Files app which only shows previews if there is a service for the particular file type available.

**Comment by marius-wieschollek** [comment]
It is not possible for the client to know which service is used to provide an api endpoint.

If you don't like the default images, you can turn of the image completely in the advanced settings.
Check the in-app manual for more information
