### ISSUE TITLE
Letter in the tiles

### ISSUE THREAD

**Issue by xsus95** [marius-wieschollek/passwords#226]
It should be possible to let the letter within the tiles be displayed either above the URL or the given name. In my opinion it would be better if the letter within the tiles would be the first letter of the given name.

**Comment by marius-wieschollek** [comment]
Please don't just ignore the provided form. Copy the [template](https://raw.githubusercontent.com/marius-wieschollek/passwords/master/.github/ISSUE_TEMPLATE/Feature_request.md) and give a precise description of what you want and how it should behave.

**Comment by marius-wieschollek** [comment]
Closed - Please follow the report form
