### ISSUE TITLE
[Feature] Export/Print Feature Missing

### ISSUE THREAD

**Issue by gewgaw4u** [marius-wieschollek/passwords#227]
We would like to have an export feature. The use case would be we export the list in a common readable format (CSV, HTML, TXT) we then store that file on a encrypted/secure (IRON KEY) USB flash drive and store that in a secure cabinet within the facility in case of a nextcloud outage and passwords are required. We all could do the same with a print feature. Ideally being able to select which records get exported (Along with email notifications that an export just occured)

I am not sure if this is possible right now but we are maintaining dual lists manually and it is a pain.

Keeping copies of the backups would require us to have a working nextcloud server?

GewGaw4U

**Comment by marius-wieschollek** [comment]
Please don't just ignore our feature request form. Copy the [template](https://raw.githubusercontent.com/marius-wieschollek/passwords/master/.github/ISSUE_TEMPLATE/Feature_request.md) and give a precise description of what you want and how it should behave. Please also describe how your feature differs from the existing export & backup options.

**Comment by marius-wieschollek** [comment]
Closed - Please follow the report form
