### ISSUE TITLE
Easy Folder change

### ISSUE THREAD

**Issue by bertrand-benoit** [marius-wieschollek/passwords#229]
Hi,

My about 450 passwords are sorted in about 30 folders.
More of them are children of the (fake) root folder.

Sometimes I want to change a password from child A, to child B, but it is a pain to find it, to move it back to the "parent" folder, and then to move it to the good child folder.

Could you add the folder as a property (a select box would be perfect) when viewing/editing a password ?

# System Information

    Nextcloud Version: 17.0.2
    PHP Version: 7.3.6
    Passwords Version: 2019.12.1
    Browser and Version: Firefox 71.0 (64-bit)
    Client OS and Version: Fedora 31 - Kernel 5.3.16-300.fc31.x86_64
    Server OS and Version: Gandi Linux 4.9.124-paas-2270098

# Steps to reproduce

    - go to Edit menu of any password

**Comment by marius-wieschollek** [comment]
I think #119 is what you are describing here.
