### ISSUE TITLE
HTTPS required - but already there

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords#23]
hello there,

i'd love to use nextcloud-passwords
when i try to access it say's "Https required"

i'm using nextcloud-apache along with jwilder-ngix && letsencrypt-companion docker-compose file.
(if needed i can provide)

![bildschirmfoto 2018-02-24 um 17 10 20](https://user-images.githubusercontent.com/3322071/36632331-c799e24c-1985-11e8-8780-5113bd7e5040.png)

**Comment by marius-wieschollek** [comment]
Hi and thank you for reporting. The HTTPS detection issue in some proxy configurations has already been reported and it is fixed in the [current nightly](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13).

**Comment by ghost** [comment]
OS: Ubuntu 17.10
Server: nginx/1.12.2 (reverse proxy that forwards requests to Apache/2.4.25. Nextcloud is processed by Apache)
HTTPS: Yes, enabled in nginx (with Let's Encrypt)
PHP version: 7.2.2
Nextcloud version: 13.0.0

installed the nightly now - https message gone
but password page stays white.
is there something additional i need to install ?
can i see a log somewhere?

**Comment by marius-wieschollek** [comment]
The app uses the normal nextcloud log (Settings -> Log / Protocol). Any PHP Errors will be logged there.
You may also check your browser console (press F12) for failed requests or javascript errors.

**Comment by marius-wieschollek** [comment]
Please do not delete keys in the nextcloud configuration. That's bad for the stability of any app.
Are there any entries in the nextcloud log relating to the passwords app?
The chrome console output seems to be related to another app.

**Comment by Gutz-Pilz** [comment]
i updated my post

**Comment by ghost** [comment]
![bildschirmfoto 2018-02-24 um 23 33 19](https://user-images.githubusercontent.com/3322071/36635766-23ecdc2c-19bb-11e8-9f3d-da290982face.png)

**Comment by marius-wieschollek** [comment]
Can you check the security section in your personal settings. there should be a token called "Passwords WebUi Zugriff ...". If so, delete it. It is encrypted and now doesn't work anymore because you deleted the encryption key.

**Comment by ghost** [comment]
that seem to work. now i got a blank screen again.
![bildschirmfoto 2018-02-24 um 23 42 38](https://user-images.githubusercontent.com/3322071/36635843-7602bba2-19bc-11e8-955e-60fa5176fc72.png)


![bildschirmfoto 2018-02-24 um 23 42 00](https://user-images.githubusercontent.com/3322071/36635833-5af20d36-19bc-11e8-8219-4fec377b858e.png)

**Comment by marius-wieschollek** [comment]
ok. i think the error is in the client api. could you try to replace `/apps/passwords/` with `/index.php/apps/passwords/` in the url?

**Comment by ghost** [comment]
that worked
![bildschirmfoto 2018-02-24 um 23 48 06](https://user-images.githubusercontent.com/3322071/36635928-3b95b5e0-19bd-11e8-9e39-80203e4c8bd7.png)

can i fix this permanently ?

**Comment by marius-wieschollek** [comment]
you can't, but i can :smiley: . I will look into this tomorrow.

**Comment by ghost** [comment]
great. thanks for the help!
looking forward to use it!

**Comment by ghost** [comment]
i cant import my passwords...
this is the error i get

![bildschirmfoto 2018-02-25 um 12 36 24](https://user-images.githubusercontent.com/3322071/36641013-792c23a0-1a29-11e8-9eae-349afe89b2ac.png)

**Comment by ghost** [comment]
i used lastpass before and created a csv.
dant didnt work.
so imported lastpass created csv into keepasscx on my mac and than exported another csv.
seems to take a little longer and imported approx. 10 entries. but than crashs.


![bildschirmfoto 2018-02-25 um 15 30 40](https://user-images.githubusercontent.com/3322071/36642530-df006f1c-1a40-11e8-851c-25734948ce46.png)

is there a way to start over ?
clear the passwords database ?

**Comment by ghost** [comment]
thats from the nextcloud log
`Undefined index: password/label/default at /var/www/html/custom_apps/passwords/lib/Services/SettingsService.php#198`

**Comment by marius-wieschollek** [comment]
I have uploaded a new nighly version, which should solve the loading issues.
I have also switched the CSV parser for testing purposes. When i tried to import the file from LastPass, it got confused with the line breaks.
You can reset the app by truncating the tables, but be aware that this will delete the passwords of all users:
```
TRUNCATE `passwords_entity_folder`;
TRUNCATE `passwords_entity_folder_revision`;
TRUNCATE `passwords_entity_password`;
TRUNCATE `passwords_entity_password_revision`;
TRUNCATE `passwords_entity_share`;
TRUNCATE `passwords_entity_tag`;
TRUNCATE `passwords_entity_tag_revision`;
TRUNCATE `passwords_relation_password_tag`;
```

**Comment by ghost** [comment]
Thanks for the new version.
Loading issue is solved!
But importing issue persists
![bildschirmfoto 2018-02-25 um 22 37 31](https://user-images.githubusercontent.com/3322071/36646803-ca4fde54-1a7c-11e8-815b-bca3cbeeab41.png)

**Comment by marius-wieschollek** [comment]
Ok. i have uploaded [build 1989](https://git.mdns.eu/nextcloud/passwords/-/jobs/5578/artifacts/raw/passwords.tar.gz) which has the full debugging enabled. Also it skips passwords that failed to import and delivers a message on which error occurred with which object. That should at least give a hint what's going wrong.

**Comment by ghost** [comment]
okay. installed the new nightly.
but have to test at home with my mac - at work (windows)says - "Falscher Dateityp" if i try upload a csv (no matter which csv)

i'll keep you posted
