### ISSUE TITLE
Option to ask for PIN in the web session

### ISSUE THREAD

**Issue by julenl** [marius-wieschollek/passwords#230]
**Current Status**
AFAIK: None

**Feature Description**
It would be useful to have an option to ask for a password or PIN every time we access the Passwords App on the browser (Nextcloud web interface). Just like in the Android "NextcloudPasswords" App.

At the moment, if the nextcloud session is left open on a browser, anybody that can access the computer has full access the whole thing.

The files, and the rest of the nextcloud Apps are also important, but the Passwords App is critical!

**Comment by marius-wieschollek** [comment]
See #80 for master passwords and 2FA
