### ISSUE TITLE
Error 500 by Exception "Unable to verify user ...." (SAML authentication)

### ISSUE THREAD

**Issue by simmstein** [marius-wieschollek/passwords#234]
### System Information
- Nextcloud Version: 17 (stable channel)
- PHP Version: 7.3
- Passwords Version: nightly
- Browser and Version: all
- Client OS and Version: all
- Server OS and Version: Debian 10 (buster)

### Steps to reproduce

1. Use SAML authentication
2. Authenticate and try browsing nextcloud

### Expected result

No exception.

### Actual result

exception thrown after authentication: `Unable to verify user user@domain`.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
<pre>
{
    "reqId": "xxxxxxxx",
    "level": 3,
    "time": "2020-01-16T12:44:47+00:00",
    "remoteAddr": "a.b.c.d",
    "user": "user@domain.com",
    "app": "index",
    "method": "GET",
    "url": "\/index.php\/apps\/passwords\/",
    "message": {
        "Exception": "Exception",
        "Message": "Unable to verify user user@domain.com",
        "Code": 0,
        "Trace": [{
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/apps\/passwords\/lib\/Services\/EnvironmentService.php",
            "line": 299,
            "function": "loadUserInformation",
            "class": "OCA\\Passwords\\Services\\EnvironmentService",
            "type": "->",
            "args": ["user@domain.com", {
                "__class__": "OC\\AppFramework\\Http\\Request"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/apps\/passwords\/lib\/Services\/EnvironmentService.php",
            "line": 159,
            "function": "determineAppMode",
            "class": "OCA\\Passwords\\Services\\EnvironmentService",
            "type": "->",
            "args": ["user@domain.com", {
                "__class__": "OC\\AppFramework\\Http\\Request"
            }]
        }, {
            "function": "__construct",
            "class": "OCA\\Passwords\\Services\\EnvironmentService",
            "type": "->",
            "args": ["user@domain.com", {
                "__class__": "OC\\AllConfig"
            }, {
                "__class__": "OC\\AppFramework\\Http\\Request"
            }, {
                "__class__": "OC\\Session\\CryptoSessionData"
            }, {
                "__class__": "OCA\\Passwords\\Services\\LoggingService"
            }, {
                "__class__": "OC\\Authentication\\Token\\Manager"
            }, {
                "__class__": "OC\\User\\Manager"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 82,
            "function": "newInstanceArgs",
            "class": "ReflectionClass",
            "type": "->",
            "args": [
                ["user@domain.com", {
                    "__class__": "OC\\AllConfig"
                }, {
                    "__class__": "OC\\AppFramework\\Http\\Request"
                }, {
                    "__class__": "OC\\Session\\CryptoSessionData"
                }, {
                    "__class__": "OCA\\Passwords\\Services\\LoggingService"
                }, {
                    "__class__": "OC\\Authentication\\Token\\Manager"
                }, {
                    "__class__": "OC\\User\\Manager"
                }]
            ]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 99,
            "function": "buildClass",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": [{
                "name": "OCA\\Passwords\\Services\\EnvironmentService",
                "__class__": "ReflectionClass"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 114,
            "function": "resolve",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\EnvironmentService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 414,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\EnvironmentService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 385,
            "function": "queryNoFallback",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\EnvironmentService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 69,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\EnvironmentService", true]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 99,
            "function": "buildClass",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": [{
                "name": "OCA\\Passwords\\Services\\ConfigurationService",
                "__class__": "ReflectionClass"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 114,
            "function": "resolve",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\ConfigurationService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 414,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\ConfigurationService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 385,
            "function": "queryNoFallback",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\ConfigurationService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 69,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\ConfigurationService", true]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 99,
            "function": "buildClass",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": [{
                "name": "OCA\\Passwords\\Helper\\Settings\\UserSettingsHelper",
                "__class__": "ReflectionClass"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 114,
            "function": "resolve",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Helper\\Settings\\UserSettingsHelper"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 414,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Helper\\Settings\\UserSettingsHelper"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 385,
            "function": "queryNoFallback",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Helper\\Settings\\UserSettingsHelper"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 69,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Helper\\Settings\\UserSettingsHelper", true]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 99,
            "function": "buildClass",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": [{
                "name": "OCA\\Passwords\\Services\\UserSettingsService",
                "__class__": "ReflectionClass"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 114,
            "function": "resolve",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\UserSettingsService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 414,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\UserSettingsService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 385,
            "function": "queryNoFallback",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\UserSettingsService"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 69,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Services\\UserSettingsService", true]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 99,
            "function": "buildClass",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": [{
                "name": "OCA\\Passwords\\Controller\\PageController",
                "__class__": "ReflectionClass"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php",
            "line": 114,
            "function": "resolve",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Controller\\PageController"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 414,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Controller\\PageController"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/DependencyInjection\/DIContainer.php",
            "line": 385,
            "function": "queryNoFallback",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Controller\\PageController"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/App.php",
            "line": 113,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Passwords\\Controller\\PageController"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php",
            "line": 47,
            "function": "main",
            "class": "OC\\AppFramework\\App",
            "type": "::",
            "args": ["OCA\\Passwords\\Controller\\PageController", "index", {
                "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            }, {
                "_route": "passwords.page.index"
            }]
        }, {
            "function": "__invoke",
            "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
            "type": "->",
            "args": [{
                "_route": "passwords.page.index"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/private\/Route\/Router.php",
            "line": 297,
            "function": "call_user_func",
            "args": [{
                "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
            }, {
                "_route": "passwords.page.index"
            }]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/lib\/base.php",
            "line": 997,
            "function": "match",
            "class": "OC\\Route\\Router",
            "type": "->",
            "args": ["\/apps\/passwords\/"]
        }, {
            "file": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/index.php",
            "line": 42,
            "function": "handleRequest",
            "class": "OC",
            "type": "::",
            "args": []
        }],
        "File": "\/var\/www\/service-web\/www\/preprod\/nextcloud\/apps\/passwords\/lib\/Services\/EnvironmentService.php",
        "Line": 337,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla\/5.0 (X11; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0",
    "version": "17.0.2.1"
}
</pre>
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy the content of the console tab
```
</details>

**Comment by simmstein** [comment]
Additionnal informations: 

* `EnvironmentService::getUserInfoFromPassword` returns `false` because of `$loginUser = $this->userManager->checkPasswordNoLogging($loginName, $password);` which returns `false` too.
* `$password` given in getUserInfoFromPassword call is an empty string (SAML authentication)

**Comment by marius-wieschollek** [comment]
SAML should now work again with the current build 3352

**Comment by simmstein** [comment]
Works for me!

Thanks and great job :)
