### ISSUE TITLE
No Share options

### ISSUE THREAD

**Issue by Be-Mann** [marius-wieschollek/passwords#236]
### System Information
- Nextcloud Version: 18.0.0
- PHP Version: 7.3.13
- Passwords Version: 2020.1.0
- Browser and Version: Chrome Version 79.0.3945.117
- Client OS and Version: MacOS 10.14.6
- Server OS and Version: Ubuntu 18.04.3 LTS

### Steps to reproduce
The share function does not work, there is no way to share the passwords
![Ohne Titel](https://user-images.githubusercontent.com/25839760/72787187-bcfc4400-3c2f-11ea-9585-03e12a690125.png)

### Nextcloud log
empty

### Browser log
[nextcloud.druckplanet24.de-1579595249949.log](https://github.com/marius-wieschollek/passwords/files/4089928/nextcloud.druckplanet24.de-1579595249949.log)

**Comment by Be-Mann** [comment]
It is the same with the Passwords Version: 2020.2.0-build3378

Only the error in the browser log is gone.

**Comment by marius-wieschollek** [comment]
If you have an adblocker, try to disable it. If you have uBlock check if the list "Fanboy’s Annoyance​​​​​​​​" or "Fanboy’s Social" is enabled and disable it.

**Comment by Be-Mann** [comment]
This is correct, I have an AdBlocker, but it should / has to work anyway. (if this is recognized by the AdBlocker as advertising, the code is faulty, i.e. a BUG)

If I pause AdBlocker temporarily, the input field is visible.

**Comment by marius-wieschollek** [comment]
This is not a bug. As you have seen the sharing options work just fine, the app works as designed.

You have installed and configured an adblocker to delete parts of the HTML DOM if they are related to "sharing". So the adblocker also works as designed.
The app does not have any anti-adblock measures, so integrating those would be a FEATURE.

From a technical standpoint all the software you have does what it is supposed to do. If you don't like the outcome, you need to configure it differently, i.e. whitelist your Nextcloud in your adblocker. A normal installation of Nextcloud does have neither ads nor tracking so i don't see the use of an adblocker here.

**Comment by Be-Mann** [comment]
This may be, but this is the only app on Nextcloud where the AdBlocker starts. In addition, on all websites that I have written, even if input fields are reloaded via Javascript, such behavior has never been seen.

Therefore, you should maybe see why AdBlock recognizes this as advertising and fix it.

**Comment by marius-wieschollek** [comment]
AdBlockers blocking elements related to sharing is definitely a well known issue. FontAwesome put up a warning for this, Nextcloud has had several tickets about blocked sharing and of course the bug trackers of AdBlockers contain many issues related to false positives. An AdBlocker blocking something has definitely been a part of any website i ever worked on.

Passwords is definitely not the only app affected by this. If i enable all anti annoyances lists in ublock and turn the Nextcloud interface to English, half of the files app gets blocked including the entire sharing tab.
![grafik](https://user-images.githubusercontent.com/8255857/72851689-a0522180-3cac-11ea-9561-47464b6fc976.png)

The social media blocking feature blocks all kinds of stuff in the app like favicons, previews, nav icons and the share tab. If you name a folder "sharing" that could already be enough. Elements with classes like ".sharing-container", ".sharing" and ".fa-share" are blocked by Fanboy’s lists and the app uses those classes.

In the end, the conclusion is the same for me as for the Nextcloud devs: There is nothing i can do that is sustainable to fix this. If your AdBlocker blocks things you wanted to see, you need to fix it yourself. I can't possibly write my app in a way that will not trigger an AdBlocker if there is an entire industry dedicated to that and still can't do it.

My final word on this is: Not a bug, won't get fixed.
