### ISSUE TITLE
Updating Nextcloud to 17.03 and password to 2020.2.0 crashes settings

### ISSUE THREAD

**Issue by Omaha2002** [marius-wieschollek/passwords#240]
After updating Passwords to latest version user is unable to access settingspage, disabling passwords fixes access to settings page.

Error while clicking on settings while passwords enabled:
![image](https://user-images.githubusercontent.com/3179748/73590478-0d528c00-44e3-11ea-94fa-90ab7a5ff750.png)

Serverlogging:
![image](https://user-images.githubusercontent.com/3179748/73590781-bd75c400-44e6-11ea-9e28-acb3ffb2d10d.png)

**User is logging in through Social Login app with AzureAD connection**

related to issue #196 ?

Ubuntu 18.0.4.4
PHP 7.3.14-1
Mariadb  Ver 15.1 Distrib 10.4.12
Nextcloud 17.0.3

**Comment by marius-wieschollek** [comment]
Yes, you seem to be right. I will fix that.

**Comment by marius-wieschollek** [comment]
I think this a similar issue to #234. The current nightly build should fix this.

**Comment by marius-wieschollek** [comment]
This should now no longer be an issue
