### ISSUE TITLE
Add option to use different screeenly instance than default

### ISSUE THREAD

**Issue by NateTheSage** [marius-wieschollek/passwords#241]
**Current Status**
Screeenly works great, in fact, so well, that I've got my own instance running alongside my Nextcloud instance in addition to using Besticon. I'm currently using a couple of hacks to make it use the local one rather than the hosted option.

**Feature Description**
Hopefully this is as simple as it sounds, but an additional text box that allows us to set our own screeenly URL would be nice to have, defaulted to the one currently in use by Passwords. Since we have the option to run our own Besticon instance, I thought that having the ability to run screeenly as well would put a very nice bow on an already excellent addon for Nextcloud.

**Additional context**
This should be a simple addition, however, it is not pressing by any means, just a quality-of-life request. :smile:

**Comment by marius-wieschollek** [comment]
I think we have this already: https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/App-Settings#website-preview-service

**Comment by NateTheSage** [comment]
Yeah, I was hoping for a GUI-based option in the Settings page for Passwords. I know we already have it, I was just asking for a more user-friendly self-hosted option, like how when Besticon pops up with the option to set the "Favicon Service API" URL. I'm just redirecting the traffic to screeenly to the localhost right now and wanted something cleaner.

Sorry if that wasn't clear!

**Comment by marius-wieschollek** [comment]
Since screeenly v2 i no longer being developed, i don't want to add a new ui just for that.
