### ISSUE TITLE
Browser is outdated

### ISSUE THREAD

**Issue by fluxx147** [marius-wieschollek/passwords#242]
Hello Marius,

i use some firefox customizations of the ghacks user.js. 
I have the current firefox (72.0.2) but the password app (2020.2.1) shows that the browser is outdated.

which firefox parameter do i have to adjust to be able to use the app again?

Thanks
fluxx

**Comment by marius-wieschollek** [comment]
You can check the browser console to see if an error message besides `Browser does not suport ECMAScript 2017 / ES2017` is there.

The app checks the following things:
* `window.crypto.subtle` must be present
* `window.TextEncoder` must be present
* `typeof WebAssembly === "object"` must be true
* `typeof WebAssembly.instantiate === "function"` must be true

The function to check the compatibility is [this one](https://github.com/marius-wieschollek/passwords/blob/master/src/js/Helper/compatibility.js#L1):
```
function isCompatibleBrowser() {
    try {
        return window.crypto.subtle &&
               window.TextEncoder &&
               typeof WebAssembly === "object" && typeof WebAssembly.instantiate === "function";
    } catch(e) {
        console.error(e);

        return false;
    }
}
```

you can paste that code into your console and then call the function. It should return true.

**Comment by fluxx147** [comment]
Thanks for your help. Yes, the script returned false. I searched for WebAssemblies and found what I was looking for:

javascript.options.wasm = false

It must be **true**. 

Everything's working again. Thanks!
