### ISSUE TITLE
Saving a custom field fails

### ISSUE THREAD

**Issue by benginoe** [marius-wieschollek/passwords#243]
### System Information
- Nextcloud Version: 18.0.1
- PHP Version: 7.3.14
- Passwords Version: 2020.2.1
- Browser and Version: Firefox 73.0
- Client OS and Version: Fedora 31
- Server OS and Version: CentOS 7

### Steps to reproduce
1. Create Password, save it, reopen and add custom secret field, save. Reopen in details perspective, no custom secret field appears.

### Expected result
Custom secret field should appear in detail view

### Actual result
Custom secret field doesnt appear in detail nor in another view.

### Browser log
<details>
<summary>Browser log</summary>

```
TypeError: "e.values is not a function"
    arrayValues https://own-cloud.eu/apps/passwords/js/Static/app.js:1
    updateCustomFields https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    r https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    $emit https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    updateField https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    r https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    $emit https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    updateField https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    type https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    run https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    hr https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    nt https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Ze https://own-cloud.eu/apps/passwords/js/Static/app.js:43
app.js:43:11689
    qe https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Ke https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Oe https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    r https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    $emit https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    updateField https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    r https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Je https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    $emit https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    updateField https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    type https://own-cloud.eu/apps/passwords/js/Static/CreatePassword.b9a1e66bee93b6a2676e.js:1
    run https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    hr https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    nt https://own-cloud.eu/apps/passwords/js/Static/app.js:43
    Ze https://own-cloud.eu/apps/passwords/js/Static/app.js:43

```
</details>

If further information are necessary dont hesitate to ask. I hope you can assist, thanks for your work!

**Comment by benginoe** [comment]
Edit:
Device: Android 10
Nextcloud Password App: 1.11


Created the Password in the Android-App, maybe this is the reason why it doesnt work? 

There is no problem with adding custom fields, with a password which was created within the webapp.

**Comment by marius-wieschollek** [comment]
Thanks for letting me know about this issue. It is indeed that the third party android app forgets to initialize the custom fields array and the web ui then can not add any entries to it since it does not exist.

The nightly version of 2020.3.0 (build 3453) contains a fix for this.
Running `./occ maintenance:repair` from a command line on the server or occweb will look for affected passwords and repair them. This only works for existing passwords, to prevent this for new passwords a patch for the android app would be necessary.

**Comment by benginoe** [comment]
I submitted now a bug in the git repo for the app as well. 

https://github.com/daper/nextcloud-passwords-app/issues/62

Thanks for your fast reply!
