### ISSUE TITLE
How do you create a master password / set up 2FA

### ISSUE THREAD

**Issue by Disco1** [marius-wieschollek/passwords#245]
Is there some way to create a master password?

How do you set up 2FA?

Sorry, if these are answered in the documentation, I can't find them. I see it mentioned in the FAQ, but nowhere else.

**Comment by marius-wieschollek** [comment]
The issue tracker is for bugs and feature requests only, not for questions.

If you have a question please check the manual, try the forum or look at the related issues here before opening a new one.
