### ISSUE TITLE
freeze nextcloud passwords when users form ispconfig mail

### ISSUE THREAD

**Issue by millosz222** [marius-wieschollek/passwords#246]
when users are form ispconfig mail integration (login is mail address) and when i started andorid app and login i cant see any passwords and after that nextcloud passwords (on www) is freeing its loading but really slowly.

How can reapair it - i want working without andorid app but now passwords app on nextcloud loading very slowly

**Comment by marius-wieschollek** [comment]
The issue tracker is for bugs and feature requests only, not for questions.

If you have a question please check the manual, try the forum or look at the related issues here before opening a new one.
