### ISSUE TITLE
Locked out asking for HTTPS 

### ISSUE THREAD

**Issue by rgarrigue** [marius-wieschollek/passwords#25]
Hi

I'm running Nextcloud via docker, behind another ontainer which is dealing with HTTPS. Seems your apps doesn't acknowledge that, it's preventing me from using it with a splash screen asking for HTTPS...

Please add a button so an admin user can ignore the warning.

Best regards,

**Comment by marius-wieschollek** [comment]
This is a known issue. You can either use the nightly version or set `forcessl => true` in the config.php
