### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry '-' for key 'pw_password_revision_index'

### ISSUE THREAD

**Issue by balmmva** [marius-wieschollek/passwords#250]
Hi

on nextcloud 17.0.2 ubuntu 18.04.3 LTS
update Passwords to 2020.3.1 failed because of php7.4.1 being detected
occ upgrade (This version of Nextcloud is not compatible with > PHP 7.3.<br/>You are currently running 7.4.1)
I had to disable the Passwords app.

I can't re-enable the app.

Any advice ?

**Comment by marius-wieschollek** [comment]
Hi. If you have a feature request or bug report please fill out the bug report form or the feature form.

If you have an issue that is related to your individual setup, please go to the forum. If you do so please include an chronological list of what you did and what happened in your forum post.

**Comment by balmmva** [comment]
which forum would you recommend ?

**Comment by marius-wieschollek** [comment]
There are serveral support options listed in the readme.

I would recommend our category in the Nextcloud forum https://help.nextcloud.com/c/apps/passwords
