### ISSUE TITLE
freeze when user login doesnt exist in nextcloud

### ISSUE THREAD

**Issue by millosz222** [marius-wieschollek/passwords#251]
### System Information
- Nextcloud Version: 18.0.1
- PHP Version: 7.3.11
- Passwords Version: 2020.3.1
- Browser and Version: chrome, edge,firefox
- Client OS and Version: windows
- Server OS and Version: debian 10

### Steps to reproduce
1. login via api (chrome widget)
2. use username what not exist in nextcloud

### Expected result
site freeze in bookmark "passwords" loading ok 60 sec.
### Actual result
site is loaded but in 60sec not imidiately
### Nextcloud log

Warning | core | Login failed: '' (Remote IP: '192.168.220.99') |   | 2020-03-06T14:10:56+0100
-- | -- | -- | -- | --
Warning | passwords | Login attempt with invalid authorization header for invalid user id |   | 2020-03-06T14:10:50+0100
Warning | core | Login failed: 'Milosz.berlik%40olsun.pl' (Remote IP: '192.168.220.99') |   | 2020-03-06T14:10:50+0100
Warning | passwords | Login attempt with invalid authorization header for invalid user id |   | 2020-03-06T14:10:46+0100
Warning | core | Login failed: 'Milosz.berlik%40olsun.pl' (Remote IP: '192.168.220.99') |   | 2020-03-06T14:10:46+0100
Warning | no app in context | Login failed: Miłosz.berlik@olsun.pl (Remote IP: 192.168.220.99) |   | 2020-03-06T14:10:28+0100
Error | PHP | count(): Parameter must be an array or an object that implements Countable at /var/www/html/nextcloud/apps/user_ispconfig/lib/user_ispconfig.php#302 |   | 2020-03-06T14:10:28+0100
Warning | core | Login failed: '' (Remote IP: '192.168.220.99') |   | 2020-03-06T14:09:47+0100
Warning | passwords | Login attempt with invalid authorization header for invalid user id |   | 2020-03-06T14:09:46+0100
Warning | core | Login failed: 'Milosz.berlik%40olsun.pl' (Remote IP: '192.168.220.99')

**Comment by marius-wieschollek** [comment]
If you try to log into Nextcloud with invalid credentials several times it will slow down any further api request. Since the app is built on the api it will be slowed down as well. You can check the table `bruteforce_attempts` in your database and delete its content to solve this issue.
