### ISSUE TITLE
very slow app and some errors

### ISSUE THREAD

**Issue by happyreacer** [marius-wieschollek/passwords#252]
Hi,
i have a problem with the password app on nextcloud. it works very slow and sometimes the connection fails.

### System Information
- Nextcloud Version: 18.0.1
- PHP Version:7.3
- Passwords Version:2020.3.1

here are the nextcloud errors logs:
The first was:
`{"reqId":"61MHoQVv75ttOyDTFS7I","level":2,"time":"2020-03-07T23:12:10+00:00","remoteAddr":"79.215.123.123","user":"user1","app":"passwords","method":"GET","url":"/apps/passwords/","message":"Cancelled expired session 5eb0d808-2d4d-4e8d-99a2-839e9f3d6253 for christoph","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3","id":"5e643496d2c65"}`

and then:
```
0. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "show")
1. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("FolderApiController", "show", OC\AppFramework\ ... {}, {_route: "passwords.folder_api.show"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwords.folder_api.show"})
3. /config/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "passwords.folder_api.show"})
4. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/passwords/api/1.0/folder/show")
5. /config/www/nextcloud/index.php line 38
   OC::handleRequest()

POST /index.php/apps/passwords/api/1.0/folder/show
from 79.215.179.122 by user1 at 2020-03-07T23:26:51+00:00`
`[passwords] Error: Exception: Class 'OCA\Passwords\Db\Session' not found at <<closure>>

0. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "show")
1. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("FolderApiController", "show", OC\AppFramework\ ... {}, {_route: "passwords.folder_api.show"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwords.folder_api.show"})
3. /config/www/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "passwords.folder_api.show"})
4. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/passwords/api/1.0/folder/show")
5. /config/www/nextcloud/index.php line 38
   OC::handleRequest()

POST /index.php/apps/passwords/api/1.0/folder/show
from 79.215.179.122 by user1 at 2020-03-07T23:26:51+00:00
````

what can i do?

**Comment by marius-wieschollek** [comment]
> [passwords] Error: Exception: Class 'OCA\Passwords\Db\Session' not found

This looks like there are files missing on your server. Download the latest version from the app store and replace the current version with the new files. Make sure that your server has enough storage space left. Run `./occ integrity:check-app passwords` and `./occ integrity:check-core` from the command line and make sure that they do not return any errors.

**This bug report is missing:**
 * Full system information
 * Steps to reproduce
 * Expected result
 * Actual result

Please complete your bug report or it will be closed
