### ISSUE TITLE
PHP 7.2 unsupported

### ISSUE THREAD

**Issue by szaimen** [marius-wieschollek/passwords#253]
The admin panel says to me that PHP 7.2 is unsupported. Why is that the case?

Nextcloud still supports it and the official PHP developer site says that it will get security updates until 30 Nov 2020 https://www.php.net/supported-versions.php

So would be really good to know why it is unsupported :)

**Comment by marius-wieschollek** [comment]
I'm pretty sure you know this is not a bug. So please use one of the issue options intended for questions.

**Comment by szaimen** [comment]
@marius-wieschollek Yes, but I asked here because it would be really nice to get your answer on that :)

**Comment by szaimen** [comment]
@marius-wieschollek Or is there already an official statement anywhere? Then I am happy if you would point me to it.
