### ISSUE TITLE
Cannot create folder

### ISSUE THREAD

**Issue by bbruno** [marius-wieschollek/passwords#259]
### System Information
- Nextcloud Version:18.0.3
- PHP Version:7.3.14
- Database and Version:MariaDB 10.3.22
- Passwords Version:2020.4.0
- Browser and Version:Firefox 68.6/Chromium 80
- Client OS and Version:Debian 11
- Server OS and Version:Debian 10

### Steps to reproduce
1. Click on "+" button, choose "New folder" 

### Expected result
Popup to create folder

### Actual result
No Popup (but error in console browser)

### Nextcloud log
No relevant information in this log

### Browser log (In firefox)
<details>
<summary>Browser log</summary>
TypeError: "t is undefined"
    jQuery 3
    prompt dialogs.js:147
    jQuery 8
    prompt dialogs.js:144
    prompt app.js:1
    D es6.promise.js:177
    prompt app.js:1
    createFolder app.js:43
    D es6.promise.js:177
    createFolder app.js:43
    createFolder app.js:43
    Je app.js:43
    r app.js:43
    _wrapper app.js:43
 data: undefined
</details>

**Comment by marius-wieschollek** [comment]
I can not reproduce this issue.

According to the stack trace you posted, there is an issue with a variable or function named "t" in line 147 of Nextcloud / dialog.js. But Nextcloud 18.0.3 does not use anything named "t" in [that line](https://github.com/nextcloud/server/blob/stable18/core/src/OC/dialogs.js#L147) only Nextcloud 17 [does](https://github.com/nextcloud/server/blob/stable17/core/src/OC/dialogs.js#L147).
So i would assume that there is maybe something wrong with your Nextcloud or you should clear the browser cache.

**Comment by bbruno** [comment]
Hi @marius-wieschollek ,

This trace is from Firefox. Oddly this from Chromium is different :
octemplate.js:90 TypeError: Cannot read property 'replace' of undefined
    at Object._build (octemplate.js:83)
    at Object.init (octemplate.js:76)
    at e.fn.init.o.a.fn.octemplate (octemplate.js:102)
    at Object.<anonymous> (dialogs.js:147)
    at Object.<anonymous> (jquery.js:3256)
    at c (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at Object.Deferred.m.each.r.<computed> [as resolve] (jquery.js:3301)
    at Object.success (dialogs.js:1025)
    at c (jquery.js:3099) "data:" undefined 

We also have test with passwords 202.4.1 (nighty build), but no change.

What can I do to investigate ?

Thank's

**Comment by marius-wieschollek** [comment]
Open the developer tools, open the network tab, disable the cache and reload the page.
Before you click on the "new folder" option, make sure that all network requests have finished.
Click on the "new folder" option. A request to `https://yourdomain/core/templates/message.html` should appear. The content should be
```
<div id="{dialog_name}" title="{title} ">
	<p><span class="ui-icon ui-icon-{type}"></span>{message}</p>
</div>
```

Also check the setup warnings and integrity check results of your Nextcloud in the admin settings.

**Comment by bbruno** [comment]
In Chromium, network tab, disable cache, reload page => click message.html line => preview, response empty.

I have 3 errors on "security & setup warnings" : 

Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
	- EXTRA_FILE
		- core/img/filetypes/mindmap.svg

Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.

**Comment by marius-wieschollek** [comment]
Ok, i think there is something wrong with your nextcloud installation. Maybe check the nextcloud documentation or the forum for the best way to fix this. I would download the current verstion from their website and overwrite the files on the server with it.

**Comment by bbruno** [comment]
Ok. Do you know another button/link in Nextcloud which is similar to this "new folder" button ? Perhaps that could lead our research...(all other app in Nextcloud seams to work normally)
Thanks for your help.

**Comment by marius-wieschollek** [comment]
I'm not sure, but i think that Nextcloud sometimes requires a password if you install an app or change the language of your account and this dialog probably uses the same functionality.

The basic call to trigger the Nextcloud dialog is `OC.dialogs.prompt('text', 'title', console.log, true, 'message', false);`. If you go offline before clicking the option, a browser prompt should appear.

**Comment by bbruno** [comment]
Ok. I'll try to find another use case in Nextcloud.
Thank you @marius-wieschollek
