### ISSUE TITLE
OCA\Passwords\Exception\ApiException: Internal Words API Error

### ISSUE THREAD

**Issue by Salokyn** [marius-wieschollek/passwords#260]
### System Information
- Nextcloud Version: 18.0.3
- PHP Version: 7.3
- Database and Version: Mariadb
- Passwords Version: 2020.4.0
- Browser and Version: FF75
- Client OS and Version: Ubuntu 18
- Server OS and Version: Alpine Linux v3.11

### Steps to reproduce
1. Generate new passwords using Leipzig Corpora Collection

### Expected result
Password generated

### Actual result
Sometimes I get the error : Internal Words API Error. I need to click on the generate button few times to have working.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```json
{
  "reqId": "rdthyGnoagQUkrI083Me",
  "level": 3,
  "time": "2020-04-14T07:50:41+00:00",
  "remoteAddr": "10.0.31.4",
  "user": "27931f44-5d32-1034-95be-2f20ab3d3769",
  "app": "passwords",
  "method": "GET",
  "url": "/index.php/apps/passwords/api/1.0/service/password",
  "message": {
    "Exception": "OCA\\Passwords\\Exception\\ApiException",
    "Message": "Internal Words API Error",
    "Code": 256,
    "Trace": [
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
        "line": 77,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
        "line": 77,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
        "line": 77,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
        "line": 77,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
        "line": 77,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
        "line": 77,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/custom_apps/passwords/lib/Controller/Api/ServiceApiController.php",
        "line": 141,
        "function": "getPassword",
        "class": "OCA\\Passwords\\Services\\WordsService",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 170,
        "function": "generatePassword",
        "class": "OCA\\Passwords\\Controller\\Api\\ServiceApiController",
        "type": "->",
        "args": [
          "*** sensitive parameter replaced ***",
          "*** sensitive parameter replaced ***",
          "*** sensitive parameter replaced ***"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 99,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Passwords\\Controller\\Api\\ServiceApiController"
          },
          "generatePassword"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 125,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Passwords\\Controller\\Api\\ServiceApiController"
          },
          "generatePassword"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "ServiceApiController",
          "generatePassword",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "passwords.service_api.generate_password"
          }
        ]
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->",
        "args": [
          {
            "_route": "passwords.service_api.generate_password"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 299,
        "function": "call_user_func",
        "args": [
          {
            "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "_route": "passwords.service_api.generate_password"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1008,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/passwords/api/1.0/service/password"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 38,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/custom_apps/passwords/lib/Services/WordsService.php",
    "Line": 80,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0",
  "version": "18.0.3.0",
  "id": "5e956cfb50c55"
}
```
</details>

**Comment by marius-wieschollek** [comment]
What is your setting for the strength of the generated password?

**Comment by Salokyn** [comment]
Strength: 2

**Comment by marius-wieschollek** [comment]
If you also use special characters or numbers, i think i found the bug. You can try the [nightly](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies) and see if it is working there.

**Comment by Salokyn** [comment]
> If you also use special characters or numbers

Indeed.

> You can try the [nightly](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies) and see if it is working there.

It happens randomly. But I can try.

**Comment by marius-wieschollek** [comment]
I have released the 2020.4.1. If the issue does not appear anymore i will consider it fixed.

**Comment by Salokyn** [comment]
I cannot reproduce the error with 2020.4.1.

**Comment by Weiming-Hu** [comment]
I started to receive this issue recently. Here is my configuration:

- Nextcloud version: 19.0.4
- PHP version: 7.3
- Passwords version: 2020.11.0
- Browser and Version: Firefox 82.0.3
- Client OS and Version: Mac OS Catalina
- Server OS and Version: Raspbian GNU/Linux 10 (buster)

Error message:

```
[passwords] Error: OCA\Passwords\Exception\ApiException: Internal Words API Error at <<closure>>

 0. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 1. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 2. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 3. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 4. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 5. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 6. /var/www/html/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php line 141
    OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
 7. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Passwords\Controller\Api\ServiceApiController->generatePassword("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 8. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "generatePassword")
 9. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "generatePassword")
10. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("ServiceApiController", "generatePassword", OC\AppFramework\ ... {}, {_route: "passwo ... "})
11. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwo ... "})
12. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "passwo ... "})
13. /var/www/html/nextcloud/lib/base.php line 1011
    OC\Route\Router->match("/apps/passwords ... d")
14. /var/www/html/nextcloud/index.php line 37
    OC::handleRequest()

GET /nextcloud/index.php/apps/passwords/api/1.0/service/password
from 104.39.106.75 by Weiming at 2020-11-11T17:20:39+00:00
```

**Comment by thowitz** [comment]
> I started to receive this issue recently. Here is my configuration:
> 
> * Nextcloud version: 19.0.4
> * PHP version: 7.3
> * Passwords version: 2020.11.0
> * Browser and Version: Firefox 82.0.3
> * Client OS and Version: Mac OS Catalina
> * Server OS and Version: Raspbian GNU/Linux 10 (buster)
> 
> Error message:
> 
> ```
> [passwords] Error: OCA\Passwords\Exception\ApiException: Internal Words API Error at <<closure>>
> 
>  0. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  1. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  2. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  3. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  4. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  5. /var/www/html/nextcloud/apps/passwords/lib/Services/WordsService.php line 77
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  6. /var/www/html/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php line 141
>     OCA\Passwords\Services\WordsService->getPassword("*** sensitive parameters replaced ***")
>  7. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
>     OCA\Passwords\Controller\Api\ServiceApiController->generatePassword("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
>  8. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
>     OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "generatePassword")
>  9. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 137
>     OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "generatePassword")
> 10. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
>     OC\AppFramework\App::main("ServiceApiController", "generatePassword", OC\AppFramework\ ... {}, {_route: "passwo ... "})
> 11. <<closure>>
>     OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwo ... "})
> 12. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
>     call_user_func(OC\AppFramework\ ... {}, {_route: "passwo ... "})
> 13. /var/www/html/nextcloud/lib/base.php line 1011
>     OC\Route\Router->match("/apps/passwords ... d")
> 14. /var/www/html/nextcloud/index.php line 37
>     OC::handleRequest()
> 
> GET /nextcloud/index.php/apps/passwords/api/1.0/service/password
> from 104.39.106.75 by Weiming at 2020-11-11T17:20:39+00:00
> ```

I've also been having this problem with the same passwords version

**Comment by marius-wieschollek** [comment]
@Weiming-Hu @thowitz If you're having an issue please open a new bug report. This one is resolved.
