### ISSUE TITLE
Update 2020.4.0 very slow and timeouts

### ISSUE THREAD

**Issue by lightlike** [marius-wieschollek/passwords#262]
**EDIT: most of this has solved itself over the day but some stuff is still present. More information below**

### System Information
- Nextcloud Version: 18.0.3
- PHP Version: 7.3.16
- Database and Version: MariaDB/MySQL (Docker) v10.4.12
- Passwords Version: 2020.4.0
- Client: Chrome Dev Client v2.0.0.3501

### Issue 1
Chrome Client unable to Sync

Error Message:
- Expected application/json, got text/html
- Error 502 Timeout

### Issue 2
Passwords take up to 1 minute to load (menu loads fast)

### Connected Problems
Nextcloud App Passwords flooded with session entries

### Tried
- Revert and reapply update
- clear client login
- reset client passwords

### Information for logs
**Login-Token is correct worked before update**
**Warning also appears when only using web-interface**

### Nextcloud log
**Flooded with:**
[passwords] Warning: Login attempt with invalid authorization header for invalid user id

GET /index.php/apps/passwords/api/1.0/session/keepalive
from *** at 2020-04-14T08:04:17+00:00

**additional messages (thrown once):**
[passwords] Error: OC\Authentication\Exceptions\InvalidTokenException:  at <<closure>>

 0. /config/www/nextcloud/lib/private/Authentication/Token/Manager.php line 173
    OC\Authentication\Token\DefaultTokenProvider->getTokenById("*** sensitive parameters replaced ***")
 1. /config/www/nextcloud/apps/passwords/lib/Helper/Token/ApiTokenHelper.php line 168
    OC\Authentication\Token\Manager->getTokenById("*** sensitive parameters replaced ***")
 2. /config/www/nextcloud/apps/passwords/lib/Helper/Token/ApiTokenHelper.php line 105
    OCA\Passwords\Helper\Token\ApiTokenHelper->loadWebUiToken()
 3. /config/www/nextcloud/apps/passwords/lib/Controller/PageController.php line 141
    OCA\Passwords\Helper\Token\ApiTokenHelper->getWebUiToken()
 4. /config/www/nextcloud/apps/passwords/lib/Controller/PageController.php line 107
    OCA\Passwords\Controller\PageController->addHeaders()
 5. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Passwords\Controller\PageController->index()
 6. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "index")
 7. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "index")
 8. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Passwords\ ... r", "index", OC\AppFramework\ ... {}, {_route: "passwords.page.index"})
 9. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwords.page.index"})
10. /config/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "passwords.page.index"})
11. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/passwords/")
12. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/passwords/
from *** by *** at 2020-04-14T07:51:17+00:00

[passwords] Error: Failed to load api token for ***
GET /apps/passwords/
from *** by *** at 2020-04-14T07:51:17+00:00

### Browser log
\*\*\*/:1 Refused to apply style from 'https://\*\*\*/apps/files/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
client.js:1 messages.enabled force
/index.php/apps/passwords/api/1.0/folder/show:1 Failed to load resource: the server responded with a status of 504 ()
app.js?v=baba745e-6:43 Object
app.js?v=baba745e-6:43 Uncaught (in promise) Error: Content type mismatch: Expected application/json, got text/html
    at t.b._sendRequest (app.js?v=baba745e-6:43)
    at async t.b.showFolder (app.js?v=baba745e-6:43)
(index):1 Refused to apply style from 'https://\*\*\*/apps/files/' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by lightlike** [comment]
As said above. Most of the stuff is no longer present. I am still getting some of the warnings and Passwords is still generating App-Passwords but it seems that most of this is working.

Some still present Errors:

[passwords] Warning: Login attempt with invalid authorization header for invalid user id
GET /index.php/apps/passwords/api/1.0/tag/list
from *** at 2020-04-14T19:58:31+00:00

[passwords] Error: Failed to load api token for \*user\*
GET /apps/passwords/
from *** by \*user\* at 2020-04-14T19:52:26+00:00
[passwords] Error: OC\Authentication\Exceptions\InvalidTokenException:  at <<closure>>

 0. /config/www/nextcloud/lib/private/Authentication/Token/Manager.php line 173
    OC\Authentication\Token\DefaultTokenProvider->getTokenById("*** sensitive parameters replaced ***")
 1. /config/www/nextcloud/apps/passwords/lib/Helper/Token/ApiTokenHelper.php line 168
    OC\Authentication\Token\Manager->getTokenById("*** sensitive parameters replaced ***")
 2. /config/www/nextcloud/apps/passwords/lib/Helper/Token/ApiTokenHelper.php line 105
    OCA\Passwords\Helper\Token\ApiTokenHelper->loadWebUiToken()
 3. /config/www/nextcloud/apps/passwords/lib/Controller/PageController.php line 141
    OCA\Passwords\Helper\Token\ApiTokenHelper->getWebUiToken()
 4. /config/www/nextcloud/apps/passwords/lib/Controller/PageController.php line 107
    OCA\Passwords\Controller\PageController->addHeaders()
 5. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Passwords\Controller\PageController->index()
 6. /config/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Passwords\Co ... {}, "index")
 7. /config/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Passwords\Co ... {}, "index")
 8. /config/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Passwords\ ... r", "index", OC\AppFramework\ ... {}, {_route: "passwords.page.index"})
 9. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "passwords.page.index"})
10. /config/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "passwords.page.index"})
11. /config/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/passwords/")
12. /config/www/nextcloud/index.php line 38
    OC::handleRequest()

GET /apps/passwords/
from *** by \*user\* at 2020-04-14T19:52:26+00:00

**Comment by marius-wieschollek** [comment]
The slowdowns are usually due to too many failed login attempts. This is the Nextcloud brute force protection.

> Login attempt with invalid authorization header for invalid user id

That is interesting. There is an authorization header presenr, but no user is logged in and no login data is stored in the session. (because the session is checked first and the header would not be checked then)

> Failed to load api token for *user*
Also interesting. Passwords generates a temporary token for the webui and stores it in the session. It seems that Nextcloud considers the token invalid which should only happen if you delete it.

Something seems wrong. Are you using anything special? SAML, LDAP, Social Login? Or Redis etc. for sessions?

**Comment by lightlike** [comment]
I am only using [TOTP-Provider](https://apps.nextcloud.com/apps/twofactor_totp) for all logins as foced 2FA. The Clients are connected using App-Passwords.

I did delete some of the old Session App-Passwords that "Passwords" created (always cept the newest). Do you think that might be the Problem? The Error also only occurred 2 or 3 times, not every time I tried to connect to Passwords.

The following message was also the last one I received of the invalid user id warning. I think that also sorted itself out.
[passwords] Warning: Login attempt with invalid authorization header for invalid user id
GET /index.php/apps/passwords/api/1.0/session/keepalive
from *** at 2020-04-14T20:04:04+00:00

**Comment by marius-wieschollek** [comment]
Yes, deleting the session passwords would explain the issue. It especially explains why it happened in the keep alive request.

**Comment by lightlike** [comment]
Yeah. Sorry to take your time. This was just really annoying, when I just started reorganizing and changing most of my passwords.
