### ISSUE TITLE
iOS: copy username / password to clipboard does not work

### ISSUE THREAD

**Issue by HerrDirektor80** [marius-wieschollek/passwords#263]
### System Information
- Nextcloud Version: 18.0.3
- PHP Version: 7.3.16
- Database and Version: mysql 5.7.29
- Passwords Version: 2020.4.0
- Browser and Version: Safari 
- Client OS and Version: iOS 13.4.1
- Server OS and Version: Ubuntu 18.04.4 LTS

### Steps to reproduce
Login via Safari or Chrome (both browsers are up to date) to Nextcloud. Open App Password and try to copy a password by simple click or a username by double click.

### Expected result
simple click should copy the password to clipboard and double click should copy username to clipboard.

### Actual result
There is a message something like: (in german ;)): Could not copy username / password to clipboard. Password / username are not copied to clipboard.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
{"reqId":"b6mk9wDa5gElYKSLqlYK","level":2,"time":"2020-04-15T09:02:26+02:00","remoteAddr":"185.19.233.130","user":"cw","app":"passwords","method":"GET","url":"/apps/passwords/","message":"Cancelled expired session 22455e30-05ce-4d0c-ac39-5abfafe37e42 for cw","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0","id":"5e96b47eae597"}

</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy the content of the console tab
```
</details>

**Comment by marius-wieschollek** [comment]
Since i do not have access to an iOS device, i can't test this. I would be happy to accept a PR for this.

**Comment by HerrDirektor80** [comment]
Thanks for your quick answer and thanks alot for creating this app! I use it alot and I really like it! Keep on!

I do not have a iOS development environment, but I think the problem starts here: https://github.com/marius-wieschollek/passwords/blob/master/src/js/Classes/Utility.js#L13 ... if someone is trying to fix it ;)

**Comment by marius-wieschollek** [comment]
Yes, there is a special copy mechanism just for iOS. That still seems to work, at least it worked fine on a browserstack iphone. But i also read that iOS 12 may use an useragent without iphone/ipad in it.

**Comment by HerrDirektor80** [comment]
I tested the useragent on my iPhone 11 (iOS 13.4.1):

Chrome:
Mozilla/5.0 (iPhone; CPU iPhone OS 13_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/80.0.3987.95 Mobile/15E148 Safari/604.1
Safari:
Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Mobile/15E148 Safari/604.1

This seems not to be the problem...

**Comment by marius-wieschollek** [comment]
Can you try the current [nightly](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies) and see if the issue still exists?

**Comment by HerrDirektor80** [comment]
Fixed! Perfect! Copy password and username works! Thanks alot.
