### ISSUE TITLE
Password stills shows as weak (duplicate) after deleting the duplicate

### ISSUE THREAD

**Issue by lebochequirit** [marius-wieschollek/passwords#264]
- Passwords Version: 2020.4.20
- Nextcloud Version: 18.0.2

### Steps to reproduce
1. Enter and store password, somehow messing up the URL
2. Log in to the site, entering the password by hand, letting Passwords grab it
3. Get a duplicate in the database, showing as weak password
4. Delete the first entry, keeping the grabbed one

### Expected result
Password matches only one hash, should show as strong

### Actual result
Password is shown as weak (duplicate) even after deleting the first password from bin

The App looks VERY promising, however. Thanks for all the work.

L.B.Q.R.

**Comment by marius-wieschollek** [comment]
All password security checks are executed once a day or when the password is changed. There is so far no functionality to update the status of duplicates when a password is deleted.

I thought i mentioned that in the manual but i didn't so i will add it  now.

But i think this could be added as a feature.

**Comment by marius-wieschollek** [comment]
In the current [nightly](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies), the behavior has been changed and the status of duplicates will be changed immediately if one of the duplicate is created, changed or deleted.

**Comment by smirkybg** [comment]
I have the latest Passwords Nextcloud application (2021.1.2) and it still reports multiple duplicate passwords with only 
1 single occurrence in the database. How can I resolve this?
