### ISSUE TITLE
Email address format verification is too strict

### ISSUE THREAD

**Issue by tigre-bleu** [marius-wieschollek/passwords#265]
### System Information
- Nextcloud Version: 18.0.3
- Passwords Version: 2020.4.1
- Browser: Firefox

### Steps to reproduce
1. Create a new password
2. Insert a custom field of **email** type
3. Set adress **john.doe+something@example.com**

### Expected result
Adress shall be accepted.

### Actual result
Adress is considered invalid.

### Solution
`!#$%&'*+-/=?^_``{|}~` characters are often considered invalid but this is a misconception. They are perfectly valid for the local address part (left of `@`). Even `.` is valid provided that it is not the first or last character and there are no 2 consecutive occurrences.

Use of special characters can be interesting for [subadressing](https://en.wikipedia.org/wiki/Email_address#Subaddressing)

**Comment by marius-wieschollek** [comment]
Should be fixed with 2020.5.0
