### ISSUE TITLE
Duplicate password

### ISSUE THREAD

**Issue by majkinetor** [marius-wieschollek/passwords#266]
**Current Status**
Currently if I only want to change few details I need to reenter everything again. Its sometimes the case that I have array of objects with similar purpose and names and other metadata 

**Feature Description**
Add context menu item that duplicates password under new name

**Comment by marius-wieschollek** [comment]
Can you add more detail here? Is this about creating a password for a second account or a very similar site or do you actually want to reuse the same password across multiple sites?

**Comment by majkinetor** [comment]
Very similar site. Reusing everything under new name. If I need new password I can simply regenerate it. 

Here is screenshot from LastPass:

![image](https://user-images.githubusercontent.com/85767/80908732-a2536400-8d22-11ea-80f6-057a9062b35b.png)

When you select _Clone_ you are given editor with everything the same as in original, password included, so you can do your edits there if needed.

**Comment by marius-wieschollek** [comment]
In the next update i will add the option to use a password as template. You will be able to have all fields filled out with the existing data from the password and tags will be copied as well.

But the password field and any custom field of type secret will be empty. I do not want to encourage unsafe practices with this function.

**Comment by majkinetor** [comment]
Sounds great. Thanks a lot for doing this. 

I am using passwords in production environments for few months I am very happy about how it works and how simple it is to on board (the only thing I really miss now is sharing of the folder  but that is also on todo list). I tried dozen of systems over the many years but your one hit the target for me the right way.

**Comment by majkinetor** [comment]
Edit as new seems to work fine. Thx a lot.
