### ISSUE TITLE
"500 - internal server error" when opening the Passwords App (snap installation)

### ISSUE THREAD

**Issue by Pilzinsel64** [marius-wieschollek/passwords#269]
### Steps to reproduce
1. Install Nextcloud via snap using channel "18/stable"
2. Install the app "Passwords"
3. Open the app "Passwords"

### Expected behaviour
The passwords app should just work.

### Actual behaviour
As soon as I open the passwords app it fails loading the password list with two errors titled "500 - internal server error".
This issue seems to be very similar to #182.

## Server configuration detail

**Operating system:** Linux 5.3.0-1019-raspi2 #21-Ubuntu SMP Mon Feb 17 14:05:03 UTC 2020 aarch64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.29

**PHP version:** 

7.3.17
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gmp, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - apporder: 0.9.0
 - audioplayer: 2.10.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - cospend: 0.5.2
 - dav: 1.14.0
 - drop_account: 0.2.1
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - guests: 1.4.6
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - joplin: 0.0.25
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.3.4
 - metadata: 0.11.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.3.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocdownloader: 1.7.7
 - password_policy: 1.8.0
 - passwords: 2020.5.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - qownnotesapi: 20.1.0
 - quota_warning: 1.7.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - side_menu: 1.6.3
 - spreed: 8.0.9
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.1
 - tasks: 0.13.0
 - text: 2.0.0
 - theming: 1.9.0
 - theming_customcss: 1.5.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_email: 1.0.1
 - twofactor_gateway: 0.16.0
 - twofactor_nextcloud_notification: 2.3.0
 - twofactor_totp: 4.1.3
 - unsplash: 1.1.5
 - uploaddetails: 0.1.3
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "skeletondirectory": "",
    "filelocking.enabled": true,
    "app_install_overwrite": [
        "keeweb",
        "occweb",
        "apporder",
        "audioplayer",
        "spreed",
        "unsplash",
        "documentserver_community",
        "onlyoffice",
        "ocdownloader",
        "uploaddetails",
        "bruteforcesettings",
        "joplin",
        "social"
    ],
    "onlyoffice": {
        "verify_peer_off": true
    },
    "default_language": "de_DE",
    "default_locale": "de",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [
        "2fa"
    ],
    "twofactor_enforced_excluded_groups": []
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

**Operating system:** Windows 10

**Comment by Pilzinsel64** [comment]
Could that be an issue with self-signed certificates? For my own company we use self-signed certificates (let's encrypt) and there the same error happens too. But it doesn't happen on the cloud on my webspace by strato.de where I got an more secure certificate.

**Comment by marius-wieschollek** [comment]
I have now tried the snap setup and was not able to reproduce the issue. Self-signed certificates were not an issue. Let's Encrypt uses regular certificates (not self-signed) which are just like any other certificate (and just as secure) and widely used in the Nextcloud Community. So i don't expect any issue there.

It would be great if you could check the [Nextcloud log](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/App-Debugging) for any errors. It would also be good to know if you're using an external user-backend.

**Comment by Pilzinsel64** [comment]
~~Alright, I have three Nextcloud instances running. One on a webspace by Strato.de (manual installation), one on an own server of my company (manual installation) and one on my Raspberry Pi 4 (snap installation). The one one my webspace is the only where I am able to use the Passwords App.~~

~~Sorry that I missed the logs, but yea, here are the logs of the two instances with that error (right after I tried to access the App):~~


~~And to answer your last question: I don't use an external user-backend for any of my instances.~~

While I was typing this message and was downloading the logs, it did work.

It seems like it WAS the opcache issue. I even restarted all services several times, and it didn't worked. But after one day, it does now (probably after the opcache is cleared or something), on all three instances. Weird.

Sorry, for this issue then, I will close it now. Thank you very much for help.
