### ISSUE TITLE
Nextcloud Crash

### ISSUE THREAD

**Issue by Aviortheking** [marius-wieschollek/passwords#271]
Gist containing all the informations : https://gist.github.com/Aviortheking/717e21a39b24e6d272d98737ef90fa08

### System Information
- Nextcloud Version: 18.0.4
- PHP Version: 7.3
- Database and Version: MariaDB
- Passwords Version: Actually on 2020.5.0 but happened to in 2020.4.0 and .1
- Browser and Version: Tested on Firefox 76 and Chrome 83
- Client OS and Version: Tested on Arch Linux 2020.05.01and Windows 10 
- Server OS and Version: [Docker Nextcloud Latest](https://hub.docker.com/_/nextcloud)

### Steps to reproduce
1. Install Nextcloud on docker-compose using [this](https://gist.github.com/Aviortheking/717e21a39b24e6d272d98737ef90fa08#file-docker-compose-yml) compose file (db.env contains informations on the Database)
2. Install Password app
3. try to do anything on the Password app

### Other details
After looking at my Management Dashboard there is an Enormous spike brefaure my server start giving errors the spike is made by Nextcloud
![image](https://user-images.githubusercontent.com/15822031/83449761-75df5480-a454-11ea-96ac-b60a603f8823.png)

#### Settings
![image](https://user-images.githubusercontent.com/15822031/83450086-eab28e80-a454-11ea-8e95-61ccef363b72.png)
![image](https://user-images.githubusercontent.com/15822031/83450120-f736e700-a454-11ea-9ad0-88a016fb70bc.png)

### I Tried
- Disable the Favicon 
- Disable the Preview

### Expected result
I should not have a server error

### Actual result
I have a server error and can't use properly the extension

### Nextcloud log
https://gist.github.com/Aviortheking/717e21a39b24e6d272d98737ef90fa08#file-server-log

### Browser log
https://gist.github.com/Aviortheking/717e21a39b24e6d272d98737ef90fa08#file-browser-log

**Comment by marius-wieschollek** [comment]
Technically Chrome and Firefox should only load images in the browser, but at least Firefox just loads all at once instead. Version 2020.8.0 will use the api to fetch images and also allow to regulate the amount of api requests. By default, any x86 based machine will use load up to 15 icons at the same time (worked great on my AMD Athlon 5350), any other machine up to 3 images (worked great on my Raspberry Pi 2). You can set a performance level between 0 - 6 with the following command: 

```
./occ config:app:set --value=<number here> passwords performance
```
0 means 1 request, 1-5 mean 3-15 requests (n*3) and 6 means unlimited requests. This server performance hint will also be used in other parts of the app like the import or the encryption setup where usually many requests are sent at the same time.
