### ISSUE TITLE
Completelly disable favicons

### ISSUE THREAD

**Issue by Aviortheking** [marius-wieschollek/passwords#272]
**Current Status**
the Option Favicon Service when set to `none` will generate icons with the first letter of the name

**Feature Description**
Add a new Option First Letter to containue having the feature and make the option None remove the column

**Additional context**
Having more than 100 pass on the app having to load them all generate quite lot of requests that I don't think as necessary.

**Comment by Salokyn** [comment]
Hi,
I have the same problem. Those icons are a pain to generate.

I had to raise PHP `max_execution_time = 300` and the nginx `fastcgi_read_timeout 300` to avoid timeouts.

**Comment by marius-wieschollek** [comment]
The favicon api promises to always deliver an icon. Making it optional would be a breaking change. I think the changes described in #271 are a more suitable solution than to fork the entire api.
