### ISSUE TITLE
Support Encryption on Client

### ISSUE THREAD

**Issue by 0x9060** [marius-wieschollek/passwords#273]
**Current Status**
I don't understand the `Encryption on client` value for a selected password.

**Feature Description**
Specify where decrypted credentials exist on client, or how to enable encryption.

**Additional context**
I've enabled server side encryption on my NC18 instance. Also, I an running Dockerized Nextcloud, behind a Traefik reverse proxy, which handles TLS execution. I've provided Nextcloud the proper TRUSTED_PROXIES info, and everything seems to be working fine. I installed this Passwords app with no errors related to Expected/Actual values. I've even setup HTTP -> HTTPS redirection and HSTS (all via Traefik), so I've encrypted data at rest and in transit every which way I'm aware of.

I'm confused by the meaning of the `Security / Encryption on client` value when I select a currently saved password in this app:

#### Security
- Status 
--  Secure
- Encryption on server 
--  Simple encryption (Gen. 2)
- Encryption on client 
--  No encryption 

For all of my passwords, the `Encryption on client` value equals `No encryption`. Where are these decrypted passwords stored on the client? in local storage or elsewhere?

Credentials should be encrypted on the client.

**Comment by marius-wieschollek** [comment]
See #80
