### ISSUE TITLE
Made a Rust library for the API

### ISSUE THREAD

**Issue by traxys** [marius-wieschollek/passwords#279]
I wrote a rust library binding to the HTTP API (https://github.com/traxys/nextcloud-passwords-client/). 
I saw that the documentation talks about listing your App, but I didn't see anything about listing libraries, so I thought about sharing this if it is useful for some people

It's still a bit rough, but it works

**Comment by marius-wieschollek** [comment]
I added it to the documentation and the app section. Thanks for the great work.
