### ISSUE TITLE
Old passwords disappeared after upgrade

### ISSUE THREAD

**Issue by godfuture** [marius-wieschollek/passwords#28]
I had been using the password app from fcturner. After I have migrated nc11 from standalone ubuntu to nc 12 on debian docker, I have lost my passwords in password app.

I have tried to reexecute the migration, but without success. All passwords seem to be still in db.

I applied my old instanceid and secret. How could I manully decrypt or restore my passwords?

**Comment by marius-wieschollek** [comment]
Hi. Can you check if your system fulfills the [system requirements](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration)? Did you read the [migration guide](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration)?

Did the migration actually run and if so, can you check the Nextcloud log file for errors?

**Comment by godfuture** [comment]
I guess I fullful the requirements:
```
PHP
Version: 7.1.14
Arbeitspeicher-Grenzwert: 1 GB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 511 MB
```
And yes, I have tried to downgrade the DB and restart the migration. But it seems something has gone lost:
```
reqId":"y3j6zDzIafCKbWzS3NCu","level":2,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::warning: Repair warning: Failed migrating password #42: Calculated hashes do not match in \/var\/www\/html\/custom_apps\/passwords\/lib\/Migration\/Legacy\/DecryptionModule.php line 54","userAgent":"--","version":"13.0.0.14"}
{"reqId":"y3j6zDzIafCKbWzS3NCu","level":1,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::advance:  (1)","userAgent":"--","version":"13.0.0.14"}
{"reqId":"y3j6zDzIafCKbWzS3NCu","level":1,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::finishProgress","userAgent":"--","version":"13.0.0.14"}
{"reqId":"y3j6zDzIafCKbWzS3NCu","level":1,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::info: Repair info: Migrating shares (total: 0)","userAgent":"--","version":"13.0.0.14"}
{"reqId":"y3j6zDzIafCKbWzS3NCu","level":1,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::startProgress: Starting ... Passwords Legacy Database Migration (0)","userAgent":"--","version":"13.0.0.14"}
{"reqId":"y3j6zDzIafCKbWzS3NCu","level":1,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::finishProgress","userAgent":"--","version":"13.0.0.14"}
{"reqId":"y3j6zDzIafCKbWzS3NCu","level":1,"time":"2018-03-05T23:49:27+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Updater::appUpgrade: Updated <passwords> to 2018.2.1","userAgent":"--","version":"13.0.0.14"}
```
Could I somehow do the decrypt my own? Are there binaries I could use?

**Comment by marius-wieschollek** [comment]
I just saw that i misread your first post. You need to set your passwordsalt, not your instanceid. The password salt was used by the old app to encrypt the passwords. The following commands should do for you. Replace `<yourpasswordsalt>` with the actual password salt.

```
./occ config:system:set passwordsalt --value <yourpasswordsalt>
./occ config:app:set passwords installed_version --value 2017.12
./occ upgrade
```

**Comment by godfuture** [comment]
Understood. Do other accounts still work, if I change the passwordsalt? I mean it would be a tragedy being locked out of the admin account...

**Comment by marius-wieschollek** [comment]
First i would always recommend to make a backup in situations like this (config and database).
Passwords itself does not user the password salt for encryption anymore. This means that you can set the old salt for the migration and then set the current salt again.

**Comment by godfuture** [comment]
It worked! :-)
All passwords are back and I can use the system while the "old" salt is in place...
If I understood you correctly, I do not need to restore my new password salt, right?

Thank you a lot for the support!

**Comment by marius-wieschollek** [comment]
Passwords does not use the password salt, but Nextcloud does. So you should run the new Nextcloud instance with the passwords salt which was used during set up.
