### ISSUE TITLE
Allow for multiple urls on each password

### ISSUE THREAD

**Issue by ChameleonScales** [marius-wieschollek/passwords#282]
**Current Status**
The password editor has only one field for the website url. This means if a website has different urls from which you can enter credentials or has both a local and global address, the extension cannot auto-detect the passwords for all of them.

**Feature Description**
a little + sign next to the Website field to add an additional url

**Comment by marius-wieschollek** [comment]
This already exists in the app, there is already an issue requesting this for the browser extension, it is already implemented in the nightly version of the extension _and you did not follow the issue template_.

**Comment by ChameleonScales** [comment]
... and it's a triplicate. I'm so very sorry.
