### ISSUE TITLE
502 - Bad Gateway

### ISSUE THREAD

**Issue by Dellyjoe** [marius-wieschollek/passwords#285]
Hello Everyone,

I just started using Passwords, and when I log in using firebox or chrome, I log into my nextcloud sever, nothing wrong. I then click on the password icon at the top. Then for every password I have, I get a 502 - Bad Gateway, I click x on all the error boxes that pop up on the right hand side and everything works as normal. I will also add that sharing doesn't seem to work for me. 

### System Information
- Nextcloud Version: 19.0.0
- PHP Version: 7.4.7
- Database and Version:  mysql 10.3.23
- Passwords Version:  2020.8.0
- Browser and Version: chrome or firefox same issue
- Client OS and Version:
- Server OS and Version: Freenas 11.3-U4.1

### Steps to reproduce
Log into nextcloud then click on password icon at the top, and if you have a current password there it will display on the right hand side a 502 - Bad Gateway error. After clicking on the x, you can remove the box but it will pop up again if you go back into the page at any time. 

Also the sharing doesn't seem to work as well.

**Comment by marius-wieschollek** [comment]
This looks like an issue in the backend part of the app. Can you [check the logs](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/App-Debugging) to see if any errors were logged?

**Comment by Dellyjoe** [comment]
@marius-wieschollek  I ended up fixing the issue by going into the admin settings and under Passwords --> Favicon Service I was using Local analyzer, I ended up changing it to Besticon and then after that it loads in the pictures from the website and doesn't report an errors -502 in the nextcloud interface or in the nextcloud logs.

Sorry I didn't grab the logs before.

Joe
