### ISSUE TITLE
Latest update breaks settings in Nextcloud

### ISSUE THREAD

**Issue by Omaha2002** [marius-wieschollek/passwords#286]
### System Information
- Nextcloud Version: 19.0.1
- PHP Version: 7.3.20
- Database and Version: 10.4.13
- Passwords Version: 2020.8.0
- Browser and Version: chrome / edge / firefox
- Client OS and Version: windows 10 latest / Macos / linux
- Server OS and Version: Ubuntu 18.04

### Steps to reproduce
1.  update to lastest passwords
2. click settings 
3. Internal Servererror

Related to earlier bug?  https://github.com/marius-wieschollek/passwords/issues/240 

### Expected result
show settings page

### Actual result
Internal server error page

### Nextcloud log

{"reqId":"tTQLMrLpr0LPqq3udEVz","level":2,"time":"2020-08-10T08:08:28+02:00","remoteAddr":"xx.xx.xx.xx","user":"xxxxxx","app":"passwords","method":"GET","url":"/settings/user","message":"Login attempt with invalid session for xxxxxx","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52","version":"19.0.1.1"}
{"reqId":"tTQLMrLpr0LPqq3udEVz","level":3,"time":"2020-08-10T08:08:28+02:00","remoteAddr":"xx.xx.xx.xx","user":"xxxxxx","app":"index","method":"GET","url":"/settings/user","message":{"Exception":"Exception","Message":"Unable to verify user xxxxxx","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":346,"function":"loadUserInformation","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->","args":["xxxxxx",{"__class__":"OC\\AppFramework\\Http\\Request"}]},{"file":"/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","line":172,"function":"determineAppMode","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->","args":["xxxxxx",{"__class__":"OC\\AppFramework\\Http\\Request"}]},{"function":"__construct","class":"OCA\\Passwords\\Services\\EnvironmentService","type":"->","args":["xxxxxx",{"__class__":"OC\\AllConfig"},{"__class__":"OC\\AppFramework\\Http\\Request"},{"__class__":"OC\\Session\\CryptoSessionData"},{"__class__":"OCA\\Passwords\\Services\\LoggingService"},{"__class__":"OC\\Authentication\\Token\\Manager"},{"__class__":"OC\\User\\Manager"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":84,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[["xxxxxx",{"__class__":"OC\\AllConfig"},{"__class__":"OC\\AppFramework\\Http\\Request"},{"__class__":"OC\\Session\\CryptoSessionData"},{"__class__":"OCA\\Passwords\\Services\\LoggingService"},{"__class__":"OC\\Authentication\\Token\\Manager"},{"__class__":"OC\\User\\Manager"}]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Services\\EnvironmentService","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":71,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\EnvironmentService",true]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Services\\ConfigurationService","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\ConfigurationService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Services\\ConfigurationService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\ConfigurationService"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":71,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Services\\ConfigurationService",true]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Passwords\\Settings\\AdminSettings","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Settings\\AdminSettings"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Passwords\\Settings\\AdminSettings"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":133,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Passwords\\Settings\\AdminSettings"]},{"file":"/var/www/nextcloud/lib/private/Settings/Manager.php","line":176,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Passwords\\Settings\\AdminSettings"]},{"file":"/var/www/nextcloud/lib/private/Settings/Manager.php","line":238,"function":"getSettings","class":"OC\\Settings\\Manager","type":"->","args":["admin","overview"]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":91,"function":"getAdminSettings","class":"OC\\Settings\\Manager","type":"->","args":["overview",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":127,"function":"formatSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":[{"0":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Overview"}],"1":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Server"}],"5":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Sharing"},{"__class__":"OCA\\SocialLogin\\Settings\\AdminSection"}],"10":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Security"},{"__class__":"OCA\\Files_External\\Settings\\Section"}],"30":[{"__class__":"OCA\\Theming\\Settings\\Section"}],"50":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Groupware"},{"__class__":"OCA\\Onlyoffice\\AdminSection"},{"__class__":"OCA\\Passwords\\Settings\\AdminSection"}],"55":[{"__class__":"OCA\\Activity\\Settings\\AdminSection"},{"__class__":"OCA\\FullTextSearch\\Settings\\AdminSection"},{"__class__":"OCA\\WorkflowEngine\\Settings\\Section"}],"70":[{"__class__":"OCA\\SideMenu\\Settings\\AdminSection"},{"__class__":"OCA\\Talk\\Settings\\Admin\\Section"}],"80":[{"__class__":"OCA\\Bookmarks\\Settings\\AdminSection"}],"90":[{"__class__":"OCA\\AppOrder\\Settings\\Section"},{"__class__":"OCA\\GroupFolders\\Settings\\Section"},{"__class__":"OCA\\LogReader\\Settings\\Section"},{"__class__":"OCA\\ServerInfo\\Settings\\AdminSection"}],"98":[{"__class__":"OCA\\Settings\\Sections\\Admin\\Additional"}]},"personal-info","admin","personal",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":76,"function":"formatAdminSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info",false]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":151,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php","Line":385,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52","version":"19.0.1.1"}

```
 - Open the Nextcloud admin settings
 - Open the "Log" section
 - Click the "Copy" icon, then Copy Raw

Opening log page through admin settings not possible, copied nextcloud.log from server

```
</details>

**Comment by Omaha2002** [comment]
It's a bit more complex, I also have social login enabled (https://github.com/zorn-v/nextcloud-social-login) and that one was updated too. Loging in with created user/password in works with passwords (can access settingspage) logging in through social login (Azure AD) gives the above described error. 

Related to earlier bug?  https://github.com/marius-wieschollek/passwords/issues/240

**Comment by marius-wieschollek** [comment]
Have you checked if this happens with the previous version of the app as well?

**Comment by marius-wieschollek** [comment]
I have taken a look at the changes in the last version of social login. 
It seems likely to me that [this](https://github.com/zorn-v/nextcloud-social-login/commit/2a583c2e6aaa61a8687586b78a2ffb1bde45958d) change in the latest update of the social login app is the cause.
The social login app sets the uid as password in the login event. This is later stored in the session. The passwords app allows [two possible options for the password value](https://github.com/marius-wieschollek/passwords/blob/master/src/lib/Services/EnvironmentService.php#L492) – the password or nothing if no password exists. An incorrect password is not accepted

**Comment by Omaha2002** [comment]
Thanks, I’ll create an issue at Social Login referring to this issue..

**Comment by Omaha2002** [comment]
Gotta love open source, thank you guys, you rock.... @marius-wieschollek & zorn-v
