### ISSUE TITLE
occ command passwords:user:move aborts

### ISSUE THREAD

**Issue by codeHorse87** [marius-wieschollek/passwords#289]
### System Information
- Nextcloud Version: 18.0.7
- PHP Version: 7.2
- Database and Version: MySQL 5.7
- Passwords Version: 2020.8.0
- Browser and Version: Firefox ESR 68.11
- Client OS and Version: Mac OS Catalina
- Server OS and Version: Ubuntu Server 18.04 LTS

### Steps to reproduce
1. issuing the command **passwords:user:move _sourceuseride targetuserid_** . Both users are active and both users have password records. the source user already shares password records with the target user
2. messaging instantly with **aborting**

### Expected result
The migration should be performed

### Actual result
message **aborting** occurs on occ 

### Nextcloud log
no according log records being created from occ nor in NC logs (checked for all log levels)

**Comment by marius-wieschollek** [comment]
I can not reproduce this issue with the given information. Are you using additional arguments for the command or are you using a non-interactive shell / occweb?

Usually the output should look something like this:
```
www-data@5b6000f268e1:~/html$ ./occ passwords:user:move max erika
Type "yes" to confirm that you want to move all data from "Max Mustermann" to "Erika Mustermann": yes
The user "Erika Mustermann" already has data.
Type "yes" to confirm that you want to overwrite the existing data of "Erika Mustermann": yes
Deleting data ... done
Moving data ... done
```

**Comment by codeHorse87** [comment]
Hi @marius-wieschollek 
Thank you for verifying! According to your questions:
- There are not additional arguments but as with your example the source user id and the target user id. 
- I carried out the exercise using occweb App
The output is only: **aborting**

Please let me know what other information I can provide to support the investigation.

**Comment by marius-wieschollek** [comment]
Thanks! I can confirm this behavior with occweb.
occweb skips the question (because it is not interactive and therefore does not support questions) and then command aborts because the answer is never "yes".

Run the command with --no-interaction to assume "yes" for all questions.
I will make the ui better in the next update

**Comment by codeHorse87** [comment]
I can confirm that moving with 
`passwords:user:move` sourceuser targetuser --no-interaction
actually works with a non-interactive shell. 
However, after the move the target user can't load passwords anymore. When open the passwords app the message *Unable to complete request* occurs. 
In the NC log I can identify two error records:

> {"reqId":"qR1x4E8YGmHevC2uL4iy","level":3,"time”:”****”,”remoteAddr":"46.223.238.173","user":"****","app":"passwords","method":"POST","url":"/index.php/apps/passwords/api/1.0/password/list","message":"Error \"HMAC does not match.\" in OCA\\Passwords\\Controller\\Api\\PasswordApiController::list","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.7.1","id":"5f3cef5f49355"}

and 

> {"reqId":"qR1x4E8YGmHevC2uL4iy","level":3,"time":"****","remoteAddr":"****","user":"****","app":"passwords","method":"POST","url":"/index.php/apps/passwords/api/1.0/password/list","message":{"Exception":"Exception","Message":"HMAC does not match.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/passwords/lib/Encryption/Object/SseV1Encryption.php","line":158,"function":"decrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/passwords/lib/Services/EncryptionService.php","line":113,"function":"decryptObject","class":"OCA\\Passwords\\Encryption\\Object\\SseV1Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/passwords/lib/Helper/ApiObjects/AbstractObjectHelper.php","line":142,"function":"decrypt","class":"OCA\\Passwords\\Services\\EncryptionService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/passwords/lib/Helper/ApiObjects/PasswordObjectHelper.php","line":111,"function":"getRevision","class":"OCA\\Passwords\\Helper\\ApiObjects\\AbstractObjectHelper","type":"->","args":[{"id":101,"__class__":"OCA\\Passwords\\Db\\Password"},{"hidden":false,"trashed":false},true]},{"file":"/var/www/nextcloud/apps/passwords/lib/Controller/Api/AbstractObjectApiController.php","line":91,"function":"getApiObject","class":"OCA\\Passwords\\Helper\\ApiObjects\\PasswordObjectHelper","type":"->","args":[{"id":101,"__class__":"OCA\\Passwords\\Db\\Password"},"model+tags",{"hidden":false,"trashed":false}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"list","class":"OCA\\Passwords\\Controller\\Api\\AbstractObjectApiController","type":"->","args":["model+tags"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\PasswordApiController"},"list"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\PasswordApiController"},"list"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["PasswordApiController","list",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"passwords.password_api.listPOST"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"passwords.password_api.listPOST"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"passwords.password_api.listPOST"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/passwords/api/1.0/password/list"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Security/Crypto.php","Line":138,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.7.1","id":"5f3cef5f49319"}

I did some tracing of the requests between the client and the backend. I recognize that the request to fetch the API key */apps/passwords/api/1.0/session/open* is answered with the response payload *{"success":true,"keys":[]}* which I believe is not correct. The following request */apps/passwords/api/1.0/folder/show* is answered with *status":"error","id":0,"message":"Unable to complete request"}*

**Comment by marius-wieschollek** [comment]
Nope, that looks like the move did not complete.

I would recommend checking `passwords:backup:list` and then restoring an earlier backup. (You can limit this to the source/target user). But also make a backup before restoring a backup :D .
I don't know what the PHP max_execution_time is on your system but it could be too low.

If it is not possible to use the move command, i recommend "More" > "Backup and Restore" and make a "Database Backup". Then go into the target account, choose the reset everything option in the settings and then restore the database backup trough the import.

**Comment by codeHorse87** [comment]
> PHP max_execution_time

Thanks for the proposal. This works just fine. FYI max_execution_time is 30 in the environment
