### ISSUE TITLE
Password required for open app.

### ISSUE THREAD

**Issue by letopisec3** [marius-wieschollek/passwords#290]
I use it on a work pc, it is problematic to take out the phone every time and enter totp password
Make it a separate setting. When going to the application, a password would be required as in a passman.

**Comment by TimoHess** [comment]
I think its a dublicate of #69 ;) Isn´t it?

**Comment by marius-wieschollek** [comment]
I'm not sure.

@letopisec3 can you please check? If #69 does not describe your feature please fill out the entire feature request form. This description is useless.

**Comment by letopisec3** [comment]
No, that's not it, I probably didn't put it right, I need a password for applications. You open the application and you need to enter the password
![изображение](https://user-images.githubusercontent.com/36674563/95133326-d287ae80-0769-11eb-9986-c6fddb7946e2.png)

**Comment by marius-wieschollek** [comment]
I think that is #80 . Enable client side encryption will make the app require a master password every time. Please note that CSE/E2E is still under development and only works in the nightly versions of the app and the official extensions.

**Comment by letopisec3** [comment]
yes, it looks like the function is in the app?)
