### ISSUE TITLE
s is undefined

### ISSUE THREAD

**Issue by HandyGadget** [marius-wieschollek/passwords#291]
Nextcloud 19.01
Passwords 2020.8.0
Version 84.0.4147.125 (Official Build) (64-bit)
Ubuntu 20.04.1 

I cannot import the passwords exported from Chrome and get only this error message "s is undefined" (see attached)

I have opened the CSV in LibreOffice and cannot see any obvious reason for this.

Terence.

![Passwords_HulaCloud](https://user-images.githubusercontent.com/4005326/90530816-37ad2380-e16d-11ea-8a92-24530270426a.png)

**Comment by marius-wieschollek** [comment]
Please us the "Bug Report" option on the new issue page when reporting bugs to make sure all necessary information is there.

I was able to reproduce the issue anyway and will include a fix in the next update. You can install the [nightly version](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies) to test the fix already, or you can just use the generic csv import for the file.

**Comment by HandyGadget** [comment]
1) My CSV contained 2719 passwords and worked fine on the current version using the generic import. 
2) Very slow and took about 5 minutes to import.
3) Moving around in the Passwords interface is really slow now as any new page takes about a 30+ seconds to load.
4) I went to remove hundreds of "Breached" passwords but there's no bulk edit.
5) I went to organize passwords into "Folders" but there's no bulk edit there either.

It looks like the coding has a performance issue with the CPU at 100% so I don't think the sluggishness is caused by the server (see below)

![ubuntu_s_2vcpu_2gb_ams3_01_DigitalOcean](https://user-images.githubusercontent.com/4005326/90625218-21f13a00-e211-11ea-9020-dc2bf459e76c.png)

**Comment by marius-wieschollek** [comment]
Yes, i can confirm your findings. 2,7k passwords is "more than average". There is already issues open to add bulk actions, but i did not have any time for this so far. I'm working on some client side improvements that will make the app faster, but this is still in an early stage.

You can actually assign the passwords to folders trough the import. Just export a custom csv with the password id, name and folder name. Then change the folder name as wished. When importing, choose the conflict mode "merge with existing". Of course you should make a backup / database export before doing so.
