### ISSUE TITLE
Encryption Tests Failed

### ISSUE THREAD

**Issue by bernatnan** [marius-wieschollek/passwords#292]
### System Information
- Nextcloud Version: 19.0.1
- PHP Version: 7.4.9
- Database and Version: PostgreSQL 11
- Passwords Version: 2020.9.0-build3598
- Browser and Version: Firefox 79.0
- Client OS and Version: Linux Debian Sid
- Server OS and Version: Linux Debian Buster

### Steps to reproduce
Enter in the Password menu, click on a register to show the password, and appear a message that call me to create an issue with the follow information:

### Actual result
eyJ0eXBlIjoicGFzc3dvcmQiLCJzdGFnZSI6ImZldGNoIiwiZXJyb3IiOnsiZmlsZSI6Imh0dHBzOi8vY2xvdWQuYnJ1Y3VzLmVtYWlsL2FwcHMvcGFzc3dvcmRzL2pzL1N0YXRpYy9hcHAuanM/dj05YjQwYWRhYy0xNSIsImxpbmUiOjQzLCJjb2x1bW4iOjIyNjUyOSwibWVzc2FnZSI6IkVuY3J5cHRpb24gbm90IGF2YWlsYWJsZSIsInN0YWNrIjpbImRlY3J5cHRPYmplY3RAaHR0cHM6Ly9jbG91ZC5icnVjdXMuZW1haWwvYXBwcy9wYXNzd29yZHMvanMvU3RhdGljL2FwcC5qcz92PTliNDBhZGFjLTE1OjQzOjIyNjUyOSIsIl9wcm9jZXNzUGFzc3dvcmRAaHR0cHM6Ly9jbG91ZC5icnVjdXMuZW1haWwvYXBwcy9wYXNzd29yZHMvanMvU3RhdGljL2FwcC5qcz92PTliNDBhZGFjLTE1OjQzOjI1MDAyNCIsIl9wcm9jZXNzUGFzc3dvcmRMaXN0QGh0dHBzOi8vY2xvdWQuYnJ1Y3VzLmVtYWlsL2FwcHMvcGFzc3dvcmRzL2pzL1N0YXRpYy9hcHAuanM/dj05YjQwYWRhYy0xNTo0MzoyNDk4ODgiLCJsaXN0UGFzc3dvcmRzQGh0dHBzOi8vY2xvdWQuYnJ1Y3VzLmVtYWlsL2FwcHMvcGFzc3dvcmRzL2pzL1N0YXRpYy9hcHAuanM/dj05YjQwYWRhYy0xNTo0MzoyNDQzMzQiLCIiXX0sInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NDsgcnY6NzkuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83OS4wIiwicHJvdG9jb2wiOiJodHRwczoiLCJjcnlwdG8iOnRydWUsInRleHRlbmNvZGVyIjp0cnVlLCJhcHAiOiIyMDIwLjguMCIsImFwaSI6IjAuMC4xMCIsImFwcHMiOlsiYWNjZXNzaWJpbGl0eSIsImFjdGl2aXR5IiwiYnJ1dGVmb3JjZXNldHRpbmdzIiwiY2FsZW5kYXIiLCJjbG91ZF9mZWRlcmF0aW9uX2FwaSIsImNvbW1lbnRzIiwiY29udGFjdHMiLCJjb250YWN0c2ludGVyYWN0aW9uIiwiY29zcGVuZCIsImRhdiIsImRlY2siLCJldmVudF91cGRhdGVfbm90aWZpY2F0aW9uIiwiZmVkZXJhdGVkZmlsZXNoYXJpbmciLCJmZWRlcmF0aW9uIiwiZmlsZXMiLCJmaWxlc19hY2Nlc3Njb250cm9sIiwiZmlsZXNfYW50aXZpcnVzIiwiZmlsZXNfcGRmdmlld2VyIiwiZmlsZXNfcmlnaHRjbGljayIsImZpbGVzX3NoYXJpbmciLCJmaWxlc190cmFzaGJpbiIsImZpbGVzX3ZlcnNpb25zIiwiZmlsZXNfdmlkZW9wbGF5ZXIiLCJmaXJzdHJ1bndpemFyZCIsImxvZ3JlYWRlciIsImxvb2t1cF9zZXJ2ZXJfY29ubmVjdG9yIiwibWFpbCIsIm5leHRjbG91ZF9hbm5vdW5jZW1lbnRzIiwibm90ZXMiLCJub3RpZmljYXRpb25zIiwib2F1dGgyIiwib25seW9mZmljZSIsInBhc3N3b3JkX3BvbGljeSIsInBhc3N3b3JkcyIsInBob25ldHJhY2siLCJwaG90b3MiLCJwb2xscyIsInByaXZhY3kiLCJwcm92aXNpb25pbmdfYXBpIiwicmVjb21tZW5kYXRpb25zIiwic2VydmVyaW5mbyIsInNldHRpbmdzIiwic2hhcmVieW1haWwiLCJzdXBwb3J0Iiwic3VydmV5X2NsaWVudCIsInN5c3RlbXRhZ3MiLCJ0YXNrcyIsInRleHQiLCJ0aGVtaW5nIiwidHdvZmFjdG9yX2JhY2t1cGNvZGVzIiwidHdvZmFjdG9yX3UyZiIsInVwZGF0ZW5vdGlmaWNhdGlvbiIsInZpZXdlciIsIndvcmtmbG93ZW5naW5lIl19

**Comment by marius-wieschollek** [comment]
the encryption tests run asynchronously in the background, they are not related to a specific action. In this case it seems that the request to the server was aborted.
