### ISSUE TITLE
Transfer Ownership of a Password

### ISSUE THREAD

**Issue by sykesdev** [marius-wieschollek/passwords#294]
sorry if this feature exists - I've searched the docs and haven't seen it.

Is it possible to transfer the ownership of a password to someone else? Particularly useful if you want to create a password record and then transfer it to an admin for management.

Similarly it would be great if an admin could assume ownership of passwords - for example if someone leaves the org and you want to take control of their passwords (and potentially redistribute)

It would be a lot easier to keep track of who had access to what if it was possible to see a full set of passwords under an admin account.

**Comment by marius-wieschollek** [comment]
If you have a question, please choose one of the question options on the new issue page.
If you have a feature request, please fill out the feature request form.
