### ISSUE TITLE
List Android App by joleaf

### ISSUE THREAD

**Issue by joleaf** [marius-wieschollek/passwords#295]
* Name of the app: **NC Passwords**
* Short description of the app: **Android App for the Nextcloud Passwords add-on, which includes actions for viewing, editing and creating the Passworts**
* Logo of your app (SVG, PNG or JPG, ca 400x400px)
![icon_400](https://user-images.githubusercontent.com/71190322/93002463-8e710780-f537-11ea-9aea-ac0048c8a239.png)
* Link to the website/store where users can get the app: [Link](https://play.google.com/store/apps/details?id=de.jbservices.nc_passwords_app)
* Link to the sources: [Link](https://gitlab.com/joleaf/nc-passwords-app/)
* Supported Systems/Browsers etc.: Android (in a future version: iOs)
* Information how we can test the app:
  1. Clone the repository
  2. [Install flutter](https://flutter.dev/docs/get-started/install)
  3. Start an android emulator
  4. Run ```flutter run``` inside the repository

**Comment by marius-wieschollek** [comment]
You can make the description a bit longer, around 160 characters

**Comment by joleaf** [comment]
Hi @marius-wieschollek ,
the last version of android app supports e2e encryption now.
Maybe you can mention this in the app overview section (because ist he other apps do not support e2e)? :)

Thank you for the great documentation :)
There is one small mistake: 
https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Encryption/PWDv1Challenge
In one sentence you say „password hash salt (salt 3)“, but is actually salt 2 :)

Best,
Jonas

**Comment by marius-wieschollek** [comment]
I fixed the error in the documentation.

I had a facelift for the apps section in the works for 2021.2.0, so i have now given the app an extra "Secure Encryption" badge to highlight the support.
![grafik](https://user-images.githubusercontent.com/8255857/106381856-f4add800-63bb-11eb-94b4-010d869abe2a.png)

It's great to have an Android app that supports e2e, thanks for your work on that.
