### ISSUE TITLE
cURL error 6: Could not resolve host: git.mdns.eu (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by dmitrymedentsov** [marius-wieschollek/passwords#298]
### System Information
- Nextcloud Version:
- PHP Version:
- Database and Version:
- Passwords Version:
- Browser and Version:
- Client OS and Version:
- Server OS and Version:

### Steps to reproduce
1. 
2. 
3. 

### Expected result
What should happen?

### Actual result
What does happen?

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
 - Open the Nextcloud admin settings
 - Open the "Log" section
 - Click the "Copy" icon, then Copy Raw
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy the content of the console tab
```
</details>

**Comment by marius-wieschollek** [comment]
There has been a configuration issue with the git.mdns.eu domain. Until this is resolved, you can find the latest release on Github: https://github.com/marius-wieschollek/passwords/releases/tag/2020.9.0

**Comment by ghost** [comment]
The tar.gz doesn't seem to be valid there right now. tar is not able to unpack:
```
tar -xf passwords.tar.gz 
tar: This does not look like a tar archive
tar: Skipping to next header
```
Unpacking the file in two steps with gunzip and tar into nextloud/apps/ and activating the app in admin webinterface solved the issue.

**Comment by marius-wieschollek** [comment]
The domain issue is now _finally_ solved and updates should start working within the next 24 hours.
