### ISSUE TITLE
php syntax error, unexpected ':', expecting ';'

### ISSUE THREAD

**Issue by Tomax77** [marius-wieschollek/passwords#3]
Hi Marius, I'm getting PHP Syntax error: 

`unexpected ':', expecting ';'` 

if I try to open passwords App (lastest master branch) in nextcloud. The error message refers to DatabaseHelper.php, line 25 which has the following content: `public function getCollation(): string {`

My PHP-Version ist 5.6.0. Is the error caused by my PHP-Version? 
How can we solve it?

Bye 
Tom

**Comment by marius-wieschollek** [comment]
Hi, yes, this error is caused by the PHP version. You should use PHP 7.1.

Since maintaining an App for old versions of PHP is a lot of work, id do only support the latest versions of PHP and Nextcloud.

**Comment by Tomax77** [comment]
Hi Marius,

my Plesk installer only supports max. PHP Version 7.0.19 and there is a 
Parse error. Do you now any solution für my problem?

Error message:

Error    index    ParseError: syntax error, unexpected '?'

/var/www/vhosts/example.com/httpdocs/nextcloud/lib/composer/composer/ClassLoader.php 
- line 322: Composer\Autoload\includeFile('/var/www/vhosts...')
[internal function] 
Composer\Autoload\ClassLoader->loadClass('OCA\\Passwords\\H...')
....

Bye
Tom

marius-wieschollek schrieb:

**Comment by marius-wieschollek** [comment]
With PHP 7.0, I assume that the issue are the return type hints in the [DatabaseHelper](https://github.com/marius-wieschollek/passwords/blob/stable/lib/Helper/DatabaseHelper.php#L47).

**Comment by Tomax77** [comment]
Is this a PHP 7.1 specific syntax, cause I'm not familiar with PHP. Do 
you know a way to solve this issue.
It's really importan for me to get passwords module working.

Thanks in advance
Tom

marius-wieschollek schrieb:

**Comment by marius-wieschollek** [comment]
The class which causes the error for you uses PHP 7.1 nullable return types. You can read about them [here](https://wiki.php.net/rfc/return_types) and [here](https://wiki.php.net/rfc/nullable_types).

As i said before, if you want  to use it with PHP 7.0 you need to remove the nullable return types completely (not just, the "?", all of it).

I will not do this in this repo because, as i said before, i will only support PHP 7.1.

**Comment by Tomax77** [comment]
I come from user side and not firm with PHP-Programming. Do I have to 
delete whole nullable Part?

/**

	* @param array $statements

	*

	* @return null|string

	*/

	public function getDatabaseDependentStatement(array $statements): ?string {

	$dbtype = $this->getDatabaseType();

	

	return isset($statements[ $dbtype ]) ? $statements[ $dbtype 
]:$statements['default'];

	}


Or how do I have to change it to work with PHP 7.0?

In this way the whole passwords module isn't usable for me (an I think 
many others) anymore what is a pitty.

Bye
Tom

marius-wieschollek schrieb:

**Comment by marius-wieschollek** [comment]
yes. this class should do for you:
