### ISSUE TITLE
Tags on the main view

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#3]
re: https://github.com/marius-wieschollek/passwords/issues/2#issuecomment-356959290

Logging this separately so it doesn't drown in that other convoluted issue:

Tags on the main view would be useful for visual cues. They could either be fully worded or just 4px coloured borders on the left hand side (unless someone has another idea).

**Comment by marius-wieschollek** [comment]
I have added a special build which contains this functionality. I would be happy if you could take a [look at it](https://git.mdns.eu/nextcloud/passwords/-/jobs/5690/artifacts/download) and give some feedback.

**Comment by HanPrower** [comment]
Seems to be working well :+1: 

I think with that option the "More" dots may be better placed at the end of the row though (as they were before I PRd that fix for the layout). As, at least to me, the layout with tags now looks a bit visually confusing:
![pwtags](https://user-images.githubusercontent.com/1781312/37024694-7d6f1b6c-2121-11e8-9bbd-fdf21cdda3fe.png)

**Comment by marius-wieschollek** [comment]
Tags are in the newest nighly build. Also i think you were right about the security status. I tried to put it where Nextcloud 13 has the file size to make it look the same. But since folders and tags do not have it, it looks a little chaotic. So i moved it back in the nightly.
