### ISSUE TITLE
Support global search

### ISSUE THREAD

**Issue by pafcioooo** [marius-wieschollek/passwords#30]
In folder view search should be working accross all folders, but it is not.
I think it is more feature request than an issue.

### System Information
- Nextcloud Version: 13.0.0
- PHP Version: 7.2
- Passwords Version 2018.4.0-build2062 (nightly) 
- Browser and Version: FF Windows 59 64-bit
- Server OS and Version: Ubuntu 16.04

### Steps to reproduce
- go to folder view
- click search for password entry
- enter some password for search that you know is in one of the folders displayed in the folder view
- password will not be found - but it should
- if one does the same search within folder where password entry is located it will be found
- if one does the seam search from All view, the entry will be found

**Comment by marius-wieschollek** [comment]
Yes, thats the "Global Search" feature. It will be available in 2018.5. See the [roadmap](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Roadmap)
