### ISSUE TITLE
Automatic generation auf Password without Numbers and/or Special Characters still uses Character '  

### ISSUE THREAD

**Issue by florom** [marius-wieschollek/passwords#303]
Hi Devs,

When generating a new Password I always encounter this Special Characters in my Password:

I use Nextcoud 19.0.3 and Passwords   2020.10.0 . As WebBrowser Firefox.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/32240626/95177453-7dc25300-07be-11eb-9d45-29f03504efbc.png)

I am really not sure if anybody else encounters it but i have two nextclouds and both are like that. 
It really is not a big deal but it starts getting annoying.

Thanks for considering.

**Comment by marius-wieschollek** [comment]
If you report a bug, please always fill out the bug reporting form.

**Comment by florom** [comment]
Hi Devs,
PhP:
Version: 7.3.19

Database:
Type: mysql
Version: 10.3.23

I use a Debian:
Operating System: 	Linux 4.19.0-9-amd64 x86_64
With Intel CPU.

{"no app in context","method":"POST","url":"/index.php/apps/passwords/api/1.0/service/password","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0","version":"19.0.3.1","id":"5f7dbf0f03ddd"}

","app":"no app in context","method":"POST","url":"/index.php/apps/passwords/api/1.0/service/password","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0","version":"19.0.3.1","id":"5f7dbf0f03e0d"}

,"app":"no app in context","method":"POST","url":"/index.php/apps/passwords/api/1.0/service/password","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0","version":"19.0.3.1","id":"5f7dbf0f03e3e"}

","app":"no app in context","method":"POST","url":"/index.php/apps/passwords/api/1.0/service/password","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0","version":"19.0.3.1","id":"5f7dbf0f03e71"}

Hope you can use it.

**Comment by marius-wieschollek** [comment]
Can you also add the words service you're using? Thanks

**Comment by florom** [comment]
Hi Devs,

If you guide me where to get this information I will happily provide it.

The Firefox Debugger Console remains empty when generating a new password.

**Comment by marius-wieschollek** [comment]
This setting can be found in the app settings in the admin area of nextcloud. There is an option called "Password Generator Service"

**Comment by florom** [comment]
Thank you:

That is "Local dictionary"

I now changed it to the recommended setting  (Leipzig Corpora Collection) there it works

I would have a question there. If it is not local, is then an online service used?
Or is there a connection anytime to Leipzig Corpora Collection to update this?
I do not want the passwords app to connect to anything outside. That's why I am asking.
Same question refers to the other one:

![image](https://user-images.githubusercontent.com/32240626/95432128-89448400-094e-11eb-9e60-f9a0f17704a8.png)



Here a Screenshot of the other settings (if neccessary):


![image](https://user-images.githubusercontent.com/32240626/95431409-66fe3680-094d-11eb-9aec-32e10c61117e.png)

Thank you very much.

**Comment by marius-wieschollek** [comment]
So i will add some additional quality checks to the local dictionary helper in the regular release.


_Leipzig and W4S use an online API for every request_
Leipzig is the recommended default because it offers many different languages and is [GDPR](https://wortschatz.uni-leipzig.de/en/privacy) compliant.The service is used to provide words, the generation of a password from these words and all further processing is done locally.

W4S is an online service which provides random words based on given options. This results in "nicer" easy to remember passwords. It is only available in English. Here also the generation of a password from these words and all further processing is done locally.

_The Local dictionary and Random Characters are completely local._
The local dictionary uses local dictionary files to create a password. The quality and size of these dictionaries varies greatly as your example shows. 

The random characters generates a (as much as possible) random string of characters. Most common users consider these passwords inconvenient as they are hard to remember or type in.

**Comment by florom** [comment]
Thanks, then I will go back do local dictionary as soon as possible.

Is there a possibility to change "local dictionary" to another local dictionary maybe on the OS?
How am I changing this from wiki "Actually available options depend on which dictionaries are installed on the server"
I am lacking the technical depth so I might ask an obvious question.

**Comment by marius-wieschollek** [comment]
> Is there a possibility to change "local dictionary" to another local dictionary maybe on the OS?

The [paths are hardcoded in the app](https://github.com/marius-wieschollek/passwords/blob/master/src/lib/Helper/Words/LocalWordsHelper.php#L19) and whatever file is there will be used. The dictionaries are usually managed by your os but you can probably place some other file there.

**Comment by florom** [comment]
Thanks, I will look into that.

**Comment by florom** [comment]
By the way ---- Great App.

**Comment by marius-wieschollek** [comment]
The [2020.11.0 nightly release](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Use-Nightlies) now removes `'s` from the end of words as well as any numbers in any word.

**Comment by florom** [comment]
Hi @marius-wieschollek ,

I just wanted to add that this happens with checked Numbers too. So Probably you could add the sanity check for checked Numbers too but without numbers: See Screenshot please:

![2020-10-21_10-38-06](https://user-images.githubusercontent.com/32240626/96695596-1eea0580-138a-11eb-8743-6f25d4cc73ac.jpg)


Thanks.

**Comment by florom** [comment]
Thank you. It works.
