### ISSUE TITLE
Browser outdated (Firefox 81.0.1) MacOS Catalina

### ISSUE THREAD

**Issue by himpierre** [marius-wieschollek/passwords#304]
### System Information
- Nextcloud Version: 20
- PHP Version: 7.4
- Database and Version: Mariadb
- Passwords Version: 2020.10
- Browser and Version: Firefox 81.0.1
- Client OS and Version: MacOS
- Server OS and Version: Linux

### Steps to reproduce
1. Open Password App with Firefox 81.0.1
2. Browser Outdated Page shows up

### Expected result
Password App should open.

### Actual result
Browser Outdated Page shows up.

Nothing in the logs so far...

**Comment by marius-wieschollek** [comment]
The deprecated browser warning is based on some tests run in the browser.

Can you run the following code from the console of the browser? (Firefox may display a warning if you paste & copy something for the first time) Or open and run this JSFiddle: https://jsfiddle.net/5e9yfc3w/
```
if(window.crypto.subtle) console.log('WebCrypto is there');
if(window.TextEncoder) console.log('TextEncoder is there');
if(typeof WebAssembly === "object" && typeof WebAssembly.instantiate === "function") console.log('WebAssembly is there');
```

This should be the output
```
WebCrypto is there
TextEncoder is there
WebAssembly is there
```

**Comment by himpierre** [comment]
Thanks for your answer @marius-wieschollek. Textencoder and webcrypto where missing. Resettet firefox to default and now it works. Thanks again.
