### ISSUE TITLE
Custom fields usage

### ISSUE THREAD

**Issue by Belface** [marius-wieschollek/passwords#306]
Hello there
I'm trying to configure an automatic connection using custom fields for this website : https://phpmyadmin-gra2.hosting.ovh.net/
I've created custom fields **pma_servername** and **input_servername** and assign them a value (I choose Text type) : but that doesn't work.

Is the automation not possible with this specific website, or am I doing something wrong ?

Thanks in advance for your help

**Comment by marius-wieschollek** [comment]
Please don't misuse the ticket system for questions

**Comment by Belface** [comment]
Hello Marius
Sorry for the misunderstanding... this is not a question... I'm reporting you a bug
Unless I'm mistaken, the "Custom fields" features is not working... in my previous message, I gave you an example. But it's not working for all websites I've tried.

Thanks in advance for your assistance
