### ISSUE TITLE
Unclear error message when API access authentication fails

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#308]
When a user configured a wrong password / app token, the error messages printed in the admin log are not telling which user has the issue. Apparently some update in Firefox reset the configured passwords, so a few of my users were trying to access their password collection with the WebExtension and an empty authentication password. This is the Nextcloud log message I see:

```
[passwords] Warning: Login attempt with invalid authorization header for invalid user id
```

### System Information
- Nextcloud Version: 19.0.4
- PHP Version: 7.4.11
- Database and Version: MySQL 10.3.23
- Passwords Version: 2020.10.0
- Browser and Version:  Firefox 81
- Client OS and Version: Ubuntu 20.04
- Server OS and Version: Debian 10 Buster

### Steps to reproduce
1. Set up WebExtension
2. Remove password or set wrong password in WebExtension
3. Check Nextcloud log for messages

### Expected result
The log message should reveal to the admin which user has an issue and maybe be a bit more precise on what is happening, so the user can be contacted and the problem fixed.

### Actual result
The above error message is printed. This then requires the admin to grep through the webserver log (if available) to correlate the error message with a user name and connection attempt.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
[passwords] Warning: Login attempt with invalid authorization header for invalid user id

GET /index.php/apps/passwords/api/1.0/session/keepalive
from <IP> at 2020-10-04T16:59:34+02:00
```
</details>

**Comment by marius-wieschollek** [comment]
I'm not sure if i can do anything about this.
"invalid user id" literally means that the login data could not be matched to any user.
I have thought about printing the authentication header, but this is user controlled data and could be used for an attack.

**Comment by simonspa** [comment]
I see the issue. Do you have any idea how this invalid user id could end up in a request when using your web extension? I have not managed to find out what exactly has triggered this and it only happened to two of my users. They claim not not have touched any settings or changed their account password or app token.

**Comment by marius-wieschollek** [comment]
If you change your Nextcloud password, it can invalidate app tokens. It can also happen that the extension login data gets corrupted during synchronization or by a browser update.
