### ISSUE TITLE
Notes are truncated without notification

### ISSUE THREAD

**Issue by tarpin** [marius-wieschollek/passwords#31]
'New Password' form doesn't warn user about truncating of content, which exceeds length limit. User may loose his data, because he doesn't know about this.
I checked only Notes field, but probably the problem occurs on the other fields.

### System Information
- Nextcloud Version: 13.0.0
- PHP Version: 7.2.2
- Passwords Version: 2018.3
- Browser and Version: Mozilla Firefox 56.0.2
- Server OS and Version: CentOS 7.2

### Steps to reproduce
1. Open 'New Password' form.
2. Fill required fields with proper data.
3. Fill the Notes field with very long text (e.g 6,000 characters). 
4. Click Save button.
5. Open newly created entry.
6. Compare content of Notes with previously saved text.

### Actual result
Saved text is shorter than text in step 3.

### Expected result
1. Notify user about reaching length limit by a counter on the bottom or by another way.
2. Increase length limit of the Notes field to 10,000 characters or more.

**Comment by marius-wieschollek** [comment]
I have added a counter and a notification when the maximum length of 4096 characters is reached. This will be in the next nightly. I will not increase the maximum size as this field is intended for notes only. See my comment in #32 about this.

**Comment by tarpin** [comment]
Thank your for quick reply and resolve. I understand, this was my workaround for storing RSA and PGP keys, as you guessed (#32).
