### ISSUE TITLE
raw.githubusercontent.com 

### ISSUE THREAD

**Issue by devnull4242** [marius-wieschollek/passwords#310]
The app "passwords" need access to raw.githubusercontent.com because of handbook.
I think this is not really nice. I load all stuff for my nextcloud from my nextcloud server.
Please write a on-prem-site for passwords-handbook with a link to the handbook 

https://help.nextcloud.com/t/passwords-app-uses-third-party-connection-raw-githubusercontent-com-is-that-really-necessary/95788

**Comment by marius-wieschollek** [comment]
1. This feature request does not follow the feature request form
2. This request has been answered in the forum
