### ISSUE TITLE
Password sharing with nextcloud groups

### ISSUE THREAD

**Issue by Addi995** [marius-wieschollek/passwords#311]
**Current Status**
At the moment we can share passwords with the users on our nextcloud.

**Feature Description**
Sharing passwords to a nextcloud group and not only users.
So all users who are in the group "pr" have access to the passwords who are shared for the group "pr". 

**Additional context**
We have a lot of passwords, some for the admins, some for the pr, and so on. 
And we would like to share these passwords to our specific nextcloud group

**Comment by rakurtz** [comment]
Or do it in another way: allow password folders to be shared with users/groups.

**Comment by dhenry123** [comment]
> Or do it in another way: allow password folders to be shared with users/groups.

how to ? share option is not available on folders

**Comment by rakurtz** [comment]
> how to ? share option is not available on folders

You got me wrong. I also want this feature urgently! I meant for a new feature, instead of sharing a pw with a group, sharing a whole folder with users (or even groups) would also do the job. That is on my feature's wish list!

**Comment by marius-wieschollek** [comment]
See #27
