### ISSUE TITLE
Option for editable password sharing

### ISSUE THREAD

**Issue by majkinetor** [marius-wieschollek/passwords#312]
**Current Status**
Currently you must click pencil icon when sharing each time.

**Feature Description**
I would like to have an Settings option or main menu checkbox or something similar so this is either enabled or disabled. If enabled, all shares are created editable.

**Additional context**
Its just slow to wait for this, and additionally, very often rotating circle does that very long or indefinitely (until page is refreshed) which is confusing to users.

**Comment by marius-wieschollek** [comment]
While we're at it, i will also add this for the resharing option

**Comment by majkinetor** [comment]
Argh, that's the reason I couldn't share passwords shared to me, didn't even notice it...

Yeah definitely. 

Could we also have those options on system administration level to serve as default for all - sounds like a hassle to notify everybody to enable both options, it would be great to set it to default for entire nextcloud instance.

**Comment by marius-wieschollek** [comment]
There is a default option for the sharing options in the nextcloud sharing admin setting so i will just respect the option chosen there.

**Comment by majkinetor** [comment]
Even better.

Are you talking about those (selected):

![image](https://user-images.githubusercontent.com/85767/99718163-c69e4480-2aaa-11eb-8b26-8c6a374c7a91.png)

**Comment by marius-wieschollek** [comment]
yes. we respect other settings on this page as well so it would be inconsistent to stop here
