### ISSUE TITLE
Search results disappear when opening details

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#317]
Here is a screencast of the issue:

![Peek 2020-12-09 09-39](https://user-images.githubusercontent.com/1677436/101605555-99d2b280-3a02-11eb-8c37-33e03c3c3489.gif)

(side note: somehow the "modified" date is in the wrong language. On that NC instance I have language set to en_US but locale to de_DE)

### System Information
- Nextcloud Version: 20.0.2
- PHP Version: 7.4.11
- Database and Version: mysql 10.4
- Passwords Version: 2020.12.0
- Browser and Version: Firefox 83
- Client OS and Version: Ubuntu 20.10
- Server OS and Version: Debian Buster

### Steps to reproduce
0. Set up Passwords such that Details page is opened on single click
1. Search passwords (global search)
2. Click on search result to open details
3. See search result entry disappear

### Expected result
It should remain visible

### Actual result
Entry disappears

### Nextcloud log
No related entries

### Browser log
No entries

**Comment by marius-wieschollek** [comment]
Yes, i have noticed that issue as well. it should be fixed in the 2020.12.1 nightly.
