### ISSUE TITLE
Files attachment (e.g RSA keys)

### ISSUE THREAD

**Issue by tarpin** [marius-wieschollek/passwords#32]
It would be useful to have possibility to attach files like RSA keys.

**Comment by marius-wieschollek** [comment]
Hello and thank you for your request. Passwords is not very good at storing large amounts of data. It would slow the whole application down by downloading the files whenever the password is requested. It would also increase memory consumption, network traffic and might lead to all kinds of technical issues that come with file storage. I can understand that you want to store things like RSA keys close to their passphrase, but uploading them in the app is not the right way to do this. If you want to store files in a secure way, i recommend using the end-to-end encryption introduced in Nextcloud 13.

**Comment by tarpin** [comment]
Thank you for quick reply, I understand. However, I've add another solution proposal in #17 for you consideration.

**Comment by phlegx** [comment]
Passman app has the possibility to add files and is also supported in Keepass etc. The app should have this feature.
