### ISSUE TITLE
Nextcloud Docker - Kubernetes

### ISSUE THREAD

**Issue by dhenry123** [marius-wieschollek/passwords#321]
**Current Status**
The nextcloud instance is hosted on kubernetes behind a reverse proxy. 
Reverse proxy is set with "https"
And when i use your app i get  a nextcloud warning : 
![image](https://user-images.githubusercontent.com/27366357/103332232-5ca49200-4a8f-11eb-8c07-12a0a3009203.png)
HTTPS is required / This application depends HTTPS to run ...

Sure my final servers are not running with "https" protocol, because this is a trusted area, and we always try to encrypt once on the communication pipeline.

**Feature Description**
Could you add parameter variable to activate/desactivate this behaviour ?

**Comment by marius-wieschollek** [comment]
If you open the passwords app with an account with administrative privileges, there is additional information on how to handle the issue. Additionally, the [system requirements](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#https-requirement) page has a section about the HTTPS requirement and links to the related Nextcloud documentation you should follow.
