### ISSUE TITLE
[Bug] 2021.1.0 Updates fails and server is stuck in maintanace mode

### ISSUE THREAD

**Issue by lightlike** [marius-wieschollek/passwords#322]
### System Information
**Server:**
```
 Nextcloud Version: 20.0.4
 PHP Version: 7.3.23
 Database and Version: mariadb (docker) mysql: 10.4.17
 Server OS and Version: openmediavault (debian)
 Passwords Version: 2021.1.0
```

### Steps to reproduce
1. Update to latest version

### Expected result
Should update properly

### Actual result
Migration fails and and gets stuck in maintanace mode (had to disable in acc to get running again)

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
[index] Error: Exception: syntax error, unexpected 'ConfigurationService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at <<closure>>

0. /config/www/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
1. /config/www/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {action: null,ap ... "})
2. /config/www/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/settings/apps/update/passwords")
3. /config/www/nextcloud/index.php line 37
   OC::handleRequest()

GET /settings/apps/update/passwords
from 80.228.222.209 by dnietfeld at 2021-01-03T14:13:06+00:00

[PHP] Error: ParseError: syntax error, unexpected 'ConfigurationService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /config/www/nextcloud/apps/passwords/lib/Migration/DatabaseObjectRepair.php#39

GET /core/ajax/update.php?requesttoken=QsxWtfODRWeyGLbw2qjHik59gCIV3FF1vreu1eDngsI%3D%3ACql5%2BqbqIxLIWs%2Be6%2Fno3jhL0lo%2BsxwU7Nj7kLHM9pg%3D
from 80.228.222.209 at 2021-01-03T14:14:53+00:00

[PHP] Error: ParseError: syntax error, unexpected 'ConfigurationService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) at /config/www/nextcloud/apps/passwords/lib/Migration/DatabaseObjectRepair.php#39

GET /core/ajax/update.php?requesttoken=Ww%2BLParEc4MXxvUFUMfFWThku8oscBhw7cyF8gzPvn0%3D%3AE2qkcv%2BtFfZthIxrYZbqDU5S6bIHH1URv6PQt13kyic%3D
from 80.228.222.209 at 2021-01-03T14:16:09+00:00
```
</details>

**Comment by marius-wieschollek** [comment]
PHP 7.3 is no longer supported like announced by the deprecation notices in the app before. However Nextcloud does not check the minimum requirement for PHP and advertises the update anyway even if it does not work.

I will publish a guide for a downgrade soon.

**Comment by lightlike** [comment]
Oh. Yea. I'll try updating the docker to see if there is a new php-version.

**Comment by lightlike** [comment]
Someone already created an issue with the docker and on nextcloud. I'll try it there.
https://github.com/linuxserver/docker-nextcloud/issues/168
https://github.com/nextcloud/server/issues/24945

**Comment by marius-wieschollek** [comment]
Ok.

Those who want to downgrade to the last version supporting PHP 7.3, [klick here for a guide](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Migrations/Minimum-Requirement-Error).

**Comment by lightlike** [comment]
Thank you very much. I hope alpine and linuxserver.io update their docker images soon so I can update everything again.

**Comment by Gwyll** [comment]
Just one question:
do you have any advice how to force a distribution builder group to include PHP7.4?

**Comment by marius-wieschollek** [comment]
@Gwyll I don't want to force anyone to do anything. For most distributions there are package sources with up-to-date php builds available. 

I have removed the update from the appstore and won't publish it again until there is a good solution for it.

**Comment by kesselb** [comment]
The issue with app store and php version should be fixed by: https://github.com/nextcloud/server/pull/24416
