### ISSUE TITLE
Fast Access for Password and Username

### ISSUE THREAD

**Issue by benginoe** [marius-wieschollek/passwords#325]
**Current Status**
At the moment i can only copy the password by clicking on an entry, this is quite good but in circumstances I dont know my login name for a website and need to look this as well up by opening the details, which is a further more 2 click action. 

**Feature Description**
I would like to have for each entry 2 circles, one for the password and one for the user name, which copies each entry to my clipboard. 

Big thanks to all of the contributors!

**Comment by marius-wieschollek** [comment]
You can double click to copy the username (unless you changed that in the settings)

**Comment by benginoe** [comment]
Okay that works for me! 

Big thanks for the fast reply and work!!!
