### ISSUE TITLE
Provide full read and write access to all password information in browser extentions

### ISSUE THREAD

**Issue by drolex2** [marius-wieschollek/passwords#327]
**Current Status**
The Firefox browser extension only allows copying the user name or password of a Nextcloud Password entry. I cannot view the notes, custom field information or anything else. I can't even view the user name or password without copying and pasting it.

**Feature Description**
In the web browser extension, there should be a button for each password that allows the user to view the notes and custom data for the password. I suggest referencing and copying how LastPass works. That is, there could be an edit button that opens a page and allows the user to view and edit all password fields (Name, URL, user name, password, notes, custom field data).

**Additional context**
Here is a screenshot of the edit form in the LastPass Firefox extension.
![image](https://user-images.githubusercontent.com/7788689/104433176-b45bf680-5581-11eb-8536-2afd90825edd.png)

**Comment by marius-wieschollek** [comment]
Issues related to the browser extension are handled in the GitHub repository of the [browser extension](https://github.com/marius-wieschollek/passwords-webextension).
The issue https://github.com/marius-wieschollek/passwords-webextension/issues/27 seems to cover this use case.
