### ISSUE TITLE
passwords view with name, username, tags

### ISSUE THREAD

**Issue by pafcioooo** [marius-wieschollek/passwords#33]
Currently in passwords view, no matter if it is all passwords view or folder view, passwords list has only name, password strenght indicator, more indicator, date changed.
It is very important that this list has also username column which in case of two different usernames for the same name, one could easly distinguish the difference.
The workaround for this is to add the username manually to name filed but it make it more cumbersone.

**Comment by marius-wieschollek** [comment]
Tags on the main view has been added in #3 .
For the usernames, using the name field is actually the intended behavior.
If you just leave the name empty when creating a new password, it will automatically be filled like below:
![grafik](https://user-images.githubusercontent.com/8255857/37555641-08436bf4-29eb-11e8-9aa1-e794b54eee44.png)

**Comment by pafcioooo** [comment]
@marius-wieschollek what is the reason for just a name being displayed in password list then?

Adding another column (as an settings option) wouldn't make a big difference here, would it?

I have imported 200 passwords with csv importer and now I need to change them to different name.

Thanks

**Comment by marius-wieschollek** [comment]
Will be available as advanced setting in 2018.5.

**Comment by marius-wieschollek** [comment]
Now available as "Advanced" setting

**Comment by pafcioooo** [comment]
Cool:-) Thanks:-)
