### ISSUE TITLE
List iOS client

### ISSUE THREAD

**Issue by johannes-schliephake** [marius-wieschollek/passwords#332]
I have developed an iOS client for the Passwords app.

- Name of your app: **Passwords for Nextcloud**
- Short description of your app: **Allows you to view, create, edit and delete the passwords and folders on your Nextcloud server. Supports Password AutoFill.**
- Logo of your app: [Link](https://raw.githubusercontent.com/johannes-schliephake/nextcloud-passwords-ios/main/AppIcon%402x.png)
- Link to the store where users can get your app: [Link](https://apps.apple.com/app/id1546212226)
- Link to the sources: [Link](https://github.com/johannes-schliephake/nextcloud-passwords-ios)
- Supported Systems: iOS 14 and above
- Information how we can test your app: **Download from the App Store or build the Xcode project**

Thanks!

**Comment by joleaf** [comment]
Nice app :)

I tried to implement the autofill function for iOS in my [flutter app](https://gitlab.com/joleaf/nc-passwords-app/) also, but it never worked for me, so thank you for this amazing app :)

**Comment by johannes-schliephake** [comment]
Thank you so much for your kind feedback, @joleaf!

If you are interested, we could probably make iOS AutoFill work in your app as well. The way I implemented it should be quite universal.

**Comment by marius-wieschollek** [comment]
The ios app is now listed with 2021.2.0
