### ISSUE TITLE
show username in overview

### ISSUE THREAD

**Issue by Michele64** [marius-wieschollek/passwords#334]
**Current Status**
in the password list only the name is shown

**Feature Description**
if one has multiple accounts with the same name (or manages lots of client accounts with the same domain) it's impossible to distinguish them. One has to go through them one by one which is tedious
An additional column filled with the username and/or notes would be helpful. 
![Bildschirmfoto_2021-01-23_21-17-08](https://user-images.githubusercontent.com/13287876/105613102-a9466900-5dc0-11eb-888c-cb2128a4210f.png)

**Comment by marius-wieschollek** [comment]
That is an amazing view :open_mouth: 
Aside from that, take a look at the [Show username in list view option](https://git.mdns.eu/nextcloud/passwords/wikis/Users/Settings#show-username-in-list-view-advanced) in the [advanced settings](https://git.mdns.eu/nextcloud/passwords/wikis/Users/Settings#advanced-settings).
Does this fix your issue?

**Comment by Michele64** [comment]
much better, I did'nt realize that there was an advanced section, my bad. 
But since it isn't a separate column it's not possible to sort it. eg when I want to see the entries for one user without having to search for it

**Comment by Michele64** [comment]
I do have the same problem with the firefox extension: There is no way to decide which login to choose. And it doesn't display all availabe entries, only eight.

**Comment by summersab** [comment]
I enabled the option under "Advanced Settings," but I agree that having this be a separate column would make it much easier to view and manage accounts/passwords.
