### ISSUE TITLE
make second-level OTP optional

### ISSUE THREAD

**Issue by fajabird** [marius-wieschollek/passwords#335]
**Current Status**
When E2E-Encryption in Passwords and OTP are both enabled I need to enter the OTP every time I change to the passwords app inside nextcloud - even if the last thing what I did was exactly this. 
Normally with enabled OTP for nextcloud-login most apps that need to connect to nextcloud need either to complete the password/OTP process and if they do not support OTP they can be provided with an specific "app-password". But after this initial setup they continue to work without prompting for an OTP on each connection but reuse a long-time session key. 
With nextcloud-passwords OTP implementation browser-plugins or mobile applications require to enter that OTP on every start.

**Feature Description**
Make "second-level" OTP optional. For me it would be enough if password prompts me just for the E2E-Encryption passphrase on each start of the app or desktop browser. IMHO the downsides of this extra level of protection are working against usability and user should be able to decide. 

**Additional context**

**Comment by marius-wieschollek** [comment]
Being able to disable 2FA at will completely undermines the use of having 2FA in the first place.

**Comment by fajabird** [comment]
I think you should leave this decision up to the user e.g. to opt-out (secure defaults!). But if the user has to choose between convenience and max security the later is not always everyones pick. In my case I disabled E2E-encryption just because you don't offer this opt-out option - is this what you want to archive?

In a nutshell: I enabled OTP for my nextcloud login - so I have a better protection from brute force attacks agains my password which I still need to remember and enter in case I don't have a password manager. But as nextcloud paswords has been connected to my browser and mobile app using a app-key which is quite save from password brute force as its random and long enough I don't need another OTP-step every time I want to access them. 

What about an attacker that gained control over my nextcloud installation and has access to the password database? Is this database encrypted only with the passphrase I was requested to enter when setting up E2E encryption or is OTP part of that key-material as well? Also, the shared-key for OTP is stored somewhere on the server too, so the attacker has it already as well right? So the only thing that stands between an attacker on the server and my passwords is the passphrase which is unknown to the server - OTP is not - am I right?

Could you describe your "threat model"? Maybe I missed something...
