### ISSUE TITLE
Encryption Tests Failed

### ISSUE THREAD

**Issue by commdogg** [marius-wieschollek/passwords#337]
### System Information
**Server:**
```
 Put the output of "./occ passwords:system:report debug" here or fill out the fields below

 Nextcloud Version: 20.0.6
 PHP Version: 7.4.14
 Database and Version: MariaDB 5.5.68
 Server OS and Version: Centos 7.9
 Passwords Version: 2020.12.2
```

**Client:**
```
 Browser and Version: Brave 1.18.77
 Client OS and Version: Centos 8.3
```

### Steps to reproduce
1. Open password app from main user page
2. Attached per error request:
eyJ0eXBlIjoicGFzc3dvcmQiLCJzdGFnZSI6ImZldGNoIiwiZXJyb3IiOnsibWVzc2FnZSI6IkNvbnRlbnQgdHlwZSBtaXNtYXRjaDogRXhwZWN0ZWQgYXBwbGljYXRpb24vanNvbiwgZ290IHRleHQvaHRtbCIsInN0YWNrIjpbIkVycm9yOiBDb250ZW50IHR5cGUgbWlzbWF0Y2g6IEV4cGVjdGVkIGFwcGxpY2F0aW9uL2pzb24sIGdvdCB0ZXh0L2h0bWwiLCIgICAgYXQgZS5iLl9zZW5kUmVxdWVzdCAoaHR0cHM6Ly9uZXh0Y2xvdWQuZXh0ZXJuYWwuZ3J5ZG9uaXMuY29tOjg0NDUvYXBwcy9wYXNzd29yZHMvanMvU3RhdGljL2FwcC5qcz92PTk1YTI4MzUzLTA6NDM6MjQyMDQ2KSIsIiAgICBhdCBhc3luYyBlLmIubGlzdFBhc3N3b3JkcyAoaHR0cHM6Ly9uZXh0Y2xvdWQuZXh0ZXJuYWwuZ3J5ZG9uaXMuY29tOjg0NDUvYXBwcy9wYXNzd29yZHMvanMvU3RhdGljL2FwcC5qcz92PTk1YTI4MzUzLTA6NDM6MjQ3MDc1KSIsIiAgICBhdCBhc3luYyBPYmplY3QudGVzdFBhc3N3b3JkcyAoaHR0cHM6Ly9uZXh0Y2xvdWQuZXh0ZXJuYWwuZ3J5ZG9uaXMuY29tOjg0NDUvYXBwcy9wYXNzd29yZHMvanMvU3RhdGljL2FwcC5qcz92PTk1YTI4MzUzLTA6NDU6NTA3ODg2KSIsIiAgICBhdCBhc3luYyBPYmplY3QucnVuVGVzdHMgKGh0dHBzOi8vbmV4dGNsb3VkLmV4dGVybmFsLmdyeWRvbmlzLmNvbTo4NDQ1L2FwcHMvcGFzc3dvcmRzL2pzL1N0YXRpYy9hcHAuanM/dj05NWEyODM1My0wOjQ1OjUwNzA3NSkiXX0sInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChYMTE7IExpbnV4IHg4Nl82NCkgQXBwbGVXZWJLaXQvNTM3LjM2IChLSFRNTCwgbGlrZSBHZWNrbykgQ2hyb21lLzg3LjAuNDI4MC4xMDEgU2FmYXJpLzUzNy4zNiIsInByb3RvY29sIjoiaHR0cHM6IiwiY3J5cHRvIjp0cnVlLCJ0ZXh0ZW5jb2RlciI6dHJ1ZSwiYXBwIjoiMjAyMC4xMi4yIiwiYXBpIjoiMC4wLjEwIiwiYXBwcyI6WyJhY2Nlc3NpYmlsaXR5IiwiYWN0aXZpdHkiLCJhZG1pbl9hdWRpdCIsImJydXRlZm9yY2VzZXR0aW5ncyIsImNsb3VkX2ZlZGVyYXRpb25fYXBpIiwiY29tbWVudHMiLCJjb250YWN0cyIsImNvbnRhY3RzaW50ZXJhY3Rpb24iLCJkYXYiLCJmZWRlcmF0ZWRmaWxlc2hhcmluZyIsImZlZGVyYXRpb24iLCJmaWxlcyIsImZpbGVzX3BkZnZpZXdlciIsImZpbGVzX3JpZ2h0Y2xpY2siLCJmaWxlc19zaGFyaW5nIiwiZmlsZXNfdHJhc2hiaW4iLCJmaWxlc192ZXJzaW9ucyIsImZpbGVzX3ZpZGVvcGxheWVyIiwiZmlyc3RydW53aXphcmQiLCJsb2dyZWFkZXIiLCJsb29rdXBfc2VydmVyX2Nvbm5lY3RvciIsIm5leHRjbG91ZF9hbm5vdW5jZW1lbnRzIiwibm90ZXMiLCJub3RpZmljYXRpb25zIiwib2F1dGgyIiwicGFzc3dvcmRfcG9saWN5IiwicGFzc3dvcmRzIiwicGhvdG9zIiwicHJpdmFjeSIsInByb3Zpc2lvbmluZ19hcGkiLCJyYW5zb213YXJlX2RldGVjdGlvbiIsInJhbnNvbXdhcmVfcHJvdGVjdGlvbiIsInJlY29tbWVuZGF0aW9ucyIsInJpY2hkb2N1bWVudHMiLCJzZXJ2ZXJpbmZvIiwic2V0dGluZ3MiLCJzaGFyZWJ5bWFpbCIsInN1cHBvcnQiLCJzdXJ2ZXlfY2xpZW50Iiwic3lzdGVtdGFncyIsInRhc2tzIiwidGV4dCIsInRoZW1pbmciLCJ0d29mYWN0b3JfYmFja3VwY29kZXMiLCJ0d29mYWN0b3JfdG90cCIsInR3b2ZhY3Rvcl91MmYiLCJ1cGRhdGVub3RpZmljYXRpb24iLCJ1c2VyX2xkYXAiLCJ1c2VyX3N0YXR1cyIsInZpZXdlciIsIndlYXRoZXJfc3RhdHVzIiwid29ya2Zsb3dlbmdpbmUiXX0

3.  NA

### Expected result
What should happen? App opens and displays passwords

### Actual result
What does happen? Error Screen

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
 - Open the Nextcloud admin settings
 - Open the "Log" section
 - Click the "Copy" icon, then Copy Raw
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy the content of the console tab
```
</details>

**Comment by commdogg** [comment]
Investigating further, issue does NOT occur on local LAN from internal FQDN, but DOES occur on the external FQDN through the haproxy server. Seems to only occur when using the proxy. External certs are Lets Encrypt, internal certs are issued by an internal CA.

**Comment by marius-wieschollek** [comment]
The data says that the issue occurred during the fetch stage of the test. So the request failed for some reason. Since this is not an issue with the encryption, i think we can close the issue.
