### ISSUE TITLE
Enable multiple Website matching

### ISSUE THREAD

**Issue by politas** [marius-wieschollek/passwords#339]
**Current Status**
As it stands, website URLs are forced to be a single complete URL. Automatic URL matching in browser extensions and mobile apps is limited to that single URL. Matches cannot also be made to App profiles, nor to alternate URLs where the same account is used. To enable automatic matching, multiple account entries are required that all need to be updated when changing a password.

**Feature Description**
We should be able to associate a single password account entry to multiple websites, and use wildcard matching for different URLS within a single organization. It is not the case that a single user account is only used for a single URL

Allowing multiple entries and wildcard matching would ease the user experience

* match anything using the same Domain/TLD (for instance, a nextcloud instance login might also be used to log into blogs or wikis or admin interfaces hosted under the same domain)
* match where a single account allows access to multiple websites (blogs may be set up with a dedicated URLs that uses the same LDAP authentication back-end)
* Mobile device apps that do not present the service's URL could be linked to an online Service account (e.g. the Falcon Twitter app on Android would need to match `androidapp://com.jv.materialfalcon` instead of `https://twitter.com`

To maintain backwards compatibility, additional search URLS should be implemented ins a separate data structure to the existing "Website" field.

**Comment by marius-wieschollek** [comment]
You can actually specify additional urls in the custom fields section. Wildcard matching is already requested in https://github.com/marius-wieschollek/passwords-webextension/issues/87 .
