### ISSUE TITLE
Handling punycode

### ISSUE THREAD

**Issue by MrManor** [marius-wieschollek/passwords#341]
**Current Status**
User has visited a webside with a national char in url (https://ønskeskyen.dk) and created a account. To remember the password she manually has created a new entry in Nextcloud webgui for the site in question, and copy pasted the url from the browser url. Now every time she goes to the the password page in Nextcloud, a **501 bad gateway** is shown. 

**Feature Description**
It would be user friendly if pasting into the url field could automatically convert the url to punycode. Or at least just check if the url contains illegal characters.  

**Additional context**
I have not tested weather the url actually triggers the browser plugin, and a suggested password is shown using punycode or not.

**Comment by marius-wieschollek** [comment]
This should now work in 2021.2.0

**Comment by MrManor** [comment]
Great! Thanks a lot.
