### ISSUE TITLE
Apps and Extensions tab broken

### ISSUE THREAD

**Issue by barcoboy** [marius-wieschollek/passwords#343]
Running 2021.2.0-build3939 on Nextcloud server 20.0.7, the "Apps and Extensions" tab appears to be broken.  I see the following, and am unable to click on any of the headers.

![image](https://user-images.githubusercontent.com/6472190/107465040-7970c280-6b2f-11eb-9879-f8606c105b31.png)

Tried with both Firefox and Chrome on Mac and Windows, and also tried Firefox in Safe Mode with all addons disabled.

**Comment by barcoboy** [comment]
For whatever reason, the problem seems to have disappeared.  All previous browsers that were not working for me now work perfectly fine.  Don't have any explanation for as to why... no settings changed and no updates done.

**Comment by marius-wieschollek** [comment]
Sorry, i forgot to respond. The new apps & extensions listing is part of the user manual and hosted on GitHub. The data there was not yet up-to-date and therefore the tab was broken.

**Comment by barcoboy** [comment]
OK, thanks for the info.  Glad to know that I wasn't crazy seeing this.  :-)
