### ISSUE TITLE
[Feature] Share complete folder

### ISSUE THREAD

**Issue by michaelernst** [marius-wieschollek/passwords#344]
**Current Status**
I organized my passwords in folders each for a specific context, e.g. shared accounts. Currently, I have to share every password individually. 

**Feature Description**
I would like to share a folder. Every password or subfolder would be shared. This would avoid tedious work ;).

It would be the cherry on top if it would be possible that users having (shared) access to this folder would be able to create new entires as well.

**Comment by marius-wieschollek** [comment]
see #27
