### ISSUE TITLE
Multiple web sites for password

### ISSUE THREAD

**Issue by majkinetor** [marius-wieschollek/passwords#349]
**Current Status**

There are legitimate cases where you want to use the same credential on multiple places. As a developer, I have 3-5 different dev/staging/testing environments that all use the same credentials. Currently I have to copy credential and just change the website in order for it to show in web browser extension which extremely pollutes my NC workspace.

The situation is further complicated if you have multiple users. I for example typically have 5 integrated users like admin, operater etc. that come with the system by default. With 3 users and  3 environments I need to have total of 9 entries instead of 3.

**Feature Description**

Allow adding multiple web sites. This can be done by:

- Using some form of separator, unlikely to be in URL itself, such as `|` (looks like trivial for implementation and later parsing)
- Using multiple website fields that could be added with [+] button (requires UI changes)

**Comment by marius-wieschollek** [comment]
You can add additional urls under the custom fields section of the edit form. Just choose the type "link" so the extension will also treat it as url.

**Comment by majkinetor** [comment]
Will it show in browser extension ?

**Comment by marius-wieschollek** [comment]
Yes, the extension also checks these urls when creating suggestions.

**Comment by majkinetor** [comment]
Awesome. Thanks.
