### ISSUE TITLE
Allow passwords without username

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#35]
It would be nice to support passwords without the requirement of specifying a user name. I would for example like to store the administration password of my local router (AVM FritzBox) which just requires a password but no user name.

Currently the web interface requires me to enter a user.

**Comment by marius-wieschollek** [comment]
Good reminder for me :D. The api does not require a user name, but the web app still does. This should not be too hard to change.

**Comment by simonspa** [comment]
Yes, I've seen that the API already allows this already - therefore I guessed the webapp change would be trivial..

Thanks for the great work - playing around with `passwords` for testing, waiting for a few of the promised features to land before going productive...

**Comment by marius-wieschollek** [comment]
The nightly version allows this, the master now also creates a proper label if you do not set anything but the password (in the nightly it will still say `null`)

**Comment by simonspa** [comment]
Great, thanks a bunch!
