### ISSUE TITLE
app icon design background

### ISSUE THREAD

**Issue by LukeVader-IV** [marius-wieschollek/passwords#352]
**Current Status**
App icon is inconsistent with all the other nextcloud apps

**Feature Description**
The background layer of the icon should have the same gradient

**Additional context**
Almost all the other app icons for next cloud-related apps have a consistent look with a few exceptions having a flat background colour.
I am already helping the dev of Nextcloud Yaga as his icon has the same issue, So I could do the same here If you want me to (:

**Comment by LukeVader-IV** [comment]
PS: this is specifically about the android app "Nextcloud Passwords" https://play.google.com/store/apps/details?id=com.nextcloudpasswords
I have no clue how the situation is for the other versions

**Comment by marius-wieschollek** [comment]
Both android apps for the Passwords app are made by different developers.

I think you mean the app from daper: https://github.com/daper/nextcloud-passwords-app

The app from joleaf already has a gradient in the background: https://gitlab.com/joleaf/nc-passwords-app

**Comment by marius-wieschollek** [comment]
There seems to be a related ticket already: https://github.com/daper/nextcloud-passwords-app/issues/93

**Comment by LukeVader-IV** [comment]
Oh hey thanks, Didn't notice that one, Stupid me :P

**Comment by marius-wieschollek** [comment]
:+1: Seems like someone would be happy about your work

**Comment by marius-wieschollek** [comment]
Also you can get the app icon from here: https://github.com/marius-wieschollek/passwords/blob/master/src/img/app.svg

If that helps

**Comment by LukeVader-IV** [comment]
Yeah i saw that while i was browsing the files, Thanks for the help and the quick replies :)
