### ISSUE TITLE
Integrate with Nextcloud right click menu / context menu

### ISSUE THREAD

**Issue by eurecv2** [marius-wieschollek/passwords#355]
**Current Status**
The way that interactions with the password list are handled right now is pretty counter-intuitive and not that efficient

**Feature Description**
Making it so the context menu comes up when right clicking a password or folder as well, re-ordering it and adding "Copy username" and "Copy password" to it and making it so when the password is left-clicked the "Details" view opens up, instead of copying the password.

**Additional context**
Current context menu:
![image](https://user-images.githubusercontent.com/79525619/110312616-9c46a780-8005-11eb-84a8-b569a8629d43.png)
Suggested context menu (after re-ordering it and adding new buttons):
![image](https://user-images.githubusercontent.com/79525619/110313347-97cebe80-8006-11eb-9d94-ae37a9045bcf.png)
What currently happens when right-clicking a password (or folder, for that matter):
![image](https://user-images.githubusercontent.com/79525619/110313747-2ba08a80-8007-11eb-8cc2-24a2e24e0906.png)
That should open the actual password (or folder) context menu, instead of the browser's

**Comment by marius-wieschollek** [comment]
Have you seen this option: https://git.mdns.eu/nextcloud/passwords/wikis/Users/Settings#add-copy-options-in-menu

**Comment by marius-wieschollek** [comment]
And here you can set the single click action: https://git.mdns.eu/nextcloud/passwords/wikis/Users/Settings#single-click-action-advanced

**Comment by eurecv2** [comment]
I am very sorry, I've been looking in the wrong place (App's Nextcloud settings instead of the settings inside of the app). There still doesn't seem to be an option to enable right-click to open the context menu, though

**Comment by marius-wieschollek** [comment]
I have dug trough the code of the files_rightclick app and managed to get a basic right click menu working.

But since the documentation for the app is missing and the app itself seems to be quite buggy, i'm not going to add more that what's in the menu + copy actions.
