### ISSUE TITLE
Ability to have multiple URLs

### ISSUE THREAD

**Issue by eugef66** [marius-wieschollek/passwords#357]
**Current Status**
Some website have multiple domains that share same login (for example apple.com = icloud.com, etc...). Most of the time it's transparent to user and you don't realize you're at a different domain, but passwords are not being auto-filled. 
Other cloud based password managers handle this with either "equivalent domains" list in settings or multiple URLs on the password level.

**Feature Description**

Add ability to have multiple "equivalent" URLs or multiple URLs for one password

**Additional context**

Examples: 

![multiple urls](https://user-images.githubusercontent.com/11634504/110496705-c363ae80-80c3-11eb-8598-be65f0b04c5a.png)
![Domain Rules](https://user-images.githubusercontent.com/11634504/110496723-c8286280-80c3-11eb-8c22-32c0f5d14499.png)

**Comment by marius-wieschollek** [comment]
We already have the option to add multiple domains for any password entry via custom fields.

There is also #354 for domain mappings, but i haven't looked at it yet

**Comment by marius-wieschollek** [comment]
Custom fields with the type "link" are also checked by the browser extension when making recommendations.

**Comment by eugef66** [comment]
OK. Got it. I will test it out. 
It's not obvious from UI perspective though.  You can close this issue if you want or keep it open for more user-friendly experience. 
Thank you again for a great job.

**Comment by eugef66** [comment]
Great. Thank you.
