### ISSUE TITLE
PIN to access the app within the web GUI

### ISSUE THREAD

**Issue by julenl** [marius-wieschollek/passwords#358]
**Current Status**
The Passwords app is accessible by just clicking on the to bar of our Nextcloud web-GUI. This is simple, fast and convenient, just like with any other Nextcloud app.

However, due to the *extra confidential* nature of our passwords, in comparison to... everything else, it would be very good to have some way to request for some simple PIN or password, to access the app within the web GUI.
 
 A sample use case: We leave our computer unlocked (or... the screensaver crashes) in a *trusted* environment. With *trust*, I mean, that we don't care that anybody around checks out our pictures, documents, ... **But** the passwords belong to a completely different *trust* category (no-trust?).

**Feature Description**
It would probably be enough to just set an option to store a short PIN, which gets requested every time we access the App within the web-GUI, and maybe some *timeout* option to lock the app after some given time.

It does not have to be *super secure* or *sophisticated*. The goal is to provide a thin layer of protection against physical people clicking or typing in our open Nextcloud session.

**Additional context**
Just like the "Toggle security" option in the Android app :)

**Comment by marius-wieschollek** [comment]
See https://git.mdns.eu/nextcloud/passwords/wikis/Users/Encryption/Enable-End-to-End-Encryption
