### ISSUE TITLE
Clarify actions necessary to restore access to a client after multiple failed login attempts

### ISSUE THREAD

**Issue by lightnin** [marius-wieschollek/passwords#359]
**Current Status**
After multiple failed login attempts from outside apps / etc, passwords blocks access and notifies the user in their Nextcloud notification stream. The text of the notification is not clear for novice users.

**Feature Description**
The text of the notification should be clarified so that the user (or admin when necessary) understands exactly which steps must be taken to re-enable access from the app in question as simply and clearly as possible, or otherwise link to an FAQ or external resource explaining what to do in greater detail. For example, "If you want to continue using this client, you need to create a new token for it." Should instead indicate exactly which steps the user or admin must take, in which parts of the Nextcloud UI, to "create a new token for it."  (I can't provide this information because I am not certain myself.)

**Additional context**
Current text of the notification:
![image](https://user-images.githubusercontent.com/1538027/111066514-d0b3db00-84bf-11eb-94b6-5d529f15b647.png)

**Comment by marius-wieschollek** [comment]
This message means that the app password (formerly token) used by the client has been revoked. What needs to be done to enable the client again depends on the client. The browser extension allows you to simply change the app password, the android app requires logging in again.

Maybe the notification could use an update like:

> **Suspicious amount of failed login attempts detected.**
>
> We have detected several failed attempts to unlock your password database by "client".
> This could indicate that someone is trying to break into your account.
> To prevent further attempts, the app password used by this client was revoked.
> Additionally, access to the passwords API for clients not using an app password was disabled temporarily.
> If you want to use this client again, you need to create a new app token for it.
> If you don't know this client, please change your Nextcloud password and review your apps & devices list in the Nextcloud settings.
> To restore normal passwords API access, log into passwords using the correct master password.
>
> Open "Apps & Devices"
> Open "Passwords"

**Comment by lightnin** [comment]
Thanks for looking at this, and thanks for all your work making passwords.
So I appear to have reached this state by trying to connect first the passwords android app, and later the NC-Passwords app when the former didn't work (no error - just showed empty page). The prompting in these did not seem to ask for an 'app password,' so I entered my nextcloud user credentials. It may have been the encryption key for my passwords vault that was required at some point- but this wasn't indicated clearly. (The sign in dialog page looked like a Next cloud user sign in.) So a first step might be to try to clarify prompting so the user understands which class of credential is required. At not point in this process did I create an "app password" nor was it clear to me that I should, since I assumed that the 'password' android app would function in the same way that nextcloud notes or deck apps would on my phone.
I'm assuming that the only requirement for installing / using the passwords Android app are 1) User credentials, and 2) "Vault" password - if that's the case, perhaps we should use this terminology to clarify. 
I don't have a clear understanding of everything involved here, but I hope my confusion can be useful in clarifying for other users.

**Comment by lightnin** [comment]
Added related feature request #360 .

**Comment by fourprime** [comment]
> Thanks for looking at this, and thanks for all your work making passwords.
> So I appear to have reached this state by trying to connect first the passwords android app, and later the NC-Passwords app when the former didn't work (no error - just showed empty page). The prompting in these did not seem to ask for an 'app password,' so I entered my nextcloud user credentials. It may have been the encryption key for my passwords vault that was required at some point- but this wasn't indicated clearly. (The sign in dialog page looked like a Next cloud user sign in.) So a first step might be to try to clarify prompting so the user understands which class of credential is required. At not point in this process did I create an "app password" nor was it clear to me that I should, since I assumed that the 'password' android app would function in the same way that nextcloud notes or deck apps would on my phone.
> I'm assuming that the only requirement for installing / using the passwords Android app are 1) User credentials, and 2) "Vault" password - if that's the case, perhaps we should use this terminology to clarify.
> I don't have a clear understanding of everything involved here, but I hope my confusion can be useful in clarifying for other users.

I'm suffering from the same issue. Now I'm locked out and have no idea how to get back in. It isn't documented anywhere. Also, there is no "master" password. I don't understand how logging in with that would unlock anything when it just tells me "too many failed logins". There is nowhere to reset or add to white-list like the normal instance of Nextcloud. Very irritating.

**Comment by marius-wieschollek** [comment]
If you don't have a master password, you also can't run into this issue. It only happens at the master password prompt.

**Comment by ghost** [comment]
I have the same problem, `too many failed login attempts` and now I cannot unlock Passwords neither in the app nor in a browser session.

The error persists even after app/browser logout.

I don't understand how to get it to work.

**Comment by marius-wieschollek** [comment]
@MaxHillebrand you need to use the correct master password. Until you use that, any further attempt will void the credentials of the client used. The Nextcloud app can try reload to get new credentials, but it needs to reload every time which is intended to slow you down.

![passwords-unlock](https://user-images.githubusercontent.com/8255857/140513196-79eea728-9e1b-4b5a-b420-093056ac1433.gif)

**Comment by ghost** [comment]
Thank you @marius-wieschollek.
*edit* it was a wrong password 🙄

Maybe add to the notification with `too many failed attempts` also a `wrong password, ` prefix.

**Comment by marius-wieschollek** [comment]
yeah, i need to update the wording which is why the ticket is still open
