### ISSUE TITLE
Passwords Default Activity Settings

### ISSUE THREAD

**Issue by mikshepard** [marius-wieschollek/passwords#36]
As email and notification settings are getting added to the latest git version, I was hoping to request these settings to also appear in the Admin --> Activity --> Default Settings.  This way new users could automatically be setup for emails on passwords being shared with them, should the admin deem this necessary.  

It would greatly simplify our usage.  Thanks!

**Comment by marius-wieschollek** [comment]
Sounds good. Why not.

**Comment by marius-wieschollek** [comment]
I will add this in the usual password settings (Admin -> Passwords) instead of the activity settings. Adding it to the activity settings could lead users to believe that passwords respects the general activity settings as well which is not correct.

**Comment by mikshepard** [comment]
Sounds great, thanks!
