### ISSUE TITLE
Clarify which password is required when prompting for password encryption password

### ISSUE THREAD

**Issue by lightnin** [marius-wieschollek/passwords#360]
**Current Status**
Currently the prompt given to the user when attempting to unlock password vault looks like this on my instance:
![image](https://user-images.githubusercontent.com/1538027/111320556-63db4500-8667-11eb-9bcf-84cf78a09e93.png)

**Feature Description**
This should clearly prompt the user as to which password is required to avoid confusion with their user account password, which has a similar looking prompt. I suggest that the term "Vault password" conveys that the password is for the passwords 'vault,' which suggests a place where you keep important things, and seems like the best choice to me. This is superior to "Master password" which is ambiguous, and could refer to the user account password. I understand that "app" passwords are also in the space, so any solution should steer clear of those as well. Whatever is selected, the UI should be updated throughout the app to maintain consistency. 
The "Login" button should not say "Login" because that is not what this password does and Login adds to the confusion about what is happening and which password is required. Instead consider something like "unlock password vault."

**Comment by marius-wieschollek** [comment]
The term "Vault password" is also problematic. [Passman uses vaults, the passwords app doesn't.](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Feature-Comparison#features) Using that term would be misleading as we would suggest that we have a functionality that doesn't exist in the app.

From a technical point, the secret you enter in the passwords login screen has two uses.
1. It solves a challenge which proves to the server that you are in possession of the secret.
2. It decrypts the keychain which holds the actual keys used to encrypt your passwords, folders and tags.

I don't think we will be able to come up with any term that makes it clear to any user what password they need to enter here. 
I think it would be better to add a short clarification text atop the form to clearly specify what the user is doing here and what we're expecting from him.

Like:
> You're accessing the password database of **User Name**
> Please enter the encryption password and 2FA below.
> <ins>Check our handbook if you need help</ins>

Additionally we would have to 
- update wording for the login button, 
- the wording during the encryption process 
- the wording of any login related notification
- and the label of the autocreated password entry for the encryption password.
- We should also change the wording in the extension 
- and the third party apps.
- We should update the documentation for users to only use one clearly defined specific term for this password.
- We should also update the developer documentation to make it clear what term they have to use for this password.

In the end, the user needs to know what we want from him. It can be the Vault-, Encryption-, Master or SuperDuper-Password. As long as we are consistent with what we say, the term is a lot less important.

We could also adapt the browser extension to check if the url is the url of the passwords app and then only suggest that exact password - or none if it doesn't exist.

When i have time, i will make changes in the nightly releases and then we can see if that's going into the right direction.

**Comment by lightnin** [comment]
> In the end, the user needs to know what we want from him. It can be the Vault-, Encryption-, Master or SuperDuper-Password. As long as we are consistent with what we say, the term is a lot less important.
>
Agreed, with the small caveat that avoiding confusion with the main account password (or any other passwords they are likely to associate with their instance) is important.  For that reason I feel "Master" is not a good choice, and of the examples given above I like "encryption." SuperDuper is pretty good too. :)  
The prompt given above: "You're accessing the password database of User Name", while somewhat long, seems excellent. It's just tricky to see how that will translate to all the documentation where you might want a shorter way to say it. "Password database encryption password" is a bit long, although it is very clear. Perhaps "Password database encryption passphrase" is best because it will nudge the user in the right direction security wise, and is a bit more clear.
Thanks for your efforts making this software, and all the careful security work I can see went into it.
