### ISSUE TITLE
App causes server error page on docker image for Nextcloud 21 w/ PHP 7.4

### ISSUE THREAD

**Issue by killarny** [marius-wieschollek/passwords#362]
### System Information
**Server:**

Using the latest (at time of posting) tagged version of the nextcloud image at https://hub.docker.com/_/nextcloud

```json
{
    "version": {
        "server": "21.0.0.18",
        "app": "2021.3.0",
        "php": "7.4.16"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "legacyApi": {
        "enabled": 0,
        "used": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "random",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
 Browser and Version: Chrome 89.0.4389.82 64bit
 Client OS and Version: Windows 10 Home, version 21H1
```

### Steps to reproduce
1. Enable the Passwords app at /index.php/settings/apps
2. Navigate to /index.php/apps/passwords/ or most settings pages such as /settings/admin/overview
3. Observe the Internal Server Error page.
4. Disable the Passwords app.
5. Navigate to any previously broken settings pages such as /settings/admin/overview
6. Observe that the pages now render properly.

### Expected result
The app page should render, and the settings pages should render.

### Actual result
Internal Server Error page is rendered, along with a 500 error shown in the logs.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

Obtaining the Nextcloud log using the recommended method here is not possible, because settings pages will not load unless the app is disabled, which presumably renders the logs pointless. However, here's the relevant bit from `docker-compose log`:

```
app_1   | 192.168.16.1 - - [17/Mar/2021:20:58:37 +0000] "GET /index.php/settings/admin/overview HTTP/1.1" 500 5532 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
```

</details>

### Browser log
<details>
<summary>Browser log</summary>

```
index.js:46 No OC found
t.getLanguage @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
2globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
index.js:165 Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.i [as filePath] (index.js:165)
    at Module.<anonymous> (viewer.js:23)
    at o (bootstrap:63)
    at bootstrap:195
    at bootstrap:195
3globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
session-heartbeat.js:97 session heartbeat polling started
globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
pe @ globals.js:60
overview:1 Site cannot be installed: Page does not work offline. Starting in Chrome 93, the installability criteria is changing, and this site will not be installable. See https://goo.gle/improved-pwa-offline-detection for more information.
```
</details>

**Comment by marius-wieschollek** [comment]
I can't reproduce this. Using the latest Nextcloud docker image, i had no problems using the app.

> Obtaining the Nextcloud log using the recommended method here is not possible, because settings pages will not load unless the app is disabled, which presumably renders the logs pointless.

Nextcloud keeps the logs even if you disable the app. Please check for related errors.

**Comment by killarny** [comment]
I've changed nothing about my setup, except updating to the 2021.4.0 release of this app, and that appears to have fixed whatever was causing this for me.

Thank you for that, even if we couldn't nail down exactly what the problem was! I'll keep an eye on it if a problem crops up again in the future, and reopen/refile the issue.
