### ISSUE TITLE
Internal server error after changing password for Nextcloud account

### ISSUE THREAD

**Issue by CodeAlDente** [marius-wieschollek/passwords#363]
### System Information
**Server:**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

 Nextcloud Version: 20.0.4
 PHP Version: 7.4.13
 Database and Version: MySQL 10.3.28
 Server OS and Version: Linux 5.4.0-56-generic x86_64 (*) 
 Passwords Version: 2020.12.2

(*) managed by Hetzner; https://www.hetzner.com/storage/storage-share
```

**Client:**
```json
 Browser and Version: Mozilla Firefox 86.0.1 (64-Bit)
 Client OS and Version: Microsoft Windows 10 (64-Bit)
```

### Steps to reproduce
1. Login to Nextcloud
2. Change password for your Nextcloud account
3. Open Passwords (App)

### Expected result
You should be able to access Passwords (App) and see your passwords.

### Actual result
I'm getting an internal server error (500).

### Nextcloud log
There are no logs available.

### Browser log
It shows only error code 500. No further information given.

**Comment by marius-wieschollek** [comment]
I can confirm this. As a workaround, you can log out and log in.

**Comment by EpicJosch** [comment]
do you plan to fix this issue @marius-wieschollek ?

**Comment by EpicJosch** [comment]
When i change my password and then click on "Personal Settings" there is an Internal Server Error. In the logging i get this error:




Exception: Unable to verify user test2
/var/www/html/custom_apps/passwords/lib/Services/EnvironmentService.php - line 359:

OCA\Passwords\Services\EnvironmentService->loadUserInformation("test2", [ "OC\\AppFr ... "])

/var/www/html/custom_apps/passwords/lib/Services/EnvironmentService.php - line 185:

OCA\Passwords\Services\EnvironmentService->determineAppMode("test2", [ "OC\\AppFr ... "])

<<closure>>

OCA\Passwords\Services\EnvironmentService->__construct("test2", [ "OC\\AllConfig"], [ "OC\\AppFr ... "], [ "OC\\Sessi ... "], [ "OCA\\Pass ... "], [ "OC\\Authe ... "], [ "OC\\User\\Session"], [ "OC\\User\\Manager"])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 116:

ReflectionClass->newInstanceArgs([ "test2",[ ... "])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 124:

OC\AppFramework\Utility\SimpleContainer->buildClass([ "Reflectio ... "])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 142:

OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwo ... e")

/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 493:

OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwo ... e")

/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwo ... e")

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 97:

OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwo ... e", true)

<<closure>>

OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 116:

array_map([ "Closure"], [ "*** sensi ... "])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 124:

OC\AppFramework\Utility\SimpleContainer->buildClass([ "Reflectio ... "])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 142:

OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwo ... e")

/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 493:

OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwo ... e")

/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 465:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwo ... e")

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 97:

OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwo ... e", true)

<<closure>>

OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 116:

array_map([ "Closure"], [ [ "Reflect ... ]])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 124:

OC\AppFramework\Utility\SimpleContainer->buildClass([ "Reflectio ... "])

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 142:

OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwo ... s")

/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 493:

OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwo ... s")

/var/www/html/lib/private/ServerContainer.php - line 155:

OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwo ... s")

/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 65:

OC\ServerContainer->query("OCA\\Passwo ... s")

/var/www/html/lib/private/Settings/Manager.php - line 205:

OC\AppFramework\Utility\SimpleContainer->get("OCA\\Passwo ... s")

/var/www/html/lib/private/Settings/Manager.php - line 363:

OC\Settings\Manager->getSettings("admin", "overview", [ "Closure"])

/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php - line 86:

OC\Settings\Manager->getAllowedAdminSettings("overview", [ "OC\\User\\User"])

/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php - line 117:

OCA\Settings\Controller\PersonalSettingsController->formatSections([ [ [ "OCA\\ ... "], "personal-info", "admin", "personal")

/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php - line 67:

OCA\Settings\Controller\PersonalSettingsController->formatAdminSections("personal", "personal-info")

/var/www/html/apps/settings/lib/Controller/CommonSettingsTrait.php - line 148:

OCA\Settings\Controller\PersonalSettingsController->getNavigationParameters("personal", "personal-info")

/var/www/html/apps/settings/lib/Controller/PersonalSettingsController.php - line 64:

OCA\Settings\Controller\PersonalSettingsController->getIndexResponse("personal", "personal-info")

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 230:

OCA\Settings\Controller\PersonalSettingsController->index("personal-info")

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 137:

OC\AppFramework\Http\Dispatcher->executeController([ "OCA\\Sett ... "], "index")

/var/www/html/lib/private/AppFramework/App.php - line 183:

OC\AppFramework\Http\Dispatcher->dispatch([ "OCA\\Sett ... "], "index")

/var/www/html/lib/private/Route/Router.php - line 315:

OC\AppFramework\App::main("OCA\\Settin ... r", "index", [ "OC\\AppFr ... "], [ "personal- ... "])

/var/www/html/lib/base.php - line 1060:

OC\Route\Router->match("/settings/user")

/var/www/html/index.php - line 36:

OC::handleRequest()

**Comment by marius-wieschollek** [comment]
This should be fixed with the latest update
