### ISSUE TITLE
allow offline use

### ISSUE THREAD

**Issue by meonkeys** [marius-wieschollek/passwords#367]
**Current Status**

Passwords app requires a connection to the Nextcloud server.

**Feature Description**

Use localstorage or some other mechanism to cache a locally-encrypted copy of the passwords for offline use.

**Additional context**

This is a common feature with other password managers.

**Comment by meonkeys** [comment]
See also: https://github.com/marius-wieschollek/passwords-webextension/issues/162

**Comment by marius-wieschollek** [comment]
The webapp shouldn't permanently store passwords on your browser, that is a security risk. If you want to use the passwords offline, checkout the apps,
