### ISSUE TITLE
Protect browser extension access with PIN/password

### ISSUE THREAD

**Issue by squintarelli** [marius-wieschollek/passwords#368]
**Current Status**
once you install the browser extension (I use firefox) and connect to your server account, all passwords are directly accessible to anyone gaining access to the browser

**Feature Description**
the password extension shoud be protected from casual access by someone with access to the browser.

for example it could have an option to provide for a PIN/password to access to the passwords list.
if enabled, there should be options for logging out when the browser i closed or after a specific time.

alternatively, the extension could log in/out if the user is/isn't logged in to their nextcloud server in the current browser (logging in/out of nextcloud server in the current browser enables/disaables the extension functionality)

**Comment by marius-wieschollek** [comment]
See #80
