### ISSUE TITLE
Edit password record from extension

### ISSUE THREAD

**Issue by squintarelli** [marius-wieschollek/passwords#369]
Usability improvement

**Current Status**
in several occasions I have notes associated to the password that I need to read (instructions, reminders, etc) when I am n a site.
similarly, sometimes I need to manually edit the password's record data
I now have to browse  to nextcloud server's password app, search again for the specific password and edit.

**Feature Description**
ctrl-clicking a password in the extension opens a dialog to edit  the password's record content (eventually opening the "edit password" dialog on nextcloud server

**Comment by marius-wieschollek** [comment]
Wrong repository and being implemented here: https://github.com/marius-wieschollek/passwords-webextension/pull/167
