### ISSUE TITLE
open external application and handover of User / Password / additional Parameter

### ISSUE THREAD

**Issue by w-olle** [marius-wieschollek/passwords#370]
**Current Status**
Availability to setup Links (HTTP/HTTPS/SSH).
On OS level for SSH, I'm already able to define a default App. to open (e.g. Putty). 
The complete link will be handed over which Putty is not able to manage because of the SSH prefix.

**Feature Description**
To be able to define about 5 different types of external link.
To hand over additional parameter, as well as Address, Username & Password
To add new settings to define the parameters per external link:
(This is an example just for Putty to show how this parameter could be defined by the end user):
`c:/program files/putty/putty.exe %URL% -l %USERNAME% -pw %PASSWORD% -ssh`

**Additional context**
not now

**Comment by marius-wieschollek** [comment]
There is no supported way to open external programs from within the browser. Maybe any of the third party desktop apps can add support for this, but i can't.
I would also like to point out that this is a big security risk. Someone could share a password with you that executes malicious code when the link is clicked.
