### ISSUE TITLE
Cannot find existing credentials

### ISSUE THREAD

**Issue by fluxx147** [marius-wieschollek/passwords#371]
Certainly not a bug but inexplicable for me.

I haven't added a password for a while. Now when I add credentials for a new website, everything is ok. 
The browser extension also "knows" this password. 
However, I cannot find this credentials in the Nextcloud-Passwords web interface.

Searching the credentials in the browser extension I found a folder called "Private Passwords", but I never created it. 
These folder contains the credentials i was looking for. Where does this folder come from and why can't I find it in the web interface?

I also cannot edit or delete the credentials in this folder.

Can anyone help me?

**Comment by marius-wieschollek** [comment]
[If you have a question, please use one of the options for questions and help on the new issue page and don't open a bug report.](https://github.com/marius-wieschollek/passwords/issues/new/choose)
