### ISSUE TITLE
Set a new owner for a password (change ownership)

### ISSUE THREAD

**Issue by CodeAlDente** [marius-wieschollek/passwords#375]
**Current Status**
Currently you can **only share** a single password with someone else.

**Feature Description**
It would be great to actually change the ownership of a password - or even of a whole folder - to someone else. This is very useful if you create logins for customers for e.g. WordPress websites. Instead of leaking the password via email you can just "hand over" the password via Nextcloud.

**Additional context**
There is already a ticket dealing with this (#294) but it has been closed.

**Comment by ghost** [comment]
Yes, Please! its important.

**Comment by Walsonde** [comment]
I'd like that very much, too. Pretty please.

**Comment by admorgan** [comment]
+1
