### ISSUE TITLE
Update QR Code on Share tab to not default to an autogenerated password qrcode

### ISSUE THREAD

**Issue by darkesthour111** [marius-wieschollek/passwords#376]
**Current Status**
When accessing the share menu for an item the QR Code tab will default to showing a QR code for the password.

**Feature Description**
One of the following options should be taken:
1. The default should be updated to only generate the qrcode upon another button press
2. Update the default to be the website qrcode

**Additional context**
This is to reduce a potential risk factor, if someone happened to be recording your screen while using the feature (such as via security cameras inside of businesses) would have access to one of your passwords.

**Comment by marius-wieschollek** [comment]
![grafik](https://user-images.githubusercontent.com/8255857/114269436-57989c80-9a07-11eb-9d9b-14b2471c2f83.png)

I will add a warning message with the next release.

**Comment by darkesthour111** [comment]
Saw it in the latest release, this is great!
