### ISSUE TITLE
Source code repository is not accessible by IPv6

### ISSUE THREAD

**Issue by toxadx** [marius-wieschollek/passwords#377]
Source code is not accessible by IPv6.
The issue raises on IPv6-only servers. The server tries to download source code from https://git.mdns.eu/nextcloud/passwords/-/jobs/12073/artifacts/raw/passwords.tar.gz
git.mdns.eu resolves to 2003:c1:9f04:5300:e1f2:64f:4e46:e612 but the address is not accessible (no ICMP6 replies, ports closed).

This might be server misconfiguration. If the server should not be accessible via IPv6, then perhaps it is worth removing the AAAA entry so that the server becomes accessible via dns64

**Comment by marius-wieschollek** [comment]
I couldn't figure out what the issue with IPv6 is, so i removed the AAAA entry

**Comment by toxadx** [comment]
Thanks. That helped
