### ISSUE TITLE
Make passwords an official nextcloud app!

### ISSUE THREAD

**Issue by mokkin** [marius-wieschollek/passwords#379]
I don't know if this is the right place, but since a couple of years I am very happy unsing password - so first of all: Thank you very much for your work @marius-wieschollek ! :+1: 

As password is continuously developed over the years and has in my point of view a good quality, it should become an official nextcloud app. Official apps have more trust for new users and maintenance should be distributed on more shoulders.

![grafik](https://user-images.githubusercontent.com/2938748/115234537-6f63d500-a119-11eb-81a2-4b4aa0a0bfc8.png)

**Comment by marius-wieschollek** [comment]
I have honestly no clue how apps become a "featured" app. The only explanation what this tag actually means is a short sentence in the [documentation](https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html).

> Those apps are supported and developed by Nextcloud GmbH directly and have an Featured-tag

So the the "featured" tag looks to me like a tag for the apps that the company behind NC offers commercial support, not something that is open to the community.
