### ISSUE TITLE
2018.4.0 breaks app

### ISSUE THREAD

**Issue by nextgen-networks** [marius-wieschollek/passwords#38]
After upgrading from 2018.3.0 to 2018.4.0 app crashes with errors.

### System Information
- Nextcloud Version: 13.0.1
- PHP Version: 7.1.16
- DB-Version: MySQL 5.7.21
- Passwords Version: 2018.4.0
- Browser and Version: Chrome 66.0.3359.117 / Microsoft Edge 42.17133.1.0
- Client OS and Version: Microsoft Windows 10 Pro 1709 and 1803
- Server OS and Version: Ubuntu 16.04.4 LTS‬

### Steps to reproduce
open Passwords app

### Actual result

app does not load creates an error

> Interner Serverfehler
> Der Server konnte die Anfrage nicht fertig stellen.
> 
> Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.
> 
> Weitere Details können im Server-Protokoll gefunden werden.
> 
> Technische Details
> Entfernte Adresse: 217.xxx.xxx.xxx
> Anfragekennung: Wty36E4fQbwAACB8L2gAAAAH

Error-Log in backend displays message as follows:

> Error	index	ParseError: syntax error, unexpected end of file
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/private/Template/Base.php - line 151: OC\Template\Base->load('/var/www/REPLACED_FILE-FOLDER_LOCATION...', NULL)
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/private/legacy/template.php - line 204: OC\Template\Base->fetchPage(NULL)
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/public/AppFramework/Http/TemplateResponse.php - line 157: OC_Template->fetchPage()
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/private/AppFramework/Http/Dispatcher.php - line 114: OCP\AppFramework\Http\TemplateResponse->render()
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Passwords\Controller\PageController), 'index')
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Passwords\\C...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
> [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
> /var/www/REPLACED_FILE-FOLDER_LOCATION/lib/base.php - line 998: OC\Route\Router->match('/apps/passwords...')
> /var/www/REPLACED_FILE-FOLDER_LOCATION/index.php - line 37: OC handleRequest()
> {main}
> 2018-04-22T18:27:21+0200

Passwords settings in backend displays error message as follows:

> t('PHP %s is no longer supported.', [PHP_VERSION])); ?> t('Please check the system requirements.')); ?>
> t('Passwords requires HTTPS.')); ?> t('Please check the system requirements.')); ?>

### Expected result
app should show stored password entries

**Comment by marius-wieschollek** [comment]
Yes, i can confirm that. The app store build is currently broken.

**Comment by marius-wieschollek** [comment]
Version 2018.4.1 should fix the issue.

**Comment by nextgen-networks** [comment]
Working! Thanks for your fast fix!
