### ISSUE TITLE
Passwords shell client

### ISSUE THREAD

**Issue by ntrp** [marius-wieschollek/passwords#382]
**Current Status**
I see there is a javascript client but I cannot find anywhere a shell cli application which wraps the js client and makes it easy to use in a shell

**Feature Description**
The cli application can use a framework like oclif to implement all the commands
Some important features would be:
- encrypted local caching (for example with GnuPG)
- select the output of the match to be any of the fields
- matching of the password entry on any field

**Additional context**
Something similar to the 1pass console client https://github.com/robertknight/1pass

**Comment by marius-wieschollek** [comment]
Creating new client applications is out of scope for this repository and would be better discussed in the forum.
Most apps for the passwords app are built by other developers who use the api to access the app.

If you look around, there seems to be this client: https://github.com/traxys/nextpass , but it's not listed in the app and i don't know what the status of the project is.

**Comment by ntrp** [comment]
Ok clear, thanks for the response
