### ISSUE TITLE
Website and Folder field not visible in Nextcloud detail panel

### ISSUE THREAD

**Issue by fabionatali** [marius-wieschollek/passwords#386]
# System Information

## Server

- Nextcloud Version: 19.0.7
- PHP Version: 7.3.14
- Database and Version: mysql 10.2.27
- Server OS and Version: Linux 5.4.0-60-generic x86_64
- Passwords Version: 2020.12.3

## Client

- Browser and Version: Firefox 88.0.1
- Client OS and Version: GNU/Linux

# Steps to reproduce

1. Access my Nextcloud account via the web user interface
2. Access the Passwords app within Nextcloud
3. Access the detail panel of an existing password (pick a password from the list, click on the "dots" icon to access the drop down menu, select "Details")
4. The content of some fields (e.g. Website and Folder) is not visible

Apparently it is possible to fix the issue by commenting out the following section in the page CSS.

```css
#app.passwords a.link {
    color: var(--color-primary);
}
```

## Expected result

It should be possible to see all fields of the detail panel (with the exception of the password field, of course, which is obfuscated).

## Actual result

Some fields (namely, Website and Folder) are not visible. Please note that the fields are populated, it is just that they are not visible. It is possible to make them show up by tweaking the CSS, e.g. via the browser's developer tools.

**Comment by fabionatali** [comment]
The Passwords handbook (when accessed from my Nextcloud web interface) also seems to be affected by a similar CSS issue.

All the handbook links show up the same colour as the background, therefore they are completely invisible. This also seems to be related to `color: var(--color-primary);` in the CSS.

Any chance this might be a problem with my Nextcloud theme?

**Comment by marius-wieschollek** [comment]
The app generally assumes that the css variables `--color-primary` and `--color-primary-element` have a good contrast with `--color-main-background`. If that is not the case, elements using the color will not be visible.

**Comment by fabionatali** [comment]
I see, that makes sense. Thanks for your swift reply. I'll try and sort things out on the CSS side of things of my installation. I think this can be safely closed.
