### ISSUE TITLE
Support PHP 7.3

### ISSUE THREAD

**Issue by Kixunil** [marius-wieschollek/passwords#389]
**Current Status**
*According to the manifest*, `passwords` supports PHP 7.4. This is unfortunate because the last reviewed and packaged version in Debian stable is 7.3. As a result one has to either override Debian package risking breakages, incompatibility and possibly other problems and has to somehow figure out root of trust for newer PHP version or avoid using `passwords`. I'm not familiar with PHP, so I'm not sure how hard would it be to support one version older.

**Feature Description**
Support older PHP version. I didn't dare to try if it *actually* doesn't work with older version yet. If it does, then just fix the manifest.

**Comment by marius-wieschollek** [comment]
The source code does not support PHP 7.3, but there is an automated conversion of the app for PHP 7.3 (and 7.2 in the future). If you're installing from the app store in Nextcloud, it should offer the version 2021.6.*10* to you which will work. If you're using an older system (NC < 20 or PHP < 7.3) you can also use 2020.12.4 which does not offer the latest features, but got the latest bugfixes until the EOL of NC 19 this month.

See https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#lsrlegacy-support-releases for information about the automatic PHP 7.3 build.

Additionally for PHP upgrades there is a [section in the admin manual](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/System-Requirements#php-requirements) with guides and link to the most compatible package archive.

**Comment by marius-wieschollek** [comment]
I guess this issue is solved.
