### ISSUE TITLE
Cant restore Backup after update to 2021.7.21

### ISSUE THREAD

**Issue by schnello** [marius-wieschollek/passwords#396]
Nextcloud 21.0.3 stable

After update to 2021.7.21 no passwords are shown:
![image](https://user-images.githubusercontent.com/6481341/124429523-45ac6880-dd6e-11eb-82f2-74163c087066.png)

Try to restore a backup fails with this error message:
![image](https://user-images.githubusercontent.com/6481341/124429612-64126400-dd6e-11eb-9d99-9f345cd50084.png)

**Comment by marius-wieschollek** [comment]
Can you check if these tables are there:
```
'passwords_entity_challenge'        
'passwords_entity_folder'           
'passwords_entity_folder_revision'  
'passwords_entity_keychain'         
'passwords_entity_password'         
'passwords_entity_password_revision'
'passwords_entity_registration'     
'passwords_entity_session'          
'passwords_entity_share'            
'passwords_entity_tag'              
'passwords_entity_tag_revision'     
'passwords_relation_password_tag'   
```

**Comment by schnello** [comment]
hi.

I checked the tabels and my output is:
![image](https://user-images.githubusercontent.com/6481341/124437194-1e0dce00-dd77-11eb-9a21-04f33ea40baf.png)

So what i see... all is available.

Greetings

**Comment by marius-wieschollek** [comment]
That looks like another issue like #395 where the migration was incompletely executed.

**Comment by schnello** [comment]
Do you have any recommendations how I should proceed here?

**Comment by schnello** [comment]
Solved my issue. I restore the full database, upgrade NC to 22 .... and rename the tabels manualy to:
            'passwords_entity_challenge'         => 'passwords_challenge',
            'passwords_entity_folder'            => 'passwords_folder',
            'passwords_entity_folder_revision'   => 'passwords_folder_rv',
            'passwords_entity_keychain'          => 'passwords_keychain',
            'passwords_entity_password'          => 'passwords_password',
            'passwords_entity_password_revision' => 'passwords_password_rv',
            'passwords_entity_registration'      => 'passwords_pw_tag_rel',
            'passwords_entity_session'           => 'passwords_registration',
            'passwords_entity_share'             => 'passwords_session',
            'passwords_entity_tag'               => 'passwords_share',
            'passwords_entity_tag_revision'      => 'passwords_tag',
            'passwords_relation_password_tag'    => 'passwords_tag_rv'
