### ISSUE TITLE
Edit times should only change when password is changed

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#4]
Currently the behaviour is the edit time changes regardless of the data changed, it should only reflect the modification time of the password (and possibly the username).

**Comment by marius-wieschollek** [comment]
This change will be in the next Alpha. After upgrading, you can use the following SQL to initially fill the fields in the database.
```
UPDATE `oc_passwords_entity_password_revision` SET `edited`=`updated`;
UPDATE `oc_passwords_entity_folder_revision` SET `edited`=`updated`;
UPDATE `oc_passwords_entity_tag_revision` SET `edited`=`updated`;
```

**Comment by marius-wieschollek** [comment]
[Those who come here from the Owncloud Forums click here for all about the original Owncloud Passwords App](https://github.com/marius-wieschollek/passwords-legacy/issues/4#issuecomment-321309895).

Alternatively you can [migrate to Nextcloud](https://docs.nextcloud.com/server/14/admin_manual/maintenance/migrating_owncloud.html?highlight=owncloud#) and then install [Passwords](https://apps.nextcloud.com/apps/passwords) and use the [legacy migration to import your passwords](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Legacy-Migration).
