### ISSUE TITLE
Sharing Broken in V4.0

### ISSUE THREAD

**Issue by mikshepard** [marius-wieschollek/passwords#40]
### System Information
- Nextcloud Version: 13.0.1
- PHP Version: 7.1.16
- MySQL Version: 5.7.22
- Passwords Version: 2018-V4.0
- Browser and Version: Chrome
- Server OS and Version: Debian Jessie, kernel 4.14.36

### Steps to reproduce

    Create password, attempt to share with another user, select username from autocomplete.

### Actual result

    Error shows up on top of Nextcloud window, stating: "Unable to share password: Invalid receiver uid"

### Expected result

    Username should show up in Shared list.

### Other info

    I am using LDAP users.  Sharing worked fine on previous version of Password 2018-v3.0

### Log Output:

> {"reqId":"095ukOijSl9Mn83Nnfky","level":3,"time":"2018-04-26T13:14:34-05:00","remoteAddr":"X.X.X.X","user":"bob","app":"passwords","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/share\/create","message":"Exception: {\"Exception\":\"OCA\\\\Passwords\\\\Exception\\\\ApiException\",\"Message\":\"Invalid receiver uid\",\"Code\":256,\"Trace\":\"#0 [internal function]: OCA\\\\Passwords\\\\Controller\\\\Api\\\\ShareApiController->create('c0e9d810-0544-4...', 'alice', 'user', NULL, false, true)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\ShareApiController), 'create')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passwords\\\\Controller\\\\Api\\\\ShareApiController), 'create')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ShareApiControl...', 'create', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/passwords...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/index.php(37): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/passwords\\\/lib\\\/Controller\\\/Api\\\/ShareApiController.php\",\"Line\":199}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.183 Safari\/537.36 Vivaldi\/1.96.1147.32","version":"13.0.1.1"}

**Comment by marius-wieschollek** [comment]
I can confirm this, you can currently not share Passwords with other LDAP users

**Comment by marius-wieschollek** [comment]
[Nightly Build 2018.4.2-build2180](https://apps.nextcloud.com/apps/passwords/releases) should fix the issue.

**Comment by mikshepard** [comment]
Confirmed, working great now.  Thanks for the quick fix!!

**Comment by marius-wieschollek** [comment]
Fix has been released with 2018.4.2
