### ISSUE TITLE
Error restoring from Backup in 2021.7.22

### ISSUE THREAD

**Issue by darkernoise** [marius-wieschollek/passwords#402]
I have spent days trying to recover from the complete loss of all passwords in the Passwords application.  Here is where my server is:

- Rolled back to nextcloud 21.0.3 from 22.x
- restored database from a backup
- installed Passwords 2021.4.0 from https://git.mdns.eu/nextcloud/passwords/-/archive/2021.4.0/passwords-2021.4.0.zip 
- ./occ app:enable passwords
- ./occ app:update passwords

The above finally worked in that the conversion to 2021.7.22 seems to have worked this time. Great so far.  Next, I attempted to restore the Passwords from a prior backup, but get the error:

Restoring backup ...
In AbstractEntity.php line 86:
                                 
  pwid is not a valid attribute  
                                 
passwords:backup:restore [-u|--user [USER]] [--no-data] [--no-user-settings] [--no-app-settings] [--] <backup>

Tables in the database at this point are:

oc_passwords
oc_passwords_categories
oc_passwords_challenge
oc_passwords_entity_challenge
oc_passwords_entity_folder
oc_passwords_entity_folder_revision
oc_passwords_entity_keychain
oc_passwords_entity_password
oc_passwords_entity_password_revision
oc_passwords_entity_registration
oc_passwords_entity_session
oc_passwords_entity_share
oc_passwords_entity_tag
oc_passwords_entity_tag_revision
oc_passwords_folder
oc_passwords_folder_rv
oc_passwords_keychain
oc_passwords_password
oc_passwords_password_rv
oc_passwords_pw_tag_rel
oc_passwords_registration
oc_passwords_relation_password_tag
oc_passwords_session
oc_passwords_share
oc_passwords_tag
oc_passwords_tag_rv

I have checked the log and do not see anything specific to this error.  Any suggestions as to how to recover the backups?

### System Information
Server: 21.0.3 Docker Image

 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below:

www-data@74e9ee579ef5:~/html$ ./occ passwords:system:report debug

In AbstractEntity.php line 86:
                                 
  pwid is not a valid attribute  
                                 

passwords:system:report [-b|--basic] [--] [<sections>...]

 Nextcloud Version:
 PHP Version: 7.4.21
 Database and Version: 10.5.11
 Server OS and Version: Official Nextcloud docker image
 Passwords Version: 2021.7.22

### Steps to reproduce
1. ./occ passwords:backup:restore 2021-07-06_04-22-12

### Expected result
What should happen? : Restore should complete

### Actual result
What does happen? Error: pwid is not a valid attribute  

### Nextcloud log
No error present in the log.

**Comment by marius-wieschollek** [comment]
I do not remember ever using an attribute called `pwid`, but i added it to the exclude list with 2021.7.3. Does this fix the issue?

**Comment by darkernoise** [comment]
Thank you Marius!  Yes, I think that will correct the issue.  I was able to complete the recovery by remarking the exception on AbstractEntity.php line 86, essentially skipping the pwid attribute as you have done.
