### ISSUE TITLE
Lost all my passwords

### ISSUE THREAD

**Issue by Byter3** [marius-wieschollek/passwords#405]
Hi there I just realized I lost all my passwords sometime in the past. Maybe wehen uprgaded from NC 20 to NC 21. That is preatty devesting for me. I can't say any further details since I'm not aware when this happened, I already save one new password into it and that is the only one password now. So I have no idea when this happened, but I'm in deep troulble now. I'm using an univention appliance.

**Comment by marius-wieschollek** [comment]
Check the app backups: https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Backups

**Comment by Adphi** [comment]
I got the same issue, all my passwords are gone during Nextcloud upgrade to NC21.
After having taken a look at the database, they are all still there, but in the `oc_passwords_entity_password`, not in `oc_passwords_password`.

Maybe I missed something during the upgrade about a database migration...

**Comment by DecaTec** [comment]
Have you tried the commands from that comment? https://github.com/marius-wieschollek/passwords/issues/395#issuecomment-881699576
