### ISSUE TITLE
Ansible integration update

### ISSUE THREAD

**Issue by markuman** [marius-wieschollek/passwords#406]
Just a follow up of #307 

Since collection version 7.0.0 of `markuman.nextcloud` it can does many more than just use it as a password store (lookup plugin).    
It can also create, update and delete passwords. So it is possible to use it for an entire password rotation of your infrastructure managed by ansible.   
Is can also just fetch auto-generated passwords from nextcloud passwords.

https://galaxy.ansible.com/markuman/nextcloud

**Comment by marius-wieschollek** [comment]
Good to know. i updated the description in the apps & extensions  section to mention this.

Also i have seen that you have a ticket to add e2e. Should you implement it, give me a notice so i can add the badge for that.
