### ISSUE TITLE
Add option to disable sharing with admin accounts

### ISSUE THREAD

**Issue by basti1982** [marius-wieschollek/passwords#408]
Currently admin users show up in the sharing dialog. In my case, the admin user is only used for configuring the Nextcloud. 

Some of the users are confused when the admin account is shown in the sharing dialog. It would be great if there was an option on the Passwords configuration page in the Nextcloud Admin section to disable sharing to admins.

Screenshot:
![2021-07-23_16-33](https://user-images.githubusercontent.com/38282605/126799157-c699b620-5dc1-4bdb-93b6-ad84628fcfce.png)

**Comment by marius-wieschollek** [comment]
I'm not aware of any such option for normal NC file sharing.

I would recommend putting users and admins in different groups and then only allowing users to share within their group.
