### ISSUE TITLE
Sharing passwords stays in a loading state. User don't receive shared passwords.

### ISSUE THREAD

**Issue by Der-Alex** [marius-wieschollek/passwords#41]
### System Information
- Nextcloud Version: 13.0.2
- PHP Version: 7.2.4
- Passwords Version: 2018.4.2
- Browser and Version: chrome 66.0.3359.139
- Client OS and Version: win 10 home x64
- Server OS and Version: ubuntu 16.04

### Steps to reproduce
1. Tell us how to reproduce your issue.

- Install and activate the passwords app
- Create a new password
- Share password with another user

2. Provide sample data if needed
3. Include relevant user settings and app settings if not standard

### Actual result
What does happen?
- On the share screen there is a loading indicator circle, that moves around the user avatar i wanted to share the password with
- Hovering over the avatar shows a tooltip message that there is data that has to be synced.
- The browser dev tool shows a loading information in the dom
- That state stays, no matter what i do (except removing the share or deleting the password)
- The user who should get the shared password, cannot see it / doesn't receive it
- Unfortunately i don't find any related message in the nexcloud log or the webserver access / error logs... 
If i can help inspecting the issue any further, please tell me where i should search. 

### Expected result
What should happen?
- After sharing the password, there should be a notice, that the password has been shared successfully
- The user should receive the shared password
- The user should get informed about a new shared password

**Comment by marius-wieschollek** [comment]
Have you consulted the manual? "More" > "Handbook" > "F.A.Q" > Sharing or [here](https://github.com/marius-wieschollek/passwords/wiki/F.A.Q#sharing). Sharing will be completed once the Nextcloud cron job was executed.

**Comment by Der-Alex** [comment]
Hi Marius, 
thanks for your reply. I will check that. But all the passwords I tried to share today, haven't been shared for 4 hours now. 

I found a Error Message: 
`
Error while running background job (Exception): User key requested with illegal user id: xx
OCA\Passwords\Cron\SynchronizeShares ):
.../apps/passwords/lib/Encryption/SseV1Encryption.php - line 163: OCA\Passwords\Encryption\SseV1Encryption->getUserKey('xx')
.../apps/passwords/lib/Encryption/SseV1Encryption.php - line 99: OCA\Passwords\Encryption\SseV1Encryption->getEncryptionKey('xxxxxxx', 'xx')
.../apps/passwords/lib/Services/EncryptionService.php - line 74: OCA\Passwords\Encryption\SseV1Encryption->encryptObject(Object(OCA\Passwords\Db\PasswordRevision))
.../apps/passwords/lib/Services/Object/AbstractRevisionService.php - line 125: OCA\Passwords\Services\EncryptionService->encrypt(*** sensitive parameters replaced ***)
.../apps/passwords/lib/Cron/SynchronizeShares.php - line 194: OCA\Passwords\Services\Object\AbstractRevisionService->save(Object(OCA\Passwords\Db\PasswordRevision))
.../apps/passwords/lib/Cron/SynchronizeShares.php - line 107: OCA\Passwords\Cron\SynchronizeShares->createNewShares()
.../lib/private/BackgroundJob/Job.php - line 61: OCA\Passwords\Cron\SynchronizeShares->run(NULL)
.../lib/private/BackgroundJob/TimedJob.php - line 55: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
.../cron.php - line 146: OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
{main}
`

**Comment by marius-wieschollek** [comment]
How are background jobs executed on your server? Cron or HTTP?

**Comment by Der-Alex** [comment]
Ajax, atm. I will try the other two and give you another feedback.

**Comment by marius-wieschollek** [comment]
Take a look at the documentation when trying it: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/background_jobs_configuration.html.

I will check if i can reproduce the error

**Comment by marius-wieschollek** [comment]
I will check if that is possible later, but for the next version (and the nightly) there will simply be a warning when you use ajax.

**Comment by marius-wieschollek** [comment]
The reason why ajax cron jobs and also app updates over the Nextcloud web ui do not work is that Nextcloud is very inconsistent in how it handles the user session regarding these actions. If you run a command or cron job from the command line there is no user id available. But if a cron job is run via ajax, the user id and session of the current user are being used.
Passwords just checks if a user id is present and if that is the case every sql statement etc. has to contain that user id. This way it is ensured that no user can accidentally access the data of someone else.
Since Nextcloud does not have a way to check if it is running as cronjob, i have now added an environment layer which detects if the app is executed in the context of a cron job.

The nightly build [2018.6.0-build2264](https://apps.nextcloud.com/apps/passwords/releases) contains this change and ajax cron jobs should now work. The warning in the admin ui is still there because this is experimental.

**Comment by danielschubert** [comment]
I have this Problem still with
- Version 2018.11.1
- Nextcloud 14.0.3

**Comment by marius-wieschollek** [comment]
@danielschubert This ticket is solved. Please read the [F.A.Q](https://git.mdns.eu/nextcloud/passwords/wikis/Users/F.A.Q#sharing) about sharing, check the [admin notes](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Administrator-Notes#sharing-passwords) and if this does not solve your problem, please create a new issue.
