### ISSUE TITLE
Icon issues in sidebar

### ISSUE THREAD

**Issue by hellojaccc** [marius-wieschollek/passwords#419]
### System Information
**Server:server":Debian 10**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

 Nextcloud Version:22.1.0.1
 PHP Version:8.0.9
 Database and Version:mariadb 10.3.29-0
 Server OS and Version:Debian 10
 Passwords Version:2021.7.23
```

**Client:**
```
 Browser and Version:Chrome 92 / Also tried on firefox same issue
 Client OS and Version: Linux kernel 5.13
```

### Steps to reproduce
1. 
- Go to nextcloud passwords app 
- Look at sidebar(dont know what it called)
2. 
![Screenshot_20210810_093044](https://user-images.githubusercontent.com/71537512/128790773-915a08d6-9a81-4fcc-ba54-c379d5fc460f.png)
3. 
Even tried completely reinstalling nextcloud
### Expected result
What should happen?
Show proper sidebar with icons
### Actual result
What does happen?
Showed sidebar with blue dots instead of icons
### Nextcloud log
<details>
{"reqId":"o4uhx7cv9WibMq158xtc","level":2,"time":"2021-08-10T00:14:39+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"PROPFIND","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":""}
{"reqId":"o4uhx7cv9WibMq158xtc","level":2,"time":"2021-08-10T00:14:39+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"PROPFIND","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":""}
{"reqId":"wb0DLf3T4qSD2Ft6EOrC","level":2,"time":"2021-08-10T00:14:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"wb0DLf3T4qSD2Ft6EOrC","level":2,"time":"2021-08-10T00:14:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"mKc7awYPQa3RvYFIZLHD","level":2,"time":"2021-08-10T00:14:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"mKc7awYPQa3RvYFIZLHD","level":2,"time":"2021-08-10T00:14:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"BoRUrFWdbPYvPr7tHykf","level":2,"time":"2021-08-10T00:15:41+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"PROPFIND","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":""}
{"reqId":"BoRUrFWdbPYvPr7tHykf","level":2,"time":"2021-08-10T00:15:41+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"PROPFIND","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":""}
{"reqId":"ONyn0e5I6HEmQUZ0iF8G","level":2,"time":"2021-08-10T00:15:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"ONyn0e5I6HEmQUZ0iF8G","level":2,"time":"2021-08-10T00:15:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"DGy9MIXaGkxRnAe8WHMv","level":2,"time":"2021-08-10T00:15:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"DGy9MIXaGkxRnAe8WHMv","level":2,"time":"2021-08-10T00:15:44+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"jWwgRgZBNVZUawn9HGBW","level":2,"time":"2021-08-10T00:16:34+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"jWwgRgZBNVZUawn9HGBW","level":2,"time":"2021-08-10T00:16:34+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"NUJ99nVS6WpYLByLMzzH","level":2,"time":"2021-08-10T00:16:38+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/photos/service-worker.js","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"NUJ99nVS6WpYLByLMzzH","level":2,"time":"2021-08-10T00:16:38+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/photos/service-worker.js","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"JozqMcFjabM84jF9lenz","level":2,"time":"2021-08-10T00:16:42+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"PROPFIND","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":""}
{"reqId":"JozqMcFjabM84jF9lenz","level":2,"time":"2021-08-10T00:16:42+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"PROPFIND","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":""}
{"reqId":"EYWhPoaYmPpJHYe8jFc5","level":2,"time":"2021-08-10T00:16:43+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"EYWhPoaYmPpJHYe8jFc5","level":2,"time":"2021-08-10T00:16:43+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"LayKgS1wK9AXQmkNnfgj","level":2,"time":"2021-08-10T00:16:43+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"LayKgS1wK9AXQmkNnfgj","level":2,"time":"2021-08-10T00:16:43+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"emMchL1H5AqOm20ZL7ZY","level":2,"time":"2021-08-10T00:17:14+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"emMchL1H5AqOm20ZL7ZY","level":2,"time":"2021-08-10T00:17:14+00:00","remoteAddr":"MYIP","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":""}
{"reqId":"FN7hFe4iQSOTUwk1rl1c","level":3,"time":"2021-08-10T00:20:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Not installed","userAgent":"--","version":"22.1.0.1","exception":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/base.php","line":649,"function":"checkInstalled","class":"OC","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1083,"function":"init","class":"OC","type":"::"},{"file":"/var/www/html/nextcloud/cron.php","line":42,"args":["/var/www/html/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/base.php","Line":277,"CustomMessage":"--"}}
{"reqId":"gBYpQEsrAcuLdzp4oceL","level":2,"time":"2021-08-10T00:21:45+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"e3Vb99opzGrvmduDNXvr","level":2,"time":"2021-08-10T00:21:47+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"0BIoq7y2EfOPwRjVUlbw","level":2,"time":"2021-08-10T00:21:54+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"PROPFIND","url":"/nextcloud/remote.php/webdav/","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.4git (Nextcloud, endeavouros-5.13.9-arch1-1 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"22.1.0.1"}
{"reqId":"kIT8KhJEI1BNx0cF15JZ","level":2,"time":"2021-08-10T00:22:45+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"JbVbPHOtd3C16JMXlczi","level":2,"time":"2021-08-10T00:22:46+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"OkanxfkCbM9zMvQV8rFL","level":2,"time":"2021-08-10T00:23:45+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"YqdgdBuYUkhBBHuhh2OL","level":2,"time":"2021-08-10T00:23:47+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"F2uAmZeqnCRmFLX0Przn","level":2,"time":"2021-08-10T00:24:46+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"T82T2ZpbvyESQV0mnh3u","level":2,"time":"2021-08-10T00:24:51+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"xiuMB8HezyH0tF0LmBGX","level":2,"time":"2021-08-10T00:25:51+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"yngMa1rj2TO6PTyoX4Bb","level":2,"time":"2021-08-10T00:26:05+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"7vnBJ3VvQ6SumbNTYisd","level":2,"time":"2021-08-10T00:27:10+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"HWxubr3qVJJp4hcLuMpu","level":2,"time":"2021-08-10T00:27:36+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"hI26Pd6VClYax5e2ZQdk","level":2,"time":"2021-08-10T00:28:10+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"00qVkzfqlm4tW1UvTdAx","level":2,"time":"2021-08-10T00:28:36+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"1EjP7Imns6wJVKGSMz7I","level":2,"time":"2021-08-10T00:29:10+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"jnu1F5Go0v0YidyLZQSP","level":2,"time":"2021-08-10T00:29:36+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"FDeDIGc5UbxdB4YBsuPk","level":3,"time":"2021-08-10T00:30:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306","userAgent":"--","version":"22.1.0.1","exception":{"Exception":"Error","Message":"Trying to access array offset on value of type null at /var/www/html/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php","line":306,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/html/nextcloud/apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php","line":69,"function":"resetForUser","class":"OCA\\DAV\\CalDAV\\BirthdayService","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\DAV\\BackgroundJob\\GenerateBirthdayCalendarBackgroundJob","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/BackgroundJob/QueuedJob.php","line":45,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/html/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"Wbq1Snu49CQIyKKMQDZi","level":2,"time":"2021-08-10T00:30:10+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"efkmafwHzcQeUSuilfrh","level":2,"time":"2021-08-10T00:30:11+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"B6DZr62rpkkvB1r0DBaz","level":2,"time":"2021-08-10T00:30:45+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"wpXx0n16sxJky7np1wAw","level":2,"time":"2021-08-10T00:30:47+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"YuqtD7CMTqjhFnp23l22","level":2,"time":"2021-08-10T00:31:46+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"iWYEBPOZRWWNjDR89EJ7","level":2,"time":"2021-08-10T00:31:51+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"tGbll2Wp8DhZ212iQojc","level":2,"time":"2021-08-10T00:32:52+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"19KGVkcB5WIRaUt42QhA","level":2,"time":"2021-08-10T00:33:06+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/bookmark?page=0&limit=300","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
{"reqId":"ExbqsZNCDB1fawNTR77d","level":2,"time":"2021-08-10T00:34:10+00:00","remoteAddr":"MYIP","user":"--","app":"core","method":"GET","url":"/nextcloud/index.php/apps/bookmarks/public/rest/v2/folder/-1/hash","message":"Login failed: 'hellojack' (Remote IP: 'MYIP')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.134 Safari/537.36","version":"22.1.0.1"}
<summary>Nextcloud log</summary>

```
 - Open the Nextcloud admin settings
 - Open the "Log" section
 - Click the "Copy" icon, then "Copy Raw"
```
</details>

### Browser log
<details>
index.js:46 No OC found
Fr @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
2globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
ProxyBus.ts:17 Proxying an event bus of version 1.3.0 with 2.0.0
t @ ProxyBus.ts:17
10globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ue @ globals.js:62
session-heartbeat.js:101 session heartbeat polling started
social.svg:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
35util.js:135 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:135
<summary>Browser log</summary>

```
Press F12, copy the content of the console tab
```
</details>

**Comment by miguelmenendez** [comment]
In `/apps/passwords/css/app.css`

```css
#app-navigation ul li a i {
    margin-left: -44px;
}
```
Should be
```css
#app-navigation ul li a i {
    margin-left: -16px;
}
```

**Comment by marius-wieschollek** [comment]
A patch  for this is already available in the nightly version
