### ISSUE TITLE
Export fails with "createExportFolderMapping is not a function"

### ISSUE THREAD

**Issue by Der-Alex** [marius-wieschollek/passwords#42]
### System Information
- Nextcloud Version: 13.0.2
- PHP Version: 7.2.4
- Passwords Version: 2018.4.2
- Browser and Version: chrome 66.0.3359.139
- Client OS and Version: win 10 home x64
- Server OS and Version: ubuntu 16.04

### Steps to reproduce
1. Tell us how to reproduce your issue.
- Create a password
- Go to backup / restore 
- Choose export
- Choose any export except database
- Choose any additional option
- Click export.

### Actual result
What does happen?
- A popup opens that says "this._createExportFolderMapping is not a function"
- Console log says: "BackupSection.js:1 
TypeError: this._createExportFolderMapping is not a function
    at Function._convertDbToExportArray (ExportManager.js:1)
    at Function.exportCsv (ExportManager.js:1)"

### Expected result
What should happen?
I can export the csv file.

**Comment by marius-wieschollek** [comment]
The nightly build [2018.5.0-build2207](https://apps.nextcloud.com/apps/passwords/releases) should fix this issue.
