### ISSUE TITLE
"Hash for Security Test"-Setting not working correct

### ISSUE THREAD

**Issue by 9hawk8** [marius-wieschollek/passwords#423]
System Information

**Server:**
 Nextcloud Version: 21.0.4 (21.0.3 did not have this issue, at least it worked for me there, but could also be due to older passwords version, not really sure there, updated both at the same time)
 PHP Version: 7.4.9
 Database and Version: MDB 10.3.27
 Server OS and Version: DSM7.0 and same issue on Debian 10.10
 Passwords Version: 2021.7.23

**Client:**

 Browser and Version: Firefox 91.0.1 and same issue on Edge 92.0.902.73
 Client OS and Version: Windows 10 21H1

Steps to reproduce
1. Go to global settings, passwords settings
2. The feature "Hash for security check" (translated from german, maybe it is called a little different) is on "save complete Hash"
3. Set it to any other option
4. Green "Saved" marker appears
5. reload page
6. feature is set to "no hash is saved"
7. try to switch to any other option, even back to "save complete Hash" is ignored

Expected result
What should happen?
"Hash for security check" is always set to the correct option chosen before reloading page

Actual result
What does happen?
Once changed to any option "Hash for security check" is always stuck on "no hash is saved"

Nextcloud log did not produce any logs since last update three days ago other than failed login attempts.

**Comment by marius-wieschollek** [comment]
This should be fixed with 2021.9.0
