### ISSUE TITLE
Support .onion domains without HTTPS

### ISSUE THREAD

**Issue by Kixunil** [marius-wieschollek/passwords#427]
**Current Status**
Currently when Nextcloud is run as onion service without HTTPS passwords app will display an error message saying it's intended for HTTP only, presumably for security reasons. `.onion` domains are secure without HTTPS though (they're even more secure than HTTPS itself), so the reason for restriction does not apply.

**Feature Description**
If the domain ends with `.onion` enable HTTP.

**Additional context**
I have a project which many users use behind Tor so this is required for passwords app to work well.

**Comment by marius-wieschollek** [comment]
No, for three reasons:
1. The app uses NC to determine whether HTTPS is used. NC offers no option to determine whether TOR is used.
2. All clients are built to use HTTPS exclusively and usually don't/can't offer an option to connect to a server via HTTP. Allowing HTTP is a backwards compatibility break for the api. I don't want to implement it for my clients and i don't want to force other developers to add support to their clients. (Additionally, i'm certain that this would lead to loads of bugs where clients try to use HTTP when they should not)
3. The app requires JS features which are limited to a secure context (HTTPS). Onion urls are not universally recognized as a secure context and the app will be buggy when used with the officially supported browsers trough HTTP + Onion connections. I don't want to deal with the resulting support overhead for users who don't know of these issues.

Feel free to fork the app and any client and add/maintain support for this option yourself. You can also configure the apps & extensions section to use a custom list of apps to show to your users.
