### ISSUE TITLE
Password marked as duplicate, but hash only matches one password

### ISSUE THREAD

**Issue by politas** [marius-wieschollek/passwords#429]
<details>
<summary>Nextcloud System Information</summary>
### System Information
**Server:**
```json
{
    "version": {
        "server": "21.0.4.1",
        "app": "2021.7.23",
        "lsr": false,
        "php": "8.0.9"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "legacyApi": {
        "enabled": 0,
        "used": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "local",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": true,
            "default": "none"
        },
        "cse": {
            "CSEv1r1": true,
            "none": true,
            "default": "CSEv1r1"
        }
    }
}
```

**Client:**
```
 Browser and Version: Firefox 91.0.1 (64-bit)
 Client OS and Version: Manjaro Linux 5.13.11-1-MANJARO
```
</details>

### Steps to reproduce
1. Notice that passwords entry is marked as duplicate
2. Open details page
3. Click link for duplicate list

### Expected result
I expect to see multiple password entries that have the same password

### Actual result
I'm seeing a single password
![Screenshot_2021-08-23_11-02-39](https://user-images.githubusercontent.com/2109967/130377612-bf16a58f-d524-4a28-a665-3e5b55bc50a4.png)

### Nextcloud log
No associated log entries

### Browser log
No associated log entries

**Comment by marius-wieschollek** [comment]
have you checked the trash bin?

**Comment by politas** [comment]
Ah, that seems to be the answer! Shouldn't the search for duplicates include the Trash, if the check for duplicates does? Also, it would be nice to have an "Empty Trash" button somewhere when viewing the Trash; I didn't see one, so I had to go through the multi-click process of deleting every entry one at a time.

**Comment by marius-wieschollek** [comment]
The link just leads you to the search, which does not search in the trash. So this is currently not possible.
