### ISSUE TITLE
Support for longer multi-line passwords

### ISSUE THREAD

**Issue by thrau** [marius-wieschollek/passwords#436]
**Current Status**
We would like to share secret keys (like private RSA keys) with our team members, but it's not possible because of the character limit in the password field.

**Feature Description**
Being able to change the password text field to a textarea and save arbitrary multi-line content.

**Additional context**
We use the password manager of nextcloud @localstack to share access to various infrastructure. We love the tool, and we could work around the textarea issue, but the character limit is currently blocking us.

**Comment by marius-wieschollek** [comment]
The passwords app is not intended for file storage. Use Nextcloud E2EE for that.
