### ISSUE TITLE
Change default value of 'base_url' in the postman collection

### ISSUE THREAD

**Issue by jekru** [marius-wieschollek/passwords#437]
In the [postman collection](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/_files/postman-collection.json), the default value of the variable ```base_url``` is ```https://localhost/apps/passwords```. If I change ```localhost``` to ```mydomain.tld```, every api endpoint worked fine for me except the endpoint ``` POST /api/1.0/share/create```. It returns status **405 Method Not Allowed**.

![image](https://user-images.githubusercontent.com/55323459/132938152-e8a123cd-2c64-4b56-9140-b532c504541b.png)

I shared a password manually with another user in the browser and saw that the api endpoint used is ```POST https://mydomain.tld/index.php/apps/passwords/api/1.0/share/create```

**Feature Description**

Change ```base_url ``` to ```https://localhost/index.php/apps/passwords``` in the [postman collection](https://git.mdns.eu/nextcloud/passwords/wikis/Developers/_files/postman-collection.json). The other api endpoints I tested are still working and ```POST https://mydomain.tld/index.php/apps/passwords/api/1.0/share/create``` doesn't return an http error 405 anymore.

```diff
"variable": [
  {
    "key": "base_url",
-   "value": "https://localhost/apps/passwords"
+   "value": "https://localhost/index.php/apps/passwords"
  },
  {
    "key": "http_auth_user",
    "value": "admin"
  },
  ...
]
```

**Comment by jekru** [comment]
Could someone change the label to 'documentation'?

**Comment by marius-wieschollek** [comment]
done
