### ISSUE TITLE
Use @nextcloud/vue

### ISSUE THREAD

**Issue by raimund-schluessler** [marius-wieschollek/passwords#439]
**Current Status**
The app uses many custom components for which there are replacements in the @nextcloud/vue component bundle, e.g.
- [Actions](https://nextcloud-vue-components.netlify.app/#/Components/Actions) (DropdownMenu)
- [Breadcrumbs](https://nextcloud-vue-components.netlify.app/#/Components/Breadcrumbs) (Breadcrumb)
- [AppSidebar](https://nextcloud-vue-components.netlify.app/#/Components/App%20containers?id=appsidebar)
- Modal
- quite a few others.

**Feature Description**
Consider using the components provided by @nextcloud/vue, see https://github.com/nextcloud/nextcloud-vue.

**Additional context**
Using the components from @nextcloud/vue would reduce the maintenance effort for this app, since the components are then maintained by the community and Nextcloud GmbH.
It would furthermore bring the look and feel closer to other Nextcloud app which share the same components.

In case you like the idea I can start sending some PRs to get this going.

**Comment by marius-wieschollek** [comment]
If you would like to work on this, i'd be happy to look at any PR. But be aware that migrating to nextcloud vue won't be easy.

**Comment by raimund-schluessler** [comment]
@marius-wieschollek Do you have a particular reason why you think it won't be easy? I thought about starting small and replacing components like Breadcrumbs or Actions and only later on replacing app containers such as AppContent or AppSidebar (which indeed might be a bit of work). Does that make sense to you?

**Comment by marius-wieschollek** [comment]
At the time when this ticket was opened, my main concern was the icons. Passwords uses FontAwesme 4.7 and NC only supported it's own tiny iconset when i last checked. By now, NC recommends the vue material design icons, and nextcloud/vue also supports custom icons everywhere.

I have already begun to move the app over to nextcloud/vue and hope that this will make support for future NC versions easier.

The only risk that comes with this is that i don't know how compatible nextcloud/vue is with different versions of NC. I don't want to drop support for a version just because i can't fix the design.

**Comment by raimund-schluessler** [comment]
> At the time when this ticket was opened, my main concern was the icons. Passwords uses FontAwesme 4.7 and NC only supported it's own tiny iconset when i last checked. By now, NC recommends the vue material design icons, and nextcloud/vue also supports custom icons everywhere.

Yes, every component should support material design icons by now. The variety of icons in the [package used](https://github.com/robcresswell/vue-material-design-icons) is quite good, there should be a replacement for every icon.

> I have already begun to move the app over to nextcloud/vue and hope that this will make support for future NC versions easier.

Great to hear this. I think it should make it easier, since you don't need to maintain these components anymore. Let me know if you need help.

> The only risk that comes with this is that i don't know how compatible nextcloud/vue is with different versions of NC. I don't want to drop support for a version just because i can't fix the design.

This is usually not a big issue. However, the update to NC25 unfortunately brought a breaking design change in server, which lead to a breaking change in the components as well. Server v25 requires nextcloud/vue@7 which doesn't work with server <25 anymore. Most apps I know either have to maintain two branches, one for server23/24 and one for later versions; or they dropped support for 23/24 completely and only offer a version for 25 (which should then be compatible with later server versions as well). Which approach is doable depends on how much time one has to support different versions, I guess.

**Comment by marius-wieschollek** [comment]
First batch of changes is part of 2023.1.0.
One thing i didn't know before was how much bloat the nextcloud vue components have. See https://help.nextcloud.com/t/how-to-deal-with-nextcloud-vue-bloat/153227 for details.

I was able to keep the initial app size acceptable by removing and replacing other dependencies and making a lot more use of asynchronous loading to load components only when needed.

IMO @nextcloud/vue really needs to go on a diet. 180kb for a list entry isn't normal

**Comment by ghost** [comment]
Is the entire app transferred to Nextcloud Vue?

**Comment by marius-wieschollek** [comment]
Anything that profits from the migration has been migrated.

**Comment by ghost** [comment]
The Share section in the sidebar could benefit from this.  E.g. sharing with groups, circles, etc.

**Comment by marius-wieschollek** [comment]
Nextcloud vue is just ui. There won't be new sharing functionality just because i use any of the components.

I used the select component and had to do most of the styling myself as nextcloud/vue apparently provided no styling for this component for some reason. And the Nextcloud list item components add a lot of file size to the app, but all they can do is show the list. There is no benefit to using them.
