### ISSUE TITLE
Update to version 2018.5.0 leaves installation in maintenance mode

### ISSUE THREAD

**Issue by KornPhleax** [marius-wieschollek/passwords#44]
### System Information
- Nextcloud Version: 12.0.7
- PHP Version: 7.1.16
- Passwords Version  2018.5.0
- Browser and Version: Chromium 66.0.3359.139
- Client OS and Version: Windows 10 Pro
- Server OS and Version: Debian 9 Stretch

### Steps to reproduce
Install passwords app and update over the web interface.

### Actual result
Update fails due to following error:
`PHP Fatal error: Interface 'OCP\Migration\IMigrationStep' not found in /var/www/nextcloud/apps/passwords/lib/Migration/LegacyDatabaseMigration.php on line 24`

### Cause
The error is probably caused by the [IMigrationStep](https://docs.nextcloud.com/server/13/developer_manual/api/OCP/Migration/IMigrationStep.html) interface introduced in nextcloud 13 which is not present in nexcloud 12 and breaks the update of the passwords app.

### Expected result
Update goes through without problems.

### Fix that worked for me
I downloaded the new Nextcloud Version 13.0.2 and upgraded my instance following the guide in the wiki [Wiki](https://docs.nextcloud.com/server/13/admin_manual/maintenance/manual_upgrade.html)

**Comment by marius-wieschollek** [comment]
Thanks for reporting this.
