### ISSUE TITLE
Initialisation Error  The app was unable to obtain the api access credentials.

### ISSUE THREAD

**Issue by berti34** [marius-wieschollek/passwords#443]
Hi,

installing the app works as expected. But opening fails because of missing database tables. Installing the app should create the needed tables.  An  occ maintenance:repair does not solve the issue.

{
    "version": {
        "server": "22.2.0.2",
        "app": "2021.10.20-build4245",
        "lsr": false,
        "php": "7.4.15"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "legacyApi": {
        "enabled": 2,
        "used": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": [],
        "cse": []
    }
}

### Steps to reproduce
every time when opening the passwords app via app menue

### Expected result
The app should open...

### Actual result
the modal error message appears:
Initialisation Error  The app was unable to obtain the api access credentials.
![image](https://user-images.githubusercontent.com/47418901/135651065-ef00d229-ec8f-460d-b619-c41b2f106526.png)

### Nextcloud log
<details>
<summary>Nextcloud log</summary>
[passwords] Fatal: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist

{"reqId":"UATeysmQKk0elyKRqIx8","level":4,"time":"2021-10-01T15:55:02+00:00","remoteAddr":"","user":"--","app":"passwords","method":"","url":"--","message":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist","userAgent":"--","version":"22.2.0.2","exception":{"Exception":"OC\\DB\\Exceptions\\DbalException","Message":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist","Code":1146,"Trace":[{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":302,"function":"wrap","class":"OC\\DB\\Exceptions\\DbalException","type":"::"},{"file":"/var/www/cloud/html/lib/public/AppFramework/Db/QBMapper.php","line":334,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php","line":151,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Services/Object/AbstractService.php","line":79,"function":"findAllDeleted","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":183,"function":"findDeleted","class":"OCA\\Passwords\\Services\\Object\\AbstractService","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":171,"function":"deleteObjects","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/CleanUpEntities.php","line":81,"function":"run","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/AbstractTimedJob.php","line":74,"function":"runJob","class":"OCA\\Passwords\\Cron\\CleanUpEntities","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/cloud/html/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/cloud/html/lib/private/DB/Exceptions/DbalException.php","Line":71,"Previous":{"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist","Code":1146,"Trace":[{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Connection.php","line":1040,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/Connection.php","line":231,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":210,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":300,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/lib/public/AppFramework/Db/QBMapper.php","line":334,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php","line":151,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Services/Object/AbstractService.php","line":79,"function":"findAllDeleted","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":183,"function":"findDeleted","class":"OCA\\Passwords\\Services\\Object\\AbstractService","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":171,"function":"deleteObjects","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/CleanUpEntities.php","line":81,"function":"run","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/AbstractTimedJob.php","line":74,"function":"runJob","class":"OCA\\Passwords\\Cron\\CleanUpEntities","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/cloud/html/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":47,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist","Code":1146,"Trace":[{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Connection.php","line":1030,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/Connection.php","line":231,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":210,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":300,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/lib/public/AppFramework/Db/QBMapper.php","line":334,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php","line":151,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Services/Object/AbstractService.php","line":79,"function":"findAllDeleted","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":183,"function":"findDeleted","class":"OCA\\Passwords\\Services\\Object\\AbstractService","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":171,"function":"deleteObjects","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/CleanUpEntities.php","line":81,"function":"run","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/AbstractTimedJob.php","line":74,"function":"runJob","class":"OCA\\Passwords\\Cron\\CleanUpEntities","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/cloud/html/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist","Code":"42S02","Trace":[{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Connection.php","line":1030,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/Connection.php","line":231,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":210,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":300,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/lib/public/AppFramework/Db/QBMapper.php","line":334,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php","line":151,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Services/Object/AbstractService.php","line":79,"function":"findAllDeleted","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":183,"function":"findDeleted","class":"OCA\\Passwords\\Services\\Object\\AbstractService","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Helper/CleanUp/CleanDeletedEntitiesHelper.php","line":171,"function":"deleteObjects","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/CleanUpEntities.php","line":81,"function":"run","class":"OCA\\Passwords\\Helper\\CleanUp\\CleanDeletedEntitiesHelper","type":"->"},{"file":"/var/www/cloud/html/apps/passwords/lib/Cron/AbstractTimedJob.php","line":74,"function":"runJob","class":"OCA\\Passwords\\Cron\\CleanUpEntities","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/var/www/cloud/html/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/cloud/html/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/cloud/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}}},"CustomMessage":"An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cloud.oc_passwords_pw_tag_rel' doesn't exist"},"id":"61573052921de"}
</details>

### Browser log
<details>
<summary>Browser log</summary>

No OC found index.js:46:12
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
Proxying an event bus of version 1.3.0 with 2.0.0 ProxyBus.ts:17:12
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. 2 globals.js:62:15
jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own. globals.js:62:15
$ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
</details>

**Comment by marius-wieschollek** [comment]
Did you recently upgrade the app and if so from which version? Were there any errors reported during the upgrade?

**Comment by berti34** [comment]
Hi,

yes, I've updated to Nextcloud 22.2.0.2  and the  passwords-app 
2021.10.20 - Feature release

I don't know about upgrade errors. On my fresh new and empty nextcloud 
parallel system the passwords app works very well.


Left: works fine,    Right: error message as user.

![image](https://user-images.githubusercontent.com/47418901/136513678-a61c9bb5-34d1-4ab3-b846-2bbb605a9421.png)



FORMATED:

[passwords] Fatal: Loading challenge failed

GET /index.php/apps/passwords/api/1.0/session/request
from 94.31... by berthold at 2021-10-05T12:17:44+00:00



RAW:

     "reqId": "EuEOmH0LaGDDHRYNKluv",
     "level": 4,
     "time": "2021-10-05T12:17:44+00:00",
     "remoteAddr": "94.31.90.63",
     "user": "berthold",
     "app": "passwords",
     "method": "GET",
     "url": "/index.php/apps/passwords/api/1.0/session/request",
     "message": "Loading challenge failed",
     "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) 
Gecko/20100101 Firefox/92.0",
     "version": "22.2.0.2",
     "exception": {
         "Exception": "OCA\\Passwords\\Exception\\ApiException",
         "Message": "Loading challenge failed",
         "Code": 256,
         "Trace": [
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Services/UserChallengeService.php",
                 "line": 109,
                 "function": "getDefaultChallenge",
                 "class": "OCA\\Passwords\\Services\\UserChallengeService",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Controller/Api/SessionApiController.php",
                 "line": 105,
                 "function": "getChallengeData",
                 "class": "OCA\\Passwords\\Services\\UserChallengeService",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/lib/private/AppFramework/Http/Dispatcher.php",
                 "line": 217,
                 "function": "request",
                 "class": 
"OCA\\Passwords\\Controller\\Api\\SessionApiController",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/lib/private/AppFramework/Http/Dispatcher.php",
                 "line": 126,
                 "function": "executeController",
                 "class": "OC\\AppFramework\\Http\\Dispatcher",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/lib/private/AppFramework/App.php",
                 "line": 156,
                 "function": "dispatch",
                 "class": "OC\\AppFramework\\Http\\Dispatcher",
                 "type": "->"
             },
             {
                 "file": "/var/www/cloud/html/lib/private/Route/Router.php",
                 "line": 301,
                 "function": "main",
                 "class": "OC\\AppFramework\\App",
                 "type": "::"
             },
             {
                 "file": "/var/www/cloud/html/lib/base.php",
                 "line": 1000,
                 "function": "match",
                 "class": "OC\\Route\\Router",
                 "type": "->"
             },
             {
                 "file": "/var/www/cloud/html/index.php",
                 "line": 36,
                 "function": "handleRequest",
                 "class": "OC",
                 "type": "::"
             }
         ],
         "File": 
"/var/www/cloud/html/apps/passwords/lib/Services/UserChallengeService.php",
         "Line": 189,
         "CustomMessage": "Loading challenge failed"
     },
     "id": "615c4fda9bf38"
}



{
     "reqId": "EuEOmH0LaGDDHRYNKluv",
     "level": 4,
     "time": "2021-10-05T12:17:44+00:00",
     "remoteAddr": "94.31.90.63",
     "user": "berthold",
     "app": "passwords",
     "method": "GET",
     "url": "/index.php/apps/passwords/api/1.0/session/request",
     "message": "Did expect one result but found none when executing: 
query \"SELECT * FROM `*PREFIX*passwords_challenge` WHERE (`deleted` = 
:dcValue1) AND (`user_id` = :dcValue2) AND (`uuid` = :dcValue3)\"; ",
     "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) 
Gecko/20100101 Firefox/92.0",
     "version": "22.2.0.2",
     "exception": {
         "Exception": "OCP\\AppFramework\\Db\\DoesNotExistException",
         "Message": "Did expect one result but found none when 
executing: query \"SELECT * FROM `*PREFIX*passwords_challenge` WHERE 
(`deleted` = :dcValue1) AND (`user_id` = :dcValue2) AND (`uuid` = 
:dcValue3)\"; ",
         "Code": 0,
         "Trace": [
             {
                 "file": 
"/var/www/cloud/html/lib/public/AppFramework/Db/QBMapper.php",
                 "line": 361,
                 "function": "findOneQuery",
                 "class": "OCP\\AppFramework\\Db\\QBMapper",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php",
                 "line": 201,
                 "function": "findEntity",
                 "class": "OCP\\AppFramework\\Db\\QBMapper",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php",
                 "line": 174,
                 "function": "findOneByFields",
                 "class": "OCA\\Passwords\\Db\\AbstractMapper",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Db/AbstractMapper.php",
                 "line": 99,
                 "function": "findOneByField",
                 "class": "OCA\\Passwords\\Db\\AbstractMapper",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Services/Object/AbstractService.php",
                 "line": 100,
                 "function": "findByUuid",
                 "class": "OCA\\Passwords\\Db\\AbstractMapper",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Services/Object/ChallengeService.php",
                 "line": 71,
                 "function": "findByUuid",
                 "class": 
"OCA\\Passwords\\Services\\Object\\AbstractService",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Services/UserChallengeService.php",
                 "line": 185,
                 "function": "findByUuid",
                 "class": 
"OCA\\Passwords\\Services\\Object\\ChallengeService",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Services/UserChallengeService.php",
                 "line": 109,
                 "function": "getDefaultChallenge",
                 "class": "OCA\\Passwords\\Services\\UserChallengeService",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/apps/passwords/lib/Controller/Api/SessionApiController.php",
                 "line": 105,
                 "function": "getChallengeData",
                 "class": "OCA\\Passwords\\Services\\UserChallengeService",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/lib/private/AppFramework/Http/Dispatcher.php",
                 "line": 217,
                 "function": "request",
                 "class": 
"OCA\\Passwords\\Controller\\Api\\SessionApiController",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/lib/private/AppFramework/Http/Dispatcher.php",
                 "line": 126,
                 "function": "executeController",
                 "class": "OC\\AppFramework\\Http\\Dispatcher",
                 "type": "->"
             },
             {
                 "file": 
"/var/www/cloud/html/lib/private/AppFramework/App.php",
                 "line": 156,
                 "function": "dispatch",
                 "class": "OC\\AppFramework\\Http\\Dispatcher",
                 "type": "->"
             },
             {
                 "file": "/var/www/cloud/html/lib/private/Route/Router.php",
                 "line": 301,
                 "function": "main",
                 "class": "OC\\AppFramework\\App",
                 "type": "::"
             },
             {
                 "file": "/var/www/cloud/html/lib/base.php",
                 "line": 1000,
                 "function": "match",
                 "class": "OC\\Route\\Router",
                 "type": "->"
             },
             {
                 "file": "/var/www/cloud/html/index.php",
                 "line": 36,
                 "function": "handleRequest",
                 "class": "OC",
                 "type": "::"
             }
         ],
         "File": 
"/var/www/cloud/html/lib/public/AppFramework/Db/QBMapper.php",
         "Line": 283,
         "CustomMessage": "Did expect one result but found none when 
executing: query \"SELECT * FROM `*PREFIX*passwords_challenge` WHERE 
(`deleted` = :dcValue1) AND (`user_id` = :dcValue2) AND (`uuid` = 
:dcValue3)\"; "
     },
     "id": "615c4fda9c198"
}

-- 
Mit freundlichen Grüßen
Berthold Tenhumberg

**Comment by marius-wieschollek** [comment]
Does this still happen with the latest version?

**Comment by berti34** [comment]
No, I have no problems with it last weeks. I'm using version 2.2.2
You may close this report as solved.
