### ISSUE TITLE
error in protocol

### ISSUE THREAD

**Issue by q-ki** [marius-wieschollek/passwords#445]
Hi there ...

NextcloudPi (20.0.2.2) on RBP4 and the app version 2021.10.10

The app is functioning normal.
But in the protocol I get a lot of errors when using it ...

for example ...

<html><body>

Error | PHP | Error: idn_to_utf8():  INTL_IDNA_VARIANT_2003 is deprecated at  /var/www/nextcloud/apps/passwords/lib/Helper/Favicon/AbstractFaviconHelper.php#117
-- | -- | --

</body>
</html>

<html><body>

Error | PHP | Error: idn_to_utf8():  INTL_IDNA_VARIANT_2003 is deprecated at  /var/www/nextcloud/apps/passwords/lib/Helper/Favicon/AbstractFaviconHelper.php#129
-- | -- | --

</body>
</html>

    <<closure>>

    OC\Log\ErrorHandler::onError(8192, "idn_to_utf8 ... d", "/var/www/ne ... p", 117, { domain: "w ... "})

    /var/www/nextcloud/apps/passwords/lib/Helper/Favicon/AbstractFaviconHelper.php - line 117:

    idn_to_utf8("webhoster.ag")

    /var/www/nextcloud/apps/passwords/lib/Helper/Favicon/DefaultFaviconHelper.php - line 33:

    OCA\Passwords\Helper\Favicon\AbstractFaviconHelper->getDefaultFavicon("webhoster.ag")

    /var/www/nextcloud/apps/passwords/lib/Services/FaviconService.php - line 90:

    OCA\Passwords\Helper\Favicon\DefaultFaviconHelper->getFavicon("webhoster.ag", 32)

    /var/www/nextcloud/apps/passwords/lib/Controller/Api/ServiceApiController.php - line 187:

    OCA\Passwords\Services\FaviconService->getFavicon("webhoster.ag", 32)

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Passwords\Controller\Api\ServiceApiController->getFavicon("webhoster.ag", 32)

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Password ... {}, "getFavicon")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Password ... {}, "getFavicon")

    /var/www/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("ServiceApiController", "getFavicon", OC\AppFramew ... {}, { domain: "w ... "})

    /var/www/nextcloud/lib/base.php - line 1008:

    OC\Route\Router->match("/apps/passw ... 2")

    /var/www/nextcloud/index.php - line 37:

    OC::handleRequest()

What do you think is the reason for that ? 

Any suggestions ?

Thanks for your help ...
qki

**Comment by marius-wieschollek** [comment]
Please fill out the bug report form.
