### ISSUE TITLE
List Nextcloud Password Client

### ISSUE THREAD

**Issue by j0chn1** [marius-wieschollek/passwords#446]
Hey Marius,
I'd like you to list my app.
As we already talked about it, you know that the app is in developing state and only able to retrieve and display folder and passwords yet

Name of your app: 
Nextcloud Password Client

Short description of your app (max ~160 characters, optionally in multiple languages)
Nextcloud Password Client is a Flutter based application to manage passwords from the corresponding Nextcloud App.
This app is meant to be run on desktop clients and not on mobile devices (that's what the name should intend).
This Version is in development state and there a lot of features missing right now.

Logo of your app (SVG, PNG or JPG, ca 400x400px) (only apps, not libraries)
![npc_logo_400_403](https://user-images.githubusercontent.com/87828588/137610937-f7bea9fe-df2a-433e-af89-8c3664f4b16f.png)

Link to the website/store where users can get your app
Link to the sources
https://gitlab.com/j0chn/nextcloud-password-client

Supported Systems/Browsers etc.
Theoretically every OS because this is written in Flutter. 
As I only have Windows and Linux installed, these are the supported platforms.
I don't have a Mac / Iphone so they are excluded from support
Already mentioned in the description, this app is meant for desktops so it won't get support for mobile and Web

Information how we can test your app
There are no tests implemented.
Install the app on windows or build it on your own and just use it :-)

Does your app support client side encryption?
Password challenge is implemented.

**Comment by marius-wieschollek** [comment]
I have been running into some issues when trying to test the app.

When building the app under Ubuntu, the build process works after installing `libsecret-1-dev` and `libjsoncpp-dev`, but then only an empty window opens and the error message "Failed to start Flutter renderer: GL-Context could not be created" appears in the console output:
![grafik](https://user-images.githubusercontent.com/8255857/139312154-f0851b17-9002-4544-af11-1b3364738e92.png)

When installing the included exe-file under Windows 10 in a VirtualBox VM, the start fails with the message that MSVCP140.dll is missing.
![2021-1017_MSEdge - Win10  wird ausgeführt  - Oracle VM VirtualBox_001](https://user-images.githubusercontent.com/8255857/139312585-2520531a-4617-483d-b535-1e6aa8880671.png)

I could fix this by installing Microsoft Visual C++ 2015-2022 manually, but then the app again starts with only an empty window. When i click the close icon after trying to resize the window, Windows says the app is unresponsive:
![grafik](https://user-images.githubusercontent.com/8255857/139313070-9dbd78b9-7fbe-46d0-a5af-be8a4b7a6001.png)

Any idea how to fix that?

**Comment by j0chn1** [comment]
Ubunto: do you have a keyring like "gnome-keyring"? If you built the  latest version you should find an error.log in you <documents_paht>/nextcloou_password_client folder. I could check it.
Windows: I added some lines in readme. I added the ZIP File. Just extract it and run the .exe file. If you do not already installed the [libsodium.dll](https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-stable-mingw.tar.gz) you have to obtain it and put it into you system32 folder. With that version you also get the error.log file

**Comment by marius-wieschollek** [comment]
Under ubuntu, no error.log was created anywhere.

Under windows it was created and i could figure out that i apparently used the wrong version of the libsodium.dll.  After that the exe file worked and the app launched.
I could not install the msix file with add-appxpackage due to some root certificate error.


Btw.: i noticed that encrypted password entries don't work if they have notes. should i open a ticket?

**Comment by j0chn1** [comment]
I noticed that msix problem today when I tried to install it on my works laptop. I will figure it out some time.

When there is no error log on ubuntu, could you open an issue with your output, please?

Yes please open an issue. I will try it with my test database then.
Thank you very much 😘

**Comment by j0chn1** [comment]
Hey @marius-wieschollek ,
I uploaded latest windows prebuild. 
May I ask you for a status?
Regards

**Comment by marius-wieschollek** [comment]
App is added, ticket closed
