### ISSUE TITLE
Change dictionary for password-suggestions

### ISSUE THREAD

**Issue by matthiasw2021** [marius-wieschollek/passwords#447]
**Current Status**
Regulary the app suggests passwords including words which are inappropriate.

**Feature Description**
Please change the password-suggestion-dictionary to a harmless one.

**Additional context**
I often stumble across strange words whenever the app is suggesting passwords. Today I got "Wehrmachtkrieg" (with letters exchanged with numbers as always). Not just as a German this is no good password which you want to share with family members. Infact it seems like your password-dictionary seems political biased.

**Comment by marius-wieschollek** [comment]
If you want to use a custom dictionary, you can do so by providing a file at `/usr/share/dict/words` and `/usr/share/dict/ngerman` and then switching the words service to "Local dictionary".

If you know of any (free) online service which provides good international/german dictionaries, feel free to suggest a new words service.

I won't provide a filtered dictionary for the following reasons:
 - _It's waaayyy out of scope. That's just an amount of work i'm not willing to do._ (this is the main reason)
 - Picking the words goes against the idea of them being random.
 - What is acceptable and what not is highly subjective.
 - You can just generate another password if you don't like the current one.

> Infact it seems like your password-dictionary seems political biased.

If you're using the recommended Leipzig Corpora Collection: The two main corpora are from german news and the german Wikipedia. It's open source and you're free to contribute.
