### ISSUE TITLE
Shared password not updating

### ISSUE THREAD

**Issue by nooblag** [marius-wieschollek/passwords#449]
### System Information
**Server:**
```json
{
    "version": {
        "server": "22.2.0.2",
        "app": "2021.10.20",
        "lsr": false,
        "php": "8.0.11"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "legacyApi": {
        "enabled": 0,
        "used": false
    },
    "services": {
        "images": "imagick",
        "favicons": "local",
        "previews": "screeenly",
        "security": "hibp",
        "words": "local",
        "previewApi": true,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
 Browser and Version: Firefox 93.0
 Client OS and Version: Ubuntu 20
```

### Steps to reproduce
1. Share a password with another user
2. Other user changes the password
3. Password and metadata is not updated for original user

### Expected result
Any changes to the password share are reflected for all shared users

### Actual result
Password and metadata is not updated

**Video Recording GIF of behaviour**
https://ibb.co/bXs4YWM

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
N/A
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

**Comment by marius-wieschollek** [comment]
https://git.mdns.eu/nextcloud/passwords/wikis/Users/F.A.Q#sharing

**Comment by nooblag** [comment]
Thank you for that, but continuing with example data provided above, looks like this is not happening for me. It's been 3 hours and the password hasn't updated for the original user.

**Test user** (original)
![aCapture](https://user-images.githubusercontent.com/1122344/138906550-881f3319-505e-4812-a8f5-138849480213.PNG)

**Test2 user** (share)
![Capture](https://user-images.githubusercontent.com/1122344/138906351-39172fe3-422b-4b75-a72a-4852581c9644.PNG)

Still no logs. `/var/log/nginx/error.log` is empty, no browser console logs, etc.

How can I check this 'privileged automated process on the server' is working?

**Comment by nooblag** [comment]
I can somewhat also replicate this issue on production server. `User 1` created password on 25th September at 5:31 PM and shared it with `User 2`. `User 2` changes the password on 19th October at 8:07 PM and `User 2` also changes it just now, I wait ~30 minutes, login as `User 1` the password is updated but the metadata is still incorrect.

**User 1** (original)
![user1](https://user-images.githubusercontent.com/1122344/138915416-e20202db-efde-45d3-84d8-0a19af9c3b3a.PNG)

**User 2** (share)
![user2](https://user-images.githubusercontent.com/1122344/138915274-0c331411-6e27-4be7-94e6-57ff099faa1a.PNG)

Something isn't working correctly on both servers?

**Comment by nooblag** [comment]
2nd, more fresh example on production:

`User 1` creates password at 2:38 AM, shares it with `User 2`. `User 2` logs in, changes it at 2:42 AM. As of 3:00 AM, password has updated for `User 1` but the last updated time is incorrect:

**User 2** (share)
![user2-1](https://user-images.githubusercontent.com/1122344/138916919-15c1edd1-f289-455b-a82e-8a1c5c942acd.PNG)

**User 1** (original), 16 minutes later
![user1-1](https://user-images.githubusercontent.com/1122344/138916932-4f827268-d504-4348-89da-567879bd16d9.PNG)

**Comment by marius-wieschollek** [comment]
i can confirm that the edited time is not updated correctly

**Comment by nooblag** [comment]
Nice work 👍
