### ISSUE TITLE
Move improvements

### ISSUE THREAD

**Issue by majkinetor** [marius-wieschollek/passwords#450]
**Current Status**
I want to be able to move multiple items in the single action. It would be nice to keep the last selected folder when repeating the action instead of always returning to home which is meaningless since you already have home button shortcut there. 

**Feature Description**
1. Allow option to multiselect passwords, for example with middle mouse click or by providing checkboxes
2. Remember last selected folder in the folder selection dialog

**Comment by marius-wieschollek** [comment]
Duplicate #268
