### ISSUE TITLE
Password Import from CSV - Excel generation - Msg : "application/vnd.ms-excel" but "text/csv" expected

### ISSUE THREAD

**Issue by francoisPE** [marius-wieschollek/passwords#451]
Hello,
when I try to import a csv from excel generation I obtain that.
I my excel I create a table
I export it to csv using in VBA
    Set objStream = CreateObject("ADODB.Stream")
    objStream.Type = 2
    objStream.Charset = utf-8
I obtain a CSV file utf8 encoded but... with mime-type application/vnd.ms-excel instead of expected text/csv
When I try to import, it refuses with option "password csv"
I need to go to custom csv...

### System Information
**Server:**
{
    "version": {
        "server": "21.0.5.1",
        "app": "2021.10.20",
        "lsr": false,
        "php": "7.4.3"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "legacyApi": {
        "enabled": 0,
        "used": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "local",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}

**Client:**
firefox 93.0 (64 bits)

### Steps to reproduce
1. I attach an example of concerned csv file
[PSWD_client.csv](https://github.com/marius-wieschollek/passwords/files/7448643/PSWD_client.csv)

2. import it with second choice of the import list : "paswword CSV" (in french "CSV des mots de passe")
3. see error msg

### Feature
It would be nice to have app accepting application/vnd.ms-excel mime type

Some additional details
- with excel, that's not easy to add double quote as string delimiter in csv (as you can see in attached csv, where there is no double quote)
- a further improvement would be to accept windows encoding in addition to utf-8 (easier csv creation)

**Comment by marius-wieschollek** [comment]
If i understand you correctly, what you want is an import which accepts the Excel file generated by the excel export.

The Password CSV import option expects the same CSV file as generated by the Password CSV option of the export.

The error message about the file type can be ignored as long as the file contents are actually CSV. Windows sometimes reports incorrect file types to the browser.

**Comment by francoisPE** [comment]
Sorry for being not so clear.

Import from excel would be nice : this is what I put in "additional" chapter
This is not exactly my request. Excel would generate several issues : first one utf-8 encoding... 

Then, I am talking about csv file with comma separated text encoded in utf-8 from excel via VBA 
If you look at that https://newbedev.com/what-mime-type-should-i-use-for-csv
you will see that excel is creating csv with mime-type application/vnd.ms-excel

As you can test it with the file I attached, it doesn't work with password app import process : error message 'import failed'

May be you can accept that application/vnd.ms-excel mime type. I don't know if it will work ?

**Comment by marius-wieschollek** [comment]
To me it looks like you're trying to import a custom CSV. In this case use the custom CSV import. The app will give you a warning if the file type does not match, but you can still import the file.
