### ISSUE TITLE
Please add f-droid links

### ISSUE THREAD

**Issue by fairking** [marius-wieschollek/passwords#452]
Please add f-droid links to the description. Thanks.

![image](https://user-images.githubusercontent.com/13495631/141003896-d01839fd-4da6-48b3-b5c9-1b55753db7f0.png)

**Comment by marius-wieschollek** [comment]
F-Droid and other links can be found in the appstore within the app. I don't want to fill up the app description with all kinds of links, that's hard to manage in the long term.
