### ISSUE TITLE
Local favicon service should support subdomains

### ISSUE THREAD

**Issue by psxde** [marius-wieschollek/passwords#453]
**Current Status**
Local favicon service is using the favicon from master domain example.com

**Feature Description**
Local favicon service shoud use the favicon of the respective subdomain sub.example.com

**Additional context**
Using one favicon for all subdomains is confusing if you are store passwords mainly in organization context which uses different subdomains for different services - then all password entries have the same favicon,

**Comment by marius-wieschollek** [comment]
The local favicon service supports subdomains? The only times a subdomain is ignored by the webapp is when it's a common subdomain used for login services (i.e. login.example.com).

**Comment by psxde** [comment]
Oh, you are right, but it does not support sub-sub-Domains e.g. app.local.domain.com.
