### ISSUE TITLE
Nextcloud 23 Support

### ISSUE THREAD

**Issue by rototom** [marius-wieschollek/passwords#457]
### System Information
**Server:**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

 Nextcloud Version: 23.0.0
 PHP Version:8.0
 Database and Version: mariadb 10.5.12-0+deb11u1 
 Server OS and Version: Debian Bullseye
 Passwords Version: 2021.11.20
```

**Client:**
```
 Browser and Version: 95.0b8
 Client OS and Version: arch (btw)
```

### Steps to reproduce
1. install passwords

### Expected result
It should work

### Actual result
occ is no longer usable:
```
An unhandled exception has been thrown:
ArgumentCountError: Too few arguments to function OC\App\AppStore\Fetcher\Fetcher::__construct(), 5 passed in /var/www/nextcloud/apps/passwords/lib/Fetcher/NightlyAppFetcher.php on line 92 and exactly 6 expected in /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php:70
Stack trace:
#0 /var/www/nextcloud/apps/passwords/lib/Fetcher/NightlyAppFetcher.php(92): OC\App\AppStore\Fetcher\Fetcher->__construct()
#1 [internal function]: OCA\Passwords\Fetcher\NightlyAppFetcher->__construct()
#2 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): ReflectionClass->newInstanceArgs()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#13 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#19 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#23 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#26 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#27 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#28 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#29 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#30 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#31 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#32 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#33 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#34 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(435): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#35 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#36 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#37 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(106): array_map()
#38 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(114): OC\AppFramework\Utility\SimpleContainer->buildClass()
#39 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(131): OC\AppFramework\Utility\SimpleContainer->resolve()
#40 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(463): OC\AppFramework\Utility\SimpleContainer->query()
#41 /var/www/nextcloud/lib/private/ServerContainer.php(145): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#42 /var/www/nextcloud/lib/private/Console/Application.php(217): OC\ServerContainer->query()
#43 /var/www/nextcloud/lib/private/Console/Application.php(128): OC\Console\Application->loadCommandsFromInfoXml()
#44 /var/www/nextcloud/console.php(98): OC\Console\Application->loadCommands()
#45 /var/www/nextcloud/occ(11): require_once('...')
#46 {main}
```
In the passwords settings:
 PHP 7.4.21 wird ab Version 2022.1.0 nicht mehr unterstützt. Bitte sieh dir unsere Systemanforderungen an. 
 Die letzte Hintergrundaufgabe wurde mit PHP 7.4.21 ausgeführt, der Webserver verwendet jedoch 8.0.13. Die Verwendung verschiedener Hauptversionen von PHP kann Probleme verursachen. 

I updated php from 7.4 to 8.0. php7.4 is completely uninstalled, php -v at the terminal says "PHP 8.0.13 (cli) ", fpm and apache run with 8.0, too.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"sQob7MZyO79iRmZExGYD","level":3,"time":"2021-11-26T01:20:02+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OC\\Migration\\BackgroundRepair, arguments: Array\n(\n    [app] => passwords\n    [step] => OCA\\Passwords\\Migration\\AutoBackupRestore\n)\n)","userAgent":"--","version":"23.0.0.9","exception":{"Exception":"ArgumentCountError","Message":"Too few arguments to function OC\\App\\AppStore\\Fetcher\\Fetcher::__construct(), 5 passed in /var/www/nextcloud/apps/passwords/lib/Fetcher/NightlyAppFetcher.php on line 92 and exactly 6 expected","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/passwords/lib/Fetcher/NightlyAppFetcher.php","line":92,"function":"__construct","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->"},{"function":"__construct","class":"OCA\\Passwords\\Fetcher\\NightlyAppFetcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":435,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":106,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":114,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":131,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":463,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":145,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Repair.php","line":140,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/Migration/BackgroundRepair.php","line":98,"function":"addStep","class":"OC\\Repair","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OC\\Migration\\BackgroundRepair","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/private/Migration/BackgroundRepair.php","line":71,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OC\\Migration\\BackgroundRepair","type":"->"}],"File":"/var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php","Line":70,"CustomMessage":"Error while running background job (class: OC\\Migration\\BackgroundRepair, arguments: Array\n(\n    [app] => passwords\n    [step] => OCA\\Passwords\\Migration\\AutoBackupRestore\n)\n)"},"id":"61a0393b60ac7"}
```
</details>

**Comment by marius-wieschollek** [comment]
Nextcloud 23 is not yet supported and i think that might also be the cause of the issue. Try to disable nightly updates in the app settings and see if the error is resolved then.

**Comment by rototom** [comment]
I can't downgrade my nextcloud, can I?

**Comment by marius-wieschollek** [comment]
i would not recommend trying that.

**Comment by rototom** [comment]
So, do I have to wait for nextcloud 23 support, or can I do something?

**Comment by marius-wieschollek** [comment]
You can try what i suggested before: Go into the app settings for the passwords app in Nextcloud and disable the option "Shown nightly updates in appstore". That will probably fix your error.
And then you can just wait for a regular update with NC 23 support which will be either 2021.12.0 or 2022.1.0

**Comment by rototom** [comment]
This option already is not checked.

**Comment by TheColin21** [comment]
After updating to Nextcloud 23 stable and enabling the (unsupported of course) passwords app, I experienced the same error. Nightly updates aren't checked here either.

**Comment by marius-wieschollek** [comment]
There is now a first unstable release for NC 23: https://apps.nextcloud.com/apps/passwords/releases?platform=23#23

You can install it manually.

**Comment by iTimELeZz** [comment]
Hey, even with nightly build, I became an internal server error when tried to access the app

**Comment by marius-wieschollek** [comment]
> Hey, even with nightly build, I became an internal server error when tried to access the app

Do you have any error related to this in the nextcloud log?

**Comment by iTimELeZz** [comment]
> 

Yes: 

[passwords] Warnung: Login attempt with invalid session for *user*

GET /apps/passwords/
from 192.168.x.x by *user* at 2021-12-06T10:43:48+01:00

**Comment by marius-wieschollek** [comment]
That's just a warning. if there is an internal server error there should be at least an error or fatal error in the log

**Comment by iTimELeZz** [comment]
my bad:

	Exception: Unable to verify user 
/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php - line 359:
OCA\Passwords\Services\EnvironmentService->loadUserInformation()
/var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php - line 185:
OCA\Passwords\Services\EnvironmentService->determineAppMode()
<<closure>>
OCA\Passwords\Services\EnvironmentService->__construct()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:
ReflectionClass->newInstanceArgs()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:
OC\AppFramework\Utility\SimpleContainer->buildClass()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:
OC\AppFramework\Utility\SimpleContainer->resolve()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:
OC\AppFramework\Utility\SimpleContainer->query()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:
OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:
OC\AppFramework\DependencyInjection\DIContainer->query()
<<closure>>
OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:
array_map()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:
OC\AppFramework\Utility\SimpleContainer->buildClass()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:
OC\AppFramework\Utility\SimpleContainer->resolve()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:
OC\AppFramework\Utility\SimpleContainer->query()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:
OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:
OC\AppFramework\DependencyInjection\DIContainer->query()
<<closure>>
OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:
array_map()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:
OC\AppFramework\Utility\SimpleContainer->buildClass()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:
OC\AppFramework\Utility\SimpleContainer->resolve()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:
OC\AppFramework\Utility\SimpleContainer->query()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:
OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:
OC\AppFramework\DependencyInjection\DIContainer->query()
<<closure>>
OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:
array_map()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:
OC\AppFramework\Utility\SimpleContainer->buildClass()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:
OC\AppFramework\Utility\SimpleContainer->resolve()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:
OC\AppFramework\Utility\SimpleContainer->query()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:
OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 87:
OC\AppFramework\DependencyInjection\DIContainer->query()
<<closure>>
OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensiti ... *")
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 106:
array_map()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 114:
OC\AppFramework\Utility\SimpleContainer->buildClass()
/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 131:
OC\AppFramework\Utility\SimpleContainer->resolve()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 463:
OC\AppFramework\Utility\SimpleContainer->query()
/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 435:
OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
/var/www/nextcloud/lib/private/AppFramework/App.php - line 144:
OC\AppFramework\DependencyInjection\DIContainer->query()
/var/www/nextcloud/lib/private/Route/Router.php - line 302:
OC\AppFramework\App::main()
/var/www/nextcloud/lib/base.php - line 1006:
OC\Route\Router->match()
/var/www/nextcloud/index.php - line 36:
OC::handleRequest()

**Comment by marius-wieschollek** [comment]
What user backend(s) are you using? SAML, LDAP etc.?

**Comment by iTimELeZz** [comment]
> What user backend(s) are you using? SAML, LDAP etc.?

Both backends are in use, SAML and LDAP

**Comment by marius-wieschollek** [comment]
@iTimELeZz I tried LDAP and SAML individually, but neither causes a crash in the app. did this work with NC 22?

**Comment by eglia** [comment]
I'm seeing the exact same error as @iTimELeZz. I only use SAML as backend. Everything was working in NC22.
Nextcloud Hub II (23.0.0)
PHP 8.0.13

**Comment by eglia** [comment]
I did some debugging, the problem is here:
https://github.com/marius-wieschollek/passwords/blob/ac8cb5056b50be0cd2d6bca8ab0051167ee7b0e3/src/lib/Services/EnvironmentService.php#L505
for me, `$loginCredentials->password` is null, which is not covered by this check.
When I change the line to:
``} else if(!isset($loginCredentials->password) || empty($loginCredentials->password)) { ``
the app now loads successfully, but I have no idea if that is a security problem or anything like that...

**Comment by iTimELeZz** [comment]
> I did some debugging, the problem is here:
> 
> https://github.com/marius-wieschollek/passwords/blob/ac8cb5056b50be0cd2d6bca8ab0051167ee7b0e3/src/lib/Services/EnvironmentService.php#L505
> 
> 
> for me, `$loginCredentials->password` is null, which is not covered by this check.
> When I change the line to:
> `} else if(!isset($loginCredentials->password) || empty($loginCredentials->password)) { `
> the app now loads successfully, but I have no idea if that is a security problem or anything like that...

tried this on my instance, and worked..
So @marius-wieschollek Would this be a fix, or is this relevant to the code, and a security issue?

**Comment by marius-wieschollek** [comment]
NC 23 is now supported
