### ISSUE TITLE
Similar function to daily backup calendar/contacts for passwords

### ISSUE THREAD

**Issue by Emporea** [marius-wieschollek/passwords#459]
It could be very usefull ( if you dont want to access your lost passwords via a database backup, after you have decrypted it after you figured out how) to make backups of passwords (encrypted obviuosly) on a daily basis directly into a nextcloud folder.

**Comment by marius-wieschollek** [comment]
Please no low effort tickets. 
Fill out the feature request form properly and read the manual, e.g. this: https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Backups .

**Comment by Emporea** [comment]
Thanks for the link. I wasnt aware of that. Maybe a real feature request could be to add a text that gives a hint about automatic updates to the user. But also if that should be the case and one doesn't have access to a root terminal, then getting a backup is still too "admin-dependend".

It should be able to add backup files directly into the user folder. Otherwise its not accessible.
