### ISSUE TITLE
Not really a feature request. A question.

### ISSUE THREAD

**Issue by Emporea** [marius-wieschollek/passwords#460]
Why is this app not featured? It offers almost a native nextcloud environment unlike [passman](https://github.com/nextcloud/passman).
What are the restriction, or is this information not publicly available and decided internally in the nextcloud team?

**Comment by marius-wieschollek** [comment]
**Please don't use the issue tracker for questions**

It is very clearly stated on the new issue page that questions should be posted in the forum or the chat group.

**Comment by Emporea** [comment]
Thanks for the answer. I understand now :)
