### ISSUE TITLE
Ability to exclude certain passwords for security check

### ISSUE THREAD

**Issue by wouterVE** [marius-wieschollek/passwords#463]
**Current Status**
In the 'security' view you can check for compromised passwords, which is great from security perspective.
I also use passwords to store PIN codes (for bank accounts, mobilie phones...) and due to their nature (short numeric codes) there's a big change they show up in breached passwords databases. 
So in my case 95% of the compromised passwords are PIN codes. It would be nice to have a feature to exclude them from the security scan as there's not real security issue as they belong to a physical device.

**Feature Description**
Have an option to exclude certain items from security scan. 
OR
Add an additional default field "PIN" which is excluded from security scan

**Additional context**
This is only a nice-to-have, you may ignore this request if it's to much work. A user workaround would be to add manually a text field to enter the PIN code

**Comment by marius-wieschollek** [comment]
I don't think giving users the option to disable security warnings is a good idea. If your PIN is insecure, just simply live with that.
If the PIN belongs to another account, you can store it as secret in a custom field.

If you really want the flag gone at all costs, go into settings, switch to advanced, disable the security hash, disable the duplicate check. Then save the PIN as a new password and delete the old one (incl. from the trash). then enable the security hash and duplicate check and reload the app. This needs to be done everytime the entry is changed.

**Comment by wouterVE** [comment]
OK fair point, security-wise it could be bad idea to disable security warnings (especially if you don't know what you're doing).
I think I just enter the PIN in a custom text field so that it won't be checked anymore.

Thanks for your reply/
