### ISSUE TITLE
Make umlauts (äöü) selectable like numbers and special characters

### ISSUE THREAD

**Issue by nilskamm** [marius-wieschollek/passwords#464]
**Current Status**
When generating a password umlauts (äöü) are used. I had trouble using these characters with some systems.
**Feature Description**
Would be nice to have the possibility to activate / deactivate them seperetly like numbers or special characters.

**Comment by ghost** [comment]
Yes, please!

**Comment by marius-wieschollek** [comment]
Duplicate #97
