### ISSUE TITLE
HTTPS not detected properly

### ISSUE THREAD

**Issue by mobamoba** [marius-wieschollek/passwords#47]
Describe your issue here and remember not to include personal data as this is public.

### System Information
- Nextcloud Version: 13.0.2
- PHP Version: 7.2
- Passwords Version 2018.5.2

### Steps to reproduce
Using Nextcloud behind Nginx reverse proxy and HTTPS not detected even though it's working perfectly fine.

### Actual result
HTTPS failure in Passwords app.

### Expected result
Passwords app should work since HTTPS is working.

I browsed through closed threads about this issue. My config.php has both 'overwriteprotocol' => 'https', and 'forcessl' => true, and I'm still having this issue. There are no errors in the Nextcloud logs and https is working perfectly in Nextcloud. Any idea how to overcome this issue? Thanks.

**Comment by marius-wieschollek** [comment]
`forcessl` is no longer used. Can you go to the admin settings page of passwords and check if there are any red warnings on the top? If not please open the passwords app and check if the url ends with `?https=false`.

**Comment by mobamoba** [comment]
There's this red warning:
 Passwords does not support AJAX cron jobs. Please check the system requirements. 

ETA: I changed from AJAX to regular cron and that didn't solve the problem (though it did get rid of the red warning).

**Comment by marius-wieschollek** [comment]
The Ajax issue only affects the execution of cronjobs. Can you install the [latest nightly version 2018.6.0-build2247](https://apps.nextcloud.com/apps/passwords/releases?platform=13#13) from the app store. It has an option to debug the HTTPS detection. If you enable it, it should add a little box in the right lower corner which contains all relevant variables.

**Comment by mobamoba** [comment]
Clicking that option gives me a "Connection to Server Lost" every time and then the page reloads with it unclicked. Just FYI: server is working fine and everything else is connected to it perfectly.

**Comment by marius-wieschollek** [comment]
You can try again with the version 2018.6. If you get an connection lost error, there should be some kind of log entry in the nextcloud log. Alternatively you can set the app setting `debug/https` to 1 with the command line tool.

**Comment by mobamoba** [comment]
2018.6 gave the same error. I don't know how to use the command line. What command should I enter where?

**Comment by marius-wieschollek** [comment]
Can you check the nextcloud protocol if there are any errors? Which kind of database are you using?

**Comment by mobamoba** [comment]
This is the only log output related to passwords and I'm using MYSQL:

Debug | passwords | Could not find resource file "/apps/passwords/js/Helper/compatibility.js"
-- | -- | --

**Comment by marius-wieschollek** [comment]
The command line command would be `./occ config:app:set passwords debug/https --value 1`.
You need to execute this command from the root directory of your Nextcloud installation.

I will check if i can find something related to the error.

**Comment by mobamoba** [comment]
Okay here's the output. I don't know about the PHP stuff but here's the relevant part of my config.php - the detection is clearly getting it wrong somewhere (I replaced the actual information for security purposes here):

    'overwritehost' => 'MYDOMAIN.COM',
    'overwriteprotocol' => 'https',
    'overwritecondaddr' => '^###\.###\.#\.##$',


Passwords HTTPS Detection Details
--
Passwords detects HTTPS enabled | false
Client reports HTTPS enabled | true
Nextcloud detected protocol | http
Nextcloud overwriteprotocol | not set
Nextcloud overwritecondaddr | not set
PHP $_SERVER['HTTPS'] | not set
PHP $_SERVER['REQUEST_SCHEME'] | http
PHP $_SERVER['HTTP_X_FORWARDED_PROTO'] | not set

**Comment by marius-wieschollek** [comment]
The https detection debugger is using the data provided by Nextcloud itself. You can look at the [code](https://github.com/marius-wieschollek/passwords/blob/master/src/templates/partials/https_debug.php) for that.
Passwords is using the data from `Client reports HTTPS enabled` and `Nextcloud detected protocol` to determine if https is used.
Nextcloud does either not read your configuration correctly or there is something missing. Have you set `trusted_proxies` as well?

**Comment by mobamoba** [comment]
Yes. I've been using Nextcloud behind an Nginx proxy for years with no problem. My trusted proxies settings are correct.

As I mentioned, I don't know where the PHP settings are but the code is getting wrong data from my config.php for sure as those parts of my Nextcloud instance are actually set.

**Comment by marius-wieschollek** [comment]
I just checked the https debugger on my server where i have a similar setup. `overwriteprotocol` and `overwritecondaddr` should have values as soon as the variables are set within the config.php.

Nextcloud has several ways of detecting https. Either `$_SERVER['HTTPS']` is set or `$_SERVER['HTTP_X_FORWARDED_PROTO']` is set or `$_SERVER['REMOTE_ADDR']` matches the regex in `overwritecondaddr` and `overwriteprotocol` is set. You can check how Nextcloud does this in [their code](https://github.com/nextcloud/server/blob/stable13/lib/private/AppFramework/Http/Request.php#L641).

As i said before, passwords relies on the `Nextcloud detected protocol` to know if https is enabled. So passwords itself works as designed since Nextcloud reports `http` as protocol.

You can check the Nextcloud configuration from the command line with the `./occ config:system:get overwriteprotocol` command.

`$_SERVER['HTTP_X_FORWARDED_PROTO']` is an http header which should be set by your proxy.
With nginx the configuration will look like this
```
server {
    listen  443 ssl;
    server_name nextcloud.example.com;

    …

    proxy_set_header  Host              $host;
    proxy_set_header  X-Real-IP         $remote_addr;
    proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header  X-Forwarded-Proto https;
}
```
on Apache this should do the job
```
<VirtualHost *:443>
    RequestHeader set X-Forwarded-Proto "https"
    …
</VirtualHost>
```

`$_SERVER['HTTPS']` is usually set by the actual server. Apache usually does this automatically.
If you use PHP-FPM with nginx , you need to set it manually.
```
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;

        …

        fastcgi_param HTTPS on;
    }
```

**Comment by mobamoba** [comment]
Thanks for the patience. The issue was that the three overwritexxx in my config.php were WITHIN an array. Somehow Nextcloud has been unbothered by this for the past few years and your app's HTTPS check pointed me towards the problem, so thanks.

**Comment by marius-wieschollek** [comment]
I can understand that. When i opened my config today, i noticed that the formatting of the arrays is very unreadable and you can't really tell which array you're currently in.

So is the HTTPS problem now solved?

**Comment by mobamoba** [comment]
Yes thanks. Moving those statements out of the arrays and into the main section took care it.

**Comment by marius-wieschollek** [comment]
Great. I just noticed that you also asked on the Nextcloud forums and i somehow didn't notice. Since issues with https seem to be quite common i will post a link to here over there.

**Comment by cracker0dks** [comment]
had the same problem behind a nginx reverse proxy after upgrading to oc15, solved it by adding: 
'overwriteprotocol' => 'https',
to the nextcloud config.php.

Setting  fastcgi_param to https at nginx was not helping...
