### ISSUE TITLE
Unmark entry as weak/duplicate once duplicate entries have been removed

### ISSUE THREAD

**Issue by rmbleeker** [marius-wieschollek/passwords#475]
**Current Status**
Sometimes online services change the subdomain they use for their login page, or they have several. In these cases the browser plugin shows a notification that a new password has been detected. When you save this "new" entry, the Passwords app for Nextcloud marks the two entries as *weak* because they are duplicates. This situation can not be undone except by changing the password or removing both entries and creating a new one, which both aren't very user friendly.

**Feature Description**
The ability to unmark entries as duplicates, or re-initiate the duplicate entries check, so that passwords can be marked *secure* again once duplicate entries have been removed.

**Comment by marius-wieschollek** [comment]
The duplicate check runs every day, so if the password is not considered a duplicate anymore, it will be updated automatically.

A password is considered a duplicate if:
- Any other password has the same hash, including those in the trash.
- Any other password previously had the same hash at any time.

I would recommend you empty the trash and reload the app to see if it's still marked as duplicate.

**Comment by rmbleeker** [comment]
Apologies, I had not considered that password hashes in the Trash folder would also be checked against. I've emptied the Trash and will check the status tomorrow. 

Closing request.
