### ISSUE TITLE
Upgrade to 2022.2.11 fails

### ISSUE THREAD

**Issue by Gardakant** [marius-wieschollek/passwords#480]
### System Information
**Server:**
```

 Nextcloud Version: 23.0.0
 PHP Version: 7.4
 Database and Version: MariaDB 10.4.21
 Server OS and Version: debian 11.2
 Passwords Version: 2022.2.11
```

**Client:**
```
 Browser and Version: FF 96.0.3
 Client OS and Version: Windows 10
```

### Steps to reproduce
1. Go to Applications, click to upgrade
2. Brings you to maintenance mode and ask for upgrade
3. clic to upgrade
4. upgrade fails with this error "Invalid query type, expected SELECT query"
5. stays in maintenance mode, needing to disable the Passwords application (using occ) to access Nextcloud again
6. can't active again using occ, keeps complaining about "Invalid query type, expected SELECT query"
7. go back to Applications, clic to upgrade, insults you with "Invalid query type, expected SELECT query" :)

### Expected result
Passwords application upgrade without a probleme, like any other upgrade you provided before ;)

### Actual result
Upgrade fails and you have to disable the Passwords application to access Nextcloud again

### Nextcloud log
Nothing in the logs :(

In the admin section I can see some files didn't pass the integrity check

```
Results
=======
- passwords
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [passwords] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)
```

**Comment by Gardakant** [comment]
didn't see my issue was - I think - a duplicate for #479

**Comment by Gardakant** [comment]
My bad, didn't see that relaease needed php >= 8.0 and maybe that's causing the problem.
Tried to revert to 2022.2.11 with no luck, I get the same error "Invalid query type, expected SELECT query"
Any luck I can get Passwords to work again if I try the upgrade to php8 with 2022.2.21 ?

**Comment by marius-wieschollek** [comment]
> Invalid query type, expected SELECT query

I think you have this issue: https://help.nextcloud.com/t/error-after-update-to-password-2022-2-21/133270

Can you check if this is solved with the nightly update to 2022.2.2?

**Comment by marius-wieschollek** [comment]
Oh, and PHP 7.4 is supported, but if you want to test the nightly, you need to download passwords-lsr.tar.gz from here: https://git.mdns.eu/nextcloud/passwords/-/jobs/13711/artifacts/browse

**Comment by Gardakant** [comment]
lsr didn't work, i'll give a try to 2022.2.2

**Comment by Gardakant** [comment]
Just tested with https://git.mdns.eu/nextcloud/passwords/-/jobs/13711/artifacts/file/passwords.tar.gz
and
```
App "Passwords" cannot be installed because the following dependencies are not fulfilled: PHP 8.0 or higher is required.
```

**Comment by marius-wieschollek** [comment]
what was the error with the lsr version?

**Comment by Gardakant** [comment]
Same error about invalid query type, I'll give a try again

**Comment by Gardakant** [comment]
The lsr nightly build gives another error
```
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'my_owncloud.oc_' doesn't exist
```

**Comment by marius-wieschollek** [comment]
I was able to reproduce this issue. It comes from a query that tries to remove data from the old ocPasswords app that pollutes the shares table.

The passwords-lsr version here fixed the issue for me: https://git.mdns.eu/nextcloud/passwords/-/jobs/13722/artifacts/browse

**Comment by Gardakant** [comment]
I can confirm that LSR 2022.2.12-build4433 worked like a charm, thanx for the fix :)
