### ISSUE TITLE
Fresh install NC23 (arch): The appinfo/database.xml file is not longer supported. Used in passwords

### ISSUE THREAD

**Issue by sdfg2** [marius-wieschollek/passwords#487]
### System Information
**Server:**
```There are no commands defined in the "passwords:system" namespace.```
```
 Nextcloud Version: nextcloud 23.0.2-1 (arch repo version)
 PHP Version: 8.1.3-1
 Database and Version: pgsql 13.6-1
 Server OS and Version: arch
 Passwords Version: whatever one is obtained when pressing the button.  Completely fresh install of nextcloud.  
```

**Client:**
```
 Browser and Version: Chromium, Vivaldi, Firefox same behaviour.
 Client OS and Version: localhost
```

### Steps to reproduce
1. Click install and enable
2. Yellow box comes up "The appinfo/database.xml file is not longer supported. Used in passwords"

### Expected result
What should happen?
It enables.

### Actual result
What does happen?
It doesn't enable.

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"pkQ1ZIGHfFFggZBqB63G","level":3,"time":"2022-03-10T15:01:47+00:00","remoteAddr":"127.0.0.1","user":"sdfg","app":"settings","method":"POST","url":"/nextcloud/settings/apps/enable","message":"could not enable apps","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.2.1","exception":{"Exception":"Exception","Message":"The appinfo/database.xml file is not longer supported. Used in passwords","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":452,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/Installer.php","Line":113,"CustomMessage":"could not enable apps"},"id":"622a13dcaab28"}
```
</details>

**Comment by marius-wieschollek** [comment]
> whatever one is obtained when pressing the button.

Would be interesting to know. Passwords doesn't use the database.xml file in any version compatible with NC 22 or NC 23 (since july 2021)

>  PHP Version: 8.1.3-1

Is not officially supported by the Passwords app or [Nextcloud](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server)

**Comment by sdfg2** [comment]
Yeah it's confusing.  I managed to manually install it, but it won't enable because of the PHP requirements either.  I tried overriding them in SystemRequirements.php but it must not have been the correct place.

**Comment by marius-wieschollek** [comment]
I don't think modifying the checks will fix the issue here. No version compatible with NC 23 ever had a database.xml, so the version you have is just not meant to run on your server.

Nextcloud will likely add support for PHP 8.1 in NC 24 at the end of april, so you can test the [nightly release](https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Guides/Maintenance/Use-Nightlies#download-from-nextcloud-apps) which is marked as compatible with 8.1.

**Comment by sdfg2** [comment]
Oh I'm sorry, I kinda left out the important part: by 'it' I meant the app in general, I manually downloaded the latest stable release from the app website!  Been juggling too many server things, really sorry!  I wish there was a way to figure out what my nextcloud is trying to get though, I haven't seen a problem with any other app (except mail, which doesn't show up at all)

I'll try the nightly, that's a good call.

**Comment by sdfg2** [comment]
Nightly worked a charm.  Not sure if I should keep this open or not?  I mean I guess the original bug hasn't been answered, but not sure where else to go with it?

**Comment by marius-wieschollek** [comment]
I will close this. What happens in the NC appstore is out of my control.
And since your specific system configuration is not supported by any stable version i don't see it as an issue that it didn't work. If the nightly works that's great, the stable release will be in the first week of april.
