### ISSUE TITLE
Passwords web and API slow (50+ seconds)

### ISSUE THREAD

**Issue by boombatower** [marius-wieschollek/passwords#488]
### System Information
**Server:**
```json
{
    "version": {
        "server": "22.2.5.1",
        "app": "2021.12.20",
        "lsr": false,
        "php": "8.0.16"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "legacyApi": {
        "enabled": 0,
        "used": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "random",
        "previewApi": false,
        "faviconApi": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
 Browser and Version: Firefox 97.0.1
 Client OS and Version: openSUSE Tumbleweed 20220303
```

### Steps to reproduce
1. Open Firefox and navigate to Nextcloud.
2. Login.
3. Click password app in Nextcloud after logging in.
4. Wait 50+ seconds to see list of passwords after page loads nearly instantly

### Expected result
Passwords load in a few seconds at most. The passwords used to load quickly, but after some time they stopped, I had other things going on so I didn't really dig into it for a few weeks, but nextcloud is set to auto update.

### Actual result
Page takes nearly a minute to complete loading and times out for browser extension so it doesn't work any more.

### Nextcloud log
No password related log entries.

The server does not spike CPU or memory, it's essentially idle during the entire request.

### Browser log

Nothing interesting in console, but network requests shows two taking 50-60 seconds.

- /index.php/apps/passwords/api/1.0/session/open
- /index.php/apps/passwords/api/1.0/folder/show

###

I can collect addition information as needed. I have yet to dig into the code and start profile it, but doesn't seem like any database or server pressure. The list of passwords is ~200 so nothing crazy.

**Comment by marius-wieschollek** [comment]
Probably NC Bruteforce protection: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html

**Comment by boombatower** [comment]
Thanks, that does seem to be the issue although it doesn't make a lot of sense. I successfully login on browser and I get throttled only when making password app api call (made by the web app within the browser that has a logged in session)? Why is that a new session request? Every single other page on Nextcloud works fine?

Unless I am missing something, at minimum this could use called out somewhere in docs (in the context of web app not fresh session on mobile app or somesuch) so one can find it. Secondly perhaps worth adding some js that fires when either header from nextcloud indicating throttled request or takes longer than N seconds a warning that you might be experiencing...
