### ISSUE TITLE
file attached to the password

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords#489]
**Current Status**
At the moment it is possible to attach a file to a password with a new field, e.g. certificate file, ... (which is needed for login). but as soon as the file is moved in Nextcloud the file attached to the password expires (the webdav access does not update the path).

**Feature Description**
The function that I think would make sense would be to append the file in such a way that no matter if the file is moved it still remains associated with the password. Kind of like Nextcloud Deck.

**Comment by marius-wieschollek** [comment]
This is not possible because the data is encrypted. Since the server doesn't know which file is linked, it can also not track if the file is moved.

**Comment by ghost** [comment]
And how does Nextcloud Deck do that then?

**Comment by marius-wieschollek** [comment]
Nextcloud Deck doesn't have encryption.
When https://github.com/marius-wieschollek/passwords/issues/176 is implemented, it may offer an easier to use alternative to the current way.
