### ISSUE TITLE
Import of CSV,.. into Folder

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [marius-wieschollek/passwords#490]
It would be nice if you can select the folder in which passwords to import will be importat.
Especially if you use CSV-Import.

**Comment by marius-wieschollek** [comment]
You can specify the folder you want to import into in the csv file.

**Comment by GVLLIFESTYLE** [comment]
OK I guess you did not get what I need xD
I want to import a list of passwords without folders into a folder which i previously created in the password app.
Thats currently not possible.
