### ISSUE TITLE
Certificate of Webpage expired

### ISSUE THREAD

**Issue by simaxme** [marius-wieschollek/passwords#494]
### System Information
**Server:**
```json
 Nextcloud Version:
 PHP Version: 8.0
 Database and Version: mariadb (Ver 15.1 Distrib 10.5.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper)
 Server OS and Version: Debian 11
 Passwords Version: Latest
```

When going under the apps page and trying to download the app, curl is unable to download it, because the webpage's certificate expired (webpage: https://git.mdns.eu/nextcloud/passwords/-/jobs/13792/artifacts/raw/passwords.tar.gz). The only way downloading this app currently is downloading it manual with disabling certificate issues and extracting it into the `apps` folder.

**Comment by marius-wieschollek** [comment]
that should be fixed again
