### ISSUE TITLE
Have a setting to limit sharing user list to just users within your group

### ISSUE THREAD

**Issue by aiso-net** [marius-wieschollek/passwords#495]
Current Status
Not possible, shows all system users when doing a share

Feature Description
In the setting of the app have a checkbox to only have the ability to share with users within your NC user assigned group.

Additional context
Useful when you want to only allow sharing with users within your assigned group and not see all users on the system including the admin and other users in other groups.

**Comment by marius-wieschollek** [comment]
The app should follow the NC sharing settings for that

**Comment by aiso-net** [comment]
You are correct, didnt have that box checked under the NC share settings, thanks and sorry.
