### ISSUE TITLE
Self Hosted Screeenly API is invalid

### ISSUE THREAD

**Issue by MartinAirN** [marius-wieschollek/passwords#498]
### System Information
**Server:**
```json
{
    "version": {
        "server": "23.0.3.2",
        "app": "2022.4.20",
        "lsr": false,
        "php": "8.0.17",
        "cronPhp": "8.0.17"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "ddg",
        "previews": "screeenly",
        "security": "hibp",
        "words": "auto",
        "previewApi": true,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
 Browser and Version: Firefox 98.0.2
 Client OS and Version: Windows 10.0.19043
```

### Steps to reproduce
1. Run a selfhosted Screeenly
2. Test with 'Bookmarks' addon -> See that it works with url & API key
3. Set the Screeenly setting on Passwords settings according to: https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/App-Settings#website-preview-service (in format ${URL}?key=${KEY}
4. Save settings
5. Access first passwords details

### Expected result
Screenshots to appear

### Actual result
Screenshots do not appear

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

`{"reqId":"${reqId}","level":3,"time":"2022-04-04T11:22:25+00:00","remoteAddr":"${IPADDR}","user":"${USER}","app":"passwords","method":"GET","url":"/index.php/apps/passwords/api/1.0/service/preview/${DOMAIN}/desktop/640/360...","message":"Screeenly API key is invalid","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"23.0.3.2","id":"${id}"}`
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
None
```
</details>

**Comment by marius-wieschollek** [comment]
Two questions: is the screenly url you're using with https and is your api key 50 characters long?

**Comment by MartinAirN** [comment]
Yes, it is using https (valid cert), and the key itself is 41 long (84 for url+key).

**Comment by marius-wieschollek** [comment]
Well, that seems to be the issue. I assumed that the keys would always be exactly 50 characters.
The entire regex for the value is `^https:\/\/(.+)\?key=(\w{50})$`. I will update it to work with shorter keys aswell.

**Comment by MartinAirN** [comment]
An update on the documentation would also be sufficient. I'm sure we can generate a new key of proper length.
