### ISSUE TITLE
Error: Could not load categories and passwords, app makes server unstable, after moving to this fork

### ISSUE THREAD

**Issue by pafcioooo** [marius-wieschollek/passwords#5]
So I had NC 11 with fcturner/passwords and decided to move to NC12.

I upgraded to NC12 where fcturner/passwords did not work: there were some modal error windows but they appeared outside main window and seemed to be empty.

Then I upgraded to marius-wieschollek/passwords (deleting passwords folder and then gitclone this repository).

Then when I refreshed web browser nextcloud window it showem my upgrade process. That finished with ëmpty screen and internal error information at the top - strange that it doesn not look like an apache internal error).

I refreshed web browser window again and now nextcloud load properly but opening passwords app show to modal error windows:

- Error: Could not load categories

- Error: Could not load passwords 

After clicking both ok, nothing displays but circle like password are loading.

Then I disabled passwords app but while enabling it returns error "Error: this app cannot be enabled because it makes the server unstable".

**Comment by pafcioooo** [comment]
While investigating I saw some errors in log:
1. touch(): Unable to create file /(...)/data/appdata_oc0iyzw01wxw/css/theming/theming.css because No such file or directory at /(...)/lib/private/Files/Storage/Local.php#199
After I have created manually /data/appdata_oc0iyzw01wxw/css/theming/ folder, the error stoped apearing.
Still the app could not be enabled.

2. touch(): Unable to create file /(...)data/appdata_oc0iyzw01wxw/css/files_texteditor/merged.css.deps because Not a directory at /(...)/lib/private/Files/Storage/Local.php#199
After I have created manually /(...)data/appdata_oc0iyzw01wxw/css/files_texteditor/ folder, the error stoppped apearing.
And I could enable the app.

But still openming the app shows "Could not load categories and passwords" errors.

**Comment by pafcioooo** [comment]
After the above actions I have fllowing error in the log file:

  | ParseError: syntax error, unexpected '?'
/***/lib/composer/composer/ClassLoader.php - line 322:  Composer\Autoload\includeFile('/***...')
[internal function] Composer\Autoload\ClassLoader->loadClass('OCA\\Passwords\\H...')
/***/apps/passwords/db/passwordmapper.php - line 22:  spl_autoload_call('OCA\\Passwords\\H...')
[internal function] OCA\Passwords\Db\PasswordMapper->__construct(Object(OC\DB\Connection))
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 79:  ReflectionClass->newInstanceArgs(Array)
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 96:  OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 117:  OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Passwords\\D...')
/***/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 430:  OC\AppFramework\Utility\SimpleContainer->query('OCA\\Passwords\\D...')
/***/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 408:  OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Passwords\\D...')
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 66:  OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Passwords\\D...')
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 96:  OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 117:  OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Passwords\\S...')
/***/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 430:  OC\AppFramework\Utility\SimpleContainer->query('OCA\\Passwords\\S...')
/***/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 408:  OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Passwords\\S...')
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 66:  OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Passwords\\S...')
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 96:  OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
/***/lib/private/AppFramework/Utility/SimpleContainer.php - line 117:  OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\Passwords\\C...')
/***/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 430:  OC\AppFramework\Utility\SimpleContainer->query('OCA\\Passwords\\C...')
/***/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 408:  OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\Passwords\\C...')
/***/lib/private/AppFramework/App.php - line 101:  OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\Passwords\\C...')
/***/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:  OC\AppFramework\App  main('OCA\\Passwords\\C...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/***/lib/private/Route/Router.php - line 299:  call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/***/lib/base.php - line 1000:  OC\Route\Router->match('/apps/passwords...')
/***/index.php - line 40:  OC  handleRequest(){main}

*** masks the path to to nextcloud root folder.

**Comment by marius-wieschollek** [comment]
Could you check if your server is running on PHP 7.1?

If not, you need to this file: lib/Helper/DatabaseHelper.php
You can find the source code here: https://github.com/marius-wieschollek/passwords/issues/3#issuecomment-310895936

**Comment by pafcioooo** [comment]
Thanks @marius-wieschollek 
Since my server is running 7.0.18 (Ubuntu 16.04) I have removed original lib/Helper/DatabaseHelper.php and created new with this #3 (comment).
Now passwords work ok.

**Comment by osos** [comment]
Worked for me to.

Maybe be fix should be included in the repo or autodetect if php 7.0 which is default on ubuntu 16.04
