### ISSUE TITLE
New password generation needs more variety

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#5]
I suspect this is already todo, but currently the two options are both entirely letter based (and quite short).

I've already run in to the issue that a website REQUIRES a number, but neither automatic option provide this.

Also a length option would be desirable as well as a special char option like the old app.

**Comment by marius-wieschollek** [comment]
Your suspicion is correct. The backend already supports more variety, but you can not set these options anywhere in the frontend.

**Comment by marius-wieschollek** [comment]
Version 2018.3 will allow to change the default settings in the settings page.
Version 2018.4 will also allow to change the settings in the create dialog and improve the algorithms in the backend.
