### ISSUE TITLE
All passwords marked as breached when using haveibeenpwned.com

### ISSUE THREAD

**Issue by mitchy112** [marius-wieschollek/passwords#50]
### System Information
- Nextcloud Version:
13.0.2
- PHP Version:
7.1.16
- Passwords Version
  2018.5.2
- Browser and Version:
Not applicable since its not an issue with my browser
- Client OS and Version:
Not applicable since its not an issue with my OS
- Server OS and Version:
Ubuntu 16.04.2

### Steps to reproduce
1. Set HIBP as source for password security checks
2. Create a password which is not breached

### Actual result
All my passwords seem to have been breached, but when i look for them on the haveibeenpowned website they aren't breached. How is this possible that all of my passwords get this insecure status when the source where it checks (haveibeenpowned) doesn't report them as breached?
Im reporting this since i found it really weird that all of my passwords have been breached, since some of them have been generated by the passwords app and are not for online services, but for use only internally so they cannot have been leaked.

### Expected result
They shouldn't have been reported as breached, since the website doesn't report them as breached.

**Comment by marius-wieschollek** [comment]
The api endpoint for th haveibeenpwned.com password check has been changed. The old api endpoint now always delivers a `200 OK` http status which signals that the requested password has been found in the database. Therefore this error will probably affect anyone using the endpoint.

I will deliver a nightly build which fixes this error soon. It will also revalidate your passwords.

**Comment by marius-wieschollek** [comment]
The nightly build [2018.6.0-build2277](https://apps.nextcloud.com/apps/passwords/releases) solves this issue. The stable build will be available within the next days.

It will clear the bad passwords cache and clear the security status of all bad passwords. This means that all passwords will be reported as "good" even if they aren't. The correct security status will be reported as soon as the passwords security check background job has been executed. This usually happens once a day.

Thanks for reporting this error.
