### ISSUE TITLE
Download single passwords for example as .txt or similar

### ISSUE THREAD

**Issue by ghost** [marius-wieschollek/passwords#501]
**Current Status**
Single passwords cannot be downloaded.

**Feature Description**
Download individual passwords as in file management with a right click and then on download.

**Comment by marius-wieschollek** [comment]
Can you add some more details?
Is this to export & import the password again later or just a one time export of the password as a text file?

**Comment by ghost** [comment]
Both would be great.  It's about passing on passwords to people who are not in the same NC instance.  Or to download and backup a single password.  But an export and import into another account would also be conceivable.

**Comment by marius-wieschollek** [comment]
Not sure if this helps you, but the upcoming version of passwords will contain an optional "print password" option that can be enabled in the advanced settings.

**Comment by ghost** [comment]
I can imagine little under it but I wait for the version :)
