### ISSUE TITLE
Error creating user: The username *** is queued for deletion

### ISSUE THREAD

**Issue by VincentSC** [marius-wieschollek/passwords#509]
The function `preventCreationIfDeleted` has a check that prevents a previously deleted user to be recreated.

Expected behavior is that the user's password-data is deleted, instead of giving a blocking message.

See also https://github.com/nextcloud/server/issues/10297

**Comment by marius-wieschollek** [comment]
Not a bug, read the f.a.q. https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/F.A.Q#why-cant-i-reuse-an-existing-user-name

**Comment by VincentSC** [comment]
Understand that the work-around is to temporarily disable the passwords app, while the oauth-user logs in. So if the app is preventing certain behavior, why is this a work-around? And just think what a sysadmin has to do, if all apps did the same and the sysadmin has to provide a `app:user:delete` command to get the user logged in again - if they all have wikis, this is *not* improving the user-experience of NC. And the latter is important to me.

Context: the oauth-user was deleted a month ago, to do a full reset on his account. It was really gone. The cron-job seemingly had problems (a warning in the admin screen). Software cannot assume a perfect environment - all assumptions are bugs in my eyes.

I would simply not depend on cron-job alone, and the clean-up can so be triggered by an event like this. Or connect to the occ command `user:delete`.

I also suggest to redo the check if the user is queued for deletion. My suggestion is to use the NC-functions that tell if a user does not exist, as that should be leading. 

It could also be that the passwords' cron-job only checks for *recent* users?

I'm happy to check the code.
