### ISSUE TITLE
Firefox broken : unable access password fields

### ISSUE THREAD

**Issue by PhieF** [marius-wieschollek/passwords#51]
There is a bug a latest firefox version (here is 60) 
Clicking on a password field on the extension popup immediately closes the popup

here is the bug report

https://bugzilla.mozilla.org/show_bug.cgi?id=1461591

Any thought on a workaround ?

**Comment by marius-wieschollek** [comment]
I thought about making a tranparent text field and putting it over the password field, but that does not have good user feedback. So maybe just a textfield with thisfont: https://fontstruct.com/fontstructions/show/1069549/write_your_password_with_this_font

**Comment by marius-wieschollek** [comment]
What do you think? You can install the extension on the about:debugging page:
[passwords-webextension-1.5.1c.zip](https://github.com/marius-wieschollek/passwords/files/2063190/passwords-webextension-1.5.1c.zip)

**Comment by marius-wieschollek** [comment]
The version 1.5.1c with this workaround is now available on AMO: https://addons.mozilla.org/de/firefox/addon/nextcloud-passwords/

**Comment by PhieF** [comment]
thanks, sorry for being late, it worked :)))
