### ISSUE TITLE
Version clarification on migration page

### ISSUE THREAD

**Issue by brjhaverkamp** [marius-wieschollek/passwords#512]
Hi Marius,

I discovered (way overdue) that I am using a legacy version of passwords. So I have to migrate.
I found your excelent  migration guide https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Guides/Maintenance/Legacy-Migration

However, I was lost for a while on what version of passwords to use. At the top it states: "You need to use [2019.12.1](https://git.mdns.eu/nextcloud/passwords/-/jobs/9150/artifacts/raw/passwords.tar.gz) for the migration" But in the text further down, this is contradicted with "Install the newest version of Passwords from the [app store](https://apps.nextcloud.com/apps/passwords)."
I assume (yet to be tested, the line at the top is overruling the "install the newest". But it would be good to make it consistent for everyone following after me, if you have some time. 

I am also curious what
 ./occ config:app:set passwords installed_version --value 2017.12
does. Do I really have to set the version back to 2017? (instead of 2019.12) and if so why 

Regards,

Bert

**Comment by marius-wieschollek** [comment]
This isn't a bug report, this is a question. Please move it to the forum.

**Comment by brjhaverkamp** [comment]
Hi Marius,

I would think it is a bugreport! The issue is contradictory text in the migration guide.
1) At the top it states: "You need to use [2019.12.1](https://git.mdns.eu/nextcloud/passwords/-/jobs/9150/artifacts/raw/passwords.tar.gz) for the migration"
2) Further down, this is contradicted with "Install the newest version of Passwords from the [app store](https://apps.nextcloud.com/apps/passwords)."

I would agree it is not the highest prio bug, and I also agree I phrased it a bit too much like a question. I also shouldn't have added the followup question, in hindsight. I will follow up on the forum for that one.

Regards,

Bert
