### ISSUE TITLE
Error: Constant FILTER_SANITIZE_STRING is deprecated

### ISSUE THREAD

**Issue by vincentstans** [marius-wieschollek/passwords#514]
Using php8.1-fpm 

`[PHP] Fout: Error: Constant FILTER_SANITIZE_STRING is deprecated at /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php#621 at <<closure>>

 0. /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php line 621
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php line 557
    OCA\Passwords\Services\EnvironmentService->getClientFromRequest()
 2. /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php line 504
    OCA\Passwords\Services\EnvironmentService->getUserInfoFromPassword()
 3. /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php line 375
    OCA\Passwords\Services\EnvironmentService->loadUserFromSession()
 4. /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php line 359
    OCA\Passwords\Services\EnvironmentService->loadUserInformation()
 5. /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php line 185
    OCA\Passwords\Services\EnvironmentService->determineAppMode()
 6. <<closure>>
    OCA\Passwords\Services\EnvironmentService->__construct()
 7. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    ReflectionClass->newInstanceArgs()
 8. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
 9. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
10. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
11. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 437
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
12. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 89
    OC\AppFramework\DependencyInjection\DIContainer->query()
13. <<closure>>
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
14. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    array_map()
15. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
16. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
17. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
18. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 437
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
19. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 89
    OC\AppFramework\DependencyInjection\DIContainer->query()
20. <<closure>>
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
21. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    array_map()
22. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
23. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
24. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
25. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 437
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
26. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 89
    OC\AppFramework\DependencyInjection\DIContainer->query()
27. <<closure>>
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
28. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    array_map()
29. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
30. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
31. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
32. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 437
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
33. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 89
    OC\AppFramework\DependencyInjection\DIContainer->query()
34. <<closure>>
    OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}("*** sensitive parameters replaced ***")
35. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 108
    array_map()
36. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 116
    OC\AppFramework\Utility\SimpleContainer->buildClass()
37. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 133
    OC\AppFramework\Utility\SimpleContainer->resolve()
38. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 465
    OC\AppFramework\Utility\SimpleContainer->query()
39. /var/www/nextcloud/lib/private/ServerContainer.php line 145
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
40. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 57
    OC\ServerContainer->query()
41. /var/www/nextcloud/lib/private/Notification/Manager.php line 206
    OC\AppFramework\Utility\SimpleContainer->get()
42. /var/www/nextcloud/lib/private/Notification/Manager.php line 372
    OC\Notification\Manager->getNotifiers()
43. /var/www/nextcloud/apps/notifications/lib/Controller/EndpointController.php line 111
    OC\Notification\Manager->prepare()
44. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Notifications\Controller\EndpointController->listNotifications()
45. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
46. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
47. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
48. /var/www/nextcloud/ocs/v1.php line 62
    OC\Route\Router->match()
49. /var/www/nextcloud/ocs/v2.php line 23
    require_once("/var/www/nextcloud/ocs/v1.php")`

I've changed line 621 **FILTER_SANITIZE_STRING** to **FILTER_UNSAFE_RAW** and not get the message anymore.

**Comment by marius-wieschollek** [comment]
Please use on of the options on the new issue page to report a bug or request a feature.

Replacing FILTER_SANITIZE_STRING with FILTER_UNSAFE_RAW is certainly adding a security vulnerability to the app
