### ISSUE TITLE
Request Image Rendering support for Imaginary

### ISSUE THREAD

**Issue by armouredking** [marius-wieschollek/passwords#515]
**Current Status**
Passwords Image Rendering only supports PHP GDLib and G|Imagick.

**Feature Description**
Allow to pull in / send processing request to Imaginary as well, see https://github.com/nextcloud/server/pull/24166

**Additional context**
Imaginary is new for NC24, so there will likely be growing pains. But it's supposed to be a far better option, and it's more secure regardless. I am currently using it in lieu of Imagick and have not yet encountered issues doing so. I can see it being used in Imaginary's log output so I know NC is using it.

NC seems to be setup for [the following](https://github.com/nextcloud/server/blob/0d929086d0c4d67e80e8d77ba0cdf117ddae69db/lib/private/Preview/Imaginary.php#L59) currently, but [the app](https://github.com/h2non/imaginary) is actually capable of doing more than this.

**Comment by marius-wieschollek** [comment]
Imaginary support is now available in the latest nightly build.
