### ISSUE TITLE
PW-Addon in Kiwi-Browser fails

### ISSUE THREAD

**Issue by robshnup** [marius-wieschollek/passwords#516]
Installing the browser add-on with Kiwi-Browser is no problem. But it does not fill any fields.

With newest browser and android-version (12) I get the old-hand message:
“Could not establish connection. Receiving end does not exist”

The old thread from 2019 doesn’t help because the mentioned options don’t exist in new NC (24.02). And the hint on the passwords-wiki concerning Kiwi-Browser doesn’t equally exist in modern kiwi://flags.

What can I do?
Regards Rob

**Comment by robshnup** [comment]
Pushed to passwords-webextension...

**Comment by marius-wieschollek** [comment]
> Pushed to passwords-webextension...

What does that mean?
