### ISSUE TITLE
The backend of this app uses insecure method(http) to obtain the corpus as the source of entropy for the password

### ISSUE THREAD

**Issue by jimlinntu** [marius-wieschollek/passwords#517]
https://github.com/marius-wieschollek/passwords/blob/cd1e6b9df57e95282af966dbf750749d68ccc08f/src/lib/Helper/Words/LeipzigCorporaHelper.php#L19

**Comment by marius-wieschollek** [comment]
Yes, that is correct. The service is not available with HTTPS
