### ISSUE TITLE
Using middle mouse Button -> reevaluate please

### ISSUE THREAD

**Issue by florom** [marius-wieschollek/passwords#518]
Hi Devs,

Is it possible to reevaluate this Feature request?

https://github.com/marius-wieschollek/passwords/issues/127

3 years have passed, so probably there are new possibilities.
Today I came accross the click and double click actions,
which are configurable (I did not know that).
A third click possibility would be really nice. (Website, Username, Password).

Since it is closed I cannot post in it so I (unfortunatly) had to open a new topic.
If filling out the whole form is necessary I will happily do that on request.

Thank you.

EDIT (as reqeusted):

**Current Status**
There are only two options to quickly copy password details.
Click and Doubleclick
but there are in my opinion 3 crucial details.
Website, Username, password
so one of it cannot be copied quickly.
In  https://github.com/marius-wieschollek/passwords/issues/127 it is described
that the Middle Mouse button cannot be used for actions.
Since 3 years have passed probably it is possible to reevaluate the again 
and there might be another outcome.

**Feature Description**
New possible click action: Middle mouse

**Additional context**
 - Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
 - passwords: 2022.6.10
 - php 7.4.28
 - Nextcloud 23.0.6.1
 - Apache/2.4.53 (Debian) (apache2handler)

**Comment by marius-wieschollek** [comment]
Please stick to the form when requesting features

**Comment by florom** [comment]
@marius-wieschollek  

ok, done.
