### ISSUE TITLE
Reevaluate Middle Mouse as Copy Click action

### ISSUE THREAD

**Issue by florom** [marius-wieschollek/passwords#519]
Hi Devs,

**Current Status**
There are only two options to quickly copy password details.
Click and Doubleclick
but there are in my opinion 3 crucial details.
Website, Username, password
so one of it cannot be copied quickly.
In https://github.com/marius-wieschollek/passwords/issues/127 it is described
that the Middle Mouse button cannot be used for actions.
Since 3 years have passed probably it is possible to reevaluate the again
and there might be another outcome.

**Feature Description**
New possible click action: Middle mouse

**Additional context**
Since it is closed I cannot post in it so I (unfortunatly) had to open a new topic,
and the new topic was closed ( https://github.com/marius-wieschollek/passwords/issues/518 ) and I have the feeling that it won't be reopend.

Linux 5.10.0-13-amd64 
https://github.com/marius-wieschollek/passwords/pull/1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
passwords: 2022.6.10
php 7.4.28
Nextcloud 23.0.6.1
Apache/2.4.53 (Debian) (apache2handler).

Thank you.

**Comment by marius-wieschollek** [comment]
The middle mouse clipboard function as it is known from linux is the latest selection made by the user.
I have not found any way to automatically write to this buffer.

The best thing i could implement would be a middle mouse action which can be configured to copy to the default clipboard.

**Comment by florom** [comment]
Hi marius-wieschollek ,

Thanks for the reply.

"a middle mouse action which can be configured to copy to the default clipboard"

That seems to me like an addtional field in here:
![image](https://user-images.githubusercontent.com/32240626/186156195-818380c9-1dc7-4d62-8aab-553a82429b71.png)

Which is exactly what I intended. That would be great.

**Comment by marius-wieschollek** [comment]
ok. i will add it

**Comment by florom** [comment]
Thank you.

**Comment by florom** [comment]
@marius-wieschollek 
It works perfect.
Thanks for Adding 
"Open Url" makes it even better
