### ISSUE TITLE
Launching Passwords app kill External Storage

### ISSUE THREAD

**Issue by zippytiff** [marius-wieschollek/passwords#53]
So i have found that after being in Passwords App, if i go back to my File list (which is only made up of External Storage mounts), they are then not accessible.

The Auth against External mounts, when this fails is
- SMB / CIFS
- Login credentials, save in database
- which is authenticated against AD via LDAP setup

I did notice that if the external mounts uses these settings its ok
- SMB / CIFS
- Username & Password
- which is just a local user on a remote unix box

Also when in this 'state' the desktop client can also no longer sync those external mounts either !

Thanks

ZT

**Comment by marius-wieschollek** [comment]
Can you check the Nextcloud log for any errors related to this?

**Comment by zippytiff** [comment]
Will do, can you confirm which log/file etc and i will provide

**Comment by marius-wieschollek** [comment]
I mean the Nextcloud log which you can access in the Nextcloud admin area. (See "Settings" > "Logging")

**Comment by zippytiff** [comment]
ok, thanks for confirming

i have debug level on, but nothing shows (abnormal that is) in the logging

Let me know if i can do any more debug

to resolve, i need to logout and log back in again BTW

**Comment by zippytiff** [comment]
only lines on clicking the password app are, these dont happen, when i click to the files normally

I have removed customer entries in the LDAP search, which why it looks a little empty

Debug | user_ldap | Turned off SSL certificate validation successfully. | 2 minutes ago
-- | -- | -- | --
Debug | user_ldap | Ready for a paged search | 2 minutes ago
Debug | user_ldap | initializing paged search for Filter (&(\|(\|(memberof=CN=_Uniquity Users,OU=<REMOVED> Users,DC=<REMOVED>,DC=<REMOVED>)(primaryGroupID=3661)))(samaccountname=<REMOVED>)) base Array ( [0] => dc=<REMOVED>,dc=<REMOVED>) attr Array ( [0] => entryuuid [1] => nsuniqueid [2] => objectguid [3] => guid [4] => ipauniqueid [5] => dn [6] => uid [7] => samaccountname [8] => memberof [9] => sAMAccountName [10] => [11] => [12] => sAMAccountName [13] => displayname [14] => jpegphoto [15] => thumbnailphoto ) limit 500 offset 0 | 2 minutes ago
Debug | user_ldap | Turned off SSL certificate validation successfully. | 2 minutes ago

**Comment by zippytiff** [comment]
Hi,

Any thoughts ? anything else i can do ?

- I have confirmed that my ealier comment about the client not working at this time, may be wrong
- If i change the auth on the external folder to 'Login credentials, save in session', then it works again for that test, but the other using 'Login credentials, save in database', dont work.  I cant use this as a solution as then the ios client stops working

Perhaps the passwords app is locking or deleting the necessary details from the credentials database, which then get refreshed when i logout/log back in again

I did once, after a period of time, see the folders become available again, but not been able to repeat (yet!), to know what timeframe this is/was

Keen to get this resolved, passwords app is brilliant !

ZT

**Comment by marius-wieschollek** [comment]
I didn't have time to look at this at the weekend, so i will look at this later.

**Comment by zippytiff** [comment]
Thanks,

I have spent last hour trying the replicate the 'folders becoming available again', it can range from 2 to 20mins, but eventually the folders will reconnect. likely due to the ldap refresh.... i will do some more testing

Regards

ZT

**Comment by zippytiff** [comment]
i tried the ldap cache clear time, made no difference

so my gut feel is the database is being locked by opening passwords app somehow....

**Comment by marius-wieschollek** [comment]
Ok, I think after digging trough the documentation i know what the problem is. The option `Login credentials, save in database` will use the users password to access the smb share. Passwords uses an Auth-Token to access its own api. This token does not have a "backup" copy of the actual user password (which tokens usually have). Even if passwords token does not have file system access, the external storage app still tries to access the smb share which then fails because no password is available. After that the smb share is suspended for ten minutes until the external storage app tries to access it again.

Passwords Nightly 2018.7.0-build2321 will store the password when creating a new token. You can download it from the [app store](https://apps.nextcloud.com/apps/passwords/releases) and install it manually or just enable the `Enable Passwords Nightly Builds` option in the passwords admin settings and wait until Nextcloud asks you to update.
_After installing the update you need to go to your personal settings and delete the "Passwords WebUi Acces Token" in the security section._ Passwords will then create a new token the next time you open the app.

**Comment by zippytiff** [comment]
Hi,

im probably being dumb, but:

1. how do i install correctly these beta builds ? i tried untaring into the apps folder
2. how do see what version i have installed, to check step 1 worked

But the good news is, after i deleted the token the fix worked..... will i need to get all the users to delete their token now ?

Thanks, top job !

ZT

**Comment by marius-wieschollek** [comment]
You can install the nightly manually by just unpacking the tar file in the apps folder. You can check the version in the overview of your installed apps. Just search for "passwords" and the version should be "2018.7.0-build2321". 

Every user needs to delete his token. Alternatively you can go to the `authtoken` table in your database and search for any token with "Passwords" in the name. (`SELECT * FROM *PREFIX*authtoken WHERE name LIKE '%Passwords%'`). Then check which of the tokens are from the passwords app and delete those.

**Comment by zippytiff** [comment]
perfect thank you, i had moved the existing folder to _old then created new one.... so didnt see the correct stuff in gui

doing your way, i see the build now

thanks for the token help


ZT

**Comment by marius-wieschollek** [comment]
Great. Then i will mark this as solved.

**Comment by marius-wieschollek** [comment]
@zippytiff I just realized that Nextcloud may have a little surprise for you. Just for fun: Change your password. And then use an app token that was created before you changed the password. (Like open the app). Tell me if the issue now happens again.

(You may want to use a test account for this)

**Comment by zippytiff** [comment]
Ha ! i dont quite understand the whole app token aspect of nextcloud, so wouldnt really know

any hints and tips appreciated

Re your surprise, why a test account ? ;-)

**Comment by zippytiff** [comment]
Interesting indeed, thanks for explaining

I just took a look, and the list had easily 100 entries in there..... i hope they enable some better gui/admin management of this feature

Do you do any other apps? involvement with nextcloud, i wish the rest of community was a pro-active as yourself !

ZT

**Comment by marius-wieschollek** [comment]
I do not develop any other apps - one is already a lot of work :smile_cat:
