### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by fthibaud** [marius-wieschollek/passwords#530]
Hello,

Since today, when I try to export my data I get an error message : "t is null". It happens with any export format except json. 

Nextcloud version : 24.0.4
Passwords version : 2022.9.10

Btw I read this "Issues not following the template will be closed without review". But there is no reference. Which template should I use ?

Thanks

**Comment by marius-wieschollek** [comment]
Does this bug still exist in the current version of the app?

> Btw I read this "Issues not following the template will be closed without review". But there is no reference. Which template should I use ?

Github should only offer "Bug report" and "Feature Request" when creating an issue. I have no clue how users still get around this.
