### ISSUE TITLE
The "View shared passwords" button wording in sharing notifications seems to be hard-coded (cannot translate it)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [marius-wieschollek/passwords#531]
### System Information
**Server:**
```
 Nextcloud Version: 24.0.5 
 PHP Version: 8.0.23
 Database and Version: mysql 10.3.34
 Server OS and Version: Ubuntu 20.04 LTS
 Passwords Version: 2022.9.20
```

**Client:**
```
 Browser and Version: Firefox 104.0
 Client OS and Version: Ubuntu 20.04 LTS
```

### Steps to reproduce
1. Turn your user in French (or maybe another language)
2. Ask another user of your instance to share a password with your user
3. See that the notification is written in English, except the "View shared passwords" button

### Expected result
This button should be translated, but it's impossible to find this wording in Transiflex ... so I think this wording is hard-coded.

### Actual result
![2022-09-09_16-19](https://user-images.githubusercontent.com/33763786/189379866-77a36605-50ae-4f5d-a657-470b402d257b.png)

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
Can be provided if necessary
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Can be provided if necessary
```
</details>

**Comment by marius-wieschollek** [comment]
I don't think that is the case. The translation was added after the last release. With the current 2022.10 nightly release it shows up just fine.

**Comment by Jerome-Herbinet** [comment]
OK thanks and I forgot to close this issue after having found where to translate it in Weblate (IMO, Weblate is a lot less user-friendly than Transifex ... that's why I did not find the original wording before opening this issue).
