### ISSUE TITLE
Nextcloud 25 support

### ISSUE THREAD

**Issue by small1** [marius-wieschollek/passwords#534]
### System Information
**Server:**
Nextcloud 25 beta 7

```json
{
    "version": {
        "server": "25.0.0.12",
        "app": "2022.9.20",
        "lsr": false,
        "php": "8.0.18",
        "cronPhp": "8.0.18"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "local",
        "previews": "pageres",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "beta",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}

```

**Client:**
```
 Browser and Version:
 Client OS and Version:
```

### Steps to reproduce
Click on the password app. I should see a list of passwords.  But the page only shows the sidebad menu and nothing else.

### Expected result
It should show me the list of passwords.

### Actual result
I only see the page background and the menu to the left, content field is empty

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
This deosnt have any usefull information. Just blank.
![Screenshot from 2022-09-22 13-07-32](https://user-images.githubusercontent.com/317830/191731222-dda2a904-0885-40fd-81a4-bd79da3e35b0.png)
![Screenshot from 2022-09-22 13-07-18](https://user-images.githubusercontent.com/317830/191731224-93e801f3-0de9-4338-8887-502e4e35a3a4.png)

```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
It says nothing
```
</details>

**Comment by Hanskes** [comment]
Is it possible to prioritize this? After the update to NC25, the app has become unusable, while we use it every day. The app is a perfect solution for our company to make passwords available to the right people within our own environment. because the app is so good, it has become indispensable!

**Comment by marius-wieschollek** [comment]
The current nightly version (2022.11.0) fixes some of the most broken styling in the app. So if you have upgraded to NC25, this will get the web interface working again.
But NC 25 seems to be a complete overhaul of the Nextcloud design, so don't expect a stable release anytime soon.

**Comment by victoraroyo** [comment]
> The current nightly version (2022.11.0) fixes some of the most broken styling in the app. So if you have upgraded to NC25, this will get the web interface working again. But NC 25 seems to be a complete overhaul of the Nextcloud design, so don't expect a stable release anytime soon.

Thank you very much! This is perfect for now - we can access and it is ok.

**Comment by himpierre** [comment]
Is this nightly release working for someone with nextcloud 25? I'm still getting `Initialisation Error: The app was unable to obtain the api access credentials.`

cheers, t.

**Comment by himpierre** [comment]
Here the error raised in the log file:
```
"reqId":"XYA2UVECQza9vSI1xOEl","level":4,"time":"2022-10-19T10:08:29+00:00","remoteAddr":"","user":"admin","app":"p
asswords","method":"GET","url":"/index.php/apps/passwords/","message":"Cannot assign OC\\Cache\\CappedMemoryCache to property 
OC\\AllConfig::$userCache of type OCP\\Cache\\CappedMemoryCache","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0
) Gecko/20100101 Firefox/106.0","version":"25.0.0.18","exception":{"Exception":"TypeError","Message":"Cannot assign OC\\Cache\
\CappedMemoryCache to property OC\\AllConfig::$userCache of type OCP\\Cache\\CappedMemoryCache","Code":0,"Trace":[{"file":"/va
r/www/nextcloud.dev.domain.de/htdocs/apps/passwords/lib/Services/ConfigurationService.php","line":190,"function":"setValue"
,"class":"ReflectionProperty","type":"->"},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/apps/passwords/lib/Encryption/O
bject/SseV1Encryption.php","line":230,"function":"clearCache","class":"OCA\\Passwords\\Services\\ConfigurationService","type":
"->"},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/apps/passwords/lib/Encryption/Object/SimpleEncryption.php","line":67
,"function":"getServerKey","class":"OCA\\Passwords\\Encryption\\Object\\SseV1Encryption","type":"->"},{"file":"/var/www/nextcl
oud.dev.domain.de/htdocs/apps/passwords/lib/Encryption/Object/SimpleEncryption.php","line":38,"function":"getSimpleEncrypti
onKey","class":"OCA\\Passwords\\Encryption\\Object\\SimpleEncryption","type":"->"},{"file":"/var/www/nextcloud.dev.domain.d
e/htdocs/apps/passwords/lib/Services/SessionService.php","line":311,"function":"encrypt","class":"OCA\\Passwords\\Encryption\\
Object\\SimpleEncryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud.dev.de/htdocs/apps/passwords/lib/Services/SessionService.php","line":231,"function":"encryptSessionData","class":"OCA\\Passwor
ds\\Services\\SessionService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud.dev.de/htdocs/apps/passwords/lib/Helper/Token/ApiTokenHelper.php","line":204,"function":"save","class":"OCA\\Passwords\\Se
rvices\\SessionService","type":"->"},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/apps/passwords/lib/Helper/Token/ApiTo
kenHelper.php","line":118,"function":"createWebUiToken","class":"OCA\\Passwords\\Helper\\Token\\ApiTokenHelper","type":"->"},{
"file":"/var/www/nextcloud.dev.domain.de/htdocs/apps/passwords/lib/Controller/PageController.php","line":160,"function":"ge
tWebUiToken","class":"OCA\\Passwords\\Helper\\Token\\ApiTokenHelper","type":"->"},{"file":"/var/www/nextcloud.dev.domain.de
/htdocs/apps/passwords/lib/Controller/PageController.php","line":124,"function":"addHeaders","class":"OCA\\Passwords\\Controll
er\\PageController","type":"->"},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/lib/private/AppFramework/Http/Dispatcher.
php","line":225,"function":"index","class":"OCA\\Passwords\\Controller\\PageController","type":"->"},{"file":"/var/www/nextclo
ud.dev.domain.de/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC
\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/lib/private/AppFramework/Ap
p.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud.
dev.domain.de/htdocs/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"
},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router"
,"type":"->"},{"file":"/var/www/nextcloud.dev.domain.de/htdocs/index.php","line":36,"function":"handleRequest","class":"OC"
,"type":"::"}],"File":"/var/www/nextcloud.dev.domain.de/htdocs/apps/passwords/lib/Services/ConfigurationService.php","Line"
:
```

Something to do with server side encryption?

**Comment by victoraroyo** [comment]
One of my servers have this as well. Strange but the other is ok. May be something to do with LDAP? I've the error on server with LDAP clients.

**Comment by himpierre** [comment]
No LDAP involved on my side.

Am 19. Oktober 2022 12:23:05 MESZ schrieb Victor Aroyo ***@***.***>:
>One of my servers have this as well. Strange but the other is ok. May be something to do with LDAP? I've the error on server with LDAP clients.
>

**Comment by marius-wieschollek** [comment]
I published a new nightly which fixes the error that causes the stack trace above.
It's indeed caused by the server side encryption which is a bit concerning because this function is only called if the SSE is initialized for the first time.

**Comment by himpierre** [comment]
Works! Thank you!

Am 19. Oktober 2022 21:56:54 MESZ schrieb "M. Wieschollek" ***@***.***>:
>I published a new nightly which fixes the error that causes the stack trace above.
>It's indeed caused by the server side encryption which is a bit concerning because this function is only called if the SSE is initialized for the first time. 
>

**Comment by RealSerga** [comment]
New nightly build works
But has graphic artifacts
See screenshot
![image](https://user-images.githubusercontent.com/23523391/196943199-5395756c-4c91-4b12-9fe0-cd36e3d28848.png)

**Comment by marius-wieschollek** [comment]
I know. As you can see from my previous comments, i have fixed the worst of the styling issues but not all.

**Comment by ghost** [comment]
For those wondering, the Chrome extension for using Passwords still functions regardless of this styling problem. Also, the nightly version has fixed my issues with this extension in the meantime. Thank you Marius!

**Comment by daSubby** [comment]
Hello i have also an styling issue. He warned me about the update to Nextcloud 25, of course. I am aware of that.
See the screenshot.
![screen](https://user-images.githubusercontent.com/61833245/197207319-299ac291-1274-4669-8b1c-fcf29940e91c.png)

I use these setting: 

Linux: Ubuntu 20.04.1 / Kernel 5.15.0-41-generic
Nextcloud: Nextcloud Hub 3 (stable)
Passwords: 2022.10.20
Microsoft Edge: Version 106.0.1370.47 (Offizielles Build) (64-Bit)
Opera: Version:91.0.4516.77

By the way. Thank you very much for your effort. I love the project.

**Comment by marius-wieschollek** [comment]
@daSubby Please use the nightly version. The styling issues are less problematic with that version. You should be able to switch to the nightly build by enabling the "Show Nightly Updates in "Apps"" setting. Afterwards it a nightly update should be available within 24 hours.

**Comment by Refhi** [comment]
> @daSubby Please use the nightly version. The styling issues are less problematic with that version. You should be able to switch to the nightly build by enabling the "Show Nightly Updates in "Apps"" setting. Afterwards it a nightly update should be available within 24 hours.

Thanks !

Though I'm having trouble finding the switch for the "Nightly Updates". Should I look for it in https://example.com/settings/apps ? (edit for better example url...)

thanks again

**Comment by marius-wieschollek** [comment]
No, it's in the admin area, e.g: https://example.com/settings/admin/passwords

**Comment by marius-wieschollek** [comment]
Stable version of 2022.11.0 has been released

**Comment by synthead** [comment]
Thank you very much!  Great job!
