### ISSUE TITLE
Update to Nextcloud 25.0.0.3 passwords app does not bring up password list

### ISSUE THREAD

**Issue by MrEcrm** [marius-wieschollek/passwords#538]
### System Information
**Server:**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below
root@Storage:/var/www/nextcloud# sudo -u www-data php /var/www/nextcloud/occ passwords:system:report debug
{
    "version": {
        "server": "25.0.0.18",
        "app": "2022.10.10",
        "lsr": true,
        "php": "7.4.30",
        "cronPhp": "7.4.28"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "ajax",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": true
    },
    "services": {
        "images": "imagick",
        "favicons": "ddg",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}


 Nextcloud Version:
 PHP Version:
 Database and Version:
 Server OS and Version:
 Passwords Version:
```

**Client:**
```
 Browser and Version: any
 Client OS and Version: any
```

### Steps to reproduce
1.klick on the key of the nextcloud menue
2. screen empty
3. console: $ is deprecated

### Expected result
bring up the list, including my linux root password :-(...!!

### Actual result
Picture of clouds

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
 - Open the Nextcloud admin settings
 - Open the "Log" section
 - Click the "Copy" icon, then "Copy Raw"
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Press F12, copy the content of the console tab
```
</details>

**Comment by marius-wieschollek** [comment]
Not a bug. NC 25 is not supported.
See https://github.com/marius-wieschollek/passwords/issues/534

**Comment by MrEcrm** [comment]
Thanks, my app-ologies! Somehow it installed already NC25 on a stable update channel. Well I did have some issues and had to continue the update from the command line. Most probably me as the ultimate root cause... :-(. 

However, if anyone runns into the same thing, the following hints to be provided (just by prying interest i was digging around...):

- the mobile app works!
- On a laptop, resize the screen, most importantly reduce the with and the (left hand side navigation falls off) list of passwords appears. The searching functionality works as well! And thanks for creating and maintaining the app often used!
