### ISSUE TITLE
[Feature] Microsoft Edge Support for Web Interface

### ISSUE THREAD

**Issue by zippytiff** [marius-wieschollek/passwords#54]
Hi,

Im sure the feature set wouldnt be as good, but can we have passwords at least work in ie & edge

Thanks

ZT

**Comment by marius-wieschollek** [comment]
I'm working towards getting Microsoft Edge working (Microsoft too :smiley:) but Internet Explorer is a lost cause because it will never support the technologies used by the app

**Comment by zippytiff** [comment]
ha, nobody can fix MS, it seems to be their single goal in life to self-destruct !

Great, news re Edge, when do you think you will have a beta ?

ZT

**Comment by marius-wieschollek** [comment]
It will probably be in August when the client side encryption update gets released. The issues with Edge are mostly related to encrypting passwords. If you just want to browse passwords (and not create or update them) you can uncomment line 72 in the file `lib/Controller/PageController.php`. After that the app will work in MS Edge, but creating/updating passwords will fail.

**Comment by zippytiff** [comment]
Great, I will try that

Keen to see how it looks

So it’s the encryption that is the issue and not the decryption

Is there any framework for the mobile app to include these add on apps? Or have you considered a standalone iOS/android app, that would be brilliant, what a solution. 

ZT

**Comment by marius-wieschollek** [comment]
There is a [third party app](https://play.google.com/store/apps/details?id=com.intirix.cloudpasswordmanager) to access passwords for android. I have considered making a desktop client & Android app, but there is still a lot in the pipeline for the main app so it will have to wait.

**Comment by zippytiff** [comment]
i found this ios one in dev
https://github.com/Y0nnyy/passman-ios

**Comment by marius-wieschollek** [comment]
That one seems to be for another password manager.

**Comment by NodokaMurmevent** [comment]
maybe it's useless to adapt for egde, for the next update edge will switch to blink (chromium) : [tomsguide](https://www.tomsguide.com/us/microsoft-edge-chrome-chromium-browser,news-28759.html)

**Comment by marius-wieschollek** [comment]
Yes, there will be no Edge support anymore for the main app and also the extensions.
