### ISSUE TITLE
Uncaught (in promise) Error: Content type mismatch: Expected application/json, got text/html; charset=UTF-8

### ISSUE THREAD

**Issue by schengawegga** [marius-wieschollek/passwords#544]
### System Information
**Server:**
```{
    "version": {
        "server": "25.0.1.1",
        "app": "2022.11.11",
        "lsr": true,
        "php": "7.4.28",
        "cronPhp": "7.4.28"
    },
    "environment": {
        "os": "Linux",
        "architecture": "aarch64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": true
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 1
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
 Browser and Version: Firefox 106.0.5
 Client OS and Version: Windows 10 Pro 21H1
```

### Steps to reproduce
1. No Passwords are listed in the cloud app and via the firefox extension.

### Expected result
Passwords should be listed.

### Actual result
No Passwords available. Only the loading gif is shown and a small notification "200 - OK" is show for a few seconds. There is no access to the passwords in the cloud itself and via the firefox extension (same error as in console shown).

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

```
 No Log available
```
</details>

### Browser log
<details>
<summary>Browser log</summary>

```
Uncaught (in promise) Error: Content type mismatch: Expected application/json, got text/html; charset=UTF-8
```
</details>

**Comment by marius-wieschollek** [comment]
Do you have Rainloop or SnappyMail installed?

**Comment by schengawegga** [comment]
Yes. Both of it. Rainloop will be removed soon, but snappymail will stay on the cloud.

**Comment by marius-wieschollek** [comment]
Rainloop is likely the cause, see https://help.nextcloud.com/t/solved-errors-blank-page-after-udate-to-2022-11-20/149328

**Comment by schengawegga** [comment]
Thanks. Disabling rainloop fixed the error. But i can not find any problematic changes since rainloop 7.2.5. very strange.

**Comment by marius-wieschollek** [comment]
I'm not sure what the reason within Rainloop is, but it seems it needs some additional files which cause the error if missing. It seems that running SnappyMail and Rainloop alongside causes the issue in Rainloop at some point. (In my testing it only appeared after both apps had been opened by the/a user)

But i don't really know and since it's caused outside the Passwords app it's also not fixable by me.

**Comment by schengawegga** [comment]
Your right. It´s only when rainloop and snappymail are enabled at the same time. disabling one of them fixes the issue. i will open an issue on snappymail. maybe they will find a solution. thanks for your fast response and thanks for the great password app.
