### ISSUE TITLE
Add Support for Managed AppConfig

### ISSUE THREAD

**Issue by idominiki** [marius-wieschollek/passwords#548]
**Current Status**
Currently, users must enter their server details.

**Feature Description**
It would be great if the Server URL and username can be configured through managed AppConfig

**Additional context**
https://developer.jamf.com/developer-guide/docs/managed-app-configuration

**Comment by marius-wieschollek** [comment]
This seems to be related to iOS. In that case, please open a ticket in the repository of the iOS App you use. (Most likely this one: https://github.com/johannes-schliephake/nextcloud-passwords-ios)

**Comment by idominiki** [comment]
Sorry for that!
