### ISSUE TITLE
NC25 requires a valid secret and passwordsalt

### ISSUE THREAD

**Issue by szaimen** [marius-wieschollek/passwords#551]
NC25 requires a valid secret and passwordsalt.

You may apply the same workaround like in https://github.com/nextcloud/server/pull/35600/files

Edit: looks like something like https://github.com/nextcloud/server/pull/31499/files might be needed as well

**Comment by marius-wieschollek** [comment]
Can you add more detail to this ticket? What is this about?

**Comment by szaimen** [comment]
On some instances has the secret and passwordsalt been empty. NC25.0.2 will automatically add a secret and passwordsalt to config.php if they were empty/missing before. This change may break your app IIRC.

**Comment by marius-wieschollek** [comment]
Oh yeah. That will cause issues and could lead to data loss.

**Comment by marius-wieschollek** [comment]
I have pushed a nightly version that should be able to detect and repair such versions when the `occ maintenance:repair` command is run.

**Comment by marius-wieschollek** [comment]
With the 2022.12.1 update, my suggested way to fix the issues is as follows:

1. Update to passwords 2022.12.1
2. Use `php ./occ passwords:backup:list` to verify you have a current passwords app backup
3. Update to NC 25.0.2
4. Run the NC 25 migrations (`php ./occ upgrade`)
5. Run the database repair with `php ./occ maintenance:repair`

This should detect all items in the passwords database that were encrypted with no server secret and reencrypt them with the new server secret.
