### ISSUE TITLE
Image get loaded with http instead of https when logged in as admin

### ISSUE THREAD

**Issue by ErwinJobse** [marius-wieschollek/passwords#552]
When logged in as admin the image app-dark.svg get loaded as http://site.tld/cloud/apps/passwords/img/app-dark.svg which causes the connection to not be secure.  The image only gets loaded when you get a notification about this app. 

I'm using version 2022.12.20 and Nextcloud version 25.0.1

**Comment by marius-wieschollek** [comment]
This does not seem like something that is within my control. Notifications are often sent from background tasks, so i recommend you check your `overwrite.cli.url` setting.
