### ISSUE TITLE
since update to 2022.12.20 a notification from passwords app appears again and again

### ISSUE THREAD

**Issue by Benance** [marius-wieschollek/passwords#553]
### System Information

 Nextcloud Version: 24.0.7
 PHP Version: 8.0.25
 Database and Version: mariadb 10.5.15
 Server OS and Version: debian 11
 Passwords Version: 2022.12.20
```

**Client:**
```
 Browser and Version: firefox 102.5.0 ESR
 Client OS and Version: Windows 10 21h2
```

### Steps to reproduce
1. update passwords app to version 2022.12.20 from the nextcloud apps web interface


### Expected result
a notification tells me once that it is the last passwords version compatible with my php version

### Actual result
this notification appears again and again serveral times a day

### Nextcloud log
nothing appears in the logs

**Comment by marius-wieschollek** [comment]
This notification is generated once in an upgrade step. I can't really think of any way how this notification would appear more than once except if your server reruns the upgrade/migration several times a day.
I have added a patch to the nightly version to prevent the notification from being sent again anyway so the next update should fix that.

**Comment by Benance** [comment]
All right. 
Thanks for you reply.
I'll apply the fix as soon as it will be available and I'll stay you in touch.
For your information, I've forgetten to say that my nextcloud instance is behind sso, and the icon in the top left corner of the notification is broken.
When I copy the link of the image, and paste it in a new tab, I fall on the sso login screen.
Maybe this information could help?
Regards.




9 décembre 2022 à 00:09 "M. Wieschollek" ***@***.***> a écrit:

**Comment by marius-wieschollek** [comment]
With the 2022.12.1 update i have included the additional check. So the notification should only be sent once, even if the migration is run several times.

**Comment by Benance** [comment]
Hello

I've applied the update this afternoon: it works! I no longer receive 
the same notification again and again.

Thanks for your work

Regards

Le 16/12/2022 à 23:07, M. Wieschollek a écrit :
