### ISSUE TITLE
About the language shown on top bar and manager guide list in nextcloud webpage.

### ISSUE THREAD

**Issue by SadBoen** [marius-wieschollek/passwords#555]
Is't only about a translation of language of latest verison. easy issue.
Shown webGUI language of mine is chinese, then I found titled position is still shown English.
Hope this could be fixed, 
Thank you very much.

**Comment by marius-wieschollek** [comment]
![grafik](https://user-images.githubusercontent.com/8255857/209375117-1839f982-3e12-4071-b103-b8c59295966d.png)
This one? Yes, that will be fixed with the next update

**Comment by SadBoen** [comment]
Yes, Thank you very much.

**Comment by marius-wieschollek** [comment]
Should be fixed with the release of 2023.1.0
