### ISSUE TITLE
Error 404 on " Import from backup" help page

### ISSUE THREAD

**Issue by Albirew** [marius-wieschollek/passwords#558]
Nextcloud Version: 25.0.2.3
 PHP Version: 8.1.13
 Passwords Version: 2022.12.21

### Steps to reproduce
1. go to "plus" > backup/restore > restore/import
2. choose database backup
3. click on link "read database backup import guide"

### Expected result
database import guide showing

### Actual result
error 404

the same goes for the "Import from database backup" link in `apps/passwords/#/help/Import#help-specific-importers`

**Comment by marius-wieschollek** [comment]
The error in the handbook should be fixed now (unless you're using the handbook extension),
The error in the app will be fixed with the next update.

**Comment by marius-wieschollek** [comment]
Should be fixed with the release of 2023.1.0
