### ISSUE TITLE
Archive passwords

### ISSUE THREAD

**Issue by TtuxX** [marius-wieschollek/passwords#559]
**Current Status**
It is not possible to archive old data/passwords that are not used anymore. 
It is only possible to delete them and I am not certain whether "Bin" folder could be used to archive passwords?

**Feature Description**
I would love to have the ability to archive deprecated passwords, while still being able to see them on the app (but not on the Webextension) for any future reference.

**Additional context**
There would be a "Archived" entry just above the "Bin" entry on the left panel.

**Comment by marius-wieschollek** [comment]
What is the benefit of archiving passwords?

**Comment by TtuxX** [comment]
It would be in order to keep infos about deprecated passwords and see previously used passwords.

Specific use-case:
  For my very specific case I also use your app to store my credit cards infos (terribly bad practice I know, but I love your app).
  I keep them year after year even when they expire and keep some notes with them.
  The only issue is that they keep poping-up in the Webextension, and are quite numerous for me by now. 

I would thus love, it that was possibe, to archive them but still access them, without deleting them.

**Comment by marius-wieschollek** [comment]
Are these different credit cards?
If it's the same, you can just update the item and the app will store the previous version in it's version history.

**Comment by TtuxX** [comment]
Yes they are different

**Comment by marius-wieschollek** [comment]
Tbh. i would opt more for a "Don't recommend this entry anymore" option in the extension than an archive.
This would likely benefit more users since they can use that functionality to improve the recommendations of the extension.

You can still move the cards to an archive folder in your NC to keep the UI clean.

**Comment by TtuxX** [comment]
This is a good idea! I am then closing this issue in favor of https://github.com/marius-wieschollek/passwords-webextension/issues/253
It would however be great to have this setting be client-independent.
