### ISSUE TITLE
Passwords marked as hacked but there are definitely not hacked

### ISSUE THREAD

**Issue by omocinteractive** [marius-wieschollek/passwords#56]
### System Information
- Nextcloud Version: 13.04
- PHP Version: 7.2
- Passwords Version 2018.6.3
- Browser and Version: 61
- Client OS and Version: W10
- Server OS and Version: Ubuntu 16

### Steps to reproduce
Save a password like #123HeyHo#XY

### Actual result
You got a red icon that your password was hacked. But this definitely not correct!

### Expected result
Showing a green icon.

Info: This bug was also in early versions two years ago a problem.

**Comment by Kai-Angne** [comment]
Such a password ist surely known ... 
This apps checks agains the haveibeenpwned database. If a passwords is in this database it is marked as hacked. Such a password might be used within brute force attacks / inpassword lists.

**Comment by omocinteractive** [comment]
... i checked all databases and lists (which this tool use) - the passwords are not hacked! Many of this are passwords i use in a intranet-area - so the can't be hacked. Anyway: a pw with numbers, special characters and upper case/lower case - really uncommon that this could be hacked.

**Comment by marius-wieschollek** [comment]
Around three weeks ago, there was an issue with the HIBP api. (The api endpoint to check passwords was removed without notice). This issue was fixed by an automated upgrade in 2018.6.0.

You can execute the upgrade again with the following shell commands
```
./occ  config:app:set passwords migration/hibp --value 0
./occ maintenance:repair
./occ maintenance:mode --off
```
If the issue appears again, you may want to check your logs for errors.

PS: Today passwords are usually attacked by using big lists of known passwords. Numbers etc. do not have any effect on this type of attack. This way also internal passwords can be breached if someone else happens to use the same password.

**Comment by omocinteractive** [comment]
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/vhosts/domain.tld/httpdocs/lib/private/DB/Connection.php:64

"PS: Today passwords are usually attacked by using big lists of known passwords."
yes - that's right - but i checked all this lists that you use in your code manually. Nothing found, but 30% of my passwords marked as hacked ...

**Comment by omocinteractive** [comment]
sorry. i think it's a permission problem. i will check it ...

**Comment by marius-wieschollek** [comment]
Can you elaborate?

Was there an error with your server?
The occ commands i described before will simply reset the status to good for all passwords. It will take up to one day until the correct status is shown for all passwords.

**Comment by omocinteractive** [comment]
... "bug" was referred to your posting. there was no error with my server (only that passwords marked as hacked, which are not been hacked - "have i been pwned" don't list my passwords as hacked and this service is configured).

**Comment by omocinteractive** [comment]
tommorow i will give you a feedack ...

**Comment by omocinteractive** [comment]
Everything okay. The thread can be closed. Thx!
