### ISSUE TITLE
Enforce Global "settings" - set "settings" permissions.

### ISSUE THREAD

**Issue by pieter-groeneweg** [marius-wieschollek/passwords#562]
**Current Status**
Users have all the options under "settings".

**Feature Description**
Admin can set what option in settings is available to users/groups. Also if some settings set by admin are non overridable global.

**Additional context**
Example: Company wants to enforce the use of certain settings without users being able to override. ie. only department managers can share (and set the editable)
Company wants only admins can set Security settings.

It would be very nice to have an admin "settings" page with the option to set permissions to users/groups to each option and what option is a non overridable global.

**Comment by marius-wieschollek** [comment]
Ah, yes enterprise level user management madness!

Tbh, this is currently out of scope for this app. Nextcloud itself also does not have a framework for settings with that level of detail, so i would have to develop all of that just for this app. Maybe in the future, but right now there are features that more users would benefit from than this.

With regards to sharing, the app does follow the Nextcloud system wide settings for that where applicable.
