### ISSUE TITLE
Can't change client side encryption password

### ISSUE THREAD

**Issue by PocketFR** [marius-wieschollek/passwords#565]
### System Information
**Server:**
```json
{
    "version": {
        "server": "25.0.3.2",
        "app": "2023.1.22",
        "lsr": false,
        "php": "8.1.14",
        "cronPhp": "8.1.14"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "screeenly",
        "security": "bigdb+hibp",
        "words": "random",
        "previewApi": true,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": true,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "none": true,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": true,
            "none": true,
            "default": "none"
        }
    }
}
```

**Client:**
```
 Browser and Version: Firefox 109.0 x64 & Opera 94.0.4606.38
 Client OS and Version: Windows 10 21h2
```

### Steps to reproduce
Configure client side encryption with a password.
Change the password for the client side encryption.

### Expected result
The password is changed

### Actual result
Same behavior as if you had clicked Cancel instead of Ok: the password change window is closed and nothing else happens.

### Nextcloud log
Nothing.

### Browser log (firefox)
<details>
<summary>Browser log</summary>

Uncaught (in promise) TypeError: document.getElementById(...) is null
    _unlockApp https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    updateGui https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    changeCsePassword https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    click https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    On https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    n https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    On https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    $emit https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    fireEvent https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    click https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    On https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    n https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    _wrapper https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    xi https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    ut https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    Pi https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    y https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    Bo https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    _update https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    r https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    get https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    e https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    $mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    $mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    init https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    Bo https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    _update https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    r https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    get https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    e https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
SettingsSection.899c8ed3d2f74e70f7f6.js:2:66811
    updateGui https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    InterpretGeneratorResume self-hosted:1819
    AsyncFunctionNext self-hosted:807
    (Asynchrone : async)
    changeCsePassword https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    changeCsePassword self-hosted:1356
    click https://nextcloud.example.com/apps/passwords/js/Static/SettingsSection.899c8ed3d2f74e70f7f6.js:2
    On https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    n https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    On https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    $emit https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    fireEvent https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    fireEvent self-hosted:1356
    click https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    On https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    n https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    _wrapper https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    (Asynchrone : EventListener.handleEvent)
    xi https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    ut https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    Pi https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    y https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    Bo https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    _update https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    r https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    get https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    e https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    $mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    $mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    init https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    d https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    p https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    Bo https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    _update https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    r https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    get https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    e https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
    mount https://nextcloud.example.com/apps/passwords/js/Static/app.js?v=342b3cd6-81:2
</details>

**Comment by marius-wieschollek** [comment]
Can confirm this, a fix is in the nightly version

**Comment by PocketFR** [comment]
Wow what a reactivity ! it works like a charm !
Thank you !
