### ISSUE TITLE
Error whenn starting Firefox "json.parse unexpected character"

### ISSUE THREAD

**Issue by omocinteractive** [marius-wieschollek/passwords#57]
### System Information
- Nextcloud Version: 13.04
- PHP Version: 7.2
- Passwords Version: 2018.6
- Browser and Version: Firefox 61
- Client OS and Version: W10
- Server OS and Version: Ubuntu16

### Actual result
error: "json.parse unexpected character at line 1 column 1 of the json data", but the app runs after that normal.
![image 004](https://user-images.githubusercontent.com/20245225/42027509-30d9c6be-7aca-11e8-8a7e-7308484688a5.png)

### Expected result
no error

**Comment by marius-wieschollek** [comment]
Do you have the legacy api disabled

**Comment by omocinteractive** [comment]
... yes ("Enable old API" is not checked).

**Comment by marius-wieschollek** [comment]
You need to enable it

**Comment by omocinteractive** [comment]
Okay. It seems to be eliminated. Thx!

**Comment by omocinteractive** [comment]
Everything okay. The thread can be closed.
