### ISSUE TITLE
Support well-known Password Change URLs

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords#570]
**Feature Description**
It would be nice to add support for [well-known password change URLs](https://w3c.github.io/webappsec-change-password-url/). This would allow to add a button in the UI that redirects the user directly to the change-password page of the respective service if they support the feature.

**Additional context**
This could be especially useful for the browser extension clients, but also for the web UI.

Nextcloud itself will start exposing this with NC 26 (see [here](https://github.com/nextcloud/server/pull/34742))

**Comment by marius-wieschollek** [comment]
This is now available in the nightly version
