### ISSUE TITLE
Passwords version 2023.2.20-build4828 breaks OCC

### ISSUE THREAD

**Issue by PocketFR** [marius-wieschollek/passwords#572]
### System Information
**Server:**
```json
 Run "php ./occ passwords:system:report debug" in your Nextcloud install directory and put the output here
 or fill out the fields below

 Nextcloud Version: 25.0.3
 PHP Version: 8.1.14
 Database and Version: MariaDB 10.5.18-MariaDB-0+deb11u1
 Server OS and Version: Debian 11
 Passwords Version: 2023.2.20-build4828
```

### Steps to reproduce
1. Install passwords 2023.2.20-build4828
2. try to use occ commands

### Expected result
occ console works as expected

### Actual result
PHP Fatal error:  Declaration of OCA\Passwords\Db\AbstractEntity::__call(string $methodName, array $args) must be compatible with OCP\AppFramework\Db\Entity::__call($methodName, $args) in /var/www/nextcloud/apps/passwords/lib/Db/AbstractEntity.php on line 113

### Nextcloud log
<details>
<summary>Nextcloud log</summary>

{"reqId":"MfY0Z16PEe8Gyfx3g4Zj","level":3,"time":"2023-02-08T06:51:00+00:00","remoteAddr":"172.30.249.1","user":"s.canat","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"Declaration of OCA\\Passwords\\Db\\AbstractEntity::__call(string $methodName, array $args) must be compatible with OCP\\AppFramework\\Db\\Entity::__call($methodName, $args) at /var/www/nextcloud/apps/passwords/lib/Db/AbstractEntity.php#113","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 OPR/94.0.0.0","version":"25.0.3.2","data":{"app":"PHP"},"id":"63e346546923c"}
</details>

**Comment by marius-wieschollek** [comment]
The newest build should work again

**Comment by blaine07** [comment]
Hate to revive this BUT I had this very same issue tonight. Had to manually disable maintenance mode, then run OCC UPGRADE to get "out of this."

Mine was line 25 instead of 113 thought: 

Declaration of OCA\Passwords\Db\Traits\GetterSetterTrait::setter(string $name, array $args): void must be compatible with OCP\AppFramework\Db\Entity::setter($name, $args) at /config/www/nextcloud/apps/passwords/lib/Db/AbstractEntity.php#25

**Comment by marius-wieschollek** [comment]
@blaine07 can you make a new bug report with a full copy of the log entry?
