### ISSUE TITLE
[BUG]: Cron causes PHP error after update to 2023.2.22

### ISSUE THREAD

**Issue by Flole998** [marius-wieschollek/passwords#577]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
PHP 8.1
```

### Client Information

Not used

### Bug description

Cron now has this fatal error:

`PHP Fatal error:  Declaration of OCA\Passwords\Db\Traits\GetterSetterTrait::setter(string $name, array $args): void must be compatible with OCP\AppFramework\Db\Entity::setter($name, $args) in /var/www/apps/passwords/lib/Db/Traits/GetterSetterTrait.php on line 25`

### Steps to reproduce

1. Update passwords
2. Run cron

### Expected behavior

1. No fatal error is shown

**Comment by marius-wieschollek** [comment]
I can't reproduce this issue at all.
Please add the system report and add details about how cron.php is used on your server

**Comment by Flole998** [comment]
The system report stuff doesn't work. The issue isn't always occuring. I don't have time to further debug this, so feel free to close this report. Nextcloud version is 25.0.3. Cron is called from a crontab file.

**Comment by marius-wieschollek** [comment]
What do you mean with "The system report stuff doesn't work."?

**Comment by Flole998** [comment]
The documented commands produce a "not found" error. I noticed that I had the app installed but not activated. Anyways, I uninstalled it now.

**Comment by marius-wieschollek** [comment]
Trying to run cron jobs for an app that is not activated can indeed cause errors as the app is not initialized when the code is executed.

**Comment by Flole998** [comment]
Well why does it attempt to execute the cron job for this app if it's not enabled? There's some fundamental issue in that case. It's not like there's an option to run nextclouds cronjobs for all apps except x.

**Comment by marius-wieschollek** [comment]
Since Nextcloud is managing the cronjobs, you can bring this up to them. I can't support running random parts of the app when it's not even active.

**Comment by ccandreva** [comment]
I am having the exact same issue after upgrading just now to Passwords 2023.2.22
Fedora 37, PHP 8.1 . The module is active.

System info will be attached.

/var/spool/cron/apache
```
*/5  *  *  *  * /bin/php -f /var/www/cxcloud/cron.php >/dev/null
```

Output:
```
PHP Fatal error:  Declaration of OCA\Passwords\Db\Traits\GetterSetterTrait::setter(string $name, array $args): void must be compatible with OCP\AppFramework\Db\Entity::setter($name, $args) in /var/www/cxcloud/apps/passwords/lib/Db/Traits/GetterSetterTrait.php on line 25
```

[2023-02-23.md](https://github.com/marius-wieschollek/passwords/files/10815506/2023-02-23.md)

**Comment by ccandreva** [comment]
.. and by the time I finished writing this, the errors stopped after maybe 5 runs.
This is very strange.

**Comment by Flole998** [comment]
It was the same for me, didn't always happen. But don't worry, it'll come back eventually.

**Comment by panachoi** [comment]
> It was the same for me, didn't always happen. But don't worry, it'll come back eventually.

I'm seeing this exact behavior after upgrading to 25.0.4 this week. My passwords app is disabled (has always been) but I got the same errors 3x from the cron.php on 3 runs between 22:15 and 22:25 last night, and then it "disappeared". I've now enabled it to see if this stops the errors from occuring, or if the will continue randomly.

**Comment by Flole998** [comment]
If you don't need it just uninstall it, that's what I did and that definitely solved the issue for me.
