### ISSUE TITLE
[FEATURE]: Allow empty password

### ISSUE THREAD

**Issue by sevmonster** [marius-wieschollek/passwords#578]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

Password is a required field. This means that sites and services that do not use or at least do not require passwords, but still have secure credentials or private information to be stored in Passwords, cannot have a semantically correct entry created for them. I can easily provide a random password, or a space character, but that does not really solve the problem. There isn't a password, so there should not be a password set. Also if you provide a space, dash, or etc. to signify the password is empty, the credential entry will show up as breached.

### Feature Description

1. Open Passwords NC app or extension
2. Create new credential or edit existing entry
3. Allow blank password field to be submitted

### Additional Context

It may be a good idea to warn the user if a previously filled password field is made empty before submitting changes. Of course the password should be recoverable from entry history, but still.

**Comment by marius-wieschollek** [comment]
The  password field is required by design and it's always assumed to be there.
I don't think the effort to change this is worth it.

But as part of #71 we could add the option to hide the password field and automatically fill it with random characters?

**Comment by sevmonster** [comment]
Would you be open to a patch to resolve this? In particular I am also interested in more secret types, some of which may not have a password at all, so this is would be a prerequisite to that.

I actually wanted to switch to Bitwarden because of the additional secret types it has, but for years they have not added proper tag support or other categorization, so it's unusable for me.

About templates, I disagree with replacing this functionality with templates as it was described in #442. For example, a credit card is semantically and logically divested from a "password" entry, but most "password managers" nowadays have adopted such functionality as they move more toward being general secret managers.

**Comment by marius-wieschollek** [comment]
This one not so much. It's a backwards compatibility breaking change to the API which would mean we'll need a version 2.0 just for this. And every client needs to be updated to handle this too.

**Comment by sevmonster** [comment]
I think it would be worth the version bump. And I am going to ignorantly assume that for backwards compatibility with older clients, v1 API could just pass new secret types as a normal password type with custom fields, and empty passwords with either empty or a random value (e.g. `empty <random string>`).

**Comment by marius-wieschollek** [comment]
> And I am going to ignorantly assume that for backwards compatibility with older clients, v1 API could just pass new secret types as a normal password type with custom fields, and empty passwords with either empty or a random value (e.g. empty <random string>).

Nope. E2EE requires it to be a valid encrypted string. So the V1 API won't be able to do this at all.

And putting in random strings then ends up being exactly what the alternative is right now.

> I think it would be worth the version bump.

But I'm the one who has to maintain two APIs then.

The longer i think about this idea, the more i dislike it. This requires a lot of work from me and the other developers of any apps with no benefit to most users.

I don't want this change in the app. Hiding it in the templates seems like a sufficient alternative to me.
