### ISSUE TITLE
Allow quick access to details

### ISSUE THREAD

**Issue by godfuture** [marius-wieschollek/passwords#58]
In Nextcloud files_app clicking the size or change date column opens up the details. This would make sense also for the passwords_app. The password would still be quickly copied to clipboard by clicking on the name.

### System Information
- Nextcloud Version: 13.0.4
- PHP Version: 7.1.19
- Passwords Version:  2018.6.3
- Browser and Version: Firefox x64 61.0
- Client OS and Version: Windows 7 x64
- Server OS and Version: Debian 9

### Steps to reproduce
1. Login to Nextcloud and open passwords app
2. Click on size or change date column

### Actual result
The password is copied to clipboard.

### Expected result
The details sidebar opens.

**Comment by marius-wieschollek** [comment]
Click on "More", click on "Settings", select "Advanced" view in the top right corner, set "Single click action" to "Show Details".
