### ISSUE TITLE
[BUG]: Passwords tab not starting

### ISSUE THREAD

**Issue by daukus** [marius-wieschollek/passwords#584]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "26.0.0.9",
        "app": "2023.3.20",
        "lsr": false,
        "php": "8.2.4",
        "cronPhp": "8.2.4"
    },
    "environment": {
        "os": "Linux",
        "architecture": "aarch64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 1
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version:
Client OS and Version:
Windows 11
Mozilla 110.0.1 (same behaviour on Edge or Samsung browser)

### Bug description

When accessing Passwords from web, it's not starting, despite from android app it's working

### Steps to reproduce

1. Click on Passwords
2. Waiting to open endlessly

### Expected behavior

It should open when clicking on passwd tab

**Comment by marius-wieschollek** [comment]
Apparently some change since the first beta now causes this issue. The latest nightly release should fix the issue.

**Comment by daukus** [comment]
Many thanks!
Latest nightly works.

**Comment by Der-K-2000** [comment]
I can confirm, that the app works again. Thank you!
