### ISSUE TITLE
[BUG]: PHP Fatal Error after upgrade

### ISSUE THREAD

**Issue by Aonodensetsu** [marius-wieschollek/passwords#585]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
Bug started upon upgrade to Nextcloud 26, MariaDB, Debian, */5 * * * * php -f /var/www/nextcloud/cron.php, PHP 8.0.28 (cli)
```

### Client Information

Browser and Version: Firefox latest / Chrome latest
Client OS and Version: Windows 11 latest

### Bug description

https://github.com/nextcloud/server/issues/37376 `PHP Fatal error:  Declaration of OCA\Passwords\Db\Traits\GetterSetterTrait::getter(string $name) must be compatible with OCP\AppFramework\Db\Entity::getter(string $name): mixed in /var/www/nextcloud/apps/passwords/lib/Db/AbstractEntity.php on line 66` when running occ and in logs

### Steps to reproduce

1. use any occ command

### Expected behavior

occ command runs successfully

### Nextcloud Logs

```shell
no relevant errors except `{"reqId":"12EVFzAuwFmri8wAZi3z","level":3,"time":"2023-03-23T18:40:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Declaration of OCA\\Passwords\\Db\\Traits\\GetterSetterTrait::getter(string $name) must be compatible with OCP\\AppFramework\\Db\\Entity::getter(string $name): mixed at /var/www/nextcloud/apps/passwords/lib/Db/AbstractEntity.php#66","userAgent":"--","version":"26.0.0.11","data":{"app":"PHP"},"id":"641c9d4fb161f"}` which mirrors the CLI error
```

### Browser Logs

```shell
as above
```

**Comment by marius-wieschollek** [comment]
What version of the app do you use?

**Comment by Aonodensetsu** [comment]
2023.3.11, which was installed by the nextcloud updater

**Comment by FlimFlam** [comment]
Same problem here. Version  2023.3.11. Error occurred after updating to Nextcloud 26. PHP 8.0.28
My password app says "version for obsolete systems".
![Bildschirmfoto vom 2023-03-25 15-56-16](https://user-images.githubusercontent.com/2216884/227724974-7dea02cc-465a-4b9a-8235-2216b01ad390.png)

**Comment by dontinelli** [comment]
Have the same problem as well.
I saw that in the GitLab repository commits to resolve this bug have been made (https://git.mdns.eu/nextcloud/passwords/-/commit/82664483bb5e5b298e8892906cb0f62fc11d72f7).
@marius-wieschollek: Is there a timeline when those will be available in NC?

**Comment by FlimFlam** [comment]
With version 2023.4.0 the bug is gone for me.

**Comment by dontinelli** [comment]
> With version 2023.4.0 the bug is gone for me.

I just saw the update in NC and can confirm that the bug has been resolved for me as well.
