### ISSUE TITLE
[BUG]: settings.theme.background is broken

### ISSUE THREAD

**Issue by sevmonster** [marius-wieschollek/passwords#586]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "26.0.0.11",
        "app": "2023.4.20-build4904",
        "lsr": false,
        "php": "8.1.15",
        "cronPhp": "8.1.17"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "local",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": true,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": true,
            "default": "none"
        },
        "cse": {
            "CSEv1r1": true,
            "none": true,
            "default": "CSEv1r1"
        }
    }
}
```

### Client Information

Browser and Version: Chromium 109.0.5414.120
Client OS and Version: Multiple
Client: Passwords WebExtension 2.2.6

### Bug description

`server.theme.background` returned by the API is always `/apps/theming//img/background/kamil-porembinski-clouds.jpg`. This is regardless of if I change the background from server Theming app configuration or via user appearance configuration. Naturally this file does not exist in the WebExtension files so it 404's. The URL does work if my Nextcloud URI is prepended, but it's not actually the currently set image.
Previously, the URL was pointing to `app-background.jpg` as I did not use a custom background as configured from inside Nextcloud (I replaced that file instead), so I don't know what changed.

### Steps to reproduce

1. Change background in Theming app configuration or user appearance configuration
2. Open Passwords WebExtension popup

### Expected behavior

1. Background is correct

### Nextcloud Logs

```shell
Nothing related to Theming app or Passwords.
```

### Browser Logs

```shell
Just a 404 error for the missing asset. Nothing interesting.

kamil-porembinski-clouds.jpg:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
```

**Comment by marius-wieschollek** [comment]
This should be working with the latest update
