### ISSUE TITLE
The passwords app is preventing deletion of users

### ISSUE THREAD

**Issue by XUBIUM** [marius-wieschollek/passwords#59]
Hello, 

When a user is deleted, it seems that the Password App generates errors and the user gets stuck in a state "The username <user> is queued for deletion"

The errors from the log:

```
Error | passwords | Exception: Invalid user id Frank
/home/xubiumco/teams.xubium.com/apps/passwords/lib/Cron/ProcessDeletedUsers.php - line 78:  OCA\Passwords\Helper\User\DeleteUserDataHelper->deleteUserData('Frank')
/home/xubiumco/teams.xubium.com/apps/passwords/lib/Cron/ProcessDeletedUsers.php - line 61:  OCA\Passwords\Cron\ProcessDeletedUsers->deleteUserData('Frank')
/home/xubiumco/teams.xubium.com/apps/passwords/lib/Cron/AbstractCronJob.php - line 62:  OCA\Passwords\Cron\ProcessDeletedUsers->runJob(NULL)
/home/xubiumco/teams.xubium.com/lib/private/BackgroundJob/Job.php - line 61:  OCA\Passwords\Cron\AbstractCronJob->run(NULL)
/home/xubiumco/teams.xubium.com/lib/private/BackgroundJob/TimedJob.php - line 55:  OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/home/xubiumco/teams.xubium.com/cron.php - line 146:  OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log)){main}
```

**Comment by marius-wieschollek** [comment]
Are you executing background jobs via ajax?

**Comment by XUBIUM** [comment]
Yes.

**Comment by marius-wieschollek** [comment]
You can try the nightly build 2370. It should fix the issue.

**Comment by XUBIUM** [comment]
It is a production environment... When do you plan to have the stable build?

**Comment by XUBIUM** [comment]
OK, I'll install on monday and let you know asap how it goes.

**Comment by XUBIUM** [comment]
Hello, 

The issue with deleting accounts persist (even deleting after the update), and I got this error in the registry while updating:

Error | no app in context | Exception: Repair step 'OCA\Passwords\Migration\UpdateDatabaseFields' is unknown/home/xubiumco/teams.xubium.com/lib/private/legacy/app.php - line 1107:  OC\Repair->addStep('OCA\\Passwords\\M...')/home/xubiumco/teams.xubium.com/lib/private/legacy/app.php - line 1050:  OC_App  executeRepairSteps('passwords', Array)/home/xubiumco/teams.xubium.com/lib/private/Installer.php - line 199:  OC_App  updateApp('passwords')/home/xubiumco/teams.xubium.com/settings/ajax/updateapp.php - line 45:  OC\Installer->updateAppstoreApp('passwords')/home/xubiumco/teams.xubium.com/lib/private/Route/Route.php - line 155:  require_once('/home/xubiumco/...')[internal function] OC\Route\Route->OC\Route\{closure}(*** sensitive parameters replaced ***)/home/xubiumco/teams.xubium.com/lib/private/Route/Router.php - line 297:  call_user_func(Object(Closure), Array)/home/xubiumco/teams.xubium.com/lib/base.php - line 999:  OC\Route\Router->match('/settings/ajax/...')/home/xubiumco/teams.xubium.com/index.php - line 42:  OC  handleRequest(){main}
-- | -- | --

**Comment by marius-wieschollek** [comment]
The error you saw after the upgrade is probably related to [nextcloud/server#9781](https://github.com/nextcloud/server/issues/9781). 

Can you set the log level of your Nextcloud instance to debug and check if an entry like the following will appear in the logs afterwards. (This command will work from the command line: `./occ  config:system:set loglevel --value=0 --type=int`)

Level | App | Message
-- | -- | --
Debug | passwords | Passwords runs /var/www/html/cron.php in global mode

**Comment by XUBIUM** [comment]
Hello, 
I have set the log level to 0, but I don't see any new log entry for the passwords app. Not sure if it has something to do, but I execute the background jobs via ajax
About the error during the update: Is that the cause that the users are still stuck in the "queued for deletion" state? Even the ones deleted after upgrading.

**Comment by tikoflano** [comment]
I'm experiencing the same problem. I can't craete a user with the same username as one I deleted. The logs show the "The username is queued for deletion" message
