### ISSUE TITLE
[FEATURE]: Do not collect credentials from specific site(s)

### ISSUE THREAD

**Issue by grimcz** [marius-wieschollek/passwords#592]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [ ] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

New credentials are automatically collected by Passwords when user fills and confirms sign-up form.

### Feature Description

Add user-editable "blacklist" containing web-sites (urls) where credentials are not collected, e.g. web-sites with sensitive information like gov webs, bank accounts etc. Some websites loads with prefilled credentials (like guest/guest)

**Comment by marius-wieschollek** [comment]
> This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.

Please check the issues there.
