### ISSUE TITLE
[FEATURE]: clear clipboard after password was copied

### ISSUE THREAD

**Issue by nobvaillant** [marius-wieschollek/passwords#596]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

If I copy a password, the password is available in the clipboard until I copy another resource. Other applications would be able to gather information of the clipboard.

### Feature Description

After copying the password, the clipboard would be cleared after a few seconds, so that no other application would be able to access the information in the clipboard. 

### Additional Context

This mitigates just the risk, but it is really helpful in the case, if you forgot it, that there is still a password in your clipboard and you paste it anywhere by accident. But I also don't know if this is technically possible by the browser edition?

**Comment by marius-wieschollek** [comment]
Browsers don't allow writing to the clipboard outside of a click action.
