### ISSUE TITLE
Stop misusing the notifications for self-promotion

### ISSUE THREAD

**Issue by Der-K-2000** [marius-wieschollek/passwords#599]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
x
```

### Client Information

x

### Bug description

Ad-like information in the notifications. I understand the reason, but that's a no-go, even for surveys or to engagement in any kind.

### Steps to reproduce

suddenly appears without opt-in

### Expected behavior

no notification

**Comment by marius-wieschollek** [comment]
This is not a bug report. If you have questions about notifications, use one of the options provided to ask questions

**Comment by Der-K-2000** [comment]
It was **not** a question.
