### ISSUE TITLE
ownCloud passwords webextension broken after NC12 upgrade

### ISSUE THREAD

**Issue by pafcioooo** [marius-wieschollek/passwords#6]
After I upgraded to NC12 and solving issue #5, firefox web browser extension [ff-oc-passwords](https://github.com/eglia/ff-oc-passwords) maintained by @eglia stopped working: it gives error "Connection to server timed out!".
No errors in nextcloud log on server.
I do not have idea how to proceed with this, should this issue be opened in ff-oc-passwords project?

**Comment by marius-wieschollek** [comment]
The extension should create two requests to your server: `GET /index.php/apps/passwords/api/0.1/version` and `GET /index.php/apps/passwords/api/0.1/passwords`.
If those you can find those requests in your server log after starting a sync, there is something wrong on the server. If the requests are not there, there was a problem with the extension. (Maybe actual connection problems).
If you are using app passwords for the extension, try your normal password.
I am using the extension and got this error before, but it disappeared before i could find out what was causing it.

**Comment by pafcioooo** [comment]
I am using the extension and got this error before, but it disappeared before i could find out what was causing it.

> And unfortunately this happend here too. Just in the morning I have noticed that it started working. I did not change anything. Magick:-) Thanks @marius-wieschollek

**Comment by marius-wieschollek** [comment]
just letting you know that i am working on a Webextension.
