### ISSUE TITLE
https://git.mdns.eu/ file server is down

### ISSUE THREAD

**Issue by AlexTCarneiro** [marius-wieschollek/passwords#60]
Good morning. 
Just an FYI, tried to download your Password installer today and the server is down. 
Address: 
https://git.mdns.eu/nextcloud/passwords/-/jobs/6606/artifacts/raw/passwords.tar.gz

I also tried to go to https://git.mdns.eu, the same thing. 

If I try https://mdns.eu/ get's a message: Welcome to Nginx!, like it's a new server.

Looking forward to getting your great app installer on my server. Cheers...!

**Comment by marius-wieschollek** [comment]
Thanks for alerting me. Seems like it was a DNS configuration issue and should be gone in around an hour.

**Comment by marius-wieschollek** [comment]
Everything is back online now
