### ISSUE TITLE
[BUG]: Could not update breached passwords database

### ISSUE THREAD

**Issue by pabloeisenhut** [marius-wieschollek/passwords#600]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
TrueNAS Scale
```

### Client Information
Client independent

### Bug description

For some time now, the following message appears at regular intervals.

Could not update breached passwords database
![1](https://github.com/marius-wieschollek/passwords/assets/137991389/af0a4433-306c-406d-96e0-c594b31592c3)

### Steps to reproduce
After a migration of the cloud, this problem appeared for the first time. Unfortunately, I can not explain how this problem came about.

### Expected behavior
No error message and the database breached passwords database updated.

### Nextcloud Logs
[passwords] Fatal: Exception: Breached password database update failed at <<closure>>

0. /var/www/html/custom_apps/passwords/lib/Cron/CheckPasswordsJob.php line 89
   OCA\Passwords\Cron\CheckPasswordsJob->registerUpdateAttempt()
1. /var/www/html/custom_apps/passwords/lib/Cron/AbstractTimedJob.php line 59
   OCA\Passwords\Cron\CheckPasswordsJob->runJob(null)
2. /var/www/html/lib/public/BackgroundJob/Job.php line 86
   OCA\Passwords\Cron\AbstractTimedJob->run(null)
3. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start(["OC\\BackgroundJob\\JobList"])
4. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start(["OC\\BackgroundJob\\JobList"])
5. /var/www/html/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute(["OC\\BackgroundJob\\JobList"], ["OC\\Log"])

at 2023-07-29T10:21:54+00:00

**Comment by marius-wieschollek** [comment]
Can you please add the missing information to this bug report.
Just posting the notification isn't helpful.

**Comment by marius-wieschollek** [comment]
The reason `none` means that the update was aborted due to the previous failures. You should have gotten an error message in the first three notifications.
If you don't have these any more, you can reset the attempts with this command:
```
./occ config:app:set passwords passwords/db/attempts --value=0;
```

**Comment by pabloeisenhut** [comment]
[passwords] Fatal: Exception: Breached password database update failed at <<closure>>

0. /var/www/html/custom_apps/passwords/lib/Cron/CheckPasswordsJob.php line 89
   OCA\Passwords\Cron\CheckPasswordsJob->registerUpdateAttempt()
1. /var/www/html/custom_apps/passwords/lib/Cron/AbstractTimedJob.php line 59
   OCA\Passwords\Cron\CheckPasswordsJob->runJob(null)
2. /var/www/html/lib/public/BackgroundJob/Job.php line 86
   OCA\Passwords\Cron\AbstractTimedJob->run(null)
3. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 103
   OCP\BackgroundJob\Job->start(["OC\\BackgroundJob\\JobList"])
4. /var/www/html/lib/public/BackgroundJob/TimedJob.php line 93
   OCP\BackgroundJob\TimedJob->start(["OC\\BackgroundJob\\JobList"])
5. /var/www/html/cron.php line 152
   OCP\BackgroundJob\TimedJob->execute(["OC\\BackgroundJob\\JobList"], ["OC\\Log"])

at 2023-07-29T10:21:54+00:00

**Comment by pabloeisenhut** [comment]
I have filled in all the information to the best of my knowledge. @marius-wieschollek is there any way to fix the problem?

**Comment by marius-wieschollek** [comment]
The exception you found in the logs is just the one that shows up once the maximum attempts have been reached. I have improved the wording in the exception and notifications in relation to this.
You can try the command i wrote in my earlier comment to reset the attempts and see if that resolves the issue or at least brings back the original error messages.
Or you can check this article in the wiki: https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Notifications/Breached-Passwords-Update-Failure-Notification

**Comment by pabloeisenhut** [comment]
Thanks, it actually seems to have been due to the opcache.memory_consumption setting.
