### ISSUE TITLE
[BUG]: Misspelling of the link in the wiki

### ISSUE THREAD

**Issue by pabloeisenhut** [marius-wieschollek/passwords#603]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
-
```

### Client Information

-

### Bug description

https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Services/Password-Security-Check-Services#have-i-been-pwned

![Bildschirmfoto vom 2023-08-27 21-32-07](https://github.com/marius-wieschollek/passwords/assets/137991389/7e1e1f66-9a9b-41e3-aec4-bfc3abb38e6e)

Misspelling of the link https:// instead of httsp://

### Steps to reproduce

-

### Expected behavior

-

### Nextcloud Logs

```shell
-
```

### Browser Logs

```shell
-
```

**Comment by marius-wieschollek** [comment]
fixed it
