### ISSUE TITLE
[NEW APP]: Nextcloud Passwords for Android

### ISSUE THREAD

**Issue by hegocre** [marius-wieschollek/passwords#604]
### ⚠️ This issue respects the following points: ⚠️

- [X] My app is open source
- [X] My app does not contain ads
- [X] Any third party service in my app is optional
- [X] My app is not branded as an "official" app
- [X] My app supports [client side encryption](https://git.mdns.eu/nextcloud/passwords/-/wikis/Developers/Encryption)

### App Name

Nextcloud Passwords

### App description

Secure app for viewing and editing passwords for the Nextcloud Passwords app. Supports end-to-end encryption. 

### App Logo

![Nextcloud Passwords for Android](https://github.com/marius-wieschollek/passwords/assets/15657088/446b8867-fb0b-42ec-b404-8d1f01018b47)

### Download URL

https://play.google.com/store/apps/details?id=com.hegocre.nextcloudpasswords

### App Sources

https://github.com/hegocre/NextcloudPasswords

### Supported Platforms

Android 7.0 or later

### Test instructions

* Download the app, either from [Google Play](https://play.google.com/store/apps/details?id=com.hegocre.nextcloudpasswords) or [GitHub releases](https://github.com/hegocre/NextcloudPasswords/releases/latest).
* Log in with a Nextcloud instance with the Passwords app installed. The [test environment](https://test.passwordsapp.org/info.html) can be used, but with the redirected hostname _nc27.passwordsapp.org_, given that the redirect does not work (not app related problem, also happens with other apps and browser).
* Enter the master password, in case the account uses E2EE.
* Test that everything works fine.

**Comment by marius-wieschollek** [comment]
Looks good to me, i added it
