### ISSUE TITLE
[FEATURE]: Allow other protocols than http:// in URL field

### ISSUE THREAD

**Issue by godfuture** [marius-wieschollek/passwords#605]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

Currently http:// is enforced when entering an URL. This means that e.g. a network ressource in Windows like "\\myhost\myshare" is never valid for entry. This is kind of odd, because I would like to store also this password in Password app.

### Feature Description

The URL field should be able to hold many different types of URI. Like the smb:// or Windows shares that start with \\host\share or ftp:// and so on.

1. Open Nextcloud password website
2. Add a new password
3. Enter User, password and URL field
4. The URL field does not enforce the http protocol

### Additional Context

I understand this behavior is because the URL field was meant for websites. Generally, the Password app could be a perfect password safe (which I try to use it for), but this feature is missing to make it a full replacement for other services.

**Comment by marius-wieschollek** [comment]
The "Website" field allows any valid URI, regardless of protocol, but will prefix the `https://` protocol if none is given.

Windows network names aren't valid URIs and can't be used as such. 

The use of the website field is to create a link that the user can click to get to the page. What browsers do with a windows share is unpredictable and therefore a potential security risk.

I recommend to create a custom text field to store windows share addresses.
