### ISSUE TITLE
[BUG]: Move dialog not available for passwords shared without edit permission

### ISSUE THREAD

**Issue by pdarko2** [marius-wieschollek/passwords#609]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

When someone shares password with you, you can't move that password to another folder, so all shared passwords are piled up in root. Passwords that are shared with edit/share privileges don't have this restriction

### Feature Description

1. Share password from account A to account B (without giving it edit and share rights)
2. On account B, there's no option (in right click or '...' menu) to move password to different folder (no editing shouldn't assume no moving)

When password is shared with edit and share rights (probably only edit needed), it can be moved to any folder for account B (i.e. there is 'move' item in right click/... menu)

**Comment by marius-wieschollek** [comment]
I see this as a bug. You should be able to move these passwords and it is also possible to drag and drop them. It's just that the move dialog isn't there.

**Comment by marius-wieschollek** [comment]
This should be fixed with 2023.10.0
