### ISSUE TITLE
Sharing does not work when auto completion disabled in Nextcloud

### ISSUE THREAD

**Issue by tjwmagic** [marius-wieschollek/passwords#61]
Unable to share passwords with users when the Nextcloud setting "Allow username auto completion in share dialog. If this is disabled the full username or email address needs to be entered." is disabled.

### System Information
- Nextcloud Version: 13.0.5
- PHP Version: 7.1.19-1
- Passwords Version 2018.7.0
- Browser and Version: Google Chrome 67.0.3396.99
- Client OS and Version: Windows 10 Pro1803
- Server OS and Version: Ubuntu 16.04 LTS

### Steps to reproduce
1. Go to the password App and create a new password
2. Go to the details of the new password and click share
3. Type in the full username or email address of the user you want to share the password to.

### Actual result
When you attempt to share a password with a user, you will receive an error "The user <username> does not exist". 

### Expected result
Password should be shared with the user. 

### Notes:
I originally spoke about this on the nextcloud forms. I was suggested to head here. https://help.nextcloud.com/t/share-password-with-other-uses-issue/34607?u=tjwmagic1

mdw believes the issue is caused by the autocomplete, because the password app appears to want to pull the data for the username via autocomplete and since I have that disable, the password app can't find anything.

**Comment by marius-wieschollek** [comment]
This bug has been fixed and released with 2018.9.1.

**Comment by caohee** [comment]
This bug has not fixed in 2018.9.1 version.
https://www.dropbox.com/s/7xkrz9bk8qrppgs/password.png

**Comment by marius-wieschollek** [comment]
@caohee Can you elaborate? From the picture you linked it looks to me like the share has been created.
The loading animation will usually end as soon as the [background job](https://git.mdns.eu/nextcloud/passwords/wikis/Users/F.A.Q#some-of-my-shares-show-a-loading-that-says-some-data-is-waiting-to-be-synchronized) was executed.
