### ISSUE TITLE
Feature Request: Password History 

### ISSUE THREAD

**Issue by Saijin-Naib** [marius-wieschollek/passwords#612]
Something I grew to appreciate from BitWarden was the ability to see prior passwords for a given entry, and the date/time of modification.

I think Firefox does this as well now.

This can help with figuring out prior passwords, especially if a site accepts but can't use a given password (bad check on supported characters, length, etc).

Without this, I'd have been locked out of a few accounts.

**Comment by marius-wieschollek** [comment]
![grafik](https://github.com/marius-wieschollek/passwords/assets/8255857/cb063381-4701-4337-88d0-df96348a5f95)

https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Passwords/Password-Detail-View#revisions

This already exists.
