### ISSUE TITLE
Feature Request: Min/Max Character Slider for Generated Passwords

### ISSUE THREAD

**Issue by Saijin-Naib** [marius-wieschollek/passwords#613]
Most password forms have varied and specific constraints, so being able to move a slider to set the min/max length per-password would be incredibly helpful.

The implementation I'm familiar with is BitWarden, and they had 5 to 128 as the range.

**Comment by marius-wieschollek** [comment]
I'm closing this issue because it's not following any of the mandatory issue forms.

PS: How did you open this issue? I want to know because this keeps happening.

**Comment by Saijin-Naib** [comment]
Oh, sorry. I used OctoDroid on Android, which I think only sometimes supports Issue Templates.

May I re-open from desktop using the correct template?
