### ISSUE TITLE
[FEATURE]: Attachments

### ISSUE THREAD

**Issue by PawelZawodzinski** [marius-wieschollek/passwords#616]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Feature Description
Hi.
It would nice to have ability to add attachments to passwords something like this in keepassxc : https://keepassxc.org/docs/KeePassXC_UserGuide#_attachments

This kind of attachments are encrypted and not directly store in next cloud files. They also can be share together with password.

**Comment by marius-wieschollek** [comment]
See https://github.com/marius-wieschollek/passwords/issues/176
