### ISSUE TITLE
[BUG]: Internal Words API Error

### ISSUE THREAD

**Issue by fyah** [marius-wieschollek/passwords#618]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {                                                                                          "server": "27.1.4.1",                                                                             "app": "2023.11.30",
        "lsr": false,
        "php": "8.2.13",
        "cronPhp": "8.2.13"                                                                           },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": true
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: FF 120
Client OS and Version: Windows 10

### Bug description

Hello,
I have seen from the application logs

![image](https://github.com/marius-wieschollek/passwords/assets/2546966/e974329f-2edf-4e72-a8f9-fd5e0486343a)

`GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to api.corpora.uni-leipzig.de port 80 after 35 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://api.corpora.uni-leipzig.de/ws/corpora/availableCorpora`

So I have contacted the people in charge of uni leipzig to notify them that api was not reachable.

Bellow their answer:

> The domain you mentioned is indeed inactive at the moment, due to a 
> new firewall being setup for the whole university network. You can 
> still find the API under a newer domain here [1]. However, we are also 
> working on a fix for the old one.
> 
> One question in return. You mentioned:
> > This API is being used by the nextcloud password application (this  
> > is how I noticed)
> Could you elaborate on this? We are not aware of any application 
> actively using our API - and I'm not quite sure how a password app 
> would utilize this service?
> 
> Best regards,
> Felix Helfer
> 
> 
> [1] https://api.wortschatz-leipzig.de/

### Steps to reproduce

Use the password nextcloud app to generate a new password

![image](https://github.com/marius-wieschollek/passwords/assets/2546966/5288fff8-e6c0-41e0-8bf8-b8c2789d065a)

Use the extension and try to generate a new password

![image](https://github.com/marius-wieschollek/passwords/assets/2546966/ee081e0c-995b-477f-bc7d-7afbb2d84651)

### Expected behavior

A new password is generated

**Comment by llaumgui** [comment]
Hi,

now I have an another issue:

![image](https://github.com/marius-wieschollek/passwords/assets/411360/8115a5f5-4949-4664-a8be-6369701e603c)

**Comment by fyah** [comment]
here the update solved the problem

![image](https://github.com/marius-wieschollek/passwords/assets/2546966/d0ecf4a8-5ca0-4670-b980-409d267eb115)

**Comment by marius-wieschollek** [comment]
@llaumgui Can you check your nextcloud log for the error message?

**Comment by llaumgui** [comment]
Solved, it's a OPCache issue. I have restarted my PHP container and all is OK.

**Comment by llaumgui** [comment]
> @llaumgui Can you check your nextcloud log for the error message?

@marius-wieschollek it's solved. It was a OPCode issue. Restarting my docker container solve it.
