### ISSUE TITLE
[BUG]: OC\AppFramework\Utility\QueryNotFoundException: ...

### ISSUE THREAD

**Issue by AlthaTechnology** [marius-wieschollek/passwords#619]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "27.1.4.1",
        "app": "2023.12.30",
        "lsr": false,
        "php": "8.2.13",
        "cronPhp": "8.2.13"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "local",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Chromium Version 120.0.6099.71 Brave Browser
Client OS and Version: Windows 11
Edition	Windows 11 Pro
Version	23H2
Installed on	‎7/‎25/‎2023
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

### Bug description

When trying to generate a password in the application on nextcloud or through the brave/chrome browser extension by MDW it does not work and gives errors.

### Steps to reproduce

1. Open the plugin
2. tools
3. generate password
4. does not generate password and gives error

### Expected behavior

1. open app
2. tools
3. generates password

### Nextcloud Logs

```shell
[index] Error: OC\AppFramework\Utility\QueryNotFoundException: Could not resolve OCA\Passwords\Controller\ServiceApiController! Class "OCA\Passwords\Controller\ServiceApiController" does not exist at <<closure>>

0. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 142
   OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Passwords\ ... r")
1. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 494
   OC\AppFramework\Utility\SimpleContainer->query("OCA\\Passwords\ ... r")
2. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 466
   OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Passwords\ ... r")
3. /var/www/html/lib/private/AppFramework/App.php line 162
   OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Passwords\ ... r")
4. /var/www/html/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main("OCA\\Passwords\ ... r", "generatePassword", ["OC\\AppFramewo ... "], ["passwords.serv ... "])
5. /var/www/html/lib/base.php line 1068
   OC\Route\Router->match("/apps/passwords ... d")
6. /var/www/html/index.php line 36
   OC::handleRequest()

POST /index.php/apps/passwords/api/1.0/service/password
from 192.168.1.1 by admin at 2023-12-13T15:35:18+00:00
```

**Comment by marius-wieschollek** [comment]
Do favicons work?

**Comment by AlthaTechnology** [comment]
They do not work.

**Comment by marius-wieschollek** [comment]
I can't reproduce this. does the file `lib/Controller/Api/ServiceApiController.php` exist in the folder of the passwords app? Are there maybe any errors shown in the Nextcloud admin area?
