### ISSUE TITLE
[BUG]: Bad URL when password change page is not found.

### ISSUE THREAD

**Issue by AiroPi** [marius-wieschollek/passwords#622]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "27.1.3.2",
        "app": "2023.12.31",
        "lsr": false,
        "php": "8.1.25",
        "cronPhp": "8.1.25"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imaginary",
        "favicons": "bi",
        "previews": "pageres",
        "security": "bigdb+hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": true,
            "default": "none"
        },
        "cse": {
            "CSEv1r1": true,
            "none": true,
            "default": "CSEv1r1"
        }
    }
}
```

### Client Information

Browser and Version: Arc 1.21.0 (chromium 120.0.6099.109)
Client OS and Version: MacOS 14.0 (23A344)

### Bug description

When we click the button "Open change password page" and Passwords sont find the direct URL, it show a popup, and the url redirect to `https://cloud.domain.com/apps/passwords/{URL}` instead of the URL.

### Steps to reproduce

Click "Open change password page"
<img width="319" alt="image" src="https://github.com/marius-wieschollek/passwords/assets/47398145/13204a12-4752-49f5-a902-81c65b450083">

If passwords don't find the direct url to the form, click on "Open {URL}"
<img width="459" alt="image" src="https://github.com/marius-wieschollek/passwords/assets/47398145/5e141fc6-448f-42a5-badd-6a7cab43d26a">

Then it redirect at `https://cloud.domain.com/apps/passwords/{URL}`
<img width="845" alt="image" src="https://github.com/marius-wieschollek/passwords/assets/47398145/e0df5df7-9fa3-487a-bafd-00f5e68cdfe3">

### Expected behavior

It should open the URL directly.

**Comment by marius-wieschollek** [comment]
I can't reproduce this. The button should just open the url. The only way i can imagine how this happens is, if the url doesn't start with http:// or https://. Is that maybe the case?

**Comment by AiroPi** [comment]
> I can't reproduce this. The button should just open the url. The only way i can imagine how this happens is, if the url doesn't start with http:// or https://. Is that maybe the case?

Yes it is. I imported my passwords from bitwarden, and it seems that by default, it don't add http/https in front of the url. So the url are just (sub).domain.com

**Comment by marius-wieschollek** [comment]
With the latest update, the bitwarden import will automatically correct invalid urls in the file
