### ISSUE TITLE
[BUG]: bitwarden imports of organization vaults fail

### ISSUE THREAD

**Issue by levma** [marius-wieschollek/passwords#623]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
Nextcloud v27.1.5
Passwords v2023.12.31
```

### Client Information

Browser and Version: latest Chrome, latest Safari
Client OS and Version: latest macOS

### Bug description

Try to import a bitwarden json from an export of an organizations vault. It fails because the javascript tries to access an undefined object.

### Steps to reproduce

1. open passwords app in browser / nextcloud instance
2. goto import
3. choose bitwarden json
4. select your organizations vault export file

### Expected behavior

1. import the bitwarden json file
2. see all passwords in the passwords app
3. my proposition: use the vaults `collections` as folders 

### Nextcloud Logs

```shell
unnecessary
```

### Browser Logs

```shell
[Info] Passwords Info – "Passwords Import: Parsing input file" (app.js, line 2)
[Error] TypeError: undefined is not an object (evaluating 'e')
(anonyme Funktion) — ImportManager.d90792a2c1b05801e1b7.js:741
	(anonyme Funktion) (BackupSection.2c699d91dba4163a2847.js:1:31379)

This is https://github.com/marius-wieschollek/passwords/blob/d68396580209ac7a003065bba30aa4e8a4ffb061/src/js/Helper/Import/BitwardenConversionHelper.js#L38 trying to access `folders` which DO NOT exist in the json file.

Consider changing this line https://github.com/marius-wieschollek/passwords/blob/d68396580209ac7a003065bba30aa4e8a4ffb061/src/js/Helper/Import/BitwardenConversionHelper.js#L18C54-L18C66

to `let {tags, tagMap} = await this._processTags(data.folders || data.collections || []);`
```

**Comment by levma** [comment]
and probably on line
https://github.com/marius-wieschollek/passwords/blob/d68396580209ac7a003065bba30aa4e8a4ffb061/src/js/Helper/Import/BitwardenConversionHelper.js#L109
consider to process the `collectionIds` array…

**Comment by marius-wieschollek** [comment]
I have added a patch to the nightly version that should be able to handle the collection ids
