### ISSUE TITLE
[BUG]: undefined property

### ISSUE THREAD

**Issue by manuelkamp** [marius-wieschollek/passwords#625]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "28.0.1.1",
        "app": "2023.12.31",
        "lsr": false,
        "php": "8.1.27",
        "cronPhp": "8.1.27"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "screeenly",
        "security": "hibp",
        "words": "auto",
        "previewApi": true,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: not known which browser/user triggered this
Client OS and Version: Windows 11

### Bug description

Undefined property: OCA\Passwords\Helper\Preview\ScreeenlyHelper::$logger at /var/www/nextcloud/apps/passwords/lib/Helper/Preview/ScreeenlyHelper.php#45 

### Steps to reproduce

I do not know, I found it in error logs

### Expected behavior

No errors in logs

### Nextcloud Logs

```shell
Undefined property: OCA\Passwords\Helper\Preview\ScreeenlyHelper::$logger at /var/www/nextcloud/apps/passwords/lib/Helper/Preview/ScreeenlyHelper.php#45
```

### Browser Logs

```shell
n.a.
```

**Comment by marius-wieschollek** [comment]
Should be resolved with the latest update
