### ISSUE TITLE
API request failed

### ISSUE THREAD

**Issue by pabloeisenhut** [marius-wieschollek/passwords#626]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
.
```

### Client Information

Nextcloud Version: 28.0.1

### Bug description

If you change the settings in the admin area, the error API request failed appears

### Steps to reproduce

1. change an option in your password settings in the administrator area
2. See the error API request failed

### Expected behavior

.

### Nextcloud Logs

```shell
.
```

### Browser Logs

```shell
.
```

**Comment by admorgan** [comment]
I have the same issue. Also no logs to tell me what happened. Passwords App version 2023.12.31

**Comment by marius-wieschollek** [comment]
See https://github.com/marius-wieschollek/passwords/issues/620
