### ISSUE TITLE
Passwords app says need php 7.1, have 7.2.9; NC 13.0.6

### ISSUE THREAD

**Issue by brianfordin** [marius-wieschollek/passwords#63]
ISSUES ARE NOT FOR SUPPORT. Please go to the Nextcloud forum if you have questions or need help.
 -> https://help.nextcloud.com/c/apps/passwords
Please check the existing issues before creating a new one.
 -> https://github.com/marius-wieschollek/passwords/issues?utf8=%E2%9C%93&q=is%3Aissue
If you are reporting a bug, please check if it still exists in the nightly version.
 -> https://apps.nextcloud.com/apps/passwords/releases
If you are experiencing issues with the browser extension, report the issue in the repository
 -> https://github.com/marius-wieschollek/passwords-webextension
Describe your issue here and remember not to include personal data as this is public.

### System Information
- Nextcloud Version: 13.0.6
- PHP Version: 7.2.9
- Passwords Version na
- Browser and Version:  FF 62.0
- Client OS and Version:  Ubuntu Mate 16.04, Windows 10, KDE NEON

![selection_007](https://user-images.githubusercontent.com/16085127/45259455-8788ea80-b39b-11e8-8b7e-534e8bbaf9e2.png)
![selection_008](https://user-images.githubusercontent.com/16085127/45259456-8788ea80-b39b-11e8-8881-620614510149.png)
![selection_009](https://user-images.githubusercontent.com/16085127/45259457-8788ea80-b39b-11e8-91f0-7216a22114b7.png)

- Server OS and Version:  Ubuntu 16.04 64 bit Server (VPS)

### Steps to reproduce
1. Tell us how to reproduce your issue.  Go to apps->security and see "
This app cannot be installed because the following dependencies are not fulfilled:
    PHP 7.1 or higher is required."
2. Provide sample data if needed
3. Include relevant user settings and app settings if not standard

### Actual result
What does happen?  Says need php 7.1 or higher

### Expected result
What should happen?  Allow to enable app

**Comment by marius-wieschollek** [comment]
The PHP on the command line is not necessarily the same as the one used by your webserver.
You can check the version of PHP used for Nextcloud by looking into the Information section in the admin panel.

If you use Apache, PHP is used trough libapache2-mod-php or php-fpm and the related Apache configuration. On Nginx, only php-fpm can be used.

**Comment by brianfordin** [comment]
Thank you for the reply.  I didn't know if it were a bug but I couldn't
find anything when searching and I hope reporting it wasn't too much of a
noob thing to do.

I thought that I totally broke my install after doing an apt autoremove (I
guess to try to get error messages to help me find my way).  Then I went
back through the php part of the installation guide and started messing
with config files and didn't take good notes.  Ultimately, I think it was
just a matter of *a2dismod php7.0* and *a2enmod php7.2* (I never did that
after installing php 7.2).  The default php 7.2 configs did seem to have
some very conservative settings so probably the whole process did more good
than harm.

So now I have the Passwords app installed.

Thanks again for your help.

Brian Ford
