### ISSUE TITLE
[BUG]: Sharing not working

### ISSUE THREAD

**Issue by friedrichkeydel** [marius-wieschollek/passwords#630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "28.0.1.1",
        "app": "2024.1.20",
        "lsr": false,
        "php": "8.2.13",
        "cronPhp": "8.1.26"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "local",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Firefox 121.0.1
Client OS and Version: MacOS 14.2.1

### Bug description

Sharing does not work anymore

The Passwords App tries to reach /apps/passwords/api/cron/sharing and does not get proper response.

`Error: Content type mismatch: Expected application/json, got text/html; charset=UTF-8`

### Steps to reproduce

1. Select "Share" on password item
2. Type in name to share with
3. Nothing happens after one minute or so
4. After that, the selected person appears, but loading indicator circles forever

### Expected behavior

1. Select "Share" on password item
2. Type in name to share with
3. Shared successfull

### Browser Logs

```shell
Error: Content type mismatch: Expected application/json, got text/html; charset=UTF-8
```

**Comment by marius-wieschollek** [comment]
This should already be fixed in the nightly version.

The sharing process should still finish even with the bug, it just takes longer.

**Comment by friedrichkeydel** [comment]
thank you, it's indeed fixed with the current nightly build!
