### ISSUE TITLE
[FEATURE]: Manages linked passwords

### ISSUE THREAD

**Issue by rloutrel** [marius-wieschollek/passwords#634]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

Well.... It is one feature request, but it is something probably huge to implement...

In some cases, one password will be used for several websites, because they are synchronized behind (Ldap) or because a website is using several domains / subdomains (mypage.com ; account.mypage.com ; login.mypage.com/login , ...).

It has as consequences, that the passwords will be recognized as duplicates. Moreover, one password change, will not be synchronized for all other websites using the same "root password", even if changing on one website, means changing on several.

### Feature Description

1. Choose an existing password and select "Create a root credential from this password" (or any better formulation)
2. Optionally, select other passwords to be based on this "root password".

A root password is a [login]/[password] combination which will be changed from any of the entries based on this synchronised base entry. It might be seen (from far away) as something similar to an abstract class versus its derivated classes.

### Additional Context

Some thinkings:
* A root password should not be visible. It would not be a problem if it were, but for lisibility, it could remain hidden and access from any entry based on it.
* Keep it clean: A root password should be deleted if no more entry is based on it. Especially, if the root password are not visible.
* The abstraction mecanism should be done transparently within the API, in order to allow backward compatibility with the client and make the thing transparently.

Following feature requests (API and/or clients) to be created, if the concept is validated (I might create the request for android, linux and firefox):
* Flow when adding a new password should try to recognize if an entry might be based on other synchronised passwords and suggest it to the user. (new endpoint? + clients)

Alternative:
* Another approach would be to define a list of websites (aliases) and not a single website for an entry. It would have the benefit to reduce the amount of entries in the views.

**Comment by marius-wieschollek** [comment]
The app supports custom fields in which you can also maintain URLs. These are then also used to make suggestions e.g. in the browser extension.

Additionally the browser extension will recommend Passwords you have used before on a site even if they don't have a URL for that site.

I think this covers this use case.
