### ISSUE TITLE
[BUG]: single whitespace marked as "secure"

### ISSUE THREAD

**Issue by gitbreaker222** [marius-wieschollek/passwords#638]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
Server OS: Linux 5.15.0-88-generic x86_64
PHP Version: 8.2.12
DB Version: mysql 10.11.4
```

### Client Information

Browser and Version: Firefox 122
Client OS and Version: Ubuntu 22.04 LTS

### Bug description

passwords version: 2023.12.32
nextcloud version: Nextcloud Hub 6 (27.1.3)

# Visual
writing a single whitespace in the password field
![grafik](https://github.com/marius-wieschollek/passwords/assets/4787651/95605fd8-fc87-40a1-8b8c-5b709d0fe7af)

...gets marked with a _green_ Shield icon
![grafik](https://github.com/marius-wieschollek/passwords/assets/4787651/8cf0776a-1031-432f-9ab9-d9f7ac9567c3)

...however if I replace the single whitespace with a e.g. single number `1`, the marker turns to a _red_ shield icon.

_(Note: red and green icons with same shape are not different for users, who have color blindness)_

### Steps to reproduce

- create new entry
- fill the password input with a single whitespace
- save it
- => the security indicator marks it as "safe" (unexpected)
- edit the entry
- change the password to `1`
- save it
- => the security indicator marks it as "unsafe" (expected)

### Expected behavior

 the security indicator marks single whitespaces as "unsafe"

**Comment by marius-wieschollek** [comment]
The SHA-1 hash for a single white space is "b858cb282617fb0956d960215c8e84d1ccf909c6". This SHA has does not appear in the HIBP API for [B858C](https://api.pwnedpasswords.com/range/B858C).
This is likely because no service allows a single white space as password.
The functionality is working as intended.
