### ISSUE TITLE
[BUG]: Download server not reachable

### ISSUE THREAD

**Issue by dnavarrocueto** [marius-wieschollek/passwords#643]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
no needed
```

### Client Information

Browser and Version: Firefox
Client OS and Version: Ubuntu

### Bug description

Trying to install but the following error appears:

cURL error 28: Connection timed out after 120001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.mdns.eu/api/v4/projects/45/packages/generic/passwords/2023.12.2/passwords.tar.gz

### Steps to reproduce

Install Password app

### Expected behavior

App is installed

**Comment by marius-wieschollek** [comment]
This should be resolved by now

**Comment by dnavarrocueto** [comment]
Thank you for your response. Now it works perfectly!

**Comment by marius-wieschollek** [comment]
There seems to be a larger issue with my ISP that leads to sporadic Internet outages.
It will take longer than expected for them to fix their network, so i have uploaded the latest release on Github.

[You can find Passwords 2024.3.0 on the releases page](https://github.com/marius-wieschollek/passwords/releases/tag/2024.3.0)
