### ISSUE TITLE
[BUG]: Exception::__construct()

### ISSUE THREAD

**Issue by EpicJosch** [marius-wieschollek/passwords#646]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "28.0.3.2",
        "app": "2024.3.20",
        "lsr": false,
        "php": "8.2.16",
        "cronPhp": "8.2.16"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imaginary",
        "favicons": "bi",
        "previews": "pageres",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Google Chrome Version 122.0.6261.131 (Offizieller Build) (64-Bit)
Client OS and Version: Windows 10

### Bug description

In the Nextcloud Error Logs there is the following fatal error: Fatal | passwords | TypeErrorException::__construct(): Argument #2 ($code) must be of type int, GuzzleHttp\Exception\ClientException given

### Steps to reproduce

1. Use the passwords app
2. Look in the nextcloud logs

### Expected behavior

1. No error

**Comment by marius-wieschollek** [comment]
Yes, this should already be fixed in the nightly version of the app

**Comment by Sabering1** [comment]
i have this problem too

**Comment by TommasoCostanzo** [comment]
Same error for me and I am using Nextcloud AIO latest (Nextcloud Hub 7 (28.0.4)) and Passwords is the same version: 2024.3.20
