### ISSUE TITLE
[BUG]: error message "construct(): Argument #2 ($code) must be of type int"

### ISSUE THREAD

**Issue by GUNT0815** [marius-wieschollek/passwords#648]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "28.0.3.2",
        "app": "2024.3.20",
        "lsr": false,
        "php": "8.2.16",
        "cronPhp": "8.2.16"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imaginary",
        "favicons": "bi",
        "previews": "pageres",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Firefox 124.01
Client OS and Version: ZorinOS 17.01

### Bug description

error log shows:

[passwords] Fatal: Exception::__construct(): Argument #2 ($code) must be of type int, GuzzleHttp\Exception\ClientException given
	GET /index.php/apps/passwords/api/1.0/service/favicon/eisencloud.de/32

### Steps to reproduce

- install passwords

### Expected behavior

no error message

### Nextcloud Logs

```shell
[passwords] Fatal: Exception::__construct(): Argument #2 ($code) must be of type int, GuzzleHttp\Exception\ClientException given
	GET /index.php/apps/passwords/api/1.0/service/favicon/kinghp5.lan:9080/32
	from 192.168.1.1 by user at Mar 27, 2024, 11:51:11 AM
```

### Browser Logs

```shell
n.a.
```

**Comment by marius-wieschollek** [comment]
https://github.com/marius-wieschollek/passwords/issues/646
