### ISSUE TITLE
[BUG]: Update to 2024.03.20 doesn't work (timeout)

### ISSUE THREAD

**Issue by walhallaRV** [marius-wieschollek/passwords#649]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
PHP 8.2.17 / NC 28.0.3 / NC 28.0.4
```

### Client Information

Browser and Version: Chrome / FF
Client OS and Version: Win 10 / Linux Debian 12

### Bug description

Update does not work. After several minutes of waiting returns without update but erro in log

### Steps to reproduce

Simply try to make update in NC  -> Apps -> Update 

### Expected behavior

Making the update

### Nextcloud Logs

```shell
[no app in context] Fehler: cURL error 28: Operation timed out after 120000 milliseconds with 3799664 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://git.mdns.eu/api/v4/projects/45/packages/generic/passwords/2024.3.0/passwords.tar.gz
	GET /index.php/settings/apps/update/passwords
	von x.x.x.x von anyone um 29.03.2024, 03:21:03
```

**Comment by marius-wieschollek** [comment]
I can currently not reproduce the issue. In case of connection errors i recommend to download and install the update manually from the build server: https://git.mdns.eu/nextcloud/passwords/-/releases or try again later.
