### ISSUE TITLE
[FEATURE]: Can you add a language option for Chinese, please?

### ISSUE THREAD

**Issue by dpifox** [marius-wieschollek/passwords#650]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

Passwords is really an important plugin for Nextcloud! I'm so lucky to have found such a plugin.
But as a Chinese person who is not good at English, I wonder if you could add support for Chinese?
Thanks.

### Feature Description

Please use machine translation directly. If you need help, you can tell me the text information for assistance. Thank you!

**Comment by marius-wieschollek** [comment]
But don't we already have simplified Chinese? See https://weblate.passwordsapp.org/projects/passwords/passwords/zh_Hans/

If you change the Nextcloud language settings to "zh_CN" (should be labelled "简体中文"), the translation should be used.

If you mean any other version of Chinese, can you please provide the language tag?

**Comment by dpifox** [comment]
> But don't we already have simplified Chinese? See https://weblate.passwordsapp.org/projects/passwords/passwords/zh_Hans/
> 
> If you change the Nextcloud language settings to "zh_CN" (should be labelled "简体中文"), the translation should be used.
> 
> If you mean any other version of Chinese, can you please provide the language tag?

I'm sorry, what I meant to say is about the browser extension; it still doesn't support Chinese.

**Comment by dpifox** [comment]
The official Microsoft Edge extension

**Comment by marius-wieschollek** [comment]
Ok. I have added the translation files here: https://weblate.passwordsapp.org/translate/passwords-webextension/extension/zh_Hans

They will be part of the next update. So far this is fully machine translated using DeepL and LibreTranslate, so i can't guarantee that the translation is consistent and correct. Maybe someone who speaks both Chinese and English (or any of the other manually translated languages) should go over it and check if it actually makes sense.
