### ISSUE TITLE
[BUG]: GenericFileException; Exception thrown: OCP\Files\GenericFileException

### ISSUE THREAD

**Issue by Rimos911** [marius-wieschollek/passwords#653]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
Hello,

can someone tell me what this error message means and how I can fix it.
My NC is up-to-date (28.0.4); Password-App: 2024.4.20
This error occurs even after uninstalling the app

Protocoll

Level: Fatal
Anwendug: passwords
Message:

GenericFileException
Exception thrown: OCP\Files\GenericFileException
Exception thrown: OCP\Files\GenericFileException

GenericFileException
file_put_contents failed
```

### Client Information

Browser and Version:
Client OS and Version:

### Bug description

GenericFileException
Exception thrown: OCP\Files\GenericFileException
Exception thrown: OCP\Files\GenericFileException

GenericFileException
file_put_contents failed

### Steps to reproduce

schedule daylie maintenance over night

### Expected behavior

Protocoll

**Comment by marius-wieschollek** [comment]
The issue template is mandatory
