### ISSUE TITLE
[BUG]: Tab for sharing not visible

### ISSUE THREAD

**Issue by knobsam** [marius-wieschollek/passwords#654]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
Nextcloud 28.0.3
```

### Client Information

Browser and Version: Vivaldi, 6.6.3271.57
Client OS and Version: Any OS

### Bug description

Hi,

when selecting "Share" from the menu for a password the content with the input field is not visible (but there).
Singe-use workaround is to go into the browsers Developer-Tools, search for CSS class "sharing-container" and remove/rename is. Then everything works as expected.

I cannot provide the OCC output (requested above) because my Nextcloud is managed by a Hoster, and the commands are not available to me.

Best regards,

Samuel

### Steps to reproduce

1. Click on "...", select "Share"
2. Sidebar opens with tab "Share" selected
3. Tab content (input for user search) is not visible

### Expected behavior

1. Click on "...", select "Share"
2. Sidebar opens with tab "Share" selected
3. Tab content (input for user search) is visible
4. I can search for a user

**Comment by marius-wieschollek** [comment]
Did you check your adblock?

**Comment by knobsam** [comment]
I just did. After switching it off it works.
I wonder how I got my settings that broken, because I also (re-)checked yesterday at home on my own setup and found that it works.

Looks like I'll go through my settings on each system checking where the differences are.
Thanks, I think this can be closed. :)
