### ISSUE TITLE
[BUG]: Link in navbar doesn't lead to passwords

### ISSUE THREAD

**Issue by D3nnis3n** [marius-wieschollek/passwords#656]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "29.0.0.19",
        "app": "2024.5.20",
        "lsr": false,
        "php": "8.3.7",
        "cronPhp": "8.3.6"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Google Chrome
Client OS and Version: Windows 11 Pro Insider

### Bug description

The link in navbar leads to whatever is the current page you are instead of to passwords. The same problem exists for some other extensions, like Mail and Polls.

### Steps to reproduce

1. Open Nextcloud Dashboard
2. Click Passwords menu button
3. See you just refresh the page

### Expected behavior

1. Open Nextcloud Dashboard
2. Click Passwords menu button
3. Actually go to the passwords page

**Comment by marius-wieschollek** [comment]
Did you _seriously_ open the same bug report in several projects?
I think even a non-technical user can understand that the navigation bar is part of Nextcloud and not the individual app. If the buttons only do not work within the dashboard app, then there may be an issue with that app, if they don't work in any app, then it may be an issue with Nextcloud.
I can't reproduce the issue at all, so it might also be any other app you have installed.

Please close _all_ of the unnecessary issues you have opened and describe your problem in Nextlouds support forum to receive help with the issue on your instance: https://help.nextcloud.com/c/support/7
