### ISSUE TITLE
[FEATURE]: Additional Master-Password to access passwords

### ISSUE THREAD

**Issue by DIY89** [marius-wieschollek/passwords#664]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

no master password is requested. If user is logged in it'S possible to access the password app without additional secuity

### Feature Description

1. I open the app
2. master password is requested (Ether user password or special master password)

**Comment by marius-wieschollek** [comment]
https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Encryption/Enable-End-to-End-Encryption
