### ISSUE TITLE
[BUG]: Template message.html not found

### ISSUE THREAD

**Issue by ibahnasy** [marius-wieschollek/passwords#665]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "29.0.4.1",
        "app": "2024.7.20",
        "lsr": false,
        "php": "8.3.6",
        "cronPhp": "8.3.6"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Firefox 128
Client OS and Version: Ubuntu 24.04

### Bug description

When creating a new folder, the UI does nothing and in the Browser's developer tools I see HTTP 404 for GET message.html template, however this file exists.

![Screenshot from 2024-07-29 04-31-17](https://github.com/user-attachments/assets/66e5394e-b7c1-4c0d-afdf-7844c0417cb1)

### Steps to reproduce

1. Open browser's developer tools to inspect network requests.
2. Try to create a new folder.

### Expected behavior

It should load the template file fine as it exists and create the folder.

**Comment by marius-wieschollek** [comment]
This is a core template used by Nextcloud dialogs. If your server can't deliver that, the error is outside the passwords app.

**Comment by ibahnasy** [comment]
After I modified Nginx locations, it works fine now, Thanks.
