### ISSUE TITLE
password security

### ISSUE THREAD

**Issue by ashgoodman** [marius-wieschollek/passwords#67]
"Passwords offers a safe server-side encryption using Nextclouds integrated encryption functionality. Each password is encrypted with it's own unique key"

Does this mean server-side encryption must be activated, or that the default encryption module app must be enabled?

**Comment by marius-wieschollek** [comment]
Passwords uses the `ICrypto` interface provided in the Nextcloud source code to handle encryption. No other apps are needed as this interface is always present in Nextcloud.

**Comment by ashgoodman** [comment]
@marius-wieschollek thank you for the clarification. I'll mark this as closed
