### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Bolverik** [marius-wieschollek/passwords#675]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "29.0.8.1",
        "app": "2024.9.20",
        "lsr": false,
        "php": "8.3.12",
        "cronPhp": "8.3.12"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "pgsql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "bi",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": true,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: 131.0.2 (64-разрядный)
Client OS and Version: Ubuntu 24.04

### Bug description

After update from legacy version, the error screen appears when I try to use the app.
Journal shows this message: 	
QueryException Could not resolve OCA\Passwords\Helper\Random\Randomizer! Class "OCA\Passwords\Helper\Random\Randomizer" does not exist

Turns out Random folder was not present in passwords/lib/Helper/. Whe I added it, the app started working.

### Steps to reproduce

1. I open app or admin page for the app
2. Error message appears

### Expected behavior

1. When I open the app, it should work.

**Comment by marius-wieschollek** [comment]
The class `OCA\Passwords\Helper\Random\Randomizer` is not part of versions ending on `.20`. Only LSR releases ending on `.10` have that class as a fallback. I assume you either have recently switched from LSR to normal releases but still have old code cached somewhere in PHP or you have an inconsistent installation.
