### ISSUE TITLE
[BUG]: Error while running background job AbstractMapper::findAllByField()

### ISSUE THREAD

**Issue by cyrkul** [marius-wieschollek/passwords#676]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "30.0.1.2",
        "app": "2024.9.20",
        "lsr": false,
        "php": "8.2.24",
        "cronPhp": "8.2.24"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imaginary",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Cachy Browser 131.0.3
Client OS and Version: CachyOS Linux 

### Bug description

After update to [Nextcloud Hub 9](https://nextcloud.com/) (30.0.1) I get following error:
` TypeError OCA\Passwords\Db\AbstractMapper::findAllByField(): Argument #3 ($type) must be of type int, string given, called in /var/www/nextcloud/apps/passwords/lib/Db/PasswordMapper.php on line 30
Error while running background job OCA\Passwords\Cron\SynchronizeShares (id: 55, arguments: null) `

### Steps to reproduce

It seems to be related to background cron job, I see it after some time of normal usage.

### Expected behavior

Cron job should not return Error

**Comment by kiv57** [comment]
Same here.

NC 30.0.1 (upgraded from 29.* a few days ago)
PHP 8.3.12
MariaDB 11.4.3

**Comment by HolgerHees** [comment]
https://github.com/marius-wieschollek/passwords/pull/678

**Comment by creopard** [comment]
A fix is already in the making:
https://git.mdns.eu/nextcloud/passwords/-/commit/ca89a8b9129f00002cb307c73323e68ff0bde85d
