### ISSUE TITLE
[BUG]: Cant share password on NC 9 (30.0.1)

### ISSUE THREAD

**Issue by cuseeme** [marius-wieschollek/passwords#677]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "30.0.1.2",
        "app": "2024.9.20",
        "lsr": false,
        "php": "8.2.23",
        "cronPhp": "8.2.23"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "local",
        "previews": "default",
        "security": "hibp",
        "words": "leipzig",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: Firefox 131.0.3
Client OS and Version: Win 11

### Bug description

When i try to share a password the user icon is spinning on the share tab and the message "Some data is waiting to be synchronized" is displayed in hover.

The nc log reports multi entrys wit Passwords runs /index.php/apps/passwords/cron/sharing in global mode

The password is only shared when run the folowing command: php ./occ config:app:delete passwords cron/sharing/time

### Steps to reproduce

1. Share a password with another user
2. The user icon is spinnig and the password is not shared

### Expected behavior

The password should be shared immediately

### Nextcloud Logs

```shell
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:31:04	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:31:00	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:58	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:55	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:53	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:50	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:47	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:45	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:41	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:40	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:35	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:35	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:29	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:29	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:23	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:23	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:18	
Information	passwords	
Passwords runs /index.php/apps/passwords/cron/sharing in global mode
22.10.2024, 10:30:17
```

**Comment by lucentwolf** [comment]
All my Instances are also affected after update from NC 29.x to NC 30.0.1 - also the ones running as ubuntu snaps. I noticed that after some hours, the password will eventually be shared & "spinning" stops ... wild guess: probably some cron job fixes it?

**Comment by Pfnetsch** [comment]
Same issue. NC 30.0.1 & Passwords 2024.9.20
Following error wos in the log after some time:
"TypeError
OCA\Passwords\Db\AbstractMapper::findAllByField(): Argument #3 ($type) must be of type int, string given, called in /var/www/nextcloud/apps/passwords/lib/Db/PasswordMapper.php on line 30
Error while running background job OCA\Passwords\Cron\SynchronizeShares (id: 1186, arguments: null)"

Thanks

**Comment by nmartinez-nimeops** [comment]
Hi all,
same issue
NC 30.0.1 & Passwords 2024.9.20

**Comment by nmartinez-nimeops** [comment]
Hi all,
updated to **2024.11.20** and **NC 30.0.2**, always the bug

**Comment by Oliver3911** [comment]
Hi all,
same issues in 2024.11.20 and NC 28.0.12 (also 28.0.11 but just updated to check)
