### ISSUE TITLE
[BUG]: OCA\\Passwords\\Db\\AbstractMapper::findAllByField(): Argument #3 ($type) must be of type int, string given

### ISSUE THREAD

**Issue by KernSani** [marius-wieschollek/passwords#680]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "30.0.1.2",
        "app": "2024.9.20",
        "lsr": false,
        "php": "8.3.6",
        "cronPhp": "8.3.6"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": false,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version: N/A
Client OS and Version: N/A

### Bug description

regular Message in Nextcloud log:
{"reqId":"1e7IxXcnxK2s2XNCwDN0","level":3,"time":"2024-10-22T18:10:03+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 1473, arguments: null)","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"TypeError","Message":"OCA\\Passwords\\Db\\AbstractMapper::findAllByField(): Argument #3 ($type) must be of type int, string given, called in /var/www/html/apps/passwords/lib/Db/PasswordMapper.php on line 30","Code":0,"Trace":[{"file":"/var/www/html/apps/passwords/lib/Db/PasswordMapper.php","line":30,"function":"findAllByField","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Services/Object/PasswordService.php","line":72,"function":"findAllShared","class":"OCA\\Passwords\\Db\\PasswordMapper","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Cron/SynchronizeShares.php","line":267,"function":"findShared","class":"OCA\\Passwords\\Services\\Object\\PasswordService","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Cron/SynchronizeShares.php","line":84,"function":"removeSharedAttribute","class":"OCA\\Passwords\\Cron\\SynchronizeShares","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Cron/AbstractTimedJob.php","line":59,"function":"runJob","class":"OCA\\Passwords\\Cron\\SynchronizeShares","type":"->"},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":83,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":73,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/html/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/apps/passwords/lib/Db/AbstractMapper.php","Line":179,"message":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 1473, arguments: null)","exception":{},"CustomMessage":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 1473, arguments: null)"}}

### Steps to reproduce

1. Check the log and see the error message
There's no obvious malfunction, just the log message that makes me a bit nervous... I assume there's an issue with passwords imported from lastPass (at least I noticed the log message only after I imported those passwords)

### Expected behavior

1. No error messages in log

### Nextcloud Logs

```shell
{"reqId":"1e7IxXcnxK2s2XNCwDN0","level":3,"time":"2024-10-22T18:10:03+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 1473, arguments: null)","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"TypeError","Message":"OCA\\Passwords\\Db\\AbstractMapper::findAllByField(): Argument #3 ($type) must be of type int, string given, called in /var/www/html/apps/passwords/lib/Db/PasswordMapper.php on line 30","Code":0,"Trace":[{"file":"/var/www/html/apps/passwords/lib/Db/PasswordMapper.php","line":30,"function":"findAllByField","class":"OCA\\Passwords\\Db\\AbstractMapper","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Services/Object/PasswordService.php","line":72,"function":"findAllShared","class":"OCA\\Passwords\\Db\\PasswordMapper","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Cron/SynchronizeShares.php","line":267,"function":"findShared","class":"OCA\\Passwords\\Services\\Object\\PasswordService","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Cron/SynchronizeShares.php","line":84,"function":"removeSharedAttribute","class":"OCA\\Passwords\\Cron\\SynchronizeShares","type":"->"},{"file":"/var/www/html/apps/passwords/lib/Cron/AbstractTimedJob.php","line":59,"function":"runJob","class":"OCA\\Passwords\\Cron\\SynchronizeShares","type":"->"},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\Passwords\\Cron\\AbstractTimedJob","type":"->"},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":83,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":73,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/html/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/html/apps/passwords/lib/Db/AbstractMapper.php","Line":179,"message":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 1473, arguments: null)","exception":{},"CustomMessage":"Error while running background job OCA\\Passwords\\Cron\\SynchronizeShares (id: 1473, arguments: null)"}}
```

### Browser Logs

```shell
N/A
```

**Comment by RTechSn** [comment]
Yes, i have the same problem. It occurs when trying to share a password. 
I'm unable to share passwords anymore, infinite sync state.

**Comment by RTechSn** [comment]
https://github.com/marius-wieschollek/passwords/commit/ca89a8b9129f00002cb307c73323e68ff0bde85d This commit fixes the problem. It is strange it's not yet released.

**Comment by KernSani** [comment]
I don't shre any passwords, but still have the issue - nevertheless the commit you mention looks promising, hope it will be released soon.
