### ISSUE TITLE
[IMPROVEMENT]: Allow blank password field without mandatory input

### ISSUE THREAD

**Issue by MiMoHo** [marius-wieschollek/passwords#682]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/home))_.

### Current Status

When creating a new password, the password field has to be filled. However, there are platforms that do not use a password anymore but passkeys on registered devices, a physical ID card attached to the phone or simply just send an OTP to the mailbox. Hence, requiring the user to specify a mandatory input in the password field is obsolete.

### Feature Description

Simply allow saving of new passwords without any input in the password field.

**Comment by marius-wieschollek** [comment]
https://github.com/marius-wieschollek/passwords/issues/578
