### ISSUE TITLE
Sharing passwords doesn't work when using Active Directory for authenticating.

### ISSUE THREAD

**Issue by roru69** [marius-wieschollek/passwords#72]
### System Information
- Nextcloud Version: 14
- PHP Version: 7.1
- Passwords Version: 2018.10.0-build2410
- Browser and Version: Firefox 62.0
- Client OS and Version: Windows 10
- Server OS and Version: Debian 8.11

### Steps to reproduce
Nextcloud is set to authenticate against my Active Directory (LDAP). This works just fine. Sharing files with other users also works as it should.

When i share a Password with another user I can type in (part) of a username and the user is found. When i select the user the avatar starts blinking.

### Actual result
The avatar of the user starts blinking. It never becomes solid and the password isn't shared with the other user

### Expected result
The avatar should become solid after some time and the password should be visible in account of the other user.

Kind regards, RoRo69

**Comment by roru69** [comment]
{Solved] Thank you for pointing me in the right direction.

I failed to set a Cronjob for executing background tasks. Tried it manually and sharing started to work. Added a job in Crontab and the problem was solved. Now every 5 minutes the job runs and passwords get shared.

See: [Crontab](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/background_jobs_configuration.html?highlight=crontab)

Regards, RoRu69

**Comment by caohee** [comment]
> {Solved] Thank you for pointing me in the right direction.
> 
> I failed to set a Cronjob for executing background tasks. Tried it manually and sharing started to work. Added a job in Crontab and the problem was solved. Now every 5 minutes the job runs and passwords get shared.
> 
> See: [Crontab](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/background_jobs_configuration.html?highlight=crontab)
> 
> Regards, RoRu69

**How do I execute this process? I can not share the passwords in the NextCloud version 14.**
**When i select the user the avatar starts blinking.**

Thanks!
Cao
