### ISSUE TITLE
Folder icon is on the localhost domain

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#8]
See: https://github.com/marius-wieschollek/passwords/blob/dfb5db2fe3ca52a52189ceff1df3bcc647a7b8b5/src/js/ApiClient/EnhancedApi.js#L682

`Throws: Content Security Policy: The page's settings blocked the loading of a resource at http://localhost/core/img/filetypes/folder.svg`

The http://localhost part probably wants to be qualified properly using `window.location` ?

**Comment by marius-wieschollek** [comment]
Yes, that is wrong. Thanks for reporting. It should actually be on the same domain as the api endpoint, so i changed that.
