### ISSUE TITLE
Using tab to go to next field selects hidden option

### ISSUE THREAD

**Issue by adanielvv** [marius-wieschollek/passwords#81]
### System Information
    Nextcloud Version: 13.0.6
    PHP Version: 7.2.10
    Passwords Version: 2018.9.1
    Browser and Version: Firefox 62.0
    Client OS and Version: Ubuntu 18.04
    Server OS and Version: Ubuntu 18.04

### Steps to reproduce
1. Create or edit a password entry
2. Use tab to go to the next entry field (Password)
3. Use tab again go to the next entry field (Name)

### Actual result
Hidden field gets focus (Numbers)

### Expected result
Next visible field gets focus (Name)

**Comment by adanielvv** [comment]
Setting `display: none;` on the hidden html fixes this, or:
```
jQuery("#password-password-numbers").prop('disabled', true);
jQuery("#password-password-special").prop('disabled', true);
```

**Comment by adanielvv** [comment]
Not easy to fix, wanted to create a PR on the dialog [CreatePassword.vue](https://github.com/marius-wieschollek/passwords/blob/master/src/vue/Dialog/CreatePassword.vue), implementing `display:none;`, but that removes the fade...

**Comment by marius-wieschollek** [comment]
disabling the fields solves the issue

**Comment by adanielvv** [comment]
Thanks! I think I need to learn vue.js!
