### ISSUE TITLE
Store partial SHA-1 hashes only

### ISSUE THREAD

**Issue by marius-wieschollek** [marius-wieschollek/passwords#83]
Currently, the app stores the full SHA-1 hash with each password, to check it against the Hibp? database. When client side encryption is being used, the SHA-1 has could be used to guess the password without cracking the actual encryption. Using the full SHA-1 has was a requirement for Hibp? in the past, but now it is possible to search their database by range. So if a higher number of potentially false positives is acceptable, only a part of the hash could be stored. 

### System Information
- Nextcloud Version: 14.0.1
- PHP Version: 7.2.0
- Passwords Version: 2018.9.1
- Browser and Version: Any
- Client OS and Version: Any
- Server OS and Version: Any

### Steps to reproduce
1. Create a password
2. Check the database entry for the password

### Actual result
You will find a complete SHA-1 hash of the password.

### Expected result
It should be possible to store just a partial hash.

**Comment by Misterodd** [comment]
Hi, 
I try to understand the Encryption. Are the paswords saved as a sha-1 hash in the DB? Why not sha-256? When this is for lookup, why not creating before checking and after that deleting the sha-1 again? And for the user can get a newly genrated sha-1 when he looks at the password.
Did I missed something here? https://git.mdns.eu/nextcloud/passwords/wikis/Developers/Encryption
Thank you in advance,

**Comment by marius-wieschollek** [comment]
The SHA-1 hash is only used for the HIBP password breach check.
If server side encryption is used, the SHA-1 is calculated by the server and stored with the password entry.
When client side encryption is used, the SHA-1 hash has to be provided by the client since the server can no longer create it.
Since the server can't calculate the checksum for passwords with client side encryption, we must store them permanently in order to be able to perform the password breach check.

**Comment by Misterodd** [comment]
Ah ok, thank you.

**Comment by marius-wieschollek** [comment]
The length of the hash can now be set in the advanced settings. The setting will be applied to new passwords immediately and to existing passwords / revisions when the next security check is run.
It should be obvious to every user that once the hash has been shortened, the full length can not be restored again.
