### ISSUE TITLE
[feature request] more values for custom CSV import

### ISSUE THREAD

**Issue by mokkin** [marius-wieschollek/passwords#85]
I have managed to extract my firefox password list with the help of https://github.com/kspearrin/ff-password-exporter
Unfortunately I can only import the date and time for "last changed".
The fields for "created", "last used"  and "times used" are missing.
![bildschirmfoto zu 2018-10-12 11-52-15](https://user-images.githubusercontent.com/2938748/46863050-a6552380-ce16-11e8-8c3e-5b3daa2396a6.png)
Could you add them to the import function?

**Comment by marius-wieschollek** [comment]
Sorry, i can't. created and updated are not writable. These values are managed by the server only.
For `lastUsed` i suggest that you could use a custom field after #71 is implemented.
