### ISSUE TITLE
disable mandatory https

### ISSUE THREAD

**Issue by 387119** [marius-wieschollek/passwords#88]
hi, i think will be good to add feature to disable "This application requires HTTPS in order to work safely.", for example you can have something next
Internet ---(https)-->reverse proxy ---(http)--> nextcloud

in this way you will have secure line over internet anyway.

**Comment by jchammons** [comment]
@387119 , I've had this issue with nextcloud-passwords . Per the link @marius-wieschollek  sent, the specific thing you need to change is to add the following to config.php:

```
  'overwritehost'     => 'ssl-proxy.tld',
  'overwriteprotocol' => 'https',
```

**Comment by adocampo** [comment]
I have a dockerized environment so nextcloud and other containers only servers http, and my reverse proxy handles all certificates and security.
By adding what @jhammons suggested, passwords seems to work fine. I've just added those two lines
```
   'overwritehost'     => 'cloud.example.com',
   'overwriteprotocol' => 'https',
```

**Comment by marius-wieschollek** [comment]
Since this seems to affect multiple people, the HTTPS warning will include a link to the "Reverse proxy configuration" in future versions.
