### ISSUE TITLE
Can't delete all password, password not accepted

### ISSUE THREAD

**Issue by budachst** [marius-wieschollek/passwords#89]
I am currently evaluating passwords and I have performed some rounds of importing my current passman vault, which I exported as JSON. So, I ended up with a couple of duplicates and decided to remove all the passwords and start over. However, when trying to delete everything from the preferences section, I do have to provide a password and it won't accept my password.

It may have something to do with my account being bound to LDAP and/or that I am using U2F, but it should accept my password anyway.

### System Information
- Nextcloud Version: 14.0.3
- PHP Version: 7.2
- Passwords Version: 2018.10
- Browser and Version: Chrome 70.0.3538.67/FF 62.0.3
- Client OS and Version: macOS Mojave
- Server OS and Version: Debian 9.3

### Steps to reproduce
1. go to setting/danger zone
2. hit "Delete everything"/"Alles Löschen"
3. enter account password

Here's the NC log when hitting the delete button:
`{"reqId":"sKF4z1vgo9f5h1jbZ0Fb","level":3,"time":"2018-10-27T19:47:36+02:00","remoteAddr":"10.10.0.248","user":"c3f7c232-bed6-4ede-8291-13f752448a5b","app":"passwords","method":"POST","url":"\/index.php\/apps\/passwords\/\/api\/1.0\/service\/x-reset-user-account","message":{"Exception":"OCA\\Passwords\\Exception\\ApiException","Message":"Password invalid","Code":256,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"resetUserAccount","class":"OCA\\Passwords\\Controller\\Api\\ServiceApiController","type":"->","args":["nhambm9"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\ServiceApiController"},"resetUserAccount"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Passwords\\Controller\\Api\\ServiceApiController"},"resetUserAccount"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["ServiceApiController","resetUserAccount",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"passwords.service_api.reset_user_account"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"passwords.service_api.reset_user_account"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"passwords.service_api.reset_user_account"}]},{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/passwords\/api\/1.0\/service\/x-reset-user-account"]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/apps\/passwords\/lib\/Controller\/Api\/ServiceApiController.php","Line":213,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.14; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}`

### Actual result
Password is rejected

### Expected result
all passwords get deleted

**Comment by marius-wieschollek** [comment]
When you use LDAP, the user login name and the user id in Nextcloud do not match.
The user id will be generated by Nextcloud in this case.
I used the user id to verify the password, but this will not work since the user id does not exist in LDAP.

I am working on a fix to use the user login name instead.

**Comment by marius-wieschollek** [comment]
Update is released
