### ISSUE TITLE
Browser extension goes to de localised page.

### ISSUE THREAD

**Issue by HanPrower** [marius-wieschollek/passwords#9]
See: https://github.com/marius-wieschollek/passwords/blob/dfb5db2fe3ca52a52189ceff1df3bcc647a7b8b5/src/vue/App.vue#L69

And see: https://github.com/marius-wieschollek/passwords/blob/7b51845835950989df0397d1715915e90bdd9c42/README.md#L58

The correct link to get so it works off of the user's locale is to just remove the /de, i.e.:
`https://addons.mozilla.org/firefox/addon/nextcloud-passwords/`

**Comment by marius-wieschollek** [comment]
Yes, you're right. Thanks for reporting.
