### ISSUE TITLE
Passwords not loading after importing from Passman

### ISSUE THREAD

**Issue by bingen** [marius-wieschollek/passwords#90]
### System Information
- Nextcloud Version: 14.0.3
- PHP Version: 7.2.11-2
- Passwords Version: 2018.10.0
- Browser and Version: Firefox 63.0
- Client OS and Version: Ubuntu 16.04
- Server OS and Version: Debian 9.5

### Steps to reproduce
Import passwords from Passman and then try to access Passwords app. 

### Actual result
What does happen?

The circle loading animated icon keeps going for ever.
There are 2 calls failing (error 504):
https://nextcloud.mydomain.com/index.php/apps/passwords/api/1.0/settings/get
https://nextcloud.mydomain.com/index.php/apps/passwords/api/1.0/folder/show
Server logs show the following errors:
```
{"reqId":"Yr88fMe4GdJOwd03t4bq","level":2,"time":"2018-10-28T21:48:43+00:00","remoteAddr":"172.19.0.9","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/settings\/get"
,"message":"Login failed: 'my-user-id' (Remote IP: '172.19.0.9')","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0
"}
{"reqId":"zueDJjE7Iu5IIWhlYhpn","level":2,"time":"2018-10-28T21:48:43+00:00","remoteAddr":"172.19.0.9","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/folder\/show",
"message":"Login failed: 'my-user-id' (Remote IP: '172.19.0.9')","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"
}
{"reqId":"zueDJjE7Iu5IIWhlYhpn","level":2,"time":"2018-10-28T21:48:43+00:00","remoteAddr":"172.19.0.9","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/folder\/show",
"message":"Login failed: 'my-user-id' (Remote IP: '172.19.0.9')","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"
}
{"reqId":"Yr88fMe4GdJOwd03t4bq","level":2,"time":"2018-10-28T21:48:44+00:00","remoteAddr":"172.19.0.9","user":"--","app":"core","method":"POST","url":"\/index.php\/apps\/passwords\/api\/1.0\/settings\/get"
,"message":"Login failed: 'my-user-id' (Remote IP: '172.19.0.9')","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0
"}

```
### Expected result
What should happen?

Passwords should show up.

**Comment by marius-wieschollek** [comment]
Recently, users using LDAP reported login issues. Could that apply to you?
I mean, do you use LDAP?

**Comment by bingen** [comment]
Yes, I'm using LDAP. How can I check that's the problem? Is there a way to fix it?

**Comment by marius-wieschollek** [comment]
You can try the folowing things:
- Reload the page
- Or go to the settings and delete the "Passwords WebUi Access" token in the security section. Then open the app again
- Or Log out and then log in again

**Comment by marius-wieschollek** [comment]
Do you have some kind of login limit on your ldap?

**Comment by marius-wieschollek** [comment]
I think this is caused by the same bug as #89 . LDAP users do have a different uid than login name, but the app does not respect that. I was able to reproduce the issue and at least for me it's gone with the current nightly.

**Comment by bingen** [comment]
That makes sense, my uid is indeed different than my login name. How can I test that? When is the next version going to be released? Thanks!

**Comment by marius-wieschollek** [comment]
As i said, the Nightly is already out and can be downloaded from the official [Nextcloud app store](https://apps.nextcloud.com/apps/passwords). The final release will be out the first November weekend.

**Comment by marius-wieschollek** [comment]
Update released
