### ISSUE TITLE
Home Password application load very long time with no result

### ISSUE THREAD

**Issue by kevngzc** [marius-wieschollek/passwords#92]
### System Information
- Nextcloud Version: 14.0.3
- PHP Version: 7.2
- Passwords Version: 10.0
- Browser and Version: Firefox 63.0.1 (64 bits)
- Client OS and Version:
- Server OS and Version:

### Steps to reproduce
1. Tell us how to reproduce your issue.
I installed passwords application from nextcloud store and when i click on key icon the screen load very long time.

2. Provide sample data if needed

My log 
https://imgur.com/a/kN0qL0o

3. Include relevant user settings and app settings if not standard
I applied all security recommandation of nextcloud and i've no recommandations now.

### Actual result
What does happen?
The home of passwords app load very longtime
Screenshot video : https://imgur.com/3ir5vQo
### Expected result
What should happen?
Page appear automatically like browse in nextcloud folders.

**Comment by marius-wieschollek** [comment]
The log entries look like something went wrong when the app was unzipped. Can you try Disabling and deleting the app and then downloading it again?

**Comment by kevngzc** [comment]
i already unzip it with another version downloaded directly from the app store and this is the same result.
I use cron service and not ajax or webcron.
I use https and this is the debug mode if it could helm--> https://imgur.com/a/FCD6LUd

**Comment by marius-wieschollek** [comment]
Can you press F12, then go to the Network tab and filter by XHR.
Then go to a different section in the app (like all, Folders, Favorites or Recent) and check if a new request appears.
If so, wait till it has finished and tell me the status code. If it is a 50x status code please also check the log for new entries.
If no request appears, go to the console tab and check the log for any errors.

**Comment by kevngzc** [comment]
Thanks for your answer i tried this to check logs and effectively it seem there is an issue with extract archive so i put the app on a ftp and i download it on my server. I reset permissions on the app folder and restart apache, I cleaned my cache and it works now.

Thanks again for your time and your reactivity.
