### ISSUE TITLE
Just a blank page after update

### ISSUE THREAD

**Issue by Bouni** [marius-wieschollek/passwords#94]
### System Information
- Nextcloud Version: 14.0.3
- PHP Version: 7.2.11
- Passwords Version:  2018.11.0
- Browser and Version: Firefox 63.0.1
- Client OS and Version: Windows 7
- Server OS and Version: Arch Linux 

### Steps to reproduce
1. Click the Passwords App Icon, stare at a completely blank page

I don't see any 404 if I look into the requests using the developer tools of Firefox nor can I see anything in the logs. One of my colleges said that he just updated the Passwords App and afterwards he wasn't able to see anything besides a completely white screen (except the top menue of NC).

I've seen that somebody had a similar issue #12 but that was resolved by a new release, right?

Any ideas where to look for the cause of this problem?

**Comment by marius-wieschollek** [comment]
Can you check the Nextcloud Log in the Admin Settings for any Exceptions that appear when you open the app?

**Comment by Bouni** [comment]
I've cleared the logs about 20 Minutes ago to see if any errors are getting logged, still not a single entry under /settings/admin/logging.
If I open the Passwords App I see the mentioned white page, the developer tools show that the main div is completely empty:
![grafik](https://user-images.githubusercontent.com/948965/48074544-7284d800-e1e1-11e8-9bd1-3399cb35d0b7.png)

**Comment by Bouni** [comment]
The access logs of my Nginx are showing this:
[06/Nov/2018:16:29:54 +0100] "GET /apps/passwords/ HTTP/2.0" 200 5706 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"

**Comment by marius-wieschollek** [comment]
Can you run the following JavaScript snippet:
```
!document.querySelector('meta[name=api-user]')
```

It should return *not* return true.

**Comment by Bouni** [comment]
It returns true, what does it mean?

**Comment by marius-wieschollek** [comment]
This means that the user name for the api is missing. Therefore the app can not load.
Can you try `!document.querySelector('meta[name=pwat]')`. This one should return true.

You can also try to log out and log back in and see if that helps.

**Comment by Bouni** [comment]
That one returns `false`
I also logged in and out with the admin account and a user account. Same result.

**Comment by marius-wieschollek** [comment]
The update changes how the api user information is passed to the web interface.
For some reason unknown to me, it seems like the html code still contains the old meta tags instead of the new ones.

Could you locate the installation folder of the passwords app on your server and check if the file `lib/Controller/PageController.php` matches the file from the [stable branch](https://github.com/marius-wieschollek/passwords/blob/stable/src/lib/Controller/PageController.php#L81).

**Comment by Bouni** [comment]
The source seems to match, this is copy & paste from my source file:
```
    /**
     * @NoAdminRequired
     * @NoCSRFRequired
     * @UseSession
     */
    public function index(): TemplateResponse {

        $isSecure = $this->checkIfHttpsUsed();
        if($isSecure) {
            $this->getUserSettings();
            Util::addHeader('meta', ['name' => 'api-user', 'content' => $this->environmentService->getUserLogin()]);
            Util::addHeader('meta', ['name' => 'api-token', 'content' => $this->tokenHelper->getWebUiToken()]);
        } else {
            $this->tokenHelper->destroyWebUiToken();
        }

        $response = new TemplateResponse(
            $this->appName,
            'index',
            [
                'https'       => $isSecure,
                'https_debug' => $this->config->getAppValue('debug/https', false)
            ]
        );

        $response->setContentSecurityPolicy($this->getContentSecurityPolicy());

        return $response;
    }
```

**Comment by Bouni** [comment]
I've just rebooted the server and now it works!
After thinking about it, I just tried to restart nginx yesterday without success, but maybe I should have restarted php-fpm.service instead!?

**Comment by nwps** [comment]
This fixed the issue for me:
```
snap restart nextcloud.php-fpm
snap restart nextcloud
```

**Comment by marius-wieschollek** [comment]
Seems like an issue with the php opcode cache.
I will check if i can include a command to clear the cache for future updates.
