### ISSUE TITLE
Copy to clipboard not working on iOS

### ISSUE THREAD

**Issue by dfyx** [marius-wieschollek/passwords#95]
### System Information
- Nextcloud Version: 13.0.6 (official docker container)
- PHP Version: 7.1
- Passwords Version: 2018.11.0
- Browser and Version: Mobile Safari
- Client OS and Version: iOS 11.4.1
- Server OS and Version: docker host is Ubuntu 18.04

### Steps to reproduce
1. Open passwords app on iOS (tried both iPhone SE and iPad Pro 12.9")
2. Tap an entry

### Actual result
The notification that the password was copied appears but the clipboard still has its old contents.

### Expected result
The notification that the password was copied appears and the clipboard actually contains the password.

### Additional info
I guess the app uses some clipboard API that's not supported on iOS. Copying worked fine in the owncloud passwords app so there must be a way to get it working.

**Comment by marius-wieschollek** [comment]
Seems like the iOS devices are a bit special there. I have adapted the copy action and now it works on an iPad with iOS 12. It's in the nightly version already.

**Comment by dfyx** [comment]
Wow, that was quick. Thanks a lot. Messing with the nightly is a bit weird with the dockerized version but I have no problems with waiting a few days.
