### ISSUE TITLE
Password app error

### ISSUE THREAD

**Issue by arch1mede** [marius-wieschollek/passwords#96]
### System Information
- Nextcloud Version: 14.0.3
- PHP Version: 7.1
- Passwords Version: 2018.11.0
- Browser and Version: Chrome70
- Client OS and Version: Win10 1803
- Server OS and Version: FreeNas 11.2RC1

### Steps to reproduce
1. Tell us how to reproduce your issue.
Installed Passwords App and clicked on the icon at the top
2. Provide sample data if needed
3. Include relevant user settings and app settings if not standard

### Actual result
What does happen?
Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.

Technical details
Remote Address: xx.xx.xx.xx
Request ID: GjPC4bznhIMGOwhy0N3R

TypeError: Argument 1 passed to OCA\Passwords\Helper\Token\TokenHelper::destroyToken() must be of the type string, null given, called in /usr/local/www/nextcloud/apps/passwords/lib/Helper/Token/TokenHelper.php on line 189
/usr/local/www/nextcloud/apps/passwords/lib/Helper/Token/TokenHelper.php - line 189:
OCA\Passwords\Helper\Token\TokenHelper->destroyToken(null)

/usr/local/www/nextcloud/apps/passwords/lib/Controller/PageController.php - line 84:
OCA\Passwords\Helper\Token\TokenHelper->destroyWebUiToken()

/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:
OCA\Passwords\Controller\PageController->index()

/usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:
OC\AppFramework\Http\Dispatcher->executeController(OCA\Password ... {}, "index")

/usr/local/www/nextcloud/lib/private/AppFramework/App.php - line 118:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Password ... {}, "index")

/usr/local/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
OC\AppFramework\App::main("OCA\\Passwo ... r", "index", OC\AppFramew ... {}, { _route: "p ... "})

OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "p ... "})

/usr/local/www/nextcloud/lib/private/Route/Router.php - line 297:
call_user_func(OC\AppFramew ... {}, { _route: "p ... "})

/usr/local/www/nextcloud/lib/base.php - line 987:
OC\Route\Router->match("/apps/passwords/")

/usr/local/www/nextcloud/index.php - line 42:
OC::handleRequest()

### Expected result
What should happen?
I would expect the password manager to show up

**Comment by marius-wieschollek** [comment]
Ok, i found and fixed this error. The fix will be shipped with the next update.

However this error should only appear if you try to open the app without HTTPS enabled.
If you do not use HTTPS, please configure your server to use HTTPS.
If you do use HTTPS, please read the [documentation](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/harden_server.html#use-https) and if you use a reverse proxy read this [documentation](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/reverse_proxy_configuration.html). You should check Overview > Security & setup warnings and make sure no warnings are shown there. You can also use the [https debugging setting](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Administrative-Settings#enable-https-detection-debugging).

**Comment by arch1mede** [comment]
I just setup NextCloud and hadn't had the chance to fix https yet. Will the update be pushed to the NextCloud plugin repository?
