### ISSUE TITLE
Shared passwords stays in a loading state. User don't receive shared passwords.

### ISSUE THREAD

**Issue by danielschubert** [marius-wieschollek/passwords#99]
When Sharing a password to another user the icon stays in a rotating status, the password is not being shared.

### System Information
- Nextcloud Version: 14.0.3
- Passwords Version: 2018.11.1
- Cron via Webcron every 5 Minutes

### Actual result
- Password is not being shared - The hover info  shows "Es sind Dateien zur Synchronisation vorhanden"

- I have one single error in the log :
̀ Did expect one result but found none when executing: query "SELECT * FROM `*PREFIX*passwords_entity_folder` WHERE `deleted` = ? AND `*PREFIX*passwords_entity_folder`.`user_id` = ? AND `uuid` = ?"; parameters Array ( [0] => [1] => daniel [2] => 10012c51-c579-45a4-9c4a-ca2cb8a51554 ) ; limit ""; offset ""

### Expected result
The password should be shared to the user

**Comment by danielschubert** [comment]
The Sharing worked now, though it took all night. 

Any Ideas on how to speed things up?

**Comment by joshu111** [comment]
Having same issues

**Comment by marius-wieschollek** [comment]
I just checked how Nextcloud behaves when webcron is used. Everytime the cron.php is called, _one_ background task is executed.
When the cron.php is executed trough a cronjob on the system _all_ background tasks are executed.
On my developer machine with just Nextcloud and the app installed, there are 26 background jobs.  So with one background task every five minutes, this would mean it takes more than two hours before the synchronization task is executed.

That _could_ explain why it takes so long. Another explanation could be that something went wrong during the execution which will cause Nextcloud to wait some time until it tries to execute the background task again.

@danielschubert Can you check the stack trace of the error you found in your log? if you click on the log entry it should appear.

**Comment by marius-wieschollek** [comment]
I have inspected the cron job issue and found a way how i can trigger that specific background task manually.  This should help to speed up sharing a lot in version 2018.12.

**Comment by joshu111** [comment]
> Having same issues

Thank you for explanation Marius. It takes couple of hours or few minutes to share but eventually it goes through. I didn't find any error in log

**Comment by marius-wieschollek** [comment]
Ok, the wait time should be reduced significantly in the next release.

**Comment by danielschubert** [comment]
I just tried and waited for approx. 1 Hour. The password is not yet shared. It seems the general approach to use the cron jobs doesn't work here. 

my cron job is executed every 5 mins. 
I have 15 Users here.

THX anyway!

**Comment by danielschubert** [comment]
@marius-wieschollek  i used 2018.11.2, as it was offered to me in the Nextcloud Apps List.
I just understood you mentioned the 2018.12 version in your previous comment. I'll try that and will report.

**Comment by marius-wieschollek** [comment]
Should now be solved
